; SUBROM.MAC

; MSX SUBROM, adapted Sanyo_PHC-35J version (v3.0)

; Source re-created by Z80DIS 2.2
; Z80DIS was written by Kenneth Gielow, Palo Alto, CA

; Code Copyrighted by ASCII and maybe others
; Source comments by Arjen Zeilemaker
; Adapted by Arjen Zeilemaker

; Sourcecode supplied for STUDY ONLY
; Recreation NOT permitted without authorisation of the copyrightholders

	INCLUDE	MSX.INC

	.Z80
	ASEG
	ORG	0000H

RDSLT	EQU	000CH
WRSLT	EQU	0014H
OUTDO	EQU	0018H
CALSLT	EQU	001CH
KEYINT	EQU	0038H
NMI	EQU	0066H
GICINI	EQU	0090H
CHGET	EQU	009FH
CKCNTC	EQU	00BDH
FNKSB	EQU	00C9H
SNSMAT	EQU	0141H
EOL	EQU	0168H
RDRES	EQU	017AH
WRRES	EQU	017DH

M2F92	EQU	2F92H	; convert float (SGN or DBL) to integer
M3058	EQU	3058H	; check if string
M3236	EQU	3236H	; convert to SGN in DAC
M3412	EQU	3412H	; print number
M3FD7	EQU	3FD7H	; Ok message
M4055	EQU	4055H	; syntax error
M406A	EQU	406AH	; missing operand
M406D	EQU	406DH	; type mismatch
M406F	EQU	406FH	; error
M46E6	EQU	46E6H	; basictext for constant handling
M475A	EQU	475AH	; illegal function call
M4C64	EQU	4C64H	; evaluate expression
M4FCF	EQU	4FCFH	; byte to DAC
M51D7	EQU	51D7H	; helper routine ramdisk for transfers page 0
M520F	EQU	520FH	; evaluate integer operand
M521C	EQU	521CH	; evaluate byte operand
M542F	EQU	542FH	; evaluate address operand
M5439	EQU	5439H	; convert DAC to address operand
M579C	EQU	579CH	; evaluate graphic coordinatepair
M57AB	EQU	57ABH	; evaluate 2nd graphic coordinatepair
M5EA4	EQU	5EA4H	; locate variable
M6275	EQU	6275H	; out of memory
M6627	EQU	6627H	; allocate stringspace
M6678	EQU	6678H	; print text (HL)
M67D0	EQU	67D0H	; free (temp) string
M6A0E	EQU	6A0EH	; parse filespec
M6B24	EQU	6B24H	; close io buffer
M6E6B	EQU	6E6BH	; bad filename
M6E6E	EQU	6E6EH	; file already open
M6E74	EQU	6E74H	; file not found
M6E86	EQU	6E86H	; sequential io only
M7323	EQU	7323H	; CR,LF if not at start of line
M7328	EQU	7328H	; CR,LF to OUTDO
M7EE4	EQU	7EE4H	; basic version text
M7EF2	EQU	7EF2H	; MSX Basic text
M7FFA	EQU	7FFAH	; EXTBIO entry in mainrom
M7FFD	EQU	7FFDH	; BDOS entry in mainrom

D$C010	EQU	0C010H

RDPRIM	EQU	0F380H
WRPRIM	EQU	0F385H
CLPRIM	EQU	0F38CH
CLPRM1	EQU	0F398H
LINL40	EQU	0F3AEH
LINL32	EQU	0F3AFH
LINLEN	EQU	0F3B0H
CRTCNT	EQU	0F3B1H
CLMLST	EQU	0F3B2H
TXTNAM	EQU	0F3B3H
TXTCOL	EQU	0F3B5H
TXTCGP	EQU	0F3B7H
T32NAM	EQU	0F3BDH
T32COL	EQU	0F3BFH
T32CGP	EQU	0F3C1H
T32ATR	EQU	0F3C3H
T32PAT	EQU	0F3C5H
GRPNAM	EQU	0F3C7H
GRPCOL	EQU	0F3C9H
GRPCGP	EQU	0F3CBH
GRPATR	EQU	0F3CDH
GRPPAT	EQU	0F3CFH
MLTNAM	EQU	0F3D1H
MLTCGP	EQU	0F3D5H
MLTATR	EQU	0F3D7H
MLTPAT	EQU	0F3D9H
CLIKSW	EQU	0F3DBH
CSRY	EQU	0F3DCH
CNSDFG	EQU	0F3DEH
RG0SAV	EQU	0F3DFH
RG1SAV	EQU	0F3E0H
RG2SAV	EQU	0F3E1H
RG3SAV	EQU	0F3E2H
RG4SAV	EQU	0F3E3H
RG5SAV	EQU	0F3E4H
RG6SAV	EQU	0F3E5H
RG7SAV	EQU	0F3E6H
FORCLR	EQU	0F3E9H
BAKCLR	EQU	0F3EAH
BDRCLR	EQU	0F3EBH
ATRBYT	EQU	0F3F2H
PUTPNT	EQU	0F3F8H
GETPNT	EQU	0F3FAH
CS1200	EQU	0F3FCH
CS2400	EQU	0F401H
LOW.	EQU	0F406H
ASPCT1	EQU	0F40BH
ASPCT2	EQU	0F40DH
NTMSXP	EQU	0F417H
BUF	EQU	0F55EH
TTYPOS	EQU	0F661H
VALTYP	EQU	0F663H
CONTXT	EQU	0F666H
CONSAV	EQU	0F668H
CONTYP	EQU	0F669H
CONLO	EQU	0F66AH
DSCTMP	EQU	0F698H
SUBFLG	EQU	0F6A5H
STREND	EQU	0F6C6H
DAC	EQU	0F7F6H
NULBUF	EQU	0F862H
PTRFIL	EQU	0F864H
FILNAM	EQU	0F866H
NLONLY	EQU	0F87CH
FNKSTR	EQU	0F87FH
CGPNT	EQU	0F91FH
NAMBAS	EQU	0F922H
CGPBAS	EQU	0F924H
PATBAS	EQU	0F926H
ATRBAS	EQU	0F928H
CLOC	EQU	0F92AH
CMASK	EQU	0F92CH
CSAVEA	EQU	0F942H
CSAVEM	EQU	0F944H
LOHMSK	EQU	0F949H
LOHDIR	EQU	0F94AH
LOHADR	EQU	0F94BH
LOHCNT	EQU	0F94DH
SKPCNT	EQU	0F94FH
MOVCNT	EQU	0F951H
PDIREC	EQU	0F953H
LFPROG	EQU	0F954H
RTPROG	EQU	0F955H
DPPAGE	EQU	0FAF5H
ACPAGE	EQU	0FAF6H
AVCSAV	EQU	0FAF7H
EXBRSA	EQU	0FAF8H
CHRCNT	EQU	0FAF9H
ROMA	EQU	0FAFAH
MODE	EQU	0FAFCH	; b0	= SHIFT KANA mode
			; b1-b2	= VRAM Size
			; b3	= use fast vdp transfer in MSX1 screens
			; b4	= 212/256 lines
			; b5	= screen 11
			; b6	= JIS2 rom
			; b7	= upcase status SHIFT KANA mode
XSAVE	EQU	0FAFEH
D.FAFF	EQU	0FAFFH
YSAVE	EQU	0FB00H
D.FB01	EQU	0FB01H
LOGOPR	EQU	0FB02H
HOKVLD	EQU	0FB20H
LINTTB	EQU	0FBB2H
FSTPOS	EQU	0FBCAH
FNKSWI	EQU	0FBCDH
CLIKFL	EQU	0FBD9H
NEWKEY	EQU	0FBE5H
KEYBUF	EQU	0FBF0H
LINWRK	EQU	0FC18H
PATWRK	EQU	0FC40H
INTFLG	EQU	0FC9BH
GRPHED	EQU	0FCA6H
KANAST	EQU	0FCACH
KANAMD	EQU	0FCADH
SCRMOD	EQU	0FCAFH
OLDSCR	EQU	0FCB0H
BDRATR	EQU	0FCB2H
GXPOS	EQU	0FCB3H
GYPOS	EQU	0FCB5H
GRPACX	EQU	0FCB7H
GRPACY	EQU	0FCB9H
EXPTBL	EQU	0FCC1H
SLTTBL	EQU	0FCC5H
SLTWRK	EQU	0FD09H
PROCNM	EQU	0FD89H
H.INIP	EQU	0FDC7H
H.NMI	EQU	0FDD6H
H.ERRP	EQU	0FEFDH
H.CHRG	EQU	0FF48H
H.PHYD	EQU	0FFA7H
EXTBIO	EQU	0FFCAH
RG8SAV	EQU	0FFE7H
RG9SAV	EQU	0FFE8H
RG10SA	EQU	0FFE9H
RG11SA	EQU	0FFEAH
RG18SA	EQU	0FFF1H
RG23SA	EQU	0FFF6H
D.FFF7	EQU	0FFF7H	; slotid of mainrom
RG24SA	EQU	0FFF9H
RG25SA	EQU	0FFFAH
RG26SA	EQU	0FFFBH
D.FFFF	EQU	0FFFFH	; secundary slotreg


	DEFB	"CD"
	DEFW	C3FF0
	DEFW	C1731
	DEFW	C3658

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

S.SYNCHR:
	JP	J1CB9

	DEFS	00010H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

S.CHRGTR:
	JP	J1CC1

	DEFS	00014H-$,0

	JP	C0218

	DEFS	00018H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

S.OUTDO:
	JP	J2787

	DEFS	0001CH-$,0

S.CALM01:
	JP	C0262

	DEFS	00020H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

S.DCOMPR:
	LD	A,H
	SUB	D
	RET	NZ
	LD	A,L
	SUB	E
	RET

	DEFS	00028H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

S.GETBYT:
	JP	C2824

	DEFS	00030H-$,0

S.CALM0F:
	JP	J0246

	DEFS	00038H-$,0

S.KEYINT:
	EX	AF,AF'
	EXX
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	AF,AF'
	EXX
	PUSH	IX
	PUSH	IY
	LD	IX,KEYINT
	LD	IY,(EXPTBL+0-1)
	CALL	C279D
	POP	IY
	POP	IX
	EX	AF,AF'
	EXX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	EXX
	EI
	RETI

	DEFS	00066H-$,0

	JP	H.NMI

	EI
	JP	J2651

	EI
	JP	J2833

	EI
	JP	C284C

	EI
	JP	J28E4

	EI
	JP	J2907

	EI
	JP	J291C

	EI
	JP	J2925

	EI
	JP	C299B

	EI
	JP	J11BC

	EI
	JP	C1376

	EI
	JP	C13FC

	EI
	JP	C143E

	EI
	JP	C1467

	EI
	JP	C146F

	EI
	JP	C14EB

	EI
	JP	J14FE

	EI
	JP	C14A1

	EI
	JP	J1510

	EI
	JP	C14B6

	EI
	JP	J1551

	EI
	JP	C14D9

	EI
	JP	J155D

	EI
	JP	C15A0

	EI
	JP	C1652

	EI
	JP	C295F

	EI
	JP	C2A75

	EI
	JP	J0A53

	EI
	JP	C0A75

	EI
	JP	C0AAA

	EI
	JP	C0AD8

	EI
	JP	C0B28

	EI
	JP	C0BE6

	EI
	JP	C0C40

	EI
	JP	C0C76

	EI
	JP	C0CC6

	EI
	JP	C076D

	EI
	JP	J07D1

	EI
	JP	C07E6

	EI
	JP	C07FB

	EI
	JP	C0855

	EI
	JP	C095C

	EI
	JP	C0967

	EI
	JP	C09E4

	EI
	JP	C087A

	EI
	JP	C08F5

	EI
	JP	J0DF4

	EI
	JP	J0EB1

	EI
	JP	J0EFF

	EI
	JP	J0FB8

	EI
	JP	C0688

	EI
	JP	C2BEF

	EI
	JP	J3E87

	EI
	JP	J3C4C

	EI
	JP	C0714

	EI
	JP	J1041

	EI
	JP	J1020

	EI
	JP	C100C

	EI
	JP	C1075

	EI
	JP	J20DA

	EI
	JP	J1D7D

	EI
	JP	J1E8B

	EI
	JP	J202A

	EI
	JP	J2211

	EI
	JP	J2237

	EI
	JP	J227B

	EI
	JP	J22F2

	EI
	JP	J235E

	EI
	JP	J2371

	EI
	JP	J191B

	EI
	JP	J1B53

	EI
	JP	J1C3F

	EI
	JP	J04FC

	EI
	JP	J04D6

	EI
	JP	J23AC

	EI
	JP	J2E32

	EI
	JP	J2EBB

	EI
	JP	J2E58

	EI
	JP	J3021

	EI
	JP	J312D

	EI
	JP	J2FE8

	EI
	JP	J2FF5

	EI
	JP	J3460

	EI
	JP	J176B

	EI
	JP	C0A4F

	EI
	JP	0

	EI
	JP	J10EB

J01C1:	CALL	C3F8B
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL
	LD	C,A
	AND	D
	LD	E,A
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	CALL	C3FB6			; get SLTTBL entry
	LD	(HL),E			; update copy of SSR in SLTTBL
	PUSH	DE
	PUSH	HL
	PUSH	BC
	EXX
	EX	AF,AF'
	CALL	CLPRM1
	DI
	EX	AF,AF'
	EXX
	POP	BC
	POP	HL
	POP	AF
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	(HL),C			; update copy of SSR in SLTTBL
	EX	AF,AF'
	EXX
	RET

	DEFS	01F5H-$,0


	EI
	JP	J1C96			; read nibble from clockchip register (with bank)

	EI
	JP	J1C9E			; write nibble to clockchip register (with bank)


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C01FD:	CALL	C02DD
	JP	M,J020D
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	CALL	RDPRIM
	LD	A,E
	RET

J020D:	PUSH	HL
	CALL	C0302
	EX	(SP),HL
	PUSH	BC
	CALL	C01FD
	JR	J0233


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0218:	PUSH	DE
	CALL	C02DD
	JP	M,J0228
	POP	DE
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	JP	WRPRIM

J0228:	EX	(SP),HL
	PUSH	HL
	CALL	C0302
	POP	DE
	EX	(SP),HL
	PUSH	BC
	CALL	C0218
J0233:	POP	BC
	EX	(SP),HL
	PUSH	AF
	LD	A,B
	AND	3FH
	OR	C
	OUT	(0A8H),A
	LD	A,L
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	POP	AF
	POP	HL
	RET

J0246:	EX	(SP),HL
	PUSH	AF
	PUSH	DE
	LD	A,(HL)
	PUSH	AF
	POP	IY
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	DE
	POP	IX
	POP	DE
	POP	AF
	EX	(SP),HL
J0258:	EXX
	LD	D,0FCH
	JR	J0265

;	Subroutine	call basicrom (page 1)
;	Inputs		________________________
;	Outputs		________________________
;	Remark		only usable for page 1 addresses
;			UNUSED CODE

?025D:	EXX
	LD	D,0F3H
	JR	J0265


;	  Subroutine call mainrom (page 0 and page 1)
;	     Inputs  ________________________
;	     Outputs ________________________

C0262:	EXX
	LD	D,0F0H
J0265:	EX	AF,AF'
	DI
	IN	A,(0A8H)
	LD	B,A
	LD	A,(EXPTBL+0)
	AND	03H
	LD	E,A			; primairy slot main rom
	LD	A,(EXBRSA)
	AND	03H
	CP	E			; same as primairy slot sub rom ?
	JR	NZ,J027E		; nope,
	LD	A,D
	CP	0F3H			; call to only page 1 mainrom ?
	JP	NZ,J01C1		; nope, use safe methode
J027E:	LD	A,E
	CALL	C3FB6			; get SLTTBL entry
	RRC	E
	RRC	E
	LD	A,B
	AND	3FH
	OR	E
	PUSH	AF
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL
	AND	D
	LD	C,A
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	(HL),C			; update copy of SSR in SLTTBL
	PUSH	HL
	PUSH	BC
	LD	HL,C02A8
	PUSH	HL
	PUSH	AF
	CALL	C3FA7
	EXX
	JP	CLPRIM

C02A8:	DI
	EXX
	EX	AF,AF'
	POP	BC
	POP	HL
	POP	AF
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	(HL),C			; update copy of SSR in SLTTBL
	EX	AF,AF'
	EXX
	RET

	DEFS	02BDH-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C02BD:	CALL	C02DD
	JP	M,J02CA
	IN	A,(0A8H)
	AND	C
	OR	B
	OUT	(0A8H),A
	RET

J02CA:	PUSH	HL
	CALL	C0302
	LD	C,A
	LD	B,00H
	LD	A,L
	AND	H
	OR	D
	LD	HL,SLTTBL
	ADD	HL,BC
	LD	(HL),A
	POP	HL
	LD	A,C
	JR	C02BD


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C02DD:	DI
	PUSH	AF
	LD	A,H
	RLCA
	RLCA
	AND	03H	; 3 
	LD	E,A
	LD	A,0C0H
J02E7:	RLCA
	RLCA
	DEC	E
	JP	P,J02E7
	LD	E,A
	CPL
	LD	C,A
	POP	AF
	PUSH	AF
	AND	03H	; 3 
	INC	A
	LD	B,A
	LD	A,0ABH
J02F8:	ADD	A,55H	; "U"
	DJNZ	J02F8
	LD	D,A
	AND	E
	LD	B,A
	POP	AF
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0302:	PUSH	AF
	LD	A,D
	AND	0C0H
	LD	C,A
	POP	AF
	PUSH	AF
	LD	D,A
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	OR	C
	OUT	(0A8H),A
	LD	A,D
	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	LD	A,0ABH
J031A:	ADD	A,55H	; "U"
	DEC	D
	JP	P,J031A
	AND	E
	LD	D,A
	LD	A,E
	CPL
	LD	H,A
	LD	A,(D.FFFF)
	CPL
	LD	L,A
	AND	H
	OR	D
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	POP	AF
	AND	03H	; 3 
	RET

;
;	Remark		UNUSED TEXT
;

?0336:	DEFB	"Copyright 1988 by ASCII corporation"
	DEFB	0

C035A:	LD	HL,I2C5A
	LD	DE,RG0SAV
	LD	BC,8
	LDIR
	LD	DE,RG8SAV
	LD	C,10H	; 16 
	LDIR
	LD	DE,RG24SA
	LD	C,04H	; 4 
	LDIR
	XOR	A
	LD	(DPPAGE),A
	LD	(ACPAGE),A
	CALL	C058E
	LD	(EXBRSA),A
	LD	H,A
	LD	L,0F7H
	LD	(H.ERRP+0),HL
	LD	HL,I3B94
	LD	(H.ERRP+2),HL
	LD	A,(EXPTBL+0)
	LD	(D.FFF7),A
	LD	HL,MODE
	RES	1,(HL)
	SET	2,(HL)
	LD	A,(HOKVLD)
	BIT	0,A
	JR	NZ,J03B2
	OR	01H	; 1 
	LD	(HOKVLD),A
	LD	HL,EXTBIO+0
J03A8:	LD	DE,EXTBIO+1
	LD	BC,3*5-1
	LD	(HL),0C9H
	LDIR
J03B2:	LD	A,2CH
	LD	(D.FAFF),A
	LD	A,26H
	LD	(D.FB01),A
	LD	A,0D3H
	OUT	(0F7H),A
	LD	(AVCSAV),A
	XOR	A
	OUT	(0F5H),A
	LD	C,0FFH
	OUT	(0D8H),A
	LD	A,02H	; 2 
	OUT	(0D9H),A
	LD	HL,I0586
	LD	B,08H	; 8 
J03D3:	IN	A,(0D9H)
	CP	(HL)
	JR	NZ,J03DD
	INC	HL
	DJNZ	J03D3
	RES	0,C
J03DD:	CALL	C04E6
	JR	NZ,J03E4
	RES	1,C
J03E4:	IN	A,(0C0H)
	CP	0FFH
	JR	Z,J03EC
	RES	2,C
J03EC:	IN	A,(0F7H)
	AND	77H	; "w"
	CP	77H	; "w"
	JR	Z,J03F6
	RES	3,C
J03F6:	IN	A,(0C8H)
	CP	0FFH
	JR	Z,J03FE
	RES	4,C
J03FE:	XOR	A
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	LD	A,40H	; "@"
	OUT	(81H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(81H)
	AND	3FH	; "?"
	CP	05H	; 5 
	JR	NZ,J041B
	RES	5,C
J041B:	IN	A,(0BBH)
	CP	0FFH
	JR	Z,J0423
	RES	6,C
J0423:	LD	A,C
	OUT	(0F5H),A
	CALL	C04E6
	JR	NZ,J0430
	LD	HL,MODE
	SET	6,(HL)
J0430:
	IFDEF	RTCENA
	CALL	C1C85			; select clockchip bank 2
	LD	B,0			; register 0
	CALL	C1C60			; read nibble from clockchip register
	CP	0AH
	JR	Z,J043F
J043C:	CALL	C0497			; initialize bank 2 and 3 clockchip
J043F:	CALL	C1C85			; select clockchip bank 2
	LD	B,3			; register 3
	CALL	C1C60			; read nibble from clockchip register
	AND	01H
	PUSH	AF
	CALL	C1C69			; read byte from clockchip registers
	POP	BC
	CP	80+1
	JP	NC,J043C
	OR	A
	JP	Z,J043C
	DEC	B
	JR	NZ,J045F
	CP	21H	; "!"
	JP	NC,J043C
	ENDIF

J045F:
	IFDEF	RTCENA
	CALL	C1C85			; select clockchip bank 2
	LD	B,1			; register 1
	CALL	C1C60			; read nibble from clockchip register
	LD	D,A
	CALL	C1C60			; read nibble from clockchip register
	LD	E,A
	ELSE
	LD	DE,0
	ENDIF

	CALL	C18E0

	IFDEF	RESENA
	CALL	C2769			; read reset register
	RLCA				; cold boot ?
	JR	C,J0480			; nope, skip bootup logo
	ENDIF

	CALL	C05E1			; count RAM

	IFDEF	RESENA
	PUSH	HL
	CALL	C05AA			; clear RAM (cartridge headers)
	POP	HL
	ENDIF

	CALL	C2C76			; bootup logo
J0480:
	IFDEF	RESENA
	LD	A,80H
	CALL	C276F			; flag cold boot happened
	ENDIF

	CALL	C067D			; disable vdp display output
	XOR	A
	LD	L,A
	LD	H,A
	LD	BC,04000H
	CALL	C0A08			; fill first 16 Kb VRAM with zero's
	CALL	C0AAA			; S.INIPLT (initialize palette)
	JP	J1041			; S.INIT32 and quit

;	  Subroutine initialize bank 2 and 3 clockchip
;	     Inputs  ________________________
;	     Outputs ________________________

C0497:	LD	HL,I057B
	LD	C,2
J049C:	LD	B,13			; clockchip MODE register
	LD	A,4
	SUB	C			; clock paused, alarm off, select bank
	CALL	C1B4A			; write nibble to clockchip
	LD	B,13
J04A6:	LD	A,13
	SUB	B
	OUT	(0B4H),A		; select clockchip register
	LD	A,(HL)
	INC	HL
	CP	0FFH
	JR	NZ,J04B3
	DEC	HL
	XOR	A
J04B3:	OUT	(0B5H),A		; write clockchip register
	DJNZ	J04A6
	DEC	C
	JR	NZ,J049C		; next bank
	LD	B,13			; clockchip MODE register
	LD	A,8			; clock running, alarm off, select bank 0
	CALL	C1B4A			; write nibble to clockchip
	XOR	A			; test3 off, test2 off, test1 off, test0 off
	CALL	C1B4A			; write nibble to clockchip (TEST register)
	LD	A,13			; 1 Hz test off, 16 Hz test off, do not reset divider stages, reset alarm registers
	CALL	C1B4A			; write nibble to clockchip
	LD	A,1
	CALL	C1C87			; select clockchip bank 1
	LD	B,10			; clockchip LEAPYEAR register
	LD	A,1			; 24 hour mode
	JP	C1B4A			; write nibble to clockchip

J04D6:	SCF
	CALL	C04FD
	LD	HL,M7EF2
	CALL	C280C
	LD	HL,M7EE4
	JP	C280C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C04E6:	PUSH	BC
	LD	A,3EH	; ">"
	OUT	(0DAH),A
	LD	A,35H	; "5"
	OUT	(0DBH),A
	LD	BC,00800H
J04F2:	IN	A,(0DBH)
	ADD	A,C
	LD	C,A
	DJNZ	J04F2
	CP	95H
	POP	BC
	RET

J04FC:	XOR	A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C04FD:	PUSH	AF

	IFDEF	RTCENA
	CALL	C1C85			; select clockchip bank 2
	LD	B,3			; register 3
	CALL	C1C60			; read nibble from clockchip register
	LD	C,A
	AND	01H
	ELSE
	XOR	A
	IF BASVER EQ 0
	INC	A
	ENDIF
	LD	C,A
	ENDIF

	POP	DE
	PUSH	AF
	PUSH	DE
	PUSH	BC
	LD	A,C
	RLCA
	RLCA
	AND	08H
	LD	C,A
	LD	A,(RG9SAV)
	AND	0F7H
	OR	C
	LD	B,A
	LD	C,9
	CALL	C0688
	POP	BC

	IFDEF	RTCENA
	CALL	C1C69			; read byte from clockchip registers
	ELSE
	IF BASVER EQ 0
	LD	A,01DH
	ELSE
	LD	A,025H
	ENDIF
	ENDIF

	LD	E,A
	POP	AF
	PUSH	DE
	PUSH	AF

	IFDEF	RTCENA
	CALL	C1C60			; read nibble from clockchip register
	ELSE
	LD	A,15
	ENDIF

	LD	(FORCLR),A
	LD	(ATRBYT),A

	IFDEF	RTCENA
	CALL	C1C60			; read nibble from clockchip register
	ELSE
	LD	A,4
	ENDIF

	LD	(BAKCLR),A

	IFDEF	RTCENA
	CALL	C1C60			; read nibble from clockchip register
	ELSE
	IF BASVER EQ 0
	LD	A,7
	ELSE
	LD	A,4
	ENDIF
	ENDIF
	LD	(BDRCLR),A

	IFDEF	RTCENA
	CALL	C1C60			; read nibble from clockchip register
	ELSE
	LD	A,3
	ENDIF

	LD	C,A
	RRC	C
	SBC	A,A
	LD	B,A
	POP	AF
	JR	NC,J0548
	LD	A,B
J0548:	LD	(CNSDFG),A
	RRC	C
	SBC	A,A
	LD	(CLIKSW),A
	BIT	1,C
	PUSH	BC
	LD	BC,5
	LD	HL,CS1200
	JR	Z,J055F
	LD	HL,CS2400
J055F:	LD	DE,LOW.
	LDIR
	POP	BC
	RRC	C
	SBC	A,A
	LD	(NTMSXP),A
	POP	DE
	POP	AF
	LD	(OLDSCR),A
	LD	(SCRMOD),A
	PUSH	DE
	CALL	C0A4F
	POP	DE
	JP	J204A

I057B:	DEFB	00AH
	DEFB	000H,000H

	IF BASVER EQ 0
	DEFB	001H
	ELSE
	DEFB	000H
	ENDIF

	IF BASVER EQ 0
	DEFB	00DH,001H
	ELSE
	DEFB	005H,002H
	ENDIF

	DEFB	00FH,004H

	IF BASVER EQ 0
	DEFB	007H
	ELSE
	DEFB	004H
	ENDIF

	DEFB	003H

	IF CNTRY NE 0
	DEFB	001H
	DEFB	000H
	DEFB	CNTRY
	ENDIF

	DEFB	0FFH

I0586:	DEFB	00H,40H,20H,10H,08H,04H,02H,01H


;	  Subroutine get my slotid
;	     Inputs  ________________________
;	     Outputs ________________________

C058E:	PUSH	BC
	PUSH	HL
	IN	A,(0A8H)
	AND	03H	; 3 
	LD	C,A
	LD	B,00H
	LD	HL,EXPTBL
	ADD	HL,BC
	OR	(HL)
	LD	C,A
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	AND	03H	; 3 
	RLCA
	RLCA
	OR	C
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05AA:	LD	HL,EXPTBL
	LD	B,00H
	LD	A,80H
	JR	J05B0
J05AF:	LD	C,(HL)
J05B0:	LD	A,C
	OR	B
	CALL	C05CD			; clear RAM (catridge headers in RAM)
	BIT	7,C
	JR	Z,J05C1
	LD	A,C
	ADD	A,04H	; 4 
	LD	C,A
	BIT	4,C
	JR	Z,J05B0
J05C1:	INC	HL
	INC	B
	LD	A,B
	CP	04H	; 4 
	JR	C,J05AF
	XOR	A
	LD	(D$C010),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05CD:	PUSH	BC
	PUSH	HL
	LD	HL,04000H
	LD	E,L
	PUSH	AF
	CALL	C2793
	POP	AF
	LD	H,80H
	LD	E,L
	CALL	C2793
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05E1:	LD	HL,0
	LD	DE,EXPTBL
	LD	B,00H
	LD	A,80H			; assume expanded slot 0
	JR	J05EA
J05E9:	LD	A,(DE)
J05EA:	LD	C,A
J05EB:	LD	A,C
	OR	B
	CALL	C060E			; count memorymapper
	BIT	7,C
	JR	Z,J05FC
	LD	A,C
	ADD	A,04H	; 4 
	LD	C,A
	BIT	4,C
	JR	Z,J05EB
J05FC:	INC	DE
	INC	B
	LD	A,B
	CP	04H	; 4 
	JR	C,J05E9
	PUSH	HL
	LD	H,40H
	LD	A,(EXPTBL+0)
	CALL	C02BD			; enable slot
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C060E:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	H,40H
	CALL	C02BD			; enable slot
	CALL	C0627
	POP	HL
	JR	C,J0624			; no memorymapper,
	LD	C,A
	LD	B,0
	AND	A
	JR	NZ,J0623
	INC	B
J0623:	ADD	HL,BC
J0624:	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0627:	LD	HL,04000H
	XOR	A
	OUT	(0FDH),A		; segment 0 on page 1
	LD	(HL),0AAH
	INC	A
	OUT	(0FDH),A		; segment 1 on page 1
	LD	(HL),55H
	DEC	A
	OUT	(0FDH),A		; segment 0 on page 1
	LD	A,(HL)
	CP	0AAH
	SCF				; flag no memory mapper
	JR	NZ,J0658		; not a memorymapper,
	LD	B,0			; start with segment 0
J063F:	LD	A,B
	OUT	(0FDH),A		; select segment on page 1
	LD	(HL),0AAH
	INC	B
	JR	NZ,J063F
J0647:	LD	A,B
	OUT	(0FDH),A		; select segment on page 1
	INC	B
	LD	A,(HL)
	CP	0AAH
	JR	NZ,J0656
	LD	A,55H
	LD	(HL),A
	CP	(HL)
	JR	Z,J0647
J0656:	DEC	B
	AND	A
J0658:	LD	A,2
	OUT	(0FDH),A		; segment 2 on page 1
	LD	A,B
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C065E:	LD	(CNSDFG),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0661:	LD	A,(SCRMOD)
	CP	02H	; 2 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0667:	LD	A,(SCRMOD)
	CP	04H	; 4 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C066D:	LD	A,(SCRMOD)
	CP	05H	; 5 
	RET

J0673:	CALL	C10D6
	LD	A,(RG1SAV)
	OR	60H	; "`"
	JR	J0685


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C067D:	CALL	C10D6
	LD	A,(RG1SAV)
	AND	3FH	; "?"
J0685:	LD	C,01H	; 1 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0687:	LD	B,A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0688:	LD	A,I
	PUSH	AF
	PUSH	HL
	LD	A,C
	AND	A
	JR	NZ,J06C1
	LD	A,B
	LD	HL,RG0SAV
	XOR	(HL)
	AND	01H	; 1 
	JR	Z,J06C1
	LD	HL,RG9SAV
	LD	A,(HL)
	AND	0CFH
	LD	(HL),A
	LD	A,B
	AND	01H	; 1 
	RRCA
	RRCA
	RRCA
	RRCA
	OR	(HL)
	PUSH	BC
	LD	B,A
	LD	C,09H	; 9 
	LD	HL,AVCSAV
	LD	A,(HL)
	AND	3FH	; "?"
	LD	(HL),A
	LD	A,B
	RLCA
	RLCA
	CPL
	AND	0C0H
	OR	(HL)
	OUT	(0F7H),A
	LD	(HL),A
	CALL	C0688
	POP	BC
J06C1:	LD	A,B
	DI
	OUT	(VDP.CW),A
	LD	A,C
	OR	80H
	OUT	(VDP.CW),A
	PUSH	BC
	PUSH	DE
	LD	D,B
	LD	A,C
	LD	B,00H
	CP	7+1
	LD	HL,RG0SAV
	JR	C,J06E7
	CP	23+1
	LD	HL,RG8SAV-8
	JR	C,J06E7
	JR	Z,J06E9
	CP	1CH
	JR	NC,J06E9
	LD	HL,RG25SA-25
J06E7:	ADD	HL,BC
	LD	(HL),D
J06E9:	CALL	C06F3
	POP	DE
	POP	BC
	POP	HL
	POP	AF
	RET	PO
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C06F3:	LD	A,(RG0SAV)
	AND	0EH	; 14 
	RRCA
	LD	C,A
	LD	A,(RG1SAV)
	AND	18H
	OR	C
	LD	C,A
	LD	A,(RG8SAV)
	AND	20H	; " "
	OR	C
	LD	C,A
	LD	A,(RG25SA)
	AND	18H
	RLCA
	RLCA
	RLCA
	OR	C
	OUT	(0F3H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0714:	LD	A,(SCRMOD)
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	DI
	LD	HL,I0724
	CALL	C0A59
	JR	J0768

I0724:	DEFW	0BE6H
	DEFW	0C40H
	DEFW	0C76H
	DEFW	0CC6H
	DEFW	0C7DH
	DEFW	0CFAH
	DEFW	0D24H
	DEFW	0D3BH
	DEFW	0D6BH

J0736:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	DI
	XOR	A
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	CALL	C10D6
	LD	C,VDP.CIW
	LD	HL,RG0SAV
	LD	B,08H	; 8 
	OTIR
	LD	HL,RG8SAV
	LD	B,10H	; 16 
	OTIR
	LD	A,19H
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	HL,RG25SA
	LD	B,03H	; 3 
	OTIR
	EI
	CALL	C06F3
J0768:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C076D:	CALL	C0779
	PUSH	HL
	LD	HL,0
	CALL	C0974
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0779:	LD	A,(RG1SAV)
	LD	C,01H	; 1 
	CALL	C0687
	LD	A,(SCRMOD)
	AND	A
	RET	Z
	LD	HL,(PATBAS)
	LD	BC,00800H
	XOR	A
	CALL	C0A08

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0790:	LD	A,(FORCLR)
	LD	E,A
	LD	HL,(ATRBAS)
	LD	BC,2000H
J079A:	CALL	C0667
	LD	A,0D1H
	JR	C,J07A3
	LD	A,0D9H
J07A3:	CALL	C095C
	INC	HL
	INC	HL
	LD	A,C
	CALL	C095C
	INC	HL
	INC	C
	LD	A,(RG1SAV)
	RRCA
	RRCA
	JR	NC,J07B8
	INC	C
	INC	C
	INC	C
J07B8:	LD	A,E
	CALL	C095C
	INC	HL
	DJNZ	J079A
	CALL	C0667
	RET	C
	LD	HL,(ATRBAS)
	LD	BC,512
	SBC	HL,BC
	LD	A,(FORCLR)
	JP	C0A08

J07D1:	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	CALL	C07FB
	CP	08H	; 8 
	JR	Z,J07E0
	ADD	HL,HL
	ADD	HL,HL
J07E0:	EX	DE,HL
	LD	HL,(PATBAS)
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C07E6:	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL
	LD	HL,(ATRBAS)
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C07F1:	ADD	A,A
	ADD	A,A
	CALL	C07E6
	LD	DE,0FE00H
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C07FB:	LD	A,(RG1SAV)
	RRCA
	RRCA
	LD	A,08H	; 8 
	RET	NC
	LD	A,20H	; " "
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0806:	CALL	H.INIP
	LD	HL,(CGPBAS)
	CALL	C0974
	LD	A,(CGPNT+0)
	LD	HL,(CGPNT+1)
	LD	BC,00800H
	PUSH	AF
J0819:	POP	AF
	PUSH	AF
	PUSH	BC
	DI
	CALL	C278D
	EI
	POP	BC
	OUT	(VDP.DRW),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J0819
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C082C:	CALL	C0982
	LD	A,C
	OR	A
	LD	A,B
	LD	B,C
	LD	C,VDP.DRW
	EX	DE,HL
	JR	Z,J0839
	INC	A
J0839:	INIR
	DEC	A
	JR	NZ,J0839
	EX	DE,HL
	RET

;	Subroutine	transfer from RAM to VRAM
;	Inputs		HL=RAM address, DE=VRAM base address, BC=size
;	Outputs		________________________
;	Remark		UNUSED CODE

?0840:	EX	DE,HL
	CALL	C0974
	EX	DE,HL
	LD	A,C
	OR	A
	LD	A,B
	LD	B,C
	LD	C,VDP.DRW
	JR	Z,J084E
	INC	A
J084E:	OTIR
	DEC	A
	JR	NZ,J084E
	EX	DE,HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0855:	LD	H,00H
	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL
	LD	HL,(CGPNT+1)
	ADD	HL,DE
	LD	DE,PATWRK
	LD	B,8
	LD	A,(CGPNT+0)
J0868:	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	C278D
	EI
	POP	BC
	POP	DE
	POP	HL
	LD	(DE),A
	INC	DE
	INC	HL
	POP	AF
	DJNZ	J0868
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C087A:	CALL	C0667
	JP	Z,C0926
	JR	NC,C088D
	CALL	C0661
	JP	Z,C0926
	JP	NC,C093E
	JR	C08F5


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C088D:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C2BE4
	LD	A,(BAKCLR)
	CALL	C08CF
	CALL	C2C4F
	XOR	A
	LD	H,A
	LD	L,A
	CALL	C2C09
	XOR	A
	CALL	C2C3F
	LD	A,(SCRMOD)
	AND	02H	; 2 
	LD	DE,00100H
	JR	Z,J08B2
	INC	D
J08B2:	LD	A,(MODE)
	AND	10H	; 16 
	LD	HL,000D4H
	JR	Z,J08BF
	LD	HL,00100H
J08BF:	CALL	C2C28
	LD	A,0C0H
	CALL	C2C47
	CALL	C2BE4
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08CF:	LD	B,A
	CALL	C2A0F
	JR	NZ,J08DD
	LD	A,B
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	08H	; 8 
	RET

J08DD:	LD	A,(SCRMOD)
	CP	08H	; 8 
	LD	A,B
	RET	Z
	RLCA
	RLCA
	RLCA
	RLCA
	OR	B
	LD	B,A
	LD	A,(SCRMOD)
	CP	06H	; 6 
	LD	A,B
	RET	NZ
	RRCA
	RRCA
	OR	B
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08F5:	LD	A,(SCRMOD)
	AND	A
	LD	HL,(NAMBAS)
	JR	NZ,J090F
	LD	A,(LINLEN)
	CP	29H	; ")"
	JR	NC,J090A
	LD	BC,003C0H
	JR	J0912

J090A:	LD	BC,00780H
	JR	J0912

J090F:	LD	BC,00300H
J0912:	LD	A,20H	; " "
	CALL	C0A08
	CALL	C0952
	LD	HL,LINTTB
	LD	B,24
J091F:	LD	(HL),B
	INC	HL
	DJNZ	J091F
	JP	J2781


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0926:	CALL	C0A2D
	LD	BC,J1800
	PUSH	BC
	LD	HL,(GRPCOL)
	LD	A,(BAKCLR)
	CALL	C0A08
	LD	HL,(GRPCGP)
	POP	BC
	XOR	A
J093B:	JP	C0A08


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C093E:	CALL	C0A2D
	LD	HL,BAKCLR
	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	LD	HL,(MLTCGP)
	LD	BC,00600H
	JR	J093B


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0952:	LD	HL,00101H
	LD	(CSRY),HL
	RET

;	Subroutine	________________________
;	Inputs		________________________
;	Outputs		________________________
;	Remark		UNUSED CODE

?0959:	CALL	C096D

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C095C:	PUSH	AF
	CALL	C0974
	POP	AF
	OUT	(VDP.DRW),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0964:	CALL	C096D

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0967:	CALL	C0982
	IN	A,(VDP.DRW)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C096D:	PUSH	AF
	LD	A,H
	AND	3FH	; "?"
	LD	H,A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0974:	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	CALL	C09A5
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	JR	J098C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0982:	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	CALL	C09A5
	LD	A,H
	AND	3FH	; "?"
J098C:	PUSH	AF
	LD	A,H
	AND	0C0H
	OR	D
	RLCA
	RLCA
	DI
	OUT	(VDP.CW),A
	LD	A,8EH
	OUT	(VDP.CW),A
	LD	A,L
	OUT	(VDP.CW),A
	POP	AF
	OUT	(VDP.CW),A
	EI
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C09A5:	LD	A,(SCRMOD)
	LD	C,A
	LD	A,(ACPAGE)
	AND	A
	LD	HL,I09B6
	JP	NZ,J0A5A
	EX	DE,HL
	LD	D,A
	RET

I09B6:	DEFW	C09C8
	DEFW	C09D6
	DEFW	C09D6
	DEFW	C09D6
	DEFW	C09D6
	DEFW	C09D5
	DEFW	C09D5
	DEFW	C09D4
	DEFW	C09D4

C09C8:	LD	A,(LINLEN)
	CP	29H	; ")"
	LD	A,(ACPAGE)
	JR	C,J09D8
	JR	J09D7

C09D4:	ADD	A,A
C09D5:	ADD	A,A
C09D6:	ADD	A,A
J09D7:	ADD	A,A
J09D8:	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	H,A
	LD	A,00H
	LD	L,A
	ADC	A,A
	ADD	HL,DE
	LD	D,A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C09E4:	CALL	C066D
	JP	NC,J0A28
	CALL	C0A35
	DEC	A
	JP	M,J0A1B
	PUSH	AF
	CALL	C0A2D
	POP	AF
	RET	NZ
	LD	HL,BAKCLR
	LD	A,(FORCLR)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	LD	HL,(T32COL)
	LD	BC,32

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0A08:	PUSH	AF
	CALL	C0974
	LD	A,C
	OR	A
	JR	Z,J0A11
	INC	B
J0A11:	POP	AF
J0A12:	OUT	(VDP.DRW),A
	DEC	C
	JP	NZ,J0A12
	DJNZ	J0A12
	RET

J0A1B:	LD	HL,BAKCLR
	LD	A,(FORCLR)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	JR	J0A30

J0A28:	CP	08H	; 8 
	CALL	NZ,C0A35

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0A2D:	LD	A,(BDRCLR)
J0A30:	LD	C,07H	; 7 
	JP	C0687


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0A35:	PUSH	AF
	LD	A,(BAKCLR)
	AND	0FH	; 15 
	LD	(BAKCLR),A
	LD	A,(FORCLR)
	AND	0FH	; 15 
	LD	(FORCLR),A
	POP	AF
	RET

;	Subroutine	CLS statement
;	Inputs		________________________
;	Outputs		________________________
; 	Remark		UNUSED CODE

?0A48:	RET	NZ
	PUSH	HL
	CALL	C087A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0A4F:	LD	HL,J1041
	PUSH	HL
J0A53:	CP	09H	; 9 
	RET	NC
	LD	HL,I0A63

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0A59:	LD	C,A
J0A5A:	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,C
	JP	(HL)

I0A63:	DEFW	C0A75
	DEFW	C0AAA
	DEFW	C0AD8
	DEFW	C0B28
	DEFW	C0B01
	DEFW	C0B66
	DEFW	C0B73
	DEFW	C0B80
	DEFW	C0B8D

C0A75:	XOR	A
	LD	(OLDSCR),A
	CALL	C0BB2
	LD	A,(LINL40)
	LD	(LINLEN),A
	LD	HL,00800H
	LD	(TXTCOL),HL
	LD	HL,(TXTNAM)
	LD	(NAMBAS),HL
	LD	HL,(TXTCGP)
	CP	29H	; ")"
	JR	C,J0A98
	LD	HL,1000H
J0A98:	LD	(CGPBAS),HL
	CALL	C0BE6
J0A9E:	CALL	C09E4
	CALL	C08F5
	CALL	C0806
	JP	J0673


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0AAA:	LD	A,01H	; 1 
	LD	(OLDSCR),A
	CALL	C0BB2
	LD	A,(LINL32)
	LD	(LINLEN),A
	LD	HL,(T32NAM)
	LD	(NAMBAS),HL
	LD	HL,(T32CGP)
	LD	(CGPBAS),HL
	LD	HL,(T32PAT)
	LD	(PATBAS),HL
	LD	HL,(T32ATR)
	LD	(ATRBAS),HL
	CALL	C0C40
	CALL	C0790
	JR	J0A9E

C0AD8:	LD	A,02H	; 2 
	CALL	C0BB2
	LD	HL,(GRPATR)
	CALL	C0B12
	PUSH	HL
	CALL	C0C76
J0AE7:	POP	HL
	CALL	C0974
	XOR	A
	LD	B,03H	; 3 
J0AEE:	OUT	(VDP.DRW),A
	INC	A
	JR	NZ,J0AEE
	DJNZ	J0AEE
	CALL	C0926
J0AF8:	CALL	C09E4
	CALL	C0790
	JP	J0673

C0B01:	LD	A,04H	; 4 
	CALL	C0BB2
	LD	HL,01E00H
	CALL	C0B12
	PUSH	HL
	CALL	C0C7D
	JR	J0AE7


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0B12:	LD	(ATRBAS),HL
	LD	HL,(GRPPAT)
	LD	(PATBAS),HL
	LD	HL,(GRPCGP)
	LD	(CGPBAS),HL
	LD	HL,(GRPNAM)
	LD	(NAMBAS),HL
	RET

C0B28:	LD	A,03H	; 3 
	CALL	C0BB2
	LD	HL,(MLTPAT)
	LD	(PATBAS),HL
	LD	HL,(MLTATR)
	LD	(ATRBAS),HL
	LD	HL,(MLTCGP)
	LD	(CGPBAS),HL
	LD	HL,(MLTNAM)
	LD	(NAMBAS),HL
	PUSH	HL
	CALL	C0CC6
	POP	HL
	CALL	C0974
	LD	DE,0*256+6
J0B50:	LD	C,04H	; 4 
J0B52:	LD	A,D
	LD	B,20H	; " "
J0B55:	OUT	(VDP.DRW),A
	INC	A
	DJNZ	J0B55
	DEC	C
	JR	NZ,J0B52
	LD	D,A
	DEC	E
	JR	NZ,J0B50
	CALL	C093E
	JR	J0AF8

C0B66:	LD	A,05H	; 5 
	LD	DE,07876H
	CALL	C0BA4
	CALL	C0CFA
	JR	J0B98

C0B73:	LD	A,06H	; 6 
	LD	DE,07876H
	CALL	C0BA4
	CALL	C0D24
	JR	J0B98

C0B80:	LD	A,07H	; 7 
	LD	DE,0F0FAH
	CALL	C0BA4
	CALL	C0D3B
	JR	J0B98

C0B8D:	LD	A,08H	; 8 
	LD	DE,0F0FAH
	CALL	C0BA4
	CALL	C0D6B
J0B98:	CALL	C09E4
	CALL	C088D
	CALL	C0790
	JP	J0673


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0BA4:	LD	L,00H
	LD	H,D
	LD	(PATBAS),HL
	LD	H,E
	LD	(ATRBAS),HL
	LD	H,L
	LD	(NAMBAS),HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0BB2:	LD	(SCRMOD),A
	XOR	A
	LD	(DPPAGE),A
	LD	(ACPAGE),A
	LD	HL,00100H
	LD	(ASPCT1),HL
	LD	(ASPCT2),HL
	CALL	C2BE4
	CALL	C067D
	LD	B,00H
	LD	C,17H
	CALL	C0688
	LD	C,1AH
	CALL	C0688
	LD	C,1BH
	CALL	C0688
	LD	A,(RG25SA)
	AND	0E4H
	LD	C,19H
	JP	C0687


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0BE6:	CALL	C0DD1
	LD	A,(LINLEN)
	CP	29H	; ")"
	LD	B,00H
	JR	C,J0BF4
	LD	B,04H	; 4 
J0BF4:	LD	C,10H	; 16 
	CALL	C0DE1
	LD	A,(LINLEN)
	CP	29H	; ")"
	LD	A,(DPPAGE)
	JR	NC,J0C16
	ADD	A,A
	LD	HL,(TXTCGP)
	LD	B,00H
	CALL	C0D8A
	ADD	A,A
	LD	HL,(TXTNAM)
	CALL	C0D7E
	JP	J0736

J0C16:	LD	A,(DPPAGE)
	PUSH	AF
	ADD	A,A
	ADD	A,A
	LD	B,00H
	LD	HL,(CGPBAS)
	CALL	C0D8A
	ADD	A,A
	LD	B,03H	; 3 
	LD	HL,(TXTNAM)
	CALL	C0D7E
	POP	AF
	LD	HL,(TXTCOL)
	LD	E,00H
	SRL	A
	RR	E
	LD	D,A
	LD	B,07H	; 7 
	CALL	C0D98
	JP	J0736


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0C40:	CALL	C0DD1
	LD	BC,0
	CALL	C0DE1
	LD	A,(DPPAGE)
	LD	C,A
	LD	B,00H
	LD	HL,(T32CGP)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0D8A
	LD	HL,(T32PAT)
	CALL	C0DC4
	LD	HL,(T32NAM)
	ADD	A,A
	CALL	C0D7E
	LD	E,B
	LD	D,C
	LD	HL,(T32COL)
	CALL	C0D98
	SRL	D
	RR	E
	LD	HL,(T32ATR)
	JR	J0CC0


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0C76:	XOR	A
	PUSH	AF
	LD	BC,00200H
	JR	J0C84


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0C7D:	LD	A,03H	; 3 
	OR	A
	PUSH	AF
	LD	BC,00400H
J0C84:	CALL	C0DE1
	CALL	C0DD1
	LD	A,(DPPAGE)
	LD	C,A
	LD	B,03H	; 3 
	LD	HL,(GRPCGP)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0D8A
	LD	HL,(GRPPAT)
	CALL	C0DC4
	LD	HL,(GRPNAM)
	ADD	A,A
	LD	B,00H
	CALL	C0D7E
	LD	E,B
	LD	D,C
	LD	B,7FH
	LD	HL,(GRPCOL)
	CALL	C0D98
	SRL	D
	RR	E
	POP	AF
	LD	B,A
	LD	HL,(GRPATR)
	JR	Z,J0CC0
	LD	HL,(ATRBAS)
J0CC0:	CALL	C0DAF
	JP	J0736


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0CC6:	CALL	C0DD1
	LD	BC,00008H
	CALL	C0DE1
	LD	A,(DPPAGE)
	LD	C,A
	LD	B,00H
	LD	HL,(MLTCGP)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0D8A
	LD	HL,(MLTPAT)
	CALL	C0DC4
	LD	HL,(MLTNAM)
	ADD	A,A
	LD	B,00H
	CALL	C0D7E
	LD	E,B
	LD	D,C
	SRL	D
	RR	E
	LD	B,00H
	LD	HL,(MLTATR)
	JR	J0CC0


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0CFA:	CALL	C0DD8
	LD	BC,00600H
	CALL	C0DE1
J0D03:	LD	A,(DPPAGE)
	LD	C,A
	LD	B,00H
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0DC1
	LD	HL,(NAMBAS)
	ADD	A,A
	LD	B,1FH
	CALL	C0D7E
	LD	D,C
J0D1A:	LD	E,00H
	LD	B,03H	; 3 
	CALL	C0DAC
	JP	J0736


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D24:	CALL	C0DD8
	LD	BC,00800H
	CALL	C0DE1
	LD	HL,00200H
	LD	(ASPCT1),HL
	LD	HL,00080H
	LD	(ASPCT2),HL
	JR	J0D03


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D3B:	CALL	C0DD8
	LD	BC,00A00H
	CALL	C0DE1
	LD	HL,00200H
	LD	(ASPCT1),HL
	LD	HL,00080H
	LD	(ASPCT2),HL
J0D50:	LD	A,(DPPAGE)
	LD	C,A
	LD	B,00H
	RRCA
	RRCA
	RRCA
	AND	0E0H
	CALL	C0DC1
	LD	HL,(NAMBAS)
	LD	B,1FH
	CALL	C0D7E
	LD	A,C
	ADD	A,A
	LD	D,A
	JR	J0D1A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D6B:	CALL	C0DD8
	LD	BC,00E00H
	CALL	C0DE1
	LD	A,(RG2SAV)
	SRL	A
	LD	(RG2SAV),A
	JR	J0D50


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D7E:	LD	L,A
	SRL	H
	SRL	H
	ADD	A,H
	OR	B
	LD	(RG2SAV),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D8A:	LD	L,A
	SRL	H
	SRL	H
	SRL	H
	ADD	A,H
	OR	B
	LD	(RG4SAV),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D98:	PUSH	AF
	XOR	A
	ADD	HL,HL
	ADC	A,A
	ADD	HL,HL
	ADC	A,A
	LD	L,H
	LD	H,A
	ADD	HL,DE
	LD	A,L
	OR	B
	LD	(RG3SAV),A
	LD	A,H
	LD	(RG10SA),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DAC:	LD	HL,(ATRBAS)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DAF:	PUSH	AF
	XOR	A
	ADD	HL,HL
	ADC	A,A
	LD	L,H
	LD	H,A
	ADD	HL,DE
	LD	A,L
	OR	B
	LD	(RG5SAV),A
	LD	A,H
	LD	(RG11SA),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DC1:	LD	HL,(PATBAS)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DC4:	LD	L,A
	SRL	H
	SRL	H
	SRL	H
	ADD	A,H
	LD	(RG6SAV),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DD1:	LD	A,(RG9SAV)
	AND	7FH
	JR	J0DDD


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DD8:	LD	A,(RG9SAV)
	OR	80H
J0DDD:	LD	(RG9SAV),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DE1:	LD	A,(RG0SAV)
	AND	0F1H
	OR	B
	LD	(RG0SAV),A
	LD	A,(RG1SAV)
	AND	0E7H
	OR	C
	LD	(RG1SAV),A
	RET

J0DF4:	LD	A,0FFH
	CALL	C065E
	RET	NC
	PUSH	HL
	LD	A,(CSRY)
	LD	HL,CRTCNT
	CP	(HL)
	LD	A,0AH	; 10 
	JR	NZ,J0E07
	RST	S.OUTDO
J0E07:	LD	A,(NEWKEY+6)
	RRCA
	LD	HL,FNKSTR+0*16
	LD	A,1
	JR	C,J0E16
	LD	HL,FNKSTR+5*16
	XOR	A
J0E16:	LD	(FNKSWI),A
	CALL	C0E84
	LD	C,05H	; 5 
	LD	A,(LINLEN)
	CP	29H	; ")"
	JR	NC,J0E44
	CALL	C0E92
	JR	C,J0E3C
J0E2A:	PUSH	BC
	LD	C,00H
J0E2D:	CALL	C0EA0
	DJNZ	J0E2D
	LD	A,10H	; 16 
	SUB	C
	LD	C,A
	ADD	HL,BC
	INC	DE
	POP	BC
	DEC	C
	JR	NZ,J0E2A
J0E3C:	LD	HL,(CRTCNT)
	CALL	C0F79
	POP	HL
	RET

J0E44:	PUSH	AF
	CALL	C0E92
	POP	AF
	SUB	28H	; "("
J0E4B:	PUSH	BC
	LD	C,00H
J0E4E:	EX	AF,AF'
	CALL	C0EA0
	EX	AF,AF'
	DEC	A
	CALL	Z,C0E74
	DJNZ	J0E4E
	DEC	A
	JR	NZ,J0E60
	CALL	C0E74
	DEC	DE
J0E60:	EX	AF,AF'
	LD	A,10H	; 16 
	SUB	C
	LD	C,A
	ADD	HL,BC
	EX	AF,AF'
	INC	DE
	POP	BC
	DEC	C
	JR	NZ,J0E4B
	LD	HL,(CRTCNT)
	CALL	C0F94
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0E74:	PUSH	BC
	PUSH	HL
	LD	HL,(CRTCNT)
	CALL	C0F7A
	CALL	C0E84
	POP	HL
	POP	BC
	LD	A,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0E84:	LD	DE,LINWRK
	PUSH	DE
	LD	B,40
	LD	A,20H	; " "
J0E8C:	LD	(DE),A
	INC	DE
	DJNZ	J0E8C
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0E92:	SUB	04H	; 4 
	RET	C
	LD	B,0FFH
J0E97:	INC	B
	SUB	05H	; 5 
	JR	NC,J0E97
	LD	A,B
	SUB	01H	; 1 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0EA0:	LD	A,(HL)
	INC	HL
	INC	C
	CALL	C1357
	JR	NC,C0EA0
	JR	NZ,J0EAE
	CP	20H	; " "
	JR	C,J0EAF
J0EAE:	LD	(DE),A
J0EAF:	INC	DE
	RET

J0EB1:	CALL	C0FA2
	SUB	L
	RET	C
	JP	Z,J0F4B
	PUSH	HL
	PUSH	AF
	LD	C,A
	LD	B,00H
	CALL	C0FAC
	LD	L,E
	LD	H,D
	INC	HL
	LDIR
	LD	HL,FSTPOS
	DEC	(HL)
	POP	AF
	POP	HL
	PUSH	AF
	LD	A,(LINLEN)
	CP	29H	; ")"
	JR	NC,J0EE5
	POP	AF
J0ED5:	PUSH	AF
	INC	L
	CALL	C0F50
	DEC	L
	CALL	C0F79
	INC	L
	POP	AF
	DEC	A
	JR	NZ,J0ED5
	JR	J0EFC

J0EE5:	POP	AF
J0EE6:	PUSH	AF
	INC	L
	CALL	C0F51
	DEC	L
	CALL	C0F7A
	INC	L
	CALL	C0F6A
	DEC	L
	CALL	C0F94
	INC	L
	POP	AF
	DEC	A
	JR	NZ,J0EE6
J0EFC:	JP	J0F4B

J0EFF:	CALL	C0FA2
	LD	H,A
	SUB	L
	RET	C
	JP	Z,J0F4B
	LD	L,H
	PUSH	HL
	PUSH	AF
	LD	C,A
	LD	B,00H
	CALL	C0FAC
	LD	L,E
	LD	H,D
	PUSH	HL
	DEC	HL
	LDDR
	POP	HL
	LD	(HL),H
	POP	AF
	POP	HL
	PUSH	AF
	LD	A,(LINLEN)
	CP	29H	; ")"
	JR	NC,J0F34
	POP	AF
J0F24:	PUSH	AF
	DEC	L
	CALL	C0F50
	INC	L
	CALL	C0F79
	DEC	L
	POP	AF
	DEC	A
	JR	NZ,J0F24
	JR	J0F4B

J0F34:	POP	AF
J0F35:	PUSH	AF
	DEC	L
	CALL	C0F51
	INC	L
	CALL	C0F7A
	DEC	L
	CALL	C0F6A
	INC	L
	CALL	C0F94
	DEC	L
	POP	AF
	DEC	A
	JR	NZ,J0F35
J0F4B:	LD	H,01H	; 1 
	JP	J27A6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F50:	DEFB	0F6H

C0F51:	XOR	A
	PUSH	HL
	PUSH	AF
	LD	H,01H	; 1 
	CALL	C0FD7
	POP	AF
	LD	A,(LINLEN)
	JR	NZ,J0F61
	SUB	28H	; "("
J0F61:	LD	B,A
J0F62:	LD	DE,LINWRK
	CALL	C0FC4
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F6A:	PUSH	HL
	LD	A,(LINLEN)
	SUB	28H	; "("
	INC	A
	LD	H,A
	CALL	C0FD7
	LD	B,28H	; "("
	JR	J0F62


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F79:	DEFB	0F6H

C0F7A:	XOR	A
	PUSH	HL
	PUSH	AF
	LD	H,01H	; 1 
	CALL	C0FD7
	POP	AF
	LD	A,(LINLEN)
	JR	NZ,J0F8A
	SUB	28H	; "("
J0F8A:	LD	B,A
J0F8B:	EX	DE,HL
	LD	HL,LINWRK
	CALL	C0FCD
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F94:	PUSH	HL
	LD	A,(LINLEN)
	SUB	27H	; "'"
	LD	H,A
	CALL	C0FD7
	LD	B,28H	; "("
	JR	J0F8B


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0FA2:	LD	A,(CNSDFG)
	PUSH	HL
	LD	HL,CRTCNT
	ADD	A,(HL)
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0FAC:	PUSH	HL
	LD	DE,LINTTB-1
	LD	H,00H
	ADD	HL,DE
	LD	A,(HL)
	EX	DE,HL
	POP	HL
	AND	A
	RET

J0FB8:	PUSH	HL
	CALL	C0FD7
	CALL	C0974
	LD	A,C
	OUT	(VDP.DRW),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0FC4:	CALL	C0982
	EX	DE,HL
	LD	C,VDP.DRW
	INIR
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0FCD:	EX	DE,HL
	CALL	C0974
	EX	DE,HL
	LD	C,VDP.DRW
	OTIR
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0FD7:	PUSH	BC
	DEC	H
	DEC	L
	LD	E,H
	LD	H,00H
	LD	D,H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	LD	C,L
	LD	B,H
	ADD	HL,HL
	ADD	HL,HL
	LD	A,(SCRMOD)
	AND	A
	LD	A,(LINLEN)
	JR	Z,J0FF2
	SUB	22H	; """
	JR	J0FFF

J0FF2:	CP	29H	; ")"
	JR	C,J0FFC
	ADD	HL,BC
	ADD	HL,HL
	SUB	52H	; "R"
	JR	J0FFF

J0FFC:	ADD	HL,BC
	SUB	2AH	; "*"
J0FFF:	ADD	HL,DE
	CPL
	AND	A
	RRA
	LD	E,A
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(NAMBAS)
	ADD	HL,DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C100C:	PUSH	HL
	LD	D,A
	CALL	C109B
	CALL	C0982
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(VDP.DRW)
	LD	B,A
	DEFB	0,0
	IN	A,(VDP.DRW)
	LD	C,A
	POP	HL
	RET

J1020:	PUSH	HL
	LD	D,00H
	CALL	C109B
	CALL	C0982
	LD	B,D
	LD	C,10H	; 16 
	CALL	C0688
	LD	B,10H	; 16 
J1031:	IN	A,(VDP.DRW)
	NOP
	OUT	(VDP.PRW),A
	NOP
	IN	A,(VDP.DRW)
	NOP
	OUT	(VDP.PRW),A
	NOP
	DJNZ	J1031
	POP	HL
	RET

J1041:	PUSH	HL
	LD	HL,I1055
	LD	B,10H	; 16 
	LD	D,00H
J1049:	LD	A,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	CALL	C1075
	INC	D
	DJNZ	J1049
	POP	HL
	RET

I1055:	DEFB	00H,00H,00H,00H,11H,06H,33H,07H
	DEFB	17H,01H,27H,03H,51H,01H,27H,06H
	DEFB	71H,01H,73H,03H,61H,06H,64H,06H
	DEFB	11H,04H,65H,02H,55H,05H,77H,07H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1075:	PUSH	BC
	PUSH	HL
	LD	B,D
	LD	C,10H	; 16 
	PUSH	AF
	CALL	C0688
	POP	AF
	LD	C,VDP.PRW
	OUT	(C),A
	PUSH	AF
	POP	AF
	OUT	(C),E
	PUSH	AF
	CALL	C109B
	CALL	C0974
	EX	(SP),HL
	EX	(SP),HL
	POP	AF
	OUT	(VDP.DRW),A
	PUSH	AF
	POP	AF
	LD	A,E
	OUT	(VDP.DRW),A
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C109B:	PUSH	AF
	LD	A,(SCRMOD)
	LD	HL,I10C2
	PUSH	BC
	INC	A
	LD	C,A
	LD	B,00H
	DEC	A
	JR	NZ,J10B2
	LD	A,(LINLEN)
	CP	29H	; ")"
	JR	NC,J10B2
	DEC	C
J10B2:	ADD	HL,BC
	ADD	HL,BC
	POP	BC
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	DE
	LD	E,D
	LD	D,00H
	ADD	HL,DE
	ADD	HL,DE
	POP	DE
	POP	AF
	RET

I10C2:	DEFW	0400H
	DEFW	0F00H
	DEFW	2020H
	DEFW	1B80H
	DEFW	2020H
	DEFW	1B80H
	DEFW	7680H
	DEFW	7680H
	DEFW	0FA80H
	DEFW	0FA80H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C10D6:	LD	A,02H	; 2 
	CALL	C2BEF
	AND	40H	; "@"
	JR	NZ,C10D6
J10DF:	LD	A,02H	; 2 
	CALL	C2BEF
	AND	40H	; "@"
	JR	Z,J10DF
	RET

J10E9:	POP	AF
	RET

J10EB:	PUSH	AF
	LD	A,B
	CP	21H	; "!"
	JR	C,J10E9
	CP	28H	; "("
	JR	C,J10FD
	CP	30H	; "0"
	JR	C,J10E9
	CP	75H	; "u"
	JR	NC,J10E9
J10FD:	LD	A,C
	CP	21H	; "!"
	JR	C,J10E9
	CP	7FH
	JR	NC,J10E9
	POP	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	A,C
	SUB	20H	; " "
	LD	E,A
	LD	D,00H
	LD	A,B
	SUB	20H	; " "
	LD	L,A
	LD	H,D
	LD	C,L
	LD	B,H
	ADD	HL,HL
	ADD	HL,BC
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	CP	30H	; "0"
	JR	C,J112C
	LD	A,H
	SUB	12H	; 18 
	LD	H,A
	LD	C,0DAH
	JR	J1134

J112C:	CP	10H	; 16 
	JR	C,J1132
	DEC	H
	DEC	H
J1132:	LD	C,0D8H
J1134:	OUT	(C),L
	ADD	HL,HL
	ADD	HL,HL
	INC	C
	OUT	(C),H
	LD	B,20H	; " "
	LD	HL,LINWRK
	INIR
	POP	AF
	PUSH	AF
	AND	A
	LD	C,02H	; 2 
	JR	Z,J1173
	LD	HL,LINWRK
	LD	E,L
	LD	D,H
	DEC	A
	JR	Z,J1152
	INC	HL
J1152:	LD	C,02H	; 2 
J1154:	LD	B,08H	; 8 
J1156:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	HL
	INC	DE
	LD	A,B
	CP	05H	; 5 
	JR	NZ,J1166
	PUSH	BC
	LD	BC,8
	ADD	HL,BC
	POP	BC
J1166:	DJNZ	J1156
	PUSH	BC
	LD	BC,-16
	ADD	HL,BC
	POP	BC
	DEC	C
	JR	NZ,J1154
	LD	C,01H	; 1 
J1173:	LD	HL,(GRPACX)
	PUSH	HL
	LD	HL,(GRPACY)
	PUSH	HL
	LD	DE,LINWRK
J117E:	LD	HL,(GRPACY)
	PUSH	HL
	LD	HL,(GRPACX)
	PUSH	HL
	LD	B,02H	; 2 
J1188:	PUSH	BC
	EX	DE,HL
	LD	DE,PATWRK
	LD	BC,8
	LDIR
	PUSH	HL
	CALL	C11DB
	POP	DE
	POP	BC
	DJNZ	J1188
	POP	HL
	LD	(GRPACX),HL
	POP	HL
	PUSH	BC
	LD	BC,8
	ADD	HL,BC
	POP	BC
	LD	(GRPACY),HL
	DEC	C
	JR	NZ,J117E
	POP	HL
	LD	(GRPACY),HL
	POP	HL
	LD	BC,16
	ADD	HL,BC
	LD	(GRPACX),HL
I11B7:	POP	AF
	POP	BC
	POP	DE
	POP	HL
	RET

J11BC:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I11B7
	PUSH	HL
	CALL	C1357
	RET	NC
	JR	NZ,J11D2
	CP	0DH	; 13 
	JP	Z,J1211
	CP	20H	; " "
	RET	C
J11D2:	CALL	C0855
	LD	A,(FORCLR)
	LD	(ATRBYT),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C11DB:	LD	HL,(GRPACY)
	EX	DE,HL
	LD	BC,(GRPACX)
	CALL	C1376
	RET	NC
	CALL	C13FC
	CALL	C1225
	LD	A,(SCRMOD)
	AND	0FEH
	CP	06H	; 6 
	JR	Z,J1201
	LD	A,(GRPACX)
	ADD	A,08H	; 8 
	JR	C,J1211
	LD	(GRPACX),A
	RET

J1201:	LD	HL,(GRPACX)
	LD	BC,8
	ADD	HL,BC
	LD	A,H
	AND	0FEH
	JR	NZ,J1211
	LD	(GRPACX),HL
	RET

J1211:	LD	HL,0
	LD	(GRPACX),HL
	LD	A,(GRPACY)
	ADD	A,08H	; 8 
	CP	0D4H
	JR	C,J1221
	XOR	A
J1221:	LD	(GRPACY),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1225:	CALL	C2A1D
	CALL	C2BE4
	XOR	A
	CALL	C2C3F
	CALL	C1430
	LD	E,A
	CALL	C2C09
	LD	A,E
	SUB	0CDH
	LD	L,08H	; 8 
	JR	C,J1242
	LD	L,A
	LD	A,07H	; 7 
	SUB	L
	LD	L,A
J1242:	LD	B,L
	LD	DE,8
	LD	H,D
	CALL	C2C28
	LD	HL,(ATRBYT)
	LD	A,(BAKCLR)
	LD	H,A
	LD	DE,PATWRK
	LD	A,(DE)
	ADD	A,A
	LD	C,A
	LD	A,H
	JR	NC,J125B
	LD	A,L
J125B:	CALL	C2C4F
	LD	A,(LOGOPR)
	AND	0FH	; 15 
	OR	0B0H
	CALL	C2C47
	DI
	LD	A,0ACH
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	A,C
	LD	C,VDP.CIW
	DI
	JR	J128C

J1277:	DI
	LD	A,0ACH
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	INC	DE
	LD	A,(DE)
	RLCA
	JR	NC,J128A
	OUT	(C),L
	JP	J128C

J128A:	OUT	(C),H
J128C:	RLCA
	JR	NC,J1294
	OUT	(C),L
	JP	J1296

J1294:	OUT	(C),H
J1296:	RLCA
	JR	NC,J129E
	OUT	(C),L
	JP	J12A0

J129E:	OUT	(C),H
J12A0:	RLCA
	JR	NC,J12A8
	OUT	(C),L
	JP	J12AA

J12A8:	OUT	(C),H
J12AA:	RLCA
	JR	NC,J12B2
	OUT	(C),L
	JP	J12B4

J12B2:	OUT	(C),H
J12B4:	RLCA
	JR	NC,J12BC
	OUT	(C),L
	JP	J12BE

J12BC:	OUT	(C),H
J12BE:	RLCA
	JR	NC,J12C6
	OUT	(C),L
	JP	J12C8

J12C6:	OUT	(C),H
J12C8:	RLCA
	JR	NC,J12D0
	OUT	(C),L
	JP	J12D2

J12D0:	OUT	(C),H
J12D2:	EI
	DJNZ	J1277
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C12D6:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I11B7
	PUSH	HL
	CALL	C1357
	RET	NC
	JR	NZ,J12EC
	CP	07H	; 7 
	JP	Z,J1B53
	CP	20H	; " "
	RET	C
J12EC:	CALL	C0855
	LD	DE,PATWRK
	PUSH	DE
	CALL	C2BE4
	XOR	A
	CALL	C2C3F
	CALL	C1430
	CALL	C2C09
	LD	HL,8
	LD	DE,16
	CALL	C2C28
	POP	DE
	LD	HL,00103H
	LD	A,(DE)
	ADD	A,A
	LD	C,A
	LD	A,H
	JR	NC,J1314
	LD	A,L
J1314:	PUSH	AF
	CALL	C2C4F
	LD	A,0B0H
	CALL	C2C47
	DI
	LD	A,0ACH
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	POP	AF
	OUT	(VDP.CIW),A
	LD	A,C
	LD	C,VDP.CIW
	LD	B,08H	; 8 
	PUSH	BC
	DEC	B
	JR	J1337

J1332:	INC	DE
	LD	A,(DE)
	PUSH	BC
	LD	B,08H	; 8 
J1337:	RLCA
	JR	NC,J1342
	OUT	(C),L
	PUSH	AF
	POP	AF
	OUT	(C),L
	JR	J1348

J1342:	OUT	(C),H
	PUSH	AF
	POP	AF
	OUT	(C),H
J1348:	DJNZ	J1337
	POP	BC
	DJNZ	J1332
	LD	HL,(CLOC)
	LD	BC,16
	ADD	HL,BC
	JP	J142C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1357:	PUSH	HL
	PUSH	AF
	LD	HL,GRPHED
	XOR	A
	CP	(HL)
	LD	(HL),A
	JR	Z,J136E
	POP	AF
	SUB	40H	; "@"
	CP	20H	; " "
	JR	C,J136C
	ADD	A,40H	; "@"
J136A:	CP	A
	SCF
J136C:	POP	HL
	RET

J136E:	POP	AF
	CP	01H	; 1 
	JR	NZ,J136A
	LD	(HL),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1376:	CALL	C066D
	JP	NC,J13B7
	PUSH	HL
	PUSH	BC
	LD	B,01H	; 1 
	EX	DE,HL
	LD	A,H
	ADD	A,A
	JR	NC,J138A
	LD	HL,0
	JR	J1392

J138A:	LD	DE,000C0H
	RST	S.DCOMPR
	JR	C,J1394
	EX	DE,HL
	DEC	HL
J1392:	LD	B,00H
J1394:	EX	(SP),HL
	LD	A,H
	ADD	A,A
	JR	NC,J139E
	LD	HL,0
	JR	J13A6

J139E:	LD	DE,00100H
	RST	S.DCOMPR
	JR	C,J13A8
	EX	DE,HL
	DEC	HL
J13A6:	LD	B,00H
J13A8:	POP	DE
	SRL	L
	SRL	L
	SRL	E
	SRL	E
	LD	A,B
	RRCA
	LD	C,L
	LD	B,H
	POP	HL
	RET

J13B7:	PUSH	HL
	PUSH	BC
	LD	B,01H	; 1 
	EX	DE,HL
	LD	A,H
	ADD	A,A
	JR	NC,J13C5
	LD	HL,0
	JR	J13D7

J13C5:	LD	A,(MODE)
	AND	10H	; 16 
	LD	DE,000D4H
	JR	Z,J13D2
	LD	DE,00100H
J13D2:	RST	S.DCOMPR
	JR	C,J13D9
	EX	DE,HL
	DEC	HL
J13D7:	LD	B,00H
J13D9:	EX	(SP),HL
	LD	A,H
	ADD	A,A
	JR	NC,J13E3
	LD	HL,0
	JR	J13F3

J13E3:	LD	A,(SCRMOD)
	AND	02H	; 2 
	LD	DE,00200H
	JR	NZ,J13EE
	DEC	D
J13EE:	RST	S.DCOMPR
	JR	C,J13F5
	EX	DE,HL
	DEC	HL
J13F3:	LD	B,00H
J13F5:	LD	A,B
	RRCA
	LD	B,H
	LD	C,L
	POP	DE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C13FC:	CALL	C066D
	JR	C,J1409
	LD	H,B
	LD	L,C
	LD	A,E
	LD	(CMASK),A
	JR	J142C

J1409:	PUSH	BC
	LD	A,C
	RRCA
	LD	A,0F0H
	JR	NC,J1412
	LD	A,0FH	; 15 
J1412:	LD	(CMASK),A
	LD	A,C
	ADD	A,A
	ADD	A,A
	AND	0F8H
	LD	C,A
	LD	A,E
	AND	07H	; 7 
	OR	C
	LD	C,A
	LD	A,E
	RRCA
	RRCA
	RRCA
	AND	07H	; 7 
	LD	B,A
	LD	HL,(MLTCGP)
	ADD	HL,BC
	POP	BC
J142C:	LD	(CLOC),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1430:	LD	A,(CMASK)
	LD	HL,(CLOC)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1437:	LD	(CMASK),A
	LD	(CLOC),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C143E:	CALL	C066D
	JP	NC,J145B
	PUSH	BC
	PUSH	HL
	CALL	C1430
	LD	B,A
	CALL	C0964
	INC	B
	DEC	B
	JP	P,J1456
	RRCA
	RRCA
	RRCA
	RRCA
J1456:	AND	0FH	; 15 
	POP	HL
	POP	BC
	RET

J145B:	PUSH	HL
	LD	HL,(CLOC)
	LD	A,(CMASK)
	CALL	C2B99
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1467:	CALL	C1DCE
	RET	C
	LD	(ATRBYT),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C146F:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C066D
	LD	A,(CMASK)
	LD	HL,(CLOC)
	JR	C,J1484
	CALL	C2BC0
	POP	HL
	POP	DE
	POP	BC
	RET

J1484:	LD	B,A
	CALL	C0967
	LD	C,A
	LD	A,B
	CPL
	AND	C
	LD	C,A
	LD	A,(ATRBYT)
	INC	B
	DEC	B
	JP	P,J1499
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
J1499:	OR	C
	CALL	C095C
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C14A1:	PUSH	HL
	CALL	C066D
	CALL	C1430
	JP	C,J152B
	DEC	HL
	LD	A,H
	OR	A
	JP	M,J1536
	LD	(CLOC),HL
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C14B6:	PUSH	HL
	CALL	C066D
	CALL	C1430
	JP	C,J1539
	LD	A,(MODE)
	AND	10H	; 16 
	LD	A,(CMASK)
	JR	Z,J14CE
	CP	0FFH
	JR	J14D0

J14CE:	CP	0D3H
J14D0:	JR	NC,J1536
	INC	A
	LD	(CMASK),A
	POP	HL
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C14D9:	CALL	C066D
	JP	C,J1573
	LD	A,(CMASK)
	OR	A
	SCF
	RET	Z
	DEC	A
	LD	(CMASK),A
	OR	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C14EB:	PUSH	HL
	CALL	C1430
	AND	A
	LD	A,0FH	; 15 
	JP	M,J1525
	LD	A,L
	AND	0F8H
	CP	0F8H
	JR	NZ,J1508
	JR	J1536

J14FE:	PUSH	HL
	CALL	C1430
	AND	A
	LD	A,0FH	; 15 
	JP	M,J1525
J1508:	PUSH	DE
	LD	DE,8
	LD	A,0F0H
	JR	J1520

J1510:	PUSH	HL
	CALL	C1430
	AND	A
	LD	A,0F0H
	JP	P,J1525
J151A:	PUSH	DE
	LD	DE,-8
	LD	A,0FH	; 15 
J1520:	ADD	HL,DE
	LD	(CLOC),HL
	POP	DE
J1525:	LD	(CMASK),A
	AND	A
	POP	HL
	RET

J152B:	AND	A
	LD	A,0F0H
	JP	P,J1525
	LD	A,L
	AND	0F8H
	JR	NZ,J151A
J1536:	SCF
	POP	HL
	RET

J1539:	PUSH	DE
	PUSH	HL
	LD	HL,(MLTCGP)
	LD	DE,00500H
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	S.DCOMPR
	JR	C,J1553
	LD	A,L
	INC	A
	AND	07H	; 7 
	JR	NZ,J1553
	SCF
	POP	DE
	POP	HL
	RET

J1551:	PUSH	HL
	PUSH	DE
J1553:	CALL	C1430
	INC	HL
	LD	A,L
	LD	DE,000F8H
	JR	J1567

J155D:	PUSH	HL
	PUSH	DE
J155F:	CALL	C1430
	LD	A,L
	DEC	HL
	LD	DE,0FF08H
J1567:	AND	07H	; 7 
	JR	NZ,J156C
	ADD	HL,DE
J156C:	LD	(CLOC),HL
	AND	A
	POP	DE
	POP	HL
	RET

J1573:	PUSH	HL
	PUSH	DE
	LD	HL,(MLTCGP)
	LD	DE,00100H
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(CLOC)
	RST	S.DCOMPR
	JR	NC,J155F
	LD	A,L
	AND	07H	; 7 
	JR	NZ,J155F
	SCF
	POP	DE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C158C:	AND	A
	PUSH	AF
	LD	A,(SCRMOD)
	CP	08H	; 8 
	JR	Z,J159D
	POP	AF
	CP	10H	; 16 
	CCF
J1599:	LD	(BDRATR),A
	RET

J159D:	POP	AF
	JR	J1599


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C15A0:	LD	HL,0
	LD	C,L
	CALL	C066D
	JP	C,J1629
	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	HL,(CLOC)
	LD	A,(CMASK)
	LD	E,A
	LD	D,00H
	LD	A,(BDRATR)
	CALL	C2AC8
	JR	C,J15C4
	POP	DE
J15BF:	POP	BC
	POP	HL
	LD	D,H
	LD	E,H
	RET

J15C4:	POP	DE
	PUSH	HL
	LD	HL,(CLOC)
	ADD	HL,DE
	POP	DE
	OR	A
	SBC	HL,DE
	JR	C,J15BF
	JR	Z,J15BF
	POP	BC
	POP	BC
	PUSH	HL
	EX	DE,HL
	LD	(CSAVEA),HL
	LD	A,(CMASK)
	LD	(CSAVEM),A
	LD	E,A
	LD	D,00H
	LD	A,(BDRATR)
	CALL	C2ACC
	PUSH	AF
	JR	C,J15F6
	LD	A,(SCRMOD)
	AND	02H	; 2 
	LD	HL,001FFH
	JR	NZ,J15F6
	DEC	H
J15F6:	LD	(CLOC),HL
	POP	AF
	JR	C,J15FD
	INC	HL
J15FD:	PUSH	HL
	EX	DE,HL
	LD	HL,(CSAVEA)
	EX	DE,HL
	OR	A
	SBC	HL,DE
	EX	(SP),HL
	PUSH	HL
	EX	DE,HL
	LD	A,(CSAVEM)
	LD	E,A
	LD	D,00H
	LD	A,(ATRBYT)
	CALL	C2AC8
	POP	DE
	JR	NC,J1624
	RST	S.DCOMPR
	JR	NC,J1624
	POP	DE
	LD	HL,(CSAVEA)
	CALL	C169E
	POP	DE
	RET

J1624:	LD	C,00H
	POP	HL
	POP	DE
	RET

J1629:	CALL	C171B
	JR	NC,J163B
	DEC	DE
	LD	A,D
	OR	E
	RET	Z
	CALL	C14EB
	JR	NC,J1629
	LD	DE,0
	RET

J163B:	CALL	C1430
	LD	(CSAVEA),HL
	LD	(CSAVEM),A
	LD	HL,0
J1647:	INC	HL
	CALL	C14EB
	RET	C
	CALL	C171B
	JR	NC,J1647
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1652:	LD	HL,0
	LD	C,L
	CALL	C066D
	JP	C,J170E
	CALL	C14A1
	RET	C
	LD	HL,(CLOC)
	PUSH	HL
	LD	A,(CMASK)
	LD	E,A
	LD	D,00H
	LD	A,(BDRATR)
	CALL	C2AC0
	PUSH	AF
	JR	C,J1676
	LD	HL,-1
J1676:	INC	HL
	LD	(CLOC),HL
	EX	DE,HL
	POP	HL
	EX	(SP),HL
	PUSH	HL
	OR	A
	SBC	HL,DE
	INC	HL
	EX	(SP),HL
	PUSH	DE
	LD	A,(CMASK)
	LD	E,A
	LD	D,00H
	LD	A,(ATRBYT)
	CALL	C2AC4
	JR	NC,J1703
	POP	DE
	POP	BC
	POP	AF
	PUSH	BC
	PUSH	DE
	JR	NC,J169C
	RST	S.DCOMPR
	JR	C,J1709
J169C:	POP	HL
	POP	DE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C169E:	CALL	C2A0F
	JR	NZ,J16BB
	LD	C,07H	; 7 
	LD	A,81H
	CALL	C16D1
	CALL	C2BE4
	LD	A,(ATRBYT)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	08H	; 8 
	LD	C,A
	LD	A,82H
	JR	J16CA

J16BB:	LD	A,(ATRBYT)
	LD	C,A
	LD	A,(SCRMOD)
	CP	08H	; 8 
	LD	A,80H
	JR	NZ,J16CA
	LD	A,0C0H
J16CA:	CALL	C16D1
	EX	DE,HL
	LD	C,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C16D1:	PUSH	AF
	LD	A,24H	; "$"
	DI
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	A,L
	OUT	(VDP.CIW),A
	LD	A,H
	OUT	(VDP.CIW),A
	LD	A,(CMASK)
	OUT	(VDP.CIW),A
	LD	A,(ACPAGE)
	OUT	(VDP.CIW),A
	LD	A,E
	OUT	(VDP.CIW),A
	LD	A,D
	OUT	(VDP.CIW),A
	LD	A,01H	; 1 
	OUT	(VDP.CIW),A
	XOR	A
	OUT	(VDP.CIW),A
	LD	A,C
	OUT	(VDP.CIW),A
	XOR	A
	OUT	(VDP.CIW),A
	POP	AF
	EI
	OUT	(VDP.CIW),A
	RET

J1703:	POP	DE
	POP	HL
	POP	DE
	LD	C,00H
	RET

J1709:	POP	DE
	POP	HL
	LD	C,00H
	RET

J170E:	CALL	C14A1
	RET	C
	CALL	C171B
	JP	C,J14FE
	INC	HL
	JR	J170E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C171B:	CALL	C143E
	LD	B,A
	LD	A,(BDRATR)
	SUB	B
	SCF
	RET	Z
	LD	A,(ATRBYT)
	CP	B
	RET	Z
	CALL	C146F
	LD	C,01H	; 1 
	AND	A
	RET

C1731:	EI
	LD	DE,I1748
	PUSH	HL
	LD	HL,PROCNM
	CALL	C1795
	POP	HL
	RET	C
	SCF
	RET	NZ
	CALL	C1746
	EI
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1746:	PUSH	DE
	RET

I1748:	DEFM	'MEMINI',00H
	DEFW	C3685
	DEFM	'MKILL',00H
	DEFW	C3872
	DEFM	'MNAME',00H
	DEFW	C38C9
	DEFM	'MFILES',00H
	DEFW	C379E
	DEFB	0FFH

J176B:	PUSH	AF
	PUSH	HL
	LD	DE,I1781
	CALL	C1795
	JR	C,J177D
	POP	AF
	POP	AF
	DEC	HL
	CALL	C1746
	AND	A
	RET

J177D:	POP	HL
	POP	AF
	SCF
	RET

I1781:	DEFM	0CBH,00H
	DEFW	C17C3
	DEFM	'DATE',00H
	DEFW	C17C9
	DEFM	'KANJI',00H
	DEFW	C21E0
	DEFB	0FFH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1795:	PUSH	HL
	LD	A,(DE)
	INC	A
	JR	Z,J17AE
	CALL	C17B1
	JR	Z,J17A5
	INC	DE
	INC	DE
	INC	DE
	POP	HL
	JR	C1795

J17A5:	LD	A,(HL)
	EX	(SP),HL
	EX	DE,HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	AND	A
	DEFB	038H
J17AE:	SCF
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C17B1:	LD	A,(DE)
	OR	A
	RET	Z
	CP	(HL)
	JR	NZ,J17BB
	INC	DE
	INC	HL
	JR	C17B1

J17BB:	LD	A,(DE)
	AND	A
	INC	DE
	JR	NZ,J17BB
	DEC	DE
	DEC	A
	RET

;	  Subroutine GET TIME statement
;	     Inputs  ________________________
;	     Outputs ________________________

C17C3:	DEC	B
	LD	BC,I1833
	JR	J17CD

;	  Subroutine GET DATE statement
;	     Inputs  ________________________
;	     Outputs ________________________

C17C9:	DEC	B
	LD	BC,I184F
J17CD:	JP	P,J274A
	RST	S.CHRGTR
	PUSH	BC
	CALL	C27EE
	CALL	C27E8
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J17E6
	RST	S.SYNCHR
	DEFB	","
	RST	S.SYNCHR
	DEFB	"A"
	EX	(SP),HL
	LD	BC,14
	ADD	HL,BC
	EX	(SP),HL
J17E6:	POP	BC
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	A,08H	; 8 
	CALL	C2800
	LD	HL,(DSCTMP+1)
	POP	DE
	PUSH	HL
	LD	A,(DE)
	RLCA
	AND	01H
	LD	B,A			; time/date or alarm time/date
	LD	C,04H			; keep alarm bit

	IFDEF	RTCENA
	CALL	C1A3C			; write clockchip MODE register
	ENDIF

	LD	C,02H	; 2 
J1800:	LD	B,02H	; 2 
J1802:	LD	A,(DE)
	INC	A			; 0FFH, skip
	JR	Z,J180B
	DEC	A

	IFDEF	RTCENA
	OUT	(0B4H),A		; select clockchip register
	IN	A,(0B5H)		; read clockchip register
	ELSE
	LD	A,0
	ENDIF

J180B:	INC	DE
	EX	DE,HL
	ADD	A,(HL)
	EX	DE,HL
	DEC	DE
	DAA
	AND	0FH
	OR	"0"
	LD	(HL),A
	INC	DE
	INC	DE
	INC	HL
	DJNZ	J1802
	INC	C
	DEC	C
	JR	Z,J1826
	LD	A,(DE)
	LD	(HL),A
	INC	DE
	INC	HL
	DEC	C
	JR	J1800

J1826:
	IFDEF	RTCENA
	CALL	C1A38			; put clockchip in running state
	ENDIF

	POP	DE
	POP	HL
	LD	(HL),08H	; 8 
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	HL
	RET

I1833:	DEFB	05H,00H,04H,00H,3AH,03H,00H,02H
	DEFB	00H,3AH,01H,00H,00H,00H,85H,00H
	DEFB	84H,00H,3AH,83H,00H,82H,00H,3AH
	DEFB	81H,00H,80H,00H
I184F:
	IF	DATFMT EQ 0
	DEFB	12,8
	DEFB	11,0
	DEFB	"/"
	DEFB	10,0
	DEFB	9,0
	DEFB	"/"
	DEFB	8,0
	DEFB	7,0

	DEFB	0FFH,0
	DEFB	0FFH,0
	DEFB	"/"
	DEFB	0FFH,0
	DEFB	0FFH,0
	DEFB	"/"
	DEFB	088H,0
	DEFB	087H,0
	ENDIF

	IF	DATFMT EQ 1
	DEFB	10,0
	DEFB	9,0
	DEFB	"/"
	DEFB	8,0
	DEFB	7,0
	DEFB	"/"
	DEFB	12,8
	DEFB	11,0

	DEFB	0FFH,0
	DEFB	0FFH,0
	DEFB	"/"
	DEFB	088H,0
	DEFB	087H,0
	DEFB	"/"
	DEFB	0FFH,0
	DEFB	0FFH,0
	ENDIF

	IF	DATFMT EQ 2
	DEFB	8,0
	DEFB	7,0
	DEFB	"/"
	DEFB	10,0
	DEFB	9,0
	DEFB	"/"
	DEFB	12,8
	DEFB	11,0

	DEFB	088H,0
	DEFB	087H,0
	DEFB	"/"
	DEFB	0FFH,0
	DEFB	0FFH,0
	DEFB	"/"
	DEFB	0FFH,0
	DEFB	0FFH,0
	ENDIF


J186B:	RST	S.CHRGTR

	IFDEF	RTCENA
	PUSH	HL
	CALL	C1C85			; select clockchip bank 2
	LD	B,03H	; 3 
	LD	A,(OLDSCR)
	LD	C,A
	LD	A,(RG9SAV)
	RRCA
	RRCA
	AND	02H	; 2 
	OR	C
	CALL	C1B4A			; write nibble to clockchip
	LD	A,(LINLEN)
	CALL	C1B41			; write byte to clockchip
	LD	A,(FORCLR)
	CALL	C1B4A			; write nibble to clockchip
	LD	A,(BAKCLR)
	CALL	C1B4A			; write nibble to clockchip
	LD	A,(BDRCLR)
	CALL	C1B4A			; write nibble to clockchip
	LD	C,00H
	LD	A,(CNSDFG)
	OR	A
	JR	Z,J18A3
	SET	0,C
J18A3:	LD	A,(CLIKSW)
	OR	A
	JR	Z,J18AB
	SET	1,C
J18AB:	LD	A,(NTMSXP)
	OR	A
	JR	Z,J18B3
	SET	2,C
J18B3:	LD	A,(CS1200)
	LD	HL,LOW.
	CP	(HL)
	JR	Z,J18BE
	SET	3,C
J18BE:	LD	A,C
	JP	J1B7D
	ELSE
	RET
	ENDIF

C18C2:	RST	S.SYNCHR
	DEFB	"("
	CALL	C18F5
	LD	A,E
	PUSH	AF
	RST	S.SYNCHR
	DEFB	","
	CALL	C18F5
	RST	S.SYNCHR
	DEFB	")"
	POP	AF
	AND	0FH	; 15 
	LD	D,A
	CALL	C18E0

	IFDEF	RTCENA
	CALL	C1C85			; select clockchip bank 2
	LD	B,1
	LD	A,D
	JP	C1B41			; write byte to clockchip
	ELSE
	RET
	ENDIF


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C18E0:	LD	A,E
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0F0H
	OR	D
	LD	D,A
	LD	(RG18SA),A
	DI
	OUT	(VDP.CW),A
	LD	A,92H
	EI
	OUT	(VDP.CW),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C18F5:	CALL	C281E
	PUSH	HL
	EX	DE,HL
	CALL	C28B9
	EX	DE,HL
	LD	HL,7
	RST	S.DCOMPR
	JR	NC,J190B
	LD	HL,0FFF7H
	RST	S.DCOMPR
	JP	NC,J274A
J190B:	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C190D:	CALL	C2812
	PUSH	HL
	CALL	C282A
	LD	A,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	POP	HL
	RET

J191B:	CP	0C5H
	JP	Z,J186B			; SET SCREEN
	CP	0CBH
	JP	Z,J197B			; SET TIME
	CP	0C0H
	JP	Z,J1A97			; SET BEEP
	LD	DE,I1937
	CALL	C1795
	JP	C,J2744
	DEC	HL
	RST	S.CHRGTR
	PUSH	DE
	RET

I1937:	DEFM	'PAGE',00H
	DEFW	C1F91
	DEFM	'SCROLL',00H
	DEFW	C1FBF
	DEFM	'VIDEO',00H
	DEFW	C3532
	DEFM	'ADJUST',00H
	DEFW	C18C2
	DEFM	'TITLE',00H
	DEFW	C1A71
	DEFM	'PASSW',0F7H,'D',00H
	DEFW	C1ACE
	DEFM	'PROMPT',00H
	DEFW	C1AD2
	DEFM	'DATE',00H
	DEFW	C197F
	DEFB	0FFH

J197B:	RST	S.CHRGTR
	LD	A,":"
	DEFB	001H
C197F:	LD	A,"/"
	PUSH	AF
	CALL	C190D
	POP	IX
	CP	08H
	JP	NZ,J2744
	PUSH	HL
	EX	DE,HL
	CALL	C1A4F

	IF	DATFMT EQ 0

	JR	Z,J1997
	CP	24H	; "$"
	JR	NC,J19B1
J1997:	LD	B,A
	CALL	C1A47
	JR	Z,J19A1
	CP	60H	; "`"
	JR	J19A3

J19A1:	CP	13H	; 19 
J19A3:	JR	NC,J19B1
	LD	C,A
	CALL	C1A47
	JR	Z,J19AF
	CP	60H	; "`"
	JR	J19B1

J19AF:	CP	32H	; "2"
J19B1:	JP	NC,J274A
	LD	D,A

	ENDIF

	IF	DATFMT EQ 1

	JR	NZ,J199C		; time
	CP	13H			; MM max 12
	JR	NC,J19B6
J199C:	CP	24H			; hh max 23
	JR	NC,J19B6
	LD	D,A
	LD	B,A
	CALL	C1A47			; check for seperator and get digit pair
	JR	Z,J19A6			; date
	CP	60H
	JR	NC,J19B6		; mm max 59
J19A6:	CP	32H
J19A8:	JR	NC,J19B6		; DD max 31
	LD	C,A
	CALL	C1A47			; check for seperator and get digit pair
	JR	NZ,J19B4		; time
	LD	D,C			; D= day
	LD	C,B			; C= month
	LD	B,A			; B= year
	JR	J19B9
J19B4:	CP	60H			; ss max 59
J19B6:	JP	NC,J274A		; illegal function call
	LD	D,A
J19B9:
	ENDIF

	IF	DATFMT EQ 2

	JR	Z,J199C			; date
	CP	24H			; HH max 23
	JR	NC,J19B6
J199C:	CP	32H			; DD max 31
	JR	NC,J19B6
	LD	D,A
	LD	B,A
J199D:	CALL	C1A47			; check for seperator and get digit pair
	JR	NZ,J19A6		; time
	CP	13H			; MM max 12
	JR	NC,J19B6
J19A6:	CP	60H			; MM max 59
	JR	NC,J19B6
	LD	C,A
	CALL	C1A47			; check for seperator and get digit pair
	JR	NZ,J19B4		; time
	LD	B,A			; B=year
	JR	J19B9			; YY
J19B4:	CP	60H
J19B6:	JP	NC,J274A		; SS max 59, illegal function call
	LD	D,A
J19B9:


	ENDIF


	POP	HL
	PUSH	IX
	DEC	HL
	RST	S.CHRGTR
	POP	IX
	LD	A,00H
	JR	Z,J19CA
	PUSH	IX
	RST	S.SYNCHR
	DEFB	","
	RST	S.SYNCHR
	DEFB	"A"
	POP	IX
	OR	01H
J19CA:	PUSH	HL
	PUSH	AF
	PUSH	BC
	PUSH	DE
	JR	NZ,J19DB
	LD	BC,00004H		; bank 0, keep alarm bit

	IFDEF	RTCENA
	CALL	C1A3C			; write clockchip MODE register
	ENDIF

	LD	BC,00E00H		; 1 Hz test off, 16 Hz test off, reset divider stages, do not reset alarm registers
	JR	J19E9

J19DB:	LD	BC,00108H		; bank 1, keep running bit

	IFDEF	RTCENA
	CALL	C1A3C			; write clockchip MODE register
	ENDIF

	CALL	C1A5D			; date or time ?
	JR	Z,J19EE			; date, 
	LD	BC,00D00H		; 1 Hz test off, 16 Hz test off, do not reset divider stages, reset alarm registers
J19E9:
	IFDEF	RTCENA
	LD	A,15			; RESET register
	CALL	C1A3E			; write clockchip register
	ENDIF

J19EE:	POP	DE
	LD	B,0
	CALL	C1A5D			; date or time ?
	JR	NZ,J19F8		; time,
	LD	B,7
J19F8:	LD	A,D

	IFDEF	RTCENA
	CALL	C1B41			; write byte to clockchip
	ENDIF

	POP	DE
	POP	AF
	PUSH	AF
	JR	Z,J1A06
	CALL	C1A5D			; date or time ?
	JR	Z,J1A32			; date,
J1A06:	LD	A,E

	IFDEF	RTCENA
	CALL	C1B41			; write byte to clockchip
	ENDIF

	LD	A,D
	CALL	C1A5D			; date or time ?
	JR	NZ,J1A2F		; time,
	PUSH	AF
	PUSH	BC
	BIT	4,A
	JR	Z,J1A18
	ADD	A,02H	; 2 
J1A18:	AND	03H

	IFDEF	RTCENA
	PUSH	AF
	LD	A,1
	CALL	C1C87			; select clockchip bank 1
	POP	AF
	LD	B,11
	CALL	C1B4A			; write nibble to clockchip
	XOR	A
	CALL	C1C87			; select clockchip bank 0
	ENDIF

	POP	BC
	POP	AF
	SUB	80H
	DAA
J1A2F:
	IFDEF	RTCENA
	CALL	C1B41			; write byte to clockchip
	ENDIF

J1A32:	POP	AF
	POP	HL
	LD	B,04H			; set alarm bit
	JR	NZ,J1A3A

;	  Subroutine put clockchip in running state
;	     Inputs  ________________________
;	     Outputs ________________________

C1A38:	LD	B,08H			; set running bit
J1A3A:	LD	C,0FH			; mask

;	  Subroutine write clockchip MODE register
;	     Inputs  ________________________
;	     Outputs ________________________

C1A3C:	LD	A,13			; MODE register

;	  Subroutine write clockchip register
;	     Inputs  ________________________
;	     Outputs ________________________

C1A3E:
	IFDEF	RTCENA
	OUT	(0B4H),A
	IN	A,(0B5H)
	AND	C
	OR	B
	OUT	(0B5H),A
	RET
	ELSE
	RET
	ENDIF


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1A47:	PUSH	IX
	POP	AF
	CP	(HL)
	INC	HL
	JP	NZ,J2744

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1A4F:	CALL	C1A65
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0F0H
	LD	E,A
	CALL	C1A65
	OR	E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1A5D:	PUSH	BC
	PUSH	IX
	POP	BC
	BIT	4,B
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1A65:	LD	A,(HL)
	INC	HL
	SUB	30H	; "0"
	JR	C,J1A6E
	CP	0AH	; 10 
	RET	C
J1A6E:	JP	J274A

C1A71:	CP	","
	JR	Z,J1A7C
	XOR	A
	CALL	C1ADD
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J1A7C:	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	RET	NZ
	DEC	A
	CP	04H	; 4 
	JR	NC,J1A6E
	PUSH	AF

	IFDEF	RTCENA
	CALL	C1C85			; select clockchip bank 2
	LD	B,11			; register 11
	CALL	C1C60			; read nibble from clockchip register
	ELSE
	LD	A,0
	ENDIF

	AND	0CH
	LD	C,A
	POP	AF
	OR	C
	DEC	B

	IFDEF	RTCENA
	JP	C1B4A			; write nibble to clockchip
	ELSE
	RET
	ENDIF

J1A97:
	IFDEF	RTCENA
	CALL	C1C85			; select clockchip bank 2
	LD	B,10			; register 10
	CALL	C1C60			; read nibble from clockchip register
	ELSE
	IF CNTRY NE 0
	LD	A,1
	ELSE
	LD	A,0
	ENDIF
	ENDIF

	PUSH	AF
	RST	S.CHRGTR
	CP	","
	JR	Z,J1AB9
	RST	S.GETBYT
	DEC	A
	CP	04H	; 4 
	JR	NC,J1ABF
	RLCA
	RLCA
	AND	0CH	; 12 
	LD	B,A
	POP	AF
	AND	03H	; 3 
	OR	B
	PUSH	AF
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J1AC8
J1AB9:	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	DEC	A
	CP	04H	; 4 
J1ABF:	JP	NC,J274A
	LD	B,A
	POP	AF
	AND	0CH	; 12 
	OR	B
	PUSH	AF
J1AC8:	LD	B,10
	POP	AF

	IFDEF	RTCENA
	JP	C1B4A			; write nibble to clockchip
	ELSE
	RET
	ENDIF

C1ACE:	LD	A,01H	; 1 
	JR	J1AD4

C1AD2:	LD	A,02H	; 2 
J1AD4:	CALL	C1ADD
	DEC	HL
	RST	S.CHRGTR
	JP	NZ,J2744
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1ADD:	PUSH	AF
	CALL	C190D
	LD	C,A

	IFDEF	RTCENA
	CALL	C1C81			; select clockchip bank 3
	LD	B,12
	XOR	A
J1AE8:	CALL	C1B4A			; write nibble to clockchip
	DEC	B
	DJNZ	J1AE8
	ENDIF

	POP	AF

	IFDEF	RTCENA
	CALL	C1B4A			; write nibble to clockchip
	ENDIF

	PUSH	HL
	EX	DE,HL
	DEC	A
	JR	Z,J1B08
	LD	E,06H	; 6 
J1AF9:	DEC	C
	INC	C
	JR	Z,J1B06
	LD	A,(HL)
	INC	HL

	IFDEF	RTCENA
	CALL	C1B41			; write byte to clockchip
	ENDIF

	DEC	C
	DEC	E
	JR	NZ,J1AF9
J1B06:	POP	HL
	RET

J1B08:
	IFDEF	RTCENA
	LD	A,21H
	CALL	C1B41			; write byte to clockchip
	LD	A,03H	; 3 
	CALL	C1B4A			; write nibble to clockchip
	ENDIF
	LD	A,C
	PUSH	AF
	CALL	C2E07

	IFDEF	RTCENA
	LD	B,4
	LD	A,E
	CALL	C1B41			; write byte to clockchip
	LD	A,D
	CALL	C1B41			; write byte to clockchip
	ENDIF

	POP	AF
	LD	C,A
	XOR	A
	OUT	(7FH),A
	IN	A,(7FH)
	CP	0AAH
	JR	NZ,J1B06
	LD	A,C
	OR	A
	LD	A,01H	; 1 
	JR	Z,J1B33
	INC	A
J1B33:
	IFDEF	RTCENA
	CALL	C1B4A			; write nibble to clockchip
	ENDIF

	PUSH	BC
	CALL	C2DF9
	POP	BC

	IFDEF	RTCENA
	LD	A,E
	CALL	C1B41			; write byte to clockchip
	LD	A,D
	POP	HL
	ELSE
	RET
	ENDIF

;	Subroutine	write byte to clockchip
;	Inputs		A=data,B=register
;	Outputs		B=pos+2

C1B41:	PUSH	AF
	CALL	C1B4A			; write nibble to clockchip
	POP	AF
	RRCA
	RRCA
	RRCA
	RRCA

;	Subroutine	write nibble to clockchip
;	Inputs		A=data,B=register
;	Outputs		B=pos+1

C1B4A:	PUSH	AF
	LD	A,B
	OUT	(0B4H),A
	INC	B
	POP	AF
	OUT	(0B5H),A
	RET

J1B53:	PUSH	HL

	IFDEF	RTCENA
	CALL	C1BC1			; read beep settings from clockchip
	ELSE
	IF CNTRY NE 0
	LD	BC,0001H
	ELSE
	LD	BC,0000H
	ENDIF
	ENDIF

	PUSH	AF
	DEC	B
	JR	Z,J1B81
	DEC	B
	JR	Z,J1B9E
	DEC	B
	JR	Z,J1BAD
	LD	E,55H	; "U"
	CALL	C1C02
	CALL	C1C0B
	CALL	C1C23
	LD	A,08H	; 8 
	CALL	C1C0F
	LD	BC,007D0H
	CALL	C1C19
J1B77:	CALL	C277B
	POP	AF
	LD	B,13			; MODE register
J1B7D:	POP	HL

	IFDEF	RTCENA
	JP	C1B4A			; write nibble to clockchip
	ELSE
	RET
	ENDIF

J1B81:	LD	HL,I1C2F
	LD	E,0B8H
	CALL	C1C0D
	LD	E,0A7H
	LD	A,02H	; 2 
	CALL	C1C03
	LD	E,0A8H
	LD	A,04H	; 4 
	CALL	C1C03
	LD	E,0A6H
J1B99:	CALL	C1BDB
	JR	J1B77

J1B9E:	LD	HL,I1C2F
	CALL	C1C0B
	LD	E,2AH	; "*"
	CALL	C1BDB
	LD	E,35H	; "5"
	JR	J1B99

J1BAD:	LD	HL,I1C37
	CALL	C1C0B
	LD	E,6BH	; "k"
	CALL	C1BDB
	LD	E,47H	; "G"
	CALL	C1BDB
	LD	E,55H	; "U"
	JR	J1B99


;	  Subroutine read beep settings from clockchip
;	     Inputs  ________________________
;	     Outputs ________________________

C1BC1:	LD	B,13			; MODE register
	CALL	C1C60			; read nibble from clockchip register
	PUSH	AF
	CALL	C1C85			; select clockchip bank 2
	LD	B,10			; register 10
	CALL	C1C60			; read nibble from clockchip register
	LD	C,A
	RRCA
	RRCA
	AND	03H	; 3 
	LD	B,A
	LD	A,C
	AND	03H	; 3 
	LD	C,A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1BDB:	CALL	C1C02
	PUSH	BC
	PUSH	HL
	CALL	C1C23
	POP	HL
	PUSH	HL
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
J1BEA:	LD	A,08H	; 8 
	CALL	C1C0F
	LD	A,09H	; 9 
	CALL	C1C0F
	LD	A,0AH	; 10 
	CALL	C1C0F
	CALL	C1C19
	DEC	E
	JR	NZ,J1BEA
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C02:	XOR	A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C03:	CALL	C1C0F
	LD	E,00H
	INC	A
	JR	C1C0F


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C0B:	LD	E,0BEH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C0D:	LD	A,07H	; 7 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C0F:	DI
	OUT	(0A0H),A
	PUSH	AF
	LD	A,E
	EI
	OUT	(0A1H),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C19:	PUSH	BC
J1C1A:	DEC	BC
	EX	(SP),HL
	EX	(SP),HL
	LD	A,B
	OR	C
	JR	NZ,J1C1A
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C23:	LD	B,00H
	LD	HL,I1C2B
	ADD	HL,BC
	LD	E,(HL)
	RET

I1C2B:	DEFB	04H,07H,0AH,0FH
I1C2F:	DEFW	10D8H
	DEFW	09A0H
	DEFW	06BDH
	DEFW	047EH
I1C37:	DEFW	059DH
	DEFW	0335H
	DEFW	023FH
	DEFW	017FH

J1C3F:	CALL	C27C4

	IFDEF	RTCENA
	CALL	C1C81			; select clockchip bank 3
	CALL	C1C5E			; read nibble from clockchip register 0
	CP	02H
	LD	HL,M3FD7
	JP	NZ,C280C
J1C50:	CALL	C1C69			; read byte from clockchip registers
	JR	Z,J1C5B
	RST	S.OUTDO
	LD	A,B
	CP	0DH	; 13 
	JR	C,J1C50
J1C5B:	JP	J27BE
	ELSE
	LD	HL,M3FD7
	JP	C280C
	ENDIF

;	  Subroutine read nibble from clockchip register 0
;	     Inputs  ________________________
;	     Outputs ________________________

C1C5E:	LD	B,0

;	Subroutine	read nibble from clockchip register
;	Inputs		B = register
;	Outputs		A = nibble, B = register (updated)

C1C60:	LD	A,B
	OUT	(0B4H),A
	INC	B
	IN	A,(0B5H)
	AND	0FH	; 15 
	RET

;	Subroutine	read byte from clockchip registers
;	Inputs		B = register
;	Outputs		A = byte, B = register (updated)

C1C69:	PUSH	DE
	CALL	C1C60			; read nibble from clockchip register
	LD	D,A
	CALL	C1C60			; read nibble from clockchip register
	RLCA
	RLCA
	RLCA
	RLCA
	OR	D
	POP	DE
	RET


;	  Subroutine read word from clockchip
;	     Inputs  ________________________
;	     Outputs ________________________

C1C78:	CALL	C1C69			; read byte from clockchip registers
	LD	L,A
	CALL	C1C69			; read byte from clockchip registers
	LD	H,A
	RET


;	  Subroutine select clockchip bank 3
;	     Inputs  ________________________
;	     Outputs ________________________

C1C81:	LD	A,3
	JR	C1C87			; select bank


;	  Subroutine select clockchip bank 2
;	     Inputs  ________________________
;	     Outputs ________________________

C1C85:	LD	A,2

;	  Subroutine select clockchip bank
;	     Inputs  ________________________
;	     Outputs ________________________

C1C87:	PUSH	BC
	PUSH	AF
	LD	B,13			; MODE register
	CALL	C1C60			; read nibble from clockchip register
	AND	0CH			; keep running and alarm
	POP	BC
	OR	B
	OUT	(0B5H),A		; write MODE register
	POP	BC
	RET

	IFDEF	RTCENA

;	  Subroutine read nibble from clockchip register (with bank)
;	     Inputs  ________________________
;	     Outputs ________________________

J1C96:	CALL	C1CA8			; select clockchip bank and register
	IN	A,(0B5H)
	AND	0FH
	RET

;	  Subroutine write nibble to clockchip register (with bank)
;	     Inputs  ________________________
;	     Outputs ________________________

J1C9E:	PUSH	AF
	CALL	C1CA8			; select clockchip bank and register
	POP	AF
	AND	0FH
	OUT	(0B5H),A
	RET

;	  Subroutine select clockchip bank and register
;	     Inputs  ________________________
;	     Outputs ________________________

C1CA8:	LD	A,C
	PUSH	AF
	AND	30H
	RRCA
	RRCA
	RRCA
	RRCA
	CALL	C1C87			; select clockchip bank
	POP	AF
	AND	0FH	; 15 
	OUT	(0B4H),A
	RET

	ELSE

;	  Subroutine read nibble from clockchip register (with bank)
;	     Inputs  ________________________
;	     Outputs ________________________

J1C96:	PUSH	HL
	LD	A,C
	AND	03FH
	ADD	A,LOW RTCTAB
	LD	L,A
	LD	A,HIGH RTCTAB
	ADC	A,0
	LD	H,A
	LD	A,(HL)
	AND	A
	POP	HL
	RET

RTCTAB:	DEFB	00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,08H,00H,00H
	DEFB	00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,09H,00H,00H


	DEFB	003H


	DEFB	0FFH


	DEFB	0AH,00H,00H

	IF BASVER EQ 0
	DEFB	001H
	ELSE
	DEFB	000H
	ENDIF

	IF BASVER EQ 0
	DEFB	00DH,001H
	ELSE
	DEFB	005H,002H
	ENDIF

	DEFB	0FH,04H

	IF BASVER EQ 0
	DEFB	007H
	ELSE
	DEFB	004H
	ENDIF

	DEFB	03H

	IF CNTRY NE 0
	DEFB	001H
	DEFB	000H
	DEFB	CNTRY
	ELSE
	DEFB	000H
	DEFB	000H
	DEFB	000H
	ENDIF

	DEFB	0AH,00H,00H
	DEFB	00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,00H,0BH,00H,00H

;	  Subroutine write nibble to clockchip register (with bank)
;	     Inputs  ________________________
;	     Outputs ________________________

J1C9E:	AND	0FH
	RET

	ENDIF

J1CB9:	LD	A,(HL)
	EX	(SP),HL
	CP	(HL)
	JP	NZ,J2744
	INC	HL
	EX	(SP),HL
J1CC1:	CALL	H.CHRG
	INC	HL
J1CC5:	LD	A,(HL)
	CP	3AH	; ":"
	RET	NC
	CP	20H	; " "
	JR	Z,J1CC1
	JR	NC,J1D38
	OR	A
	RET	Z
	CP	0BH	; 11 
	JR	C,J1D33
	CP	1EH
	JR	NZ,J1CDE
	LD	A,(CONSAV)
	OR	A
	RET

J1CDE:	CP	10H	; 16 
	JR	Z,J1D16
	PUSH	AF
	INC	HL
	LD	(CONSAV),A
	SUB	1CH
	JR	NC,J1D1B
	SUB	0F5H
	JR	NC,J1CF5
	CP	0FEH
	JR	NZ,J1D09
	LD	A,(HL)
	INC	HL
J1CF5:	LD	(CONTXT),HL
	LD	H,00H
J1CFA:	LD	L,A
	LD	(CONLO),HL
	LD	A,02H	; 2 
	LD	(CONTYP),A
	LD	HL,M46E6
	POP	AF
	OR	A
	RET

J1D09:	LD	A,(HL)
	INC	HL
	INC	HL
	LD	(CONTXT),HL
	DEC	HL
	LD	H,(HL)
	JR	J1CFA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________
;	     Remark  UNUSED CODE

?1D13:	CALL	C1D3E

J1D16:	LD	HL,(CONTXT)
	JR	J1CC5

J1D1B:	INC	A
	RLCA
	LD	(CONTYP),A
	PUSH	DE
	PUSH	BC
	LD	DE,CONLO
	CALL	C1D77
	POP	BC
	POP	DE
	LD	(CONTXT),HL
	POP	AF
	LD	HL,M46E6
	OR	A
	RET

J1D33:	CP	09H	; 9 
	JP	NC,J1CC1
J1D38:	CP	30H	; "0"
	CCF
	INC	A
	DEC	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1D3E:	LD	A,(CONSAV)
	CP	0FH	; 15 
	JR	NC,J1D58
	CP	0DH	; 13 
	JR	C,J1D58
	LD	HL,(CONLO)
	JR	NZ,J1D55
	INC	HL
	INC	HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
J1D55:	JP	C27F4

J1D58:	LD	A,(CONTYP)
	LD	(VALTYP),A
	CP	02H	; 2 
	JR	NZ,J1D68
	LD	HL,(CONLO)
	LD	(DAC+2),HL
J1D68:	LD	HL,CONLO
	LD	DE,DAC
	LD	A,(VALTYP)
	CP	04H	; 4 
	JR	NC,C1D77
	INC	DE
	INC	DE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1D77:	LD	C,A
	LD	B,00H
	LDIR
	RET

J1D7D:	JP	Z,J1E60
	CP	0EFH
	JP	Z,J1E4F
	CP	0C7H
	JP	Z,J208B
	LD	DE,(FORCLR)
	PUSH	DE
	CP	2CH	; ","
	JR	Z,J1D9E
	RST	S.GETBYT
	CALL	C1DC7
	POP	DE
	LD	E,A
	PUSH	DE
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J1DBA
J1D9E:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1DAF
	RST	S.GETBYT
	CALL	C1DC7
	POP	DE
	LD	D,A
	PUSH	DE
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J1DBA
J1DAF:	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	CALL	C1DC7
	LD	(BDRCLR),A
	DEC	HL
	RST	S.CHRGTR
J1DBA:	EX	(SP),HL
	LD	(FORCLR),HL
	LD	A,L
	LD	(ATRBYT),A
	CALL	C09E4
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1DC7:	CALL	C1DCE
	RET	NC
	JP	J274A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1DCE:	PUSH	AF
	CALL	C2A0F
	JR	Z,J1DDF
	LD	A,(SCRMOD)
	CP	06H	; 6 
	JR	Z,J1DE7
	CP	08H	; 8 
	JR	Z,J1DE4
J1DDF:	POP	AF
	CP	10H	; 16 
	CCF
	RET

J1DE4:	POP	AF
	AND	A
	RET

J1DE7:	POP	AF
	CP	20H	; " "
	CCF
	RET	C
	CP	10H	; 16 
	JR	C,J1DF3
	AND	0FH	; 15 
	RET

J1DF3:	AND	03H	; 3 
	PUSH	BC
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	POP	BC
	RET

J1DFC:	RST	S.CHRGTR
	LD	A,0FH	; 15 
	CALL	C1E82
	PUSH	AF
	CALL	C100C
	PUSH	BC
	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1E22
	CALL	C1E80
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	E,A
	POP	BC
	LD	A,B
	AND	0FH	; 15 
	OR	E
	LD	B,A
	PUSH	BC
	DEC	HL
	RST	S.CHRGTR
	CP	29H	; ")"
	JR	Z,J1E40
J1E22:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1E34
	CALL	C1E80
	POP	BC
	LD	C,A
	PUSH	BC
	DEC	HL
	RST	S.CHRGTR
	CP	29H	; ")"
	JR	Z,J1E40
J1E34:	RST	S.SYNCHR
	DEFB	","
	CALL	C1E80
	POP	BC
	LD	A,B
	AND	0F0H
	OR	E
	LD	B,A
	PUSH	BC
J1E40:	RST	S.SYNCHR
	DEFB	")"
	POP	BC
	LD	A,B
	LD	E,C
	POP	BC
	LD	D,B
	PUSH	AF
	CALL	C10D6
	POP	AF
	JP	C1075

J1E4F:	CALL	C1E6D
	JP	C,J274A
	RST	S.CHRGTR
	CP	28H	; "("
	JR	Z,J1DFC
	CP	8CH
	JR	Z,J1E69
	RST	S.SYNCHR
	DEFB	094H			; check for NEW token
J1E60:	CALL	C1E6D
	JP	C,J274A
	JP	J1041

J1E69:	RST	S.CHRGTR
	JP	J1020


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1E6D:	LD	A,(SCRMOD)
	CP	02H	; 2 
	RET	NC
	PUSH	HL
	XOR	A
	LD	DE,1100H
	CALL	C27AC
	POP	HL
	AND	A
	RET	Z
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1E80:	LD	A,07H	; 7 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1E82:	PUSH	AF
	RST	S.GETBYT
	POP	AF
	CP	E
	LD	A,E
	RET	NC
	JP	J274A

J1E8B:	CP	2CH	; ","
	JR	Z,J1F08
	RST	S.GETBYT
	CP	0DH	; 13 
	JP	NC,J274A
	CP	09H	; 9 
	JP	Z,J274A
	PUSH	HL
	JR	C,J1EFA
	LD	HL,RG25SA
	LD	B,(HL)
	LD	C,B
	SET	3,B
	RES	4,B
	CP	0CH	; 12 
	JR	Z,J1EE8
	SET	4,B
	LD	HL,MODE
	CP	0BH	; 11 
	SET	5,(HL)
	JR	Z,J1EB7
	RES	5,(HL)
J1EB7:	BIT	3,C
	JR	Z,J1EEC
	BIT	4,C
	JR	NZ,J1EFD
	BIT	4,(HL)
	LD	HL,000D3H
	JR	Z,J1EC9
	LD	HL,000FFH
J1EC9:	PUSH	BC
	LD	(GYPOS),HL
	LD	HL,000FFH
	LD	(GXPOS),HL
	LD	A,01H	; 1 
	LD	(LOGOPR),A
	LD	A,0F7H
	LD	(ATRBYT),A
	LD	BC,0
	LD	DE,0
	CALL	C2A78
	JR	J1EF2

J1EE8:	BIT	3,C
	JR	NZ,J1EF3
J1EEC:	PUSH	BC
	LD	A,08H	; 8 
	CALL	C0A4F
J1EF2:	POP	BC
J1EF3:	LD	C,19H
	CALL	C0688
	JR	J1EFD

J1EFA:	CALL	C0A4F
J1EFD:	LD	A,(LINLEN)
	LD	E,A
	CALL	C207E
	POP	HL
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J1F08:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F25
	RST	S.GETBYT
	CP	04H	; 4 
	JP	NC,J274A
	LD	A,(RG1SAV)
	AND	0FCH
	OR	E
	LD	(RG1SAV),A
	PUSH	HL
	CALL	C076D
	POP	HL
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J1F25:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F30
	RST	S.GETBYT
	LD	(CLIKSW),A
	RET	Z
J1F30:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F3C
	CALL	C1F65
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J1F3C:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F47
	RST	S.GETBYT
	LD	(NTMSXP),A
	RET	Z
J1F47:	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	CP	04H	; 4 
	JP	NC,J274A
	ADD	A,A
	BIT	1,A
	JR	Z,J1F56
	SET	3,A
J1F56:	AND	0CH	; 12 
	LD	B,A
	LD	A,(RG9SAV)
	AND	0F3H
	OR	B
	LD	C,09H	; 9 
J1F61:	LD	B,A
	JP	C0688


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1F65:	RST	S.GETBYT
	DEC	A
	CP	02H	; 2 
	JP	NC,J274A
	PUSH	HL
	LD	BC,5
	AND	A
	LD	HL,CS1200
	JR	Z,J1F77
	ADD	HL,BC
J1F77:	LD	DE,LOW.
	LDIR
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1F7E:	PUSH	BC
	LD	B,A
	CALL	C066D
	JR	C,J1F8E
	CP	07H	; 7 
	LD	A,01H	; 1 
	JR	NC,J1F8D
	LD	A,03H	; 3 
J1F8D:	CP	B
J1F8E:	LD	A,B
	POP	BC
	RET

C1F91:	LD	DE,(DPPAGE)
	CP	2CH	; ","
	JR	Z,J1FA7
	PUSH	DE
	RST	S.GETBYT
	POP	DE
	CALL	C1F7E
J1F9F:	JP	C,J274A
	LD	E,A
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J1FB2
J1FA7:	PUSH	DE
	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	POP	DE
	CALL	C1F7E
	JR	C,J1F9F
	LD	D,A
J1FB2:	LD	(DPPAGE),DE
	PUSH	HL
	CALL	C2BE4
	CALL	C0714
	POP	HL
	RET

C1FBF:	CP	2CH	; ","
	JR	Z,J1FEA
	CALL	C281E
	LD	A,D
	CP	02H	; 2 
	JP	NC,J274A
	LD	B,E
	DEC	DE
	RR	D
	RR	E
	SRL	E
	SRL	E
	INC	E
	LD	A,E
	AND	3FH	; "?"
	LD	E,A
	LD	A,B
	NEG
	AND	07H	; 7 
	LD	D,A
	LD	(RG26SA),DE
	LD	A,(HL)
	CP	2CH	; ","
	JR	NZ,J2027
J1FEA:	RST	S.CHRGTR
	CP	2CH	; ","
	JR	Z,J1FF8
	RST	S.GETBYT
	LD	(RG23SA),A
	LD	A,(HL)
	CP	2CH	; ","
	JR	NZ,J2027
J1FF8:	RST	S.CHRGTR
	CP	2CH	; ","
	JR	Z,J2014
	RST	S.GETBYT
	CP	02H	; 2 
	JP	NC,J274A
	AND	A
	PUSH	HL
	LD	HL,RG25SA
	RES	1,(HL)
	JR	Z,J200E
	SET	1,(HL)
J200E:	POP	HL
	LD	A,(HL)
	CP	2CH	; ","
	JR	NZ,J2027
J2014:	RST	S.CHRGTR
	RST	S.GETBYT
	CP	02H	; 2 
	JP	NC,J274A
	AND	A
	PUSH	HL
	LD	HL,RG25SA
	RES	0,(HL)
	JR	Z,J2026
	SET	0,(HL)
J2026:	POP	HL
J2027:	JP	J0736

J202A:	JP	Z,J274A
	LD	A,(OLDSCR)
	AND	A
	LD	A,E
	JR	Z,J2039
	CP	21H	; "!"
	JP	NC,J274A
J2039:	CP	29H	; ")"
	JR	C,J2042
	CP	51H	; "Q"
	JP	NC,J274A
J2042:	LD	A,(LINLEN)
	CP	E
	RET	Z
	LD	A,0CH	; 12 
	RST	S.OUTDO
J204A:	LD	A,E
	LD	(LINLEN),A
	CALL	C207E
	LD	A,(OLDSCR)
	DEC	A
	LD	A,E
	JR	NZ,J205F
	LD	(LINL32),A
	LD	A,0CH	; 12 
	RST	S.OUTDO
	RET

J205F:	LD	C,29H	; ")"
	LD	A,(LINL40)
	CP	C
	LD	A,E
	LD	(LINL40),A
	PUSH	AF
	LD	A,0CH	; 12 
	RST	S.OUTDO
	POP	AF
	JR	C,J2073
	CP	C
	RET	NC
	LD	C,A
J2073:	CP	C
	RET	C
	PUSH	AF
	PUSH	HL
	XOR	A
	CALL	C0A4F
	POP	HL
	POP	AF
	LD	E,A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C207E:	SUB	0EH	; 14 
	JR	NC,C207E
	ADD	A,1CH
	CPL
	INC	A
	ADD	A,E
	LD	(CLMLST),A
	RET

J208B:	CALL	C0667
	JP	C,J274A
	RST	S.CHRGTR
	CP	24H	; "$"
	JR	Z,J20B0
	LD	A,1FH
	CALL	C2382
	PUSH	HL
	CALL	C07F1
	EX	(SP),HL
	RST	S.SYNCHR
	DEFB	0EFH			; check for =
	RST	S.GETBYT
	AND	A
	JP	M,J274A
	LD	BC,16
	EX	(SP),HL
	CALL	C0A08
	POP	HL
	RET

J20B0:	RST	S.SYNCHR
	DEFB	"$"
	LD	A,1FH
	CALL	C2382
	PUSH	HL
	CALL	C07F1
	EX	(SP),HL
	RST	S.SYNCHR
	DEFB	0EFH			; check for =
	CALL	C2812
	PUSH	HL
	CALL	C282A
	LD	A,(HL)
	CP	11H	; 17 
	JR	C,J20CC
	LD	A,10H	; 16 
J20CC:	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	POP	HL
	EX	(SP),HL
	AND	A
	LD	B,A
	EX	DE,HL
	CALL	NZ,C0FCD
	POP	HL
	RET

J20DA:	RST	S.CHRGTR
	RST	S.GETBYT
	CP	20H	; " "
	JP	NC,J274A
	LD	(BUF+2),A
	PUSH	HL
	PUSH	AF
	CALL	C07F1
	LD	(LINWRK),HL
	LD	DE,LINWRK+2
	LD	B,10H	; 16 
	CALL	C0FC4
	POP	AF
	PUSH	AF
	CALL	C07E6
	LD	(BUF+0),HL
	POP	AF
	LD	B,A
	LD	A,20H	; " "
	SUB	B
	LD	B,A
	LD	(BUF+3),A
	LD	DE,BUF+4
	PUSH	DE
	CALL	C0FC4
	POP	HL
	EX	(SP),HL
	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J2140
	CALL	C27B2
	EX	(SP),HL
	LD	(HL),E
	INC	HL
	LD	A,B
	ADD	A,A
	LD	A,C
	LD	C,00H
	JR	NC,J2125
	ADD	A,20H	; " "
	LD	C,80H
J2125:	LD	(HL),A
	PUSH	HL
	LD	HL,LINWRK+2
	LD	B,10H	; 16 
J212C:	LD	A,(HL)
	AND	7FH
	OR	C
	LD	(HL),A
	INC	HL
	DJNZ	J212C
	CALL	C21C5
	POP	HL
	INC	HL
	EX	(SP),HL
	DEC	HL
	RST	S.CHRGTR
	POP	BC
	JR	Z,J2179
	PUSH	BC
J2140:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J2164
	RST	S.GETBYT
	AND	A
	JP	M,J274A
	PUSH	HL
	LD	HL,LINWRK+2
	LD	C,A
	LD	B,10H	; 16 
J2152:	LD	A,(HL)
	AND	80H
	OR	C
	LD	(HL),A
	INC	HL
	DJNZ	J2152
	CALL	C21C5
	POP	HL
	DEC	HL
	RST	S.CHRGTR
	POP	BC
	JR	Z,J2179
	PUSH	BC
J2164:	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	CALL	C07FB
	LD	A,E
	JR	NC,J2174
	CP	40H	; "@"
	JP	NC,J274A
	ADD	A,A
	ADD	A,A
J2174:	EX	(SP),HL
	LD	(HL),A
	LD	B,H
	LD	C,L
	POP	HL
J2179:	PUSH	HL
	LD	A,(BUF+2)
	SUB	1FH
	JR	Z,J21B5
	LD	HL,(LINWRK)
	LD	A,(BUF+3)
	LD	B,A
J2188:	LD	DE,16
	ADD	HL,DE
	PUSH	HL
	PUSH	BC
	LD	DE,LINWRK+2
	LD	B,10H	; 16 
	CALL	C0FC4
	CALL	C21D2
	POP	BC
	POP	HL
	JR	Z,J219F
	DJNZ	J2188
J219F:	LD	A,(BUF+3)
	SUB	B
	JR	Z,J21B5
	LD	B,A
	LD	HL,BUF+8
	LD	DE,(BUF+4)
J21AD:	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	INC	HL
	INC	HL
	DJNZ	J21AD
J21B5:	INC	A
	ADD	A,A
	ADD	A,A
	LD	B,A
	LD	HL,BUF+4
	LD	DE,(BUF+0)
	CALL	C0FCD
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C21C5:	LD	HL,LINWRK+2
	LD	DE,(LINWRK)
	LD	B,10H	; 16 
	CALL	C0FCD
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C21D2:	LD	HL,LINWRK+2
	LD	B,10H	; 16 
J21D7:	LD	A,(HL)
	AND	40H	; "@"
	RET	NZ
	INC	HL
	DJNZ	J21D7
	XOR	A
	RET

C21E0:	DEC	B
	JP	M,J2744
	LD	A,(SCRMOD)
	CP	05H	; 5 
	JP	C,J274A
	RST	S.CHRGTR
	CP	2CH	; ","
	CALL	NZ,C27B2
	RST	S.SYNCHR
	DEFB	","
	CALL	C281E
	PUSH	DE
	CALL	C284C
	CALL	C2871
	DEC	HL
	RST	S.CHRGTR
	CP	2CH	; ","
	LD	A,00H
	JR	NZ,J220D
	RST	S.CHRGTR
	RST	S.GETBYT
J2208:	CP	03H	; 3 
	JP	NC,J274A
J220D:	POP	BC
	JP	J10EB

J2211:	LD	A,2FH	; "/"
	CALL	C2382
	CP	08H	; 8 
	JR	C,J222F
	JP	Z,J274A
	DEC	E
	DEC	A
	CP	18H
	JR	C,J222F
	JP	Z,J274A
	CP	1CH
	JR	C,J222F
	CP	20H	; " "
	JP	C,J274A
J222F:	PUSH	DE
	RST	S.SYNCHR
	DEFB	0EFH			; check for =
	RST	S.GETBYT
	POP	BC
	JP	J1F61

J2237:	RST	S.CHRGTR
	RST	S.SYNCHR
	DEFB	"("
	CALL	C281E
	RST	S.SYNCHR
	DEFB	")"
	PUSH	HL
	LD	A,D
	RLCA
	JR	C,J2269
	AND	A
	JR	NZ,J224A
	LD	A,E
	CP	1DH
J224A:	JP	NC,J274A
	CP	09H	; 9 
	JR	NC,J2256
	LD	HL,RG0SAV
	JR	J2262

J2256:	CP	19H
	JR	Z,J224A
	LD	HL,RG25SA-25-1
	JR	NC,J2262
	LD	HL,RG8SAV-8-1
J2262:	ADD	HL,DE
	LD	A,(HL)
J2264:	CALL	C27FA
	POP	HL
	RET

J2269:	EX	DE,HL
	CALL	C28B9
	EX	DE,HL
	LD	HL,9
	RST	S.DCOMPR
	JP	C,J274A
	LD	A,E
	CALL	C2BEF
	JR	J2264

J227B:	LD	A,13H	; 19 
	CALL	C2382
	LD	D,00H
	PUSH	DE
	RST	S.SYNCHR
	DEFB	0EFH
	CALL	C281E
	CP	40H	; "@"
	JP	NC,J274A
	EX	(SP),HL
	PUSH	HL
	LD	C,E
	LD	B,D
	POP	HL
	LD	A,L
	PUSH	AF
	ADD	HL,HL
	EX	DE,HL
	LD	HL,I22CA
	ADD	HL,DE
	LD	A,C
	AND	(HL)
	JR	NZ,J22A1
	INC	HL
	LD	A,B
	AND	(HL)
J22A1:	JP	NZ,J274A
	LD	HL,TXTNAM
	ADD	HL,DE
	LD	(HL),C
	INC	HL
	LD	(HL),B
	POP	AF
	LD	E,0FFH
J22AE:	INC	E
	SUB	05H	; 5 
	JR	NC,J22AE
	LD	A,(SCRMOD)
	CP	E
	CALL	Z,C22BC
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C22BC:	DEC	A
	JP	M,C0BE6
	JP	Z,C0C40
	DEC	A
	JP	Z,C0C76
	JP	C0CC6

I22CA:	DEFW	03FFH
	DEFW	003FH
	DEFW	07FFH
	DEFW	007FH
	DEFW	07FFH
	DEFW	03FFH
	DEFW	003FH
	DEFW	07FFH
	DEFW	007FH
	DEFW	07FFH
	DEFW	03FFH
	DEFW	1FFFH
	DEFW	1FFFH
	DEFW	007FH
	DEFW	07FFH
	DEFW	03FFH
	DEFW	003FH
	DEFW	07FFH
	DEFW	007FH
	DEFW	07FFH

J22F2:	RST	S.CHRGTR
	LD	A,40H	; "@"
	CALL	C2382
	CP	2DH	; "-"
	JR	C,J2307
	CP	32H	; "2"
	JP	C,J274A
J2301:	SUB	05H	; 5 
	CP	2DH	; "-"
	JR	NC,J2301
J2307:	CP	14H	; 20 
	JR	NC,J232C
	PUSH	HL
J230C:	CP	02H	; 2 
	JR	NZ,J231C
	LD	A,(LINLEN)
	CP	29H	; ")"
	JR	C,J231C
	LD	HL,1000H
	JR	J2327

J231C:	LD	HL,TXTNAM
	LD	D,00H
	ADD	HL,DE
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
J2327:	CALL	C27F4
	POP	HL
	RET

J232C:	PUSH	HL
	SUB	19H
	JR	NC,J233D
	ADD	A,0FH	; 15 
	LD	E,A
	CP	0DH	; 13 
	JR	NZ,J230C
	LD	HL,(D2348)
	JR	J2327

J233D:	LD	D,00H
	LD	E,A
	LD	HL,I234A
	ADD	HL,DE
	LD	H,(HL)
	LD	L,D
	JR	J2327

D2348:	DEFW	1E00H
I234A:	DEFB	00H,00H,00H,76H,78H,00H,00H,00H
	DEFB	76H,78H,00H,00H,00H,0FAH,0F0H,00H
	DEFB	00H,00H,0FAH,0F0H

J235E:	CALL	C2818
	PUSH	DE
	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	EX	(SP),HL
	CALL	C095C
	LD	HL,0
	CALL	C0967
	POP	HL
	RET

J2371:	CALL	C27CA
	CALL	C0967
	PUSH	AF
	LD	HL,0
	CALL	C0967
	POP	AF
	JP	C27FA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2382:	PUSH	AF
	RST	S.SYNCHR
	DEFB	"("
	RST	S.GETBYT
	POP	AF
	CP	E
	JP	C,J274A
	RST	S.SYNCHR
	DEFB	")"
	LD	A,E
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C238F:	LD	A,(VALTYP)
	CP	08H	; 8 
	JR	NC,J239B
	SUB	03H	; 3 
	OR	A
	SCF
	RET

J239B:	SUB	03H	; 3 
	OR	A
	RET

;	Subroutine	convert to integer
;	Inputs		________________________
;	Outputs		________________________
;	Remark		UNUSED CODE

?239F:	CALL	C238F
	LD	HL,(DAC+2)
	RET	M
	JP	Z,J2756
	JP	J2806

J23AC:	CP	0C5H
	JP	Z,J35F9
	LD	(BUF+0),HL
	CP	28H	; "("
	JR	Z,J242D
	CALL	C2560
	LD	(BUF+4),DE
	LD	(BUF+6),BC
	JR	NC,J23F6
	DEC	HL
	RST	S.CHRGTR
	JP	Z,J25B7
	CP	0D9H
	JR	NZ,J23D9
	RST	S.CHRGTR
	CP	28H	; "("
	JR	NZ,J23E2
	XOR	A
	LD	(BUF+17),A
	JR	J23DC

J23D9:	CALL	C2595
J23DC:	PUSH	HL
	LD	HL,J3021
	JR	J240E

J23E2:	CALL	C2560
	JP	C,J25B7
	LD	(BUF+8),DE
	LD	(BUF+10),BC
	PUSH	HL
	LD	HL,J2FE8
	JR	J2427

J23F6:	DEC	HL
	RST	S.CHRGTR
	CP	0D9H
	JR	NZ,J2407
	RST	S.CHRGTR
	CP	28H	; "("
	JR	NZ,J2415
	XOR	A
	LD	(BUF+17),A
	JR	J240A

J2407:	CALL	C2595
J240A:	PUSH	HL
	LD	HL,J2EBB
J240E:	LD	(BUF+2),HL
	POP	HL
	JP	J2513

J2415:	CALL	C2560
	JP	NC,J2744
	LD	(BUF+8),DE
	LD	(BUF+10),BC
	PUSH	HL
	LD	HL,J2FF5
J2427:	LD	(BUF+2),HL
	JP	J254E

J242D:	PUSH	HL
	LD	HL,J2E32
	LD	(BUF+2),HL
	POP	HL
	CALL	C27B2
	PUSH	BC
	PUSH	DE
	RST	S.SYNCHR
	DEFB	0F2H
	CALL	C27B8
	DEC	HL
	RST	S.CHRGTR
	CP	0D9H
	LD	A,(ACPAGE)
	JR	Z,J244B
	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
J244B:	CALL	C1F7E
	JP	C,J274A
	LD	(BUF+7),A
	POP	DE
	POP	BC
	RST	S.SYNCHR
	DEFB	0D9H
	PUSH	HL
	CALL	C1376
	LD	(BUF+4),BC
	LD	A,E
	LD	(BUF+6),A
	CALL	C28CE
	CALL	C1376
	CALL	C28CE
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C28B2
	JR	NC,J2479
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J2479:	INC	HL
	LD	(BUF+12),HL
	CALL	C28C3
	JR	NC,J2486
	EX	AF,AF'
	OR	08H	; 8 
	EX	AF,AF'
J2486:	INC	HL
	LD	(BUF+14),HL
	EX	AF,AF'
	LD	(BUF+17),A
	EX	AF,AF'
	PUSH	BC
	PUSH	DE
	LD	BC,(BUF+12)
	LD	E,L
	LD	D,H
	CALL	C32EF
	JP	C,J274A
	POP	DE
	POP	BC
	POP	HL
	DEC	HL
	RST	S.CHRGTR
	CP	28H	; "("
	JR	Z,J2513
	CALL	C2560
	LD	(BUF+8),DE
	LD	(BUF+10),BC
	JR	NC,J24BA
	PUSH	HL
	LD	HL,J312D
	JP	J250E

J24BA:	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	BC,(BUF+12)
	LD	DE,(BUF+14)
	CALL	C2FCB
	LD	A,00H
	ADD	A,A
	LD	E,A
	CALL	C25A5
	DEC	B
	JR	Z,J24F7
	DEC	B
	JR	Z,J24EA
	LD	BC,3
	ADD	HL,BC
	LD	A,E
	ADC	A,00H
	SRL	A
	RR	H
	RR	L
	SRL	A
	RR	H
	RR	L
	JR	J24F7

J24EA:	LD	BC,1
	ADD	HL,BC
	LD	A,E
	ADC	A,00H
	SRL	A
	RR	H
	RR	L
J24F7:	POP	DE
	ADD	HL,DE
	JR	C,J2508
	NOP
	LD	DE,4
	ADD	HL,DE
	JR	C,J2508
	NOP
	POP	DE
	EX	DE,HL
	AND	A
	SBC	HL,DE
J2508:	JP	C,J274A
	LD	HL,J2E58
J250E:	LD	(BUF+2),HL
	JR	J2548

J2513:	CALL	C27B8
	PUSH	HL
	CALL	C1376
	LD	(BUF+8),BC
	LD	A,E
	LD	(BUF+10),A
	POP	HL
	XOR	A
	LD	(BUF+11),A
	DEC	HL
	RST	S.CHRGTR
	LD	A,(ACPAGE)
	JR	Z,J2538
	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	LD	A,(ACPAGE)
	CALL	NZ,C2824
J2538:	CALL	C1F7E
	JP	C,J274A
	LD	(BUF+11),A
	CALL	C2871
	LD	(BUF+18),A
	PUSH	HL
J2548:	CALL	C066D
	JP	C,J274A
J254E:	LD	HL,I255A
	PUSH	HL
	LD	HL,(BUF+2)
	PUSH	HL
	LD	HL,BUF+4
	RET

I255A:	POP	HL
	JP	C,J274A
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2560:	PUSH	HL
	CALL	C2812
	LD	A,(VALTYP)
	CP	03H	; 3 
	JR	Z,J258D
	POP	HL
	LD	A,01H	; 1 
	LD	(SUBFLG),A
	CALL	C27EE
	JP	NZ,J274A
	LD	(SUBFLG),A
	PUSH	HL
	LD	H,B
	LD	L,C
	EX	DE,HL
	ADD	HL,DE
	DEC	HL
	PUSH	HL
	LD	A,(BC)
	ADD	A,A
	LD	L,A
	LD	H,00H
	INC	BC
	ADD	HL,BC
	EX	DE,HL
	POP	BC
	POP	HL
	AND	A
	RET

J258D:	PUSH	HL
	CALL	C282A
	POP	HL
	POP	DE
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2595:	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	CP	04H	; 4 
	JP	NC,J274A
	ADD	A,A
	ADD	A,A
	LD	(BUF+17),A
	RST	S.SYNCHR
	DEFB	0D9H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25A5:	LD	B,01H	; 1 
	LD	A,(SCRMOD)
	CP	08H	; 8 
	RET	Z
	INC	B
	CP	05H	; 5 
	RET	Z
	CP	07H	; 7 
	RET	Z
	INC	B
	INC	B
	RET

J25B7:	XOR	A
	LD	(SUBFLG),A
	LD	HL,(BUF+0)
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25C0:	LD	A,(LFPROG)
	LD	C,A
	LD	A,(RTPROG)
	OR	C
	RET	Z
	LD	A,(PDIREC)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25CC:	LD	B,A
	CALL	C1430
	LD	C,A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25D1:	EX	(SP),HL
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	C,02H	; 2 
	PUSH	HL
	LD	HL,(STREND)
	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	A,88H
	SUB	L
	LD	L,A
	LD	A,0FFH
	SBC	A,H
	LD	H,A
	JR	C,J25EC
	ADD	HL,SP
	POP	HL
	RET	C
J25EC:	JP	J275C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25EF:	CALL	C15A0
	LD	(SKPCNT),DE
	LD	(MOVCNT),HL
	LD	A,H
	OR	L
	LD	A,C
	LD	(RTPROG),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2600:	CALL	C1430
	PUSH	HL
	PUSH	AF
	LD	HL,(CSAVEA)
	LD	A,(CSAVEM)
	CALL	C1437
	POP	AF
	POP	HL
	LD	(CSAVEA),HL
	LD	(CSAVEM),A
	CALL	C1652
	LD	A,C
	LD	(LFPROG),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C261E:	PUSH	HL
	CALL	C1376
	JP	NC,J274A
	POP	HL
	RET

J2627:	CALL	C28B9
	DEC	HL
	DEC	HL
	LD	A,H
	ADD	A,A
	JR	C,J2644
	INC	HL
	PUSH	HL
	EX	DE,HL
	LD	HL,(CLOC)
	OR	A
	SBC	HL,DE
	LD	(CLOC),HL
	POP	DE
	LD	A,(PDIREC)
	CPL
	CALL	C25CC
J2644:	JP	J2693

;
;	Remark		UNUSED DATA
;

?2647:	DEFB	0,0,0,0,0,0,0,0,0,0

J2651:	CALL	C27B2
	PUSH	BC
	PUSH	DE
	CALL	C284C
	LD	A,(ATRBYT)
	LD	E,A
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J2664
	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
J2664:	LD	A,E
	AND	A
	CALL	C158C
	JP	C,J274A
	POP	DE
	POP	BC
	PUSH	HL
	CALL	C261E
	CALL	C13FC
	LD	DE,00001H
	CALL	C25EF
	JR	Z,J2691
	PUSH	HL
	CALL	C2600
	POP	DE
	ADD	HL,DE
	EX	DE,HL
	XOR	A
	CALL	C25CC
	LD	A,40H	; "@"
	CALL	C25CC
	LD	B,0C0H
	JR	J26B3

J2691:	POP	HL
	RET

J2693:	LD	A,(INTFLG)
	OR	A
	CALL	NZ,C2799
	LD	A,(LOHDIR)
	OR	A
	JR	Z,J26AC
	LD	HL,(LOHADR)
	PUSH	HL
	LD	HL,(LOHMSK)
	PUSH	HL
	LD	HL,(LOHCNT)
	PUSH	HL
J26AC:	POP	DE
	POP	BC
	POP	HL
	LD	A,C
	CALL	C1437
J26B3:	LD	A,B
	LD	(PDIREC),A
	ADD	A,A
	JR	Z,J2691
	PUSH	DE
	JR	NC,J26C2
	CALL	C14D9
	JR	J26C5

J26C2:	CALL	C14B6
J26C5:	POP	DE
	JR	C,J26AC
	CALL	C25EF
	JP	Z,J26AC
	XOR	A
	LD	(LOHDIR),A
	CALL	C2600
	LD	E,L
	LD	D,H
	OR	A
	JR	Z,J26F4
	DEC	HL
	DEC	HL
	LD	A,H
	ADD	A,A
	JR	C,J26F4
	LD	(LOHCNT),DE
	CALL	C1430
	LD	(LOHADR),HL
	LD	(LOHMSK),A
	LD	A,(PDIREC)
	CPL
	LD	(LOHDIR),A
J26F4:	LD	HL,(MOVCNT)
	ADD	HL,DE
	EX	DE,HL
	CALL	C25C0
	LD	HL,(CSAVEA)
	LD	A,(CSAVEM)
	CALL	C1437
J2705:	LD	HL,(SKPCNT)
	LD	DE,(MOVCNT)
	OR	A
	SBC	HL,DE
	JP	Z,J2693
	JP	C,J2627
	EX	DE,HL
	LD	B,01H	; 1 
	CALL	C25EF
	JP	Z,J2693
	OR	A
	JR	Z,J2705
	EX	DE,HL
	LD	HL,(CSAVEA)
	LD	A,(CSAVEM)
	LD	C,A
	LD	A,(PDIREC)
	LD	B,A
	CALL	C25D1
	JR	J2705

J2732:	LD	IX,M6E6B
	JR	J2766

J2738:	LD	IX,M6E86
	JR	J2766

J273E:	LD	IX,M6E6E
	JR	J2766

J2744:	LD	IX,M4055
	JR	J2766

J274A:	LD	IX,M475A
	JR	J2766

J2750:	LD	IX,M406A
	JR	J2766

J2756:	LD	IX,M406D
	JR	J2766

J275C:	LD	IX,M6275
	JR	J2766

J2762:	LD	IX,M6E74
J2766:	JP	J282E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2769:	LD	IX,RDRES
	JR	C279D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C276F:	LD	IX,WRRES
	JR	C279D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2775:	LD	IX,CHGET
	JR	C279D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C277B:	LD	IX,GICINI
	JR	C279D

J2781:	LD	IX,FNKSB
	JR	C279D

J2787:	LD	IX,OUTDO
	JR	C279D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C278D:	LD	IX,RDSLT
	JR	C279D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2793:	LD	IX,WRSLT
	JR	C279D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2799:	LD	IX,CKCNTC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C279D:	JP	J0258


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27A0:	LD	IX,SNSMAT
	JR	C279D

J27A6:	LD	IX,EOL
	JR	C279D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27AC:	LD	IX,M7FFA
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27B2:	LD	IX,M579C
	JR	J282E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27B8:	LD	IX,M57AB
	JR	J282E

J27BE:	LD	IX,M7328
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27C4:	LD	IX,M7323
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27CA:	LD	IX,M5439
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27D0:	LD	IX,M6A0E
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27D6:	LD	IX,M6B24
	JR	J280A

J27DC:	LD	IX,M406F
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27E2:	LD	IX,M3412
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27E8:	LD	IX,M3058
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27EE:	LD	IX,M5EA4
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27F4:	LD	IX,M3236
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27FA:	LD	IX,M4FCF
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2800:	LD	IX,M6627
	JR	J280A

J2806:	LD	IX,M2F92
J280A:	JR	J282E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C280C:	LD	IX,M6678
	JR	J280A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2812:	LD	IX,M4C64
	JR	J282E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2818:	LD	IX,M542F
	JR	J282E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C281E:	LD	IX,M520F
	JR	J282E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2824:	LD	IX,M521C
	JR	J282E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C282A:	LD	IX,M67D0
J282E:	CALL	C0262
	EI
	RET

J2833:	PUSH	AF
	CALL	C27B8
	POP	AF
	CALL	C284F
	CALL	C2871
	PUSH	HL
	CALL	C1376
	JR	NC,J284A
	CALL	C13FC
	CALL	C146F
J284A:	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C284C:	LD	A,(FORCLR)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C284F:	PUSH	BC
	PUSH	DE
	LD	E,A
	CALL	C0661
	JP	C,J274A
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J2863
	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J2863
	RST	S.GETBYT
J2863:	LD	A,E
	PUSH	HL
	CALL	C1467
	JP	C,J274A
	POP	HL
	POP	DE
	POP	BC
	JP	J1CC5


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2871:	LD	A,00H
	PUSH	DE
	LD	D,00H
	LD	E,A
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J28A9
	RST	S.SYNCHR
	DEFB	","
	JP	Z,J2750
	CP	2CH	; ","
	JR	Z,J28A9
	LD	E,A
	CP	54H	; "T"
	JR	Z,J28A1
	CP	0D9H
	JR	Z,J2899
	INC	A
	JR	NZ,J28A8
	RST	S.CHRGTR
	RST	S.SYNCHR
	DEFB	08DH
	RST	S.SYNCHR
	DEFB	"D"
	LD	E,0F6H
	JR	J289E

J2899:	RST	S.CHRGTR
	RST	S.SYNCHR
	DEFB	"R"
	LD	E,0F7H
J289E:	DEC	HL
	JR	J28A6

J28A1:	RST	S.CHRGTR
	JP	Z,J2744
	LD	E,A
J28A6:	LD	D,08H	; 8 
J28A8:	RST	S.CHRGTR
J28A9:	LD	A,E
	CALL	C292E
	JP	C,J2744
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28B2:	LD	HL,(GXPOS)
	AND	A
	SBC	HL,BC
J28B8:	RET	NC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28B9:	XOR	A
	SUB	L
	LD	L,A
	SBC	A,H
	SUB	L
	LD	H,A
	XOR	A
	SUB	01H	; 1 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28C3:	LD	HL,(GYPOS)
	AND	A
	SBC	HL,DE
	JR	J28B8


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28CB:	CALL	C1376

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28CE:	CALL	C28DD

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28D1:	PUSH	HL
	PUSH	BC
	LD	HL,(GXPOS)
	EX	(SP),HL
	LD	(GXPOS),HL
	POP	BC
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28DD:	PUSH	HL
	LD	HL,(GYPOS)
	EX	DE,HL
	JR	J2917

J28E4:	CALL	C27B2
	PUSH	BC
	PUSH	DE
	RST	S.SYNCHR
	DEFB	0F2H
	CALL	C27B8
	CALL	C284C
	POP	DE
	POP	BC
	DEC	HL
	RST	S.CHRGTR
	JR	Z,J291C
	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J291C
	RST	S.SYNCHR
	DEFB	"B"
	JR	Z,J2925
	CP	2CH	; ","
	JR	Z,J2925
	RST	S.SYNCHR
	DEFB	"F"
J2907:	CALL	C2871
	PUSH	HL
	CALL	C2A75
J290E:	LD	HL,(GRPACX)
	LD	(GXPOS),HL
	LD	HL,(GRPACY)
J2917:	LD	(GYPOS),HL
	POP	HL
	RET

J291C:	CALL	C2871
	PUSH	HL
	CALL	C299B
	JR	J290E

J2925:	CALL	C2871
	PUSH	HL
	CALL	C295F
	JR	J290E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C292E:	AND	A
	JR	Z,J295A
	PUSH	BC
	LD	B,A
	CALL	C066D
	LD	A,B
	POP	BC
	RET	C
	CP	0F8H
	JR	Z,J2958
	CP	0F7H
	JR	Z,J2955
	CP	0F6H
	JR	Z,J2952
	CP	0C3H
	JR	Z,J294F
	CP	0C2H
	SCF
	RET	NZ
	XOR	A
	DEFB	0C2H
J294F:	LD	A,4
	DEFB	0C2H
J2952:	LD	A,1
	DEFB	0C2H
J2955:	LD	A,2
	DEFB	0C2H
J2958:	LD	A,3
J295A:	OR	D
	LD	(LOGOPR),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C295F:	CALL	C28CB
	CALL	C28CB
	CALL	C28B2
	JR	Z,C299B
	CALL	C,C28D1
	CALL	C28C3
	JR	Z,C299B
	CALL	C,C28DD
	LD	HL,(GYPOS)
	PUSH	HL
	PUSH	DE
	EX	DE,HL
	CALL	C299B
	POP	HL
	LD	(GYPOS),HL
	EX	DE,HL
	CALL	C299B
	POP	HL
	DEC	HL
	INC	DE
	LD	(GYPOS),HL
	LD	HL,(GXPOS)
	PUSH	BC
	LD	C,L
	LD	B,H
	CALL	C299B
	POP	HL
	LD	(GXPOS),HL
	LD	C,L
	LD	B,H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C299B:	CALL	C2A1D
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(GYPOS)
	PUSH	HL
	LD	HL,(GXPOS)
	PUSH	HL
	CALL	C28CB
	CALL	C1376
	CALL	C28C3
	CALL	C,C28CE
	PUSH	DE
	PUSH	HL
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C28B2
	EX	DE,HL
	JR	NC,J29C4
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J29C4:	POP	HL
	RST	S.DCOMPR
	JR	C,J29CD
	EX	DE,HL
	EX	AF,AF'
	OR	01H	; 1 
	EX	AF,AF'
J29CD:	EX	(SP),HL
	CALL	C2BE4
	LD	A,24H	; "$"
	DI
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	A,C
	OUT	(VDP.CIW),A
	LD	C,VDP.CIW
	OUT	(C),B
	OUT	(C),L
	LD	A,(ACPAGE)
	OUT	(VDP.CIW),A
	OUT	(C),E
	OUT	(C),D
	POP	HL
	OUT	(C),L
	OUT	(C),H
	LD	A,(ATRBYT)
	OUT	(VDP.CIW),A
	EX	AF,AF'
	OUT	(VDP.CIW),A
	LD	A,(LOGOPR)
	AND	0FH	; 15 
	OR	70H	; "p"
	OUT	(VDP.CIW),A
	EI
	POP	HL
	LD	(GXPOS),HL
	POP	HL
	LD	(GYPOS),HL
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2A0F:	LD	A,(RG25SA)
	AND	18H
	CP	18H
	RET	NZ
	LD	A,(MODE)
	AND	20H	; " "
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2A1D:	CALL	C2A0F
	RET	NZ
	POP	IX
	LD	A,(LOGOPR)
	AND	A
	PUSH	AF
	EX	AF,AF'
	LD	A,(BAKCLR)
	AND	A
	PUSH	AF
	EX	AF,AF'
	LD	A,(ATRBYT)
	PUSH	AF
	JR	NZ,J2A56
	LD	A,0FH	; 15 
	LD	(ATRBYT),A
	LD	(BAKCLR),A
	LD	A,01H	; 1 
	LD	(LOGOPR),A
	PUSH	IX
	CALL	CLPRM1
	POP	IX
	LD	A,02H	; 2 
	LD	(LOGOPR),A
	POP	AF
	EX	AF,AF'
	POP	AF
	PUSH	AF
	SCF
	EX	AF,AF'
	PUSH	AF
	SCF
J2A56:	RLA
	RLA
	RLA
	RLA
	LD	(ATRBYT),A
	EX	AF,AF'
	RLA
	RLA
	RLA
	RLA
	LD	(BAKCLR),A
	CALL	CLPRM1
	POP	AF
	LD	(ATRBYT),A
	POP	AF
	LD	(BAKCLR),A
	POP	AF
	LD	(LOGOPR),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2A75:	CALL	C2A1D

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2A78:	PUSH	BC
	PUSH	DE
	CALL	C1376
	LD	L,C
	LD	H,B
	LD	A,E
	CALL	C2C09
	CALL	C28CE
	CALL	C28CB
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C28B2
	JR	NC,J2A95
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J2A95:	INC	HL
	PUSH	HL
	CALL	C28C3
	JR	NC,J2AA0
	EX	AF,AF'
	OR	08H	; 8 
	EX	AF,AF'
J2AA0:	INC	HL
	POP	DE
	CALL	C2C28
	EX	AF,AF'
	CALL	C2C3F
	EX	AF,AF'
	LD	A,(ATRBYT)
	CALL	C2C4F
	LD	A,(LOGOPR)
	AND	0FH	; 15 
	ADD	A,80H
	CALL	C2C47
	CALL	C2BE4
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AC0:	LD	B,04H	; 4 
	JR	J2ACE


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AC4:	LD	B,06H	; 6 
	JR	J2ACE


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AC8:	LD	B,02H	; 2 
	JR	J2ACE


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2ACC:	LD	B,00H
J2ACE:	LD	C,A
	CALL	C2A0F
	LD	A,C
	JR	Z,J2B38
	PUSH	BC
	CALL	C2B14
	POP	AF
	DI
	OUT	(VDP.CW),A
	LD	A,0ADH
	OUT	(VDP.CW),A
	LD	A,60H	; "`"
	OUT	(VDP.CW),A
	LD	A,0AEH
	OUT	(VDP.CW),A
	CALL	C2BE4
	AND	10H	; 16 
	RET	Z
	LD	A,08H	; 8 
	DI
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	IN	A,(VDP.CW)
	LD	L,A
	LD	A,09H	; 9 
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	IN	A,(VDP.CW)
	PUSH	AF
	XOR	A
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	EI
	POP	AF
	AND	01H	; 1 
	LD	H,A
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2B14:	PUSH	AF
	CALL	C2BE4
	LD	A,20H	; " "
	DI
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	A,L
	OUT	(VDP.CIW),A
	LD	A,H
	OUT	(VDP.CIW),A
	LD	A,E
	OUT	(VDP.CIW),A
	LD	A,(ACPAGE)
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CW),A
	LD	A,0ACH
	OUT	(VDP.CW),A
	EI
	RET

J2B38:	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	08H	; 8 
	LD	C,A
	PUSH	BC
	PUSH	HL
	LD	H,E
	LD	L,00H
	LD	DE,BUF
	LD	BC,00100H
	CALL	C082C
	POP	DE
	LD	HL,BUF
	ADD	HL,DE
	POP	BC
	LD	A,E
	INC	E
	BIT	2,B
	JR	NZ,J2B76
	NEG
	BIT	1,B
	LD	B,A
	JR	NZ,J2B6B
J2B60:	LD	A,(HL)
	AND	0F8H
	CP	C
	JR	Z,J2B91
	INC	HL
	DJNZ	J2B60
	AND	A
	RET

J2B6B:	LD	A,(HL)
	AND	0F8H
	CP	C
	JR	NZ,J2B91
	INC	HL
	DJNZ	J2B6B
	AND	A
	RET

J2B76:	BIT	1,B
	LD	B,E
	JR	NZ,J2B86
J2B7B:	LD	A,(HL)
	AND	0F8H
	CP	C
	JR	Z,J2B91
	DEC	HL
	DJNZ	J2B7B
	AND	A
	RET

J2B86:	LD	A,(HL)
	AND	0F8H
	CP	C
	JR	NZ,J2B91
	DEC	HL
	DJNZ	J2B86
	AND	A
	RET

J2B91:	LD	DE,BUF
	AND	A
	SBC	HL,DE
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2B99:	PUSH	DE
	CALL	C2C04
	XOR	A
	CALL	C2C3F
	LD	A,40H	; "@"
	CALL	C2C47
	CALL	C2BE4
	LD	A,07H	; 7 
	CALL	C2BEF
	EI
	LD	E,A
	CALL	C2A0F
	LD	A,E
	POP	DE
	RET	NZ
	AND	0F8H
	RRA
	RRA
	RRA
	RRA
	RET	C
	LD	A,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2BC0:	LD	B,A
	CALL	C2A1D
	LD	A,B
	CALL	C2C09
	LD	A,2CH	; ","
	DI
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	A,(ATRBYT)
	OUT	(VDP.CIW),A
	XOR	A
	OUT	(VDP.CIW),A
	LD	A,(LOGOPR)
	AND	0FH	; 15 
	OR	50H	; "P"
	OUT	(VDP.CIW),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2BE4:	LD	A,02H	; 2 
	CALL	C2BEF
	EI
	RRCA
	JR	C,C2BE4
	RLCA
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2BEF:	DI
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	PUSH	HL
	POP	HL
	IN	A,(VDP.CW)
	PUSH	AF
	XOR	A
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2C04:	PUSH	AF
	LD	A,20H	; " "
	JR	J2C0C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2C09:	PUSH	AF
	LD	A,24H	; "$"
J2C0C:	PUSH	AF
	CALL	C2BE4
	DI
	POP	AF
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	A,L
	OUT	(VDP.CIW),A
	LD	A,H
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CIW),A
	LD	A,(ACPAGE)
	OUT	(VDP.CIW),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2C28:	LD	A,28H	; "("
	DI
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	LD	A,E
	OUT	(VDP.CIW),A
	LD	A,D
	OUT	(VDP.CIW),A
	LD	A,L
	OUT	(VDP.CIW),A
	LD	A,H
	OUT	(VDP.CIW),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2C3F:	PUSH	AF
	DI
	OUT	(VDP.CW),A
	LD	A,0ADH
	JR	J2C55


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2C47:	PUSH	AF
	DI
	OUT	(VDP.CW),A
	LD	A,0AEH
	JR	J2C55


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2C4F:	PUSH	AF
	DI
	OUT	(VDP.CW),A
	LD	A,0ACH
J2C55:	EI
	OUT	(VDP.CW),A
	POP	AF
	RET

I2C5A:	DEFB	000H,020H,000H,000H,000H,000H,000H,000H
	DEFB	008H

	IF	INTHZ EQ 60

	DEFB	000H

	ELSE

	DEFB	002H

	ENDIF

	DEFB	000H,000H,000H,000H,000H,000H
	DEFB	000H,000H,000H,000H,000H,03BH,005H,000H
	DEFB	000H,000H,000H,000H



;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2C76:	PUSH	HL
	LD	A,0C3H
	LD	(H.NMI+0),A
	LD	HL,BUF
	LD	(H.NMI+1),HL
	LD	DE,BUF
	LD	HL,I2CB9
	LD	BC,11
	LDIR
	LD	A,(EXBRSA)
	LD	(BUF+3),A
	LD	IX,NMI
	CALL	C279D
	LD	HL,0C9C9H
	LD	(H.NMI+0),HL
	LD	(H.NMI+2),HL
	LD	A,02H	; 2 
	LD	(SCRMOD),A
	POP	HL
	CALL	C2CC4
	LD	B,02H	; 2 
	LD	HL,0
J2CB1:	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J2CB1
	DJNZ	J2CB1
	RET

I2CB9:	LD	IY,0
	LD	IX,OPTENT
	JP	CALSLT


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2CC4:	LD	A,L
	OR	H
	JR	NZ,J2CCA
	LD	L,04H	; 4 
J2CCA:	PUSH	HL
	LD	HL,00070H
	LD	A,74H	; "t"
	CALL	C2D8A
	LD	HL,I2DA4
	CALL	C2D91
	POP	HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	CALL	C2DB5
	CALL	C2D91
	LD	HL,I2DAE
	CALL	C2D91
	XOR	A
	OUT	(VDP.CW),A
	OUT	(VDP.CW),A
	OUT	(VDP.CW),A
	LD	A,8EH
	OUT	(VDP.CW),A

	IFDEF	RTCENA
	CALL	C1C81			; select clockchip bank 3
	CALL	C1C5E			; read nibble from clockchip register 0
	JR	Z,J2D73
	DEC	A
	RET	NZ
	CALL	C1C60			; read nibble from clockchip register
	CP	01H
	RET	NZ
	CALL	C1C60			; read nibble from clockchip register
	CP	02H
	RET	NZ
	CALL	C1C60			; read nibble from clockchip register
	CP	03H
	RET	NZ
	LD	B,8			; register 8
	CALL	C1C60			; read nibble from clockchip register
	JR	Z,J2D2D
	XOR	A
	OUT	(7FH),A
	IN	A,(7FH)
	CP	0AAH
	JR	NZ,J2D2D
	PUSH	BC
	CALL	C2DF9
	POP	BC
	CALL	C1C78			; read word from clockchip
	RST	S.DCOMPR
	RET	Z
	JR	J2D3E

J2D2D:	LD	A,06H	; 6 
	CALL	C27A0
	AND	04H	; 4 
	JR	NZ,J2D3E
	LD	A,07H	; 7 
	CALL	C27A0
	AND	10H	; 16 
	RET	Z
J2D3E:	LD	HL,00032H
	LD	A,90H
	CALL	C2D8A
	LD	HL,I2D9A
	CALL	C2D91
	LD	B,8			; register 8
	CALL	C1C60			; read nibble from clockchip register
	DEC	A
J2D52:	JR	Z,J2D52
J2D54:	LD	HL,BUF
	LD	B,0FFH
J2D59:	CALL	C2775
	CP	0DH	; 13 
	JR	Z,J2D64
	LD	(HL),A
	INC	HL
	DJNZ	J2D59
J2D64:	LD	A,0FFH
	SUB	B
	CALL	C2E04
	LD	B,04H	; 4 
	CALL	C1C78			; read word from clockchip
	RST	S.DCOMPR
	RET	Z
	JR	J2D54
	ENDIF

J2D73:	LD	HL,000C8H
	LD	A,88H
	CALL	C2D8A
J2D7B:
	IFDEF	RTCENA
	CALL	C1C69			; read byte from clockchip registers
	RET	Z
	CALL	C12D6
	LD	A,B
	CP	0DH	; 13 
	JR	C,J2D7B
	JP	C2775
	ELSE
	RET
	ENDIF


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2D8A:	LD	(CLOC),HL
	LD	(CMASK),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2D91:	LD	A,(HL)
	INC	HL
	OR	A
	RET	Z
	CALL	C12D6
	JR	C2D91

I2D9A:	DEFM	'Password:',00H
I2DA4:	DEFM	'Main RAM:',00H
I2DAE:	DEFM	'Kbyt'
	DEFM	'es',00H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2DB5:	LD	IX,BUF
	LD	C,00H
	LD	DE,0D8F0H
	CALL	C2DE1
	LD	DE,0FC18H
	CALL	C2DE1
	LD	DE,0FF9CH
	CALL	C2DE1
	LD	DE,0FFF6H
	CALL	C2DE1
	LD	A,L
	ADD	A,30H	; "0"
	LD	(IX),A
	LD	(IX+1),00H
	LD	HL,BUF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2DE1:	LD	A,0FFH
J2DE3:	ADD	HL,DE
	INC	A
	JR	C,J2DE3
	SBC	HL,DE
	BIT	0,C
	JR	NZ,J2DF1
	AND	A
	RET	Z
	SET	0,C
J2DF1:	ADD	A,30H	; "0"
	LD	(IX),A
	INC	IX
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2DF9:	IN	A,(7FH)
	LD	L,A
	IN	A,(7FH)
	LD	H,A
	LD	(BUF+0),HL
	LD	A,02H	; 2 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2E04:	LD	HL,BUF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2E07:	LD	DE,0
	LD	C,A
	OR	A
	RET	Z
	SCF
J2E0E:	PUSH	AF
J2E0F:	LD	B,08H	; 8 
J2E11:	POP	AF
	PUSH	AF
	JR	NC,J2E17
	RLC	(HL)
J2E17:	RL	E
	RL	D
	JR	NC,J2E25
	LD	A,D
	XOR	80H
	LD	D,A
	LD	A,E
	XOR	05H	; 5 
	LD	E,A
J2E25:	DJNZ	J2E11
	INC	HL
	DEC	C
	JR	NZ,J2E0F
	POP	AF
	RET	NC
	OR	A
	LD	C,02H	; 2 
	JR	J2E0E

J2E32:	LD	BC,(BUF+12)
	LD	DE,(BUF+14)
	CALL	C32EF
	RET	C
	CALL	C2BE4
	LD	A,20H	; " "
	CALL	C32E7
	LD	HL,BUF+4
	LD	BC,00E00H+VDP.CIW
	OTIR
	LD	A,(HL)
	AND	0FH	; 15 
	OR	90H
	OUT	(C),A
	EI
	AND	A
	RET

J2E58:	CALL	C3299
	LD	A,(SCRMOD)
	SUB	06H	; 6 
	JR	C,J2E73
	JR	Z,J2E94
	DEC	A
	JR	Z,J2E73
J2E67:	CALL	C32CD
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J2E67
	RET

J2E73:	LD	D,02H	; 2 
	LD	(HL),00H
J2E77:	CALL	C2E8C
	CALL	C32CD
	OR	(HL)
	LD	(HL),A
	DEC	BC
	LD	A,C
	OR	B
	JR	Z,J2E8A
	DEC	D
	JR	NZ,J2E77
	INC	HL
	JR	J2E73

J2E8A:	DEC	D
	RET	Z

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2E8C:	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	(HL),A
	AND	A
	RET

J2E94:	LD	D,04H	; 4 
	LD	(HL),00H
J2E98:	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	LD	(HL),A
	CALL	C32CD
	OR	(HL)
	LD	(HL),A
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J2EAA
	OR	E
	JR	Z,J2EB0
	DEC	E
J2EAA:	DEC	D
	JR	NZ,J2E98
	INC	HL
	JR	J2E94

J2EB0:	DEC	D
	RET	Z
	LD	A,(HL)
J2EB3:	ADD	A,A
	ADD	A,A
	DEC	D
	JR	NZ,J2EB3
	LD	(HL),A
	AND	A
	RET

J2EBB:	CALL	C3242
	RET	C
	CALL	C2BE4
	LD	A,20H	; " "
	CALL	C32E7
	PUSH	BC
	LD	HL,BUF+4
	LD	BC,00E00H+VDP.CIW
	OTIR
	POP	BC
	LD	A,(HL)
	AND	0FH	; 15 
	OR	0B0H
	POP	HL
	PUSH	AF
	LD	A,(SCRMOD)
	SUB	06H	; 6 
	JR	C,J2F0B
	JR	Z,J2F4D
	DEC	A
	JR	Z,J2F0B
	CALL	C32E5
	LD	A,(BUF+74)
	LD	E,A
	AND	A
	CALL	NZ,C3325
	LD	A,(HL)
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CW),A
	LD	A,0AEH
	OUT	(VDP.CW),A
	EI
J2EFA:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	INC	HL
	LD	A,E
	AND	A
	CALL	NZ,C3325
	JR	C,J2EFA
	LD	A,(HL)
	OUT	(VDP.CIW),A
	JR	J2EFA

J2F0B:	CALL	C32E5
	LD	D,0FH	; 15 
	LD	A,(BUF+74)
	LD	E,A
	AND	A
	CALL	NZ,C3325
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CW),A
	LD	A,0AEH
	OUT	(VDP.CW),A
	EI
J2F28:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	LD	A,E
	AND	A
	CALL	NZ,C3325
	JR	C,J2F37
	LD	A,(HL)
	AND	D
	OUT	(VDP.CIW),A
J2F37:	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	LD	A,E
	AND	A
I2F3E:	CALL	NZ,C3325
	JR	C,J2F28
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(VDP.CIW),A
	JR	J2F28

J2F4D:	CALL	C32E5
	LD	D,03H	; 3 
	LD	A,(BUF+74)
	AND	A
	CALL	NZ,C3325
	LD	A,(HL)
	RLCA
	RLCA
	AND	D
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CW),A
	LD	A,0AEH
	OUT	(VDP.CW),A
	EI
J2F67:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J2F70
	OR	E
	RET	Z
	DEC	E
J2F70:	LD	A,(BUF+74)
	AND	A
	CALL	NZ,C3325
	JR	C,J2F81
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(VDP.CIW),A
J2F81:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J2F8A
	OR	E
	RET	Z
	DEC	E
J2F8A:	LD	A,(BUF+74)
	AND	A
	CALL	NZ,C3325
	JR	C,J2F99
	LD	A,(HL)
	RRCA
	RRCA
	AND	D
	OUT	(VDP.CIW),A
J2F99:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J2FA2
	OR	E
	RET	Z
	DEC	E
J2FA2:	LD	A,(BUF+74)
	AND	A
	CALL	NZ,C3325
	JR	C,J2FAF
	LD	A,(HL)
	AND	D
	OUT	(VDP.CIW),A
J2FAF:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J2FB8
	OR	E
	RET	Z
	DEC	E
J2FB8:	INC	HL
	LD	A,(BUF+74)
	AND	A
	CALL	NZ,C3325
	JR	C,J2F67
	LD	A,(HL)
	RLCA
	RLCA
	AND	D
	OUT	(VDP.CIW),A
	JP	J2F67


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2FCB:	LD	HL,0
	LD	A,10H	; 16 
	AND	A
J2FD1:	PUSH	AF
	ADD	HL,HL
	JR	NC,J2FD8
	POP	AF
	SCF
	PUSH	AF
J2FD8:	EX	DE,HL
	ADD	HL,HL
	EX	DE,HL
	JR	NC,J2FE3
	ADD	HL,BC
	JR	NC,J2FE3
	POP	AF
	SCF
	PUSH	AF
J2FE3:	POP	AF
	DEC	A
	JR	NZ,J2FD1
	RET

J2FE8:	PUSH	HL
	CALL	C3234
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	E,00H
	JR	J3000

J2FF5:	PUSH	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	CALL	C3234
	POP	HL
	LD	E,01H	; 1 
J3000:	PUSH	DE
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	AND	A
	SBC	HL,BC
	INC	HL
	POP	DE
	PUSH	DE
	CALL	C334A
	POP	DE
	DEC	E
	PUSH	AF
	CALL	NZ,C33C7		; ,read from file
	POP	AF
	CALL	Z,C33B6			; ,write to file
	CALL	C33DA			; close file
	AND	A
	RET

J3021:	PUSH	HL
	CALL	C3234
	LD	HL,0
	LD	E,L
	CALL	C334A
	CALL	C33C7			; read from file
	LD	(BUF+23),HL
	LD	DE,(BUF+19)
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	DEC	HL
	CALL	C3242
	JR	C,J306C
	CALL	C2BE4
	LD	A,20H	; " "
	CALL	C32E7
	PUSH	BC
	LD	HL,BUF+4
	LD	BC,00E00H+VDP.CIW
	OTIR
	POP	BC
	LD	A,(HL)
	AND	0FH	; 15 
	OR	0B0H
	LD	HL,I306B
	EX	(SP),HL
	PUSH	AF
	LD	A,(SCRMOD)
	SUB	06H	; 6 
	JR	C,J3095
	JP	Z,J30D5
	DEC	A
	JR	Z,J3095
	JR	J3072

I306B:	AND	A
J306C:	PUSH	AF
	CALL	C33DA			; close file
	POP	AF
	RET

J3072:	CALL	C32E5
	CALL	C3320
	LD	A,(HL)
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CW),A
	LD	A,0AEH
	OUT	(VDP.CW),A
	EI
J3083:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	INC	HL
	CALL	C31F2
	CALL	C3320
	JR	C,J3083
	LD	A,(HL)
	OUT	(VDP.CIW),A
	JR	J3083

J3095:	CALL	C32E5
	LD	D,00H
	CALL	C3320
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	0FH	; 15 
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CW),A
	LD	A,0AEH
	OUT	(VDP.CW),A
	EI
J30AE:	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J30B7
	OR	E
	RET	Z
	DEC	E
J30B7:	CALL	C31F2
	LD	A,D
	RRCA
	LD	A,(HL)
	INC	HL
	JR	C,J30C5
	DEC	HL
	RRCA
	RRCA
	RRCA
	RRCA
J30C5:	PUSH	AF
	CALL	C3320
	JR	C,J30D2
	POP	AF
	AND	0FH	; 15 
	OUT	(VDP.CIW),A
	JR	J30AE

J30D2:	POP	AF
	JR	J30AE

J30D5:	CALL	C32E5
	LD	D,00H
	CALL	C3320
	LD	A,(HL)
	RLCA
	RLCA
	AND	03H	; 3 
	OUT	(VDP.CIW),A
	POP	AF
	OUT	(VDP.CW),A
	LD	A,0AEH
	OUT	(VDP.CW),A
	EI
J30EC:	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J30F5
	OR	E
	RET	Z
	DEC	E
J30F5:	CALL	C31F2
	LD	A,D
	AND	03H	; 3 
	JR	Z,J3110
	DEC	A
	JR	Z,J3118
	DEC	A
	JR	Z,J3113
	CALL	C3320
	JR	C,J310D
	LD	A,(HL)
	AND	03H	; 3 
	OUT	(VDP.CIW),A
J310D:	INC	HL
	JR	J30EC

J3110:	LD	A,(HL)
	JR	J311B

J3113:	LD	A,(HL)
	RRCA
	RRCA
	JR	J311D

J3118:	LD	A,(HL)
	RLCA
	RLCA
J311B:	RLCA
	RLCA
J311D:	PUSH	AF
	CALL	C3320
	JR	C,J312A
	POP	AF
	AND	03H	; 3 
	OUT	(VDP.CIW),A
	JR	J30EC

J312A:	POP	AF
	JR	J30EC

J312D:	PUSH	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	PUSH	HL
	CALL	C3234
	LD	HL,0
	LD	E,1
	CALL	C334A
	LD	DE,(BUF+19)
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	HL
	CALL	C3299
	LD	A,(SCRMOD)
	SUB	06H	; 6 
	JR	C,J3166
	JR	Z,J31A0
	DEC	A
	JR	Z,J3166
J3156:	CALL	C320B
	CALL	C32CD
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J3156
	JP	J31E9

J3166:	LD	D,00H
J3168:	CALL	C320B
	LD	A,07H	; 7 
	DI
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	PUSH	HL
	POP	HL
	LD	A,D
	RRCA
	IN	A,(VDP.SR)
	JR	NC,J3181
	OR	(HL)
	LD	(HL),A
	INC	HL
	JR	J3186

J3181:	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	(HL),A
J3186:	XOR	A
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	EI
	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J3168
	OR	E
	JR	Z,J319A
	DEC	E
	JR	J3168

J319A:	LD	A,D
	RRCA
	JR	C,J31EA
	JR	J31E9

J31A0:	LD	D,00H
J31A2:	CALL	C320B
	LD	A,07H	; 7 
	DI
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	PUSH	HL
	POP	HL
	LD	A,D
	AND	03H	; 3 
	JR	Z,J31C2
	DEC	A
	JR	Z,J31C8
	DEC	A
	IN	A,(VDP.SR)
	JR	Z,J31CC
	OR	(HL)
	LD	(HL),A
	INC	HL
	JR	J31D0

J31C2:	IN	A,(VDP.SR)
	RRCA
	RRCA
	JR	J31CF

J31C8:	IN	A,(VDP.SR)
	RLCA
	RLCA
J31CC:	RLCA
	RLCA
	OR	(HL)
J31CF:	LD	(HL),A
J31D0:	XOR	A
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	EI
	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J31A2
	OR	E
	JR	Z,J31E4
	DEC	E
	JR	J31A2

J31E4:	LD	A,D
	AND	03H	; 3 
	JR	NZ,J31EA
J31E9:	DEC	HL
J31EA:	CALL	C3229
	CALL	C33DA			 ; close file
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C31F2:	PUSH	DE
	PUSH	HL
	LD	HL,(BUF+19)
	LD	DE,(BUF+23)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	S.DCOMPR
	POP	DE
	RET	C
	PUSH	BC
	PUSH	DE
	CALL	C33C7			; read from file
	LD	(BUF+23),HL
	JR	J3223


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C320B:	PUSH	DE
	PUSH	HL
	LD	HL,(BUF+19)
	LD	DE,(BUF+21)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	S.DCOMPR
	POP	DE
	RET	C
	LD	HL,(BUF+21)
	PUSH	BC
	PUSH	DE
	CALL	C33B9			; write to file
	AND	A
J3223:	POP	DE
	POP	BC
	LD	HL,(BUF+19)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3229:	LD	DE,(BUF+19)
	AND	A
	SBC	HL,DE
	INC	HL
	JP	C33B9			; write to file


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3234:	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	CALL	C27D0
	LD	A,D
	CP	09H	; 9 
	RET	C
	JP	J2732


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3242:	LD	HL,(BUF+4)
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	CALL	C32EF
	RET	C
	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	HL,(BUF+8)
	LD	A,(BUF+17)
	AND	04H	; 4 
	JR	NZ,J3266
	EX	DE,HL
	CALL	C3313
	AND	A
	SBC	HL,DE
	DEFB	03EH
J3266:	INC	HL
	LD	(BUF+66),HL
	LD	(BUF+68),HL
	LD	D,B
	LD	E,C
	EX	DE,HL
	SBC	HL,DE
	JR	NC,J3277
	LD	HL,0
J3277:	LD	(BUF+70),HL
	LD	(BUF+72),HL
	LD	A,H
	OR	L
	LD	(BUF+74),A
	POP	DE
	POP	BC
	LD	(BUF+12),BC
	LD	(BUF+14),DE
	CALL	C2FCB
	LD	B,H
	LD	C,L
	LD	A,00H
	ADC	A,A
	LD	E,A
	AND	A
	POP	HL
	EX	(SP),HL
	JP	(HL)


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3299:	CALL	C2BE4
	LD	A,20H	; " "
	CALL	C32E7
	LD	HL,BUF+4
	LD	BC,00E00H+VDP.CIW
	OTIR
	LD	A,0A0H
	OUT	(C),A
	EI
	LD	BC,(BUF+12)
	LD	DE,(BUF+14)
	LD	HL,(BUF+8)
	LD	(HL),C
	INC	HL
	LD	(HL),B
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	PUSH	HL
	CALL	C2FCB
	LD	B,H
	LD	C,L
	LD	A,00H
	ADC	A,A
	LD	E,A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C32CD:	DI
	LD	A,07H	; 7 
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	PUSH	HL
	POP	HL
	IN	A,(VDP.SR)
	PUSH	AF
	XOR	A
	OUT	(VDP.CW),A
	LD	A,8FH
	OUT	(VDP.CW),A
	POP	AF
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C32E5:	LD	A,0ACH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C32E7:	DI
	OUT	(VDP.CW),A
	LD	A,91H
	OUT	(VDP.CW),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C32EF:	LD	A,B
	OR	C
	SCF
	RET	Z
	LD	A,D
	OR	E
	SCF
	RET	Z
	PUSH	HL
	PUSH	DE
	LD	E,C
	LD	D,B
	CALL	C3313
	RST	S.DCOMPR
	POP	DE
	POP	HL
	RET	C
	PUSH	HL
	LD	A,(MODE)
	AND	10H	; 16 
	LD	HL,000D4H
	JR	Z,J3310
	LD	HL,00100H
J3310:	RST	S.DCOMPR
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3313:	LD	HL,00100H
	LD	A,(SCRMOD)
	AND	06H	; 6 
	CP	06H	; 6 
	RET	NZ
	INC	H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3320:	LD	A,(BUF+74)
	AND	A
	RET	Z

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3325:	PUSH	HL
	LD	HL,(BUF+68)
	LD	A,L
	OR	H
	JR	Z,J3333
	DEC	HL
	LD	(BUF+68),HL
	POP	HL
	RET

J3333:	LD	HL,(BUF+72)
	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J3344
	LD	HL,(BUF+66)
	LD	(BUF+68),HL
	LD	HL,(BUF+70)
J3344:	LD	(BUF+72),HL
	POP	HL
	SCF
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C334A:	LD	A,(H.PHYD+0)
	CP	0C9H
	JP	Z,J274A
	PUSH	BC
	PUSH	HL
	LD	HL,BUF+25
	PUSH	HL
	LD	(HL),D
	LD	A,E
	AND	A
	PUSH	AF
	EX	DE,HL
	INC	DE
	LD	HL,FILNAM
	LD	BC,11
	LDIR
	XOR	A
	LD	B,19H
J3369:	LD	(DE),A
	INC	DE
	DJNZ	J3369
	POP	AF
	POP	DE
	PUSH	AF
	LD	C,0FH			; open file
	JR	Z,J3376
	LD	C,16H			; create file
J3376:	CALL	C33DF
	INC	A			; error ?
	JR	NZ,J3384		; nope,
	POP	AF
	JP	Z,J2762
	LD	E,43H
	JR	J33D7

J3384:	LD	HL,1
	LD	(BUF+39),HL
	POP	AF
	POP	HL
	POP	DE
	LD	A,H
	OR	L
	JR	NZ,J33AB
	LD	HL,0FE00H
	ADD	HL,SP
	JR	NC,J33A4
	LD	DE,(STREND)
	AND	A
	SBC	HL,DE
	JR	C,J33A4
	LD	A,H
	AND	A
	JR	NZ,J33AB
J33A4:	LD	DE,(NULBUF)
	LD	HL,00100H
J33AB:	LD	(BUF+19),DE
	LD	(BUF+21),HL
	LD	C,1AH
	JR	C33DF			; set dta


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C33B6:	LD	HL,(BUF+21)

;	  Subroutine Write to file
;	     Inputs  ________________________
;	     Outputs ________________________

C33B9:	LD	DE,BUF+25
	LD	C,26H
	CALL	C33DF			; random block write
	AND	A
	RET	Z
	LD	E,42H
	JR	J33D7


;	  Subroutine Read from file
;	     Inputs  ________________________
;	     Outputs ________________________

C33C7:	LD	HL,(BUF+21)
	LD	DE,BUF+25
	LD	C,27H
	CALL	C33DF			; random block read
	LD	A,L
	OR	H
	RET	NZ
	LD	E,37H
J33D7:	JP	J27DC


;	  Subroutine Close file
;	     Inputs  ________________________
;	     Outputs ________________________

C33DA:	LD	DE,BUF+25
	LD	C,10H			; close file

;	  Subroutine BDOS with mainrom in page 0 and 1 
;	     Inputs  ________________________
;	     Outputs ________________________

C33DF:	LD	IX,M7FFD
	JP	C0262


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C33E6:	LD	B,00H
	AND	7FH
	LD	C,A
	SBC	HL,BC
	RET

;	  Subroutine read lightpen status
;	     Inputs  ________________________
;	     Outputs ________________________

J33EE:	IN	A,(0BAH)
	CPL
	AND	08H	; 8 
	RET	Z
	LD	A,0FFH
	RET

;	  Subroutine read lightpen
;	     Inputs  ________________________
;	     Outputs ________________________

J33F7:	LD	HL,D.FAFF
	XOR	A
	BIT	7,(HL)
	RET	Z
	RES	7,(HL)
	IN	A,(0BAH)
	AND	07H
	LD	D,A
	IN	A,(0B8H)
	LD	L,A
	LD	H,00H
	IN	A,(0B9H)
	SRL	D
	RRA
	LD	E,A
	RL	H
	PUSH	HL
	PUSH	DE
	LD	BC,-3
	ADD	HL,BC
	EX	DE,HL
	LD	C,0EEH
	ADD	HL,BC
	LD	A,E
	OUT	(0B8H),A
	RR	D
	ADC	HL,HL
	LD	A,L
	OUT	(0B9H),A
	LD	A,H
	OUT	(0BAH),A
	POP	DE
	POP	HL
	IN	A,(0BAH)
	AND	20H
	RET	Z
	LD	A,(D.FB01)
	CALL	C33E6
	LD	BC,000D3H
	CALL	C344A
	LD	A,L
	LD	(YSAVE),A
	EX	DE,HL
	LD	A,(D.FAFF)
	CALL	C33E6
	LD	BC,000FFH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C344A:	LD	A,H
	RLA
	JR	C,J3457
	PUSH	HL
	SBC	HL,BC
	POP	HL
	JR	C,J3459
	LD	L,C
	LD	H,B
	DEFB	0DAH
J3457:	LD	L,0
J3459:	LD	A,L
	LD	(XSAVE),A
	LD	A,0FFH
	RET

J3460:	CP	8			; read lightpen ?
	JR	Z,J33F7			; yep,
	CP	11			; read lightpen status ?
	JR	Z,J33EE			; yep,
	LD	E,0FH 
	LD	BC,000BFH
	LD	HL,010EFH
	CP	12			; read mouse/trackball port 1 ?
	JR	Z,J348C			; yep,
	LD	BC,040FFH
	LD	HL,020DFH
	CP	16			; read mouse/trackball port 2 ?
	JR	Z,J348C			; yep,
	AND	03H
	SUB	02H
	LD	A,(XSAVE)
	RET	M
	LD	A,(YSAVE)
	RET	Z
	XOR	A
	RET

J348C:	DI
	CALL	C3502
	CALL	C351D
	PUSH	AF
	CALL	C3508
	CALL	C3514
	PUSH	AF
	CALL	C3502
	CALL	C351A
	PUSH	AF
	CALL	C3508
	CALL	C351A
	PUSH	AF
	CALL	C3502
	CALL	C351A
	PUSH	AF
	CALL	C3508
	CALL	C3514
	PUSH	AF
	CALL	C3502
	CALL	C352D
	CALL	C3508
	CALL	C352D
	CALL	C3502
	EI
	POP	AF
	POP	HL
	POP	DE
	POP	BC
	XOR	08H	; 8 
	SUB	02H	; 2 
	CP	0DH	; 13 
	JR	C,J34E0
	POP	AF
	CALL	C34FA
	LD	(YSAVE),A
	POP	AF
	CALL	C34FA
	JR	J34F4

J34E0:	LD	A,D
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	H
	NEG
	LD	(YSAVE),A
	POP	AF
	POP	DE
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	B
	NEG
J34F4:	LD	(XSAVE),A
	LD	A,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C34FA:	XOR	08H	; 8 
	BIT	3,A
	RET	Z
	OR	0F0H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3502:	CALL	C3525
	AND	L
	JR	J350C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3508:	CALL	C3525
	OR	H
J350C:	PUSH	AF
	LD	A,E
	OUT	(0A0H),A
	POP	AF
	OUT	(0A1H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3514:	CALL	C352D
	CALL	C352D

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C351A:	CALL	C352D

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C351D:	LD	A,0EH	; 14 
	CALL	C3526
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3525:	LD	A,E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3526:	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	C
	OR	B
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C352D:	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	RET

C3532:	CP	","
	JR	Z,J3572
	RST	S.GETBYT
	CP	04H	; 4 
	JR	NC,J35B8
	AND	A
	JR	Z,J3545
	CP	01H	; 1 
	JR	Z,J3545
	LD	E,00H
	DEC	A
J3545:	PUSH	DE
	RRCA
	RRCA
	LD	D,A
	RRCA
	RRCA
	LD	E,A
	LD	A,(RG9SAV)
	AND	0CFH
	OR	E
	LD	C,09H	; 9 
	CALL	C3637
	LD	A,D
	XOR	0C0H
	LD	E,A
	LD	A,3FH	; "?"
	CALL	C35E4
	POP	DE
	LD	A,E
	RRCA
	RRCA
	RRCA
	LD	E,A
	LD	A,(RG8SAV)
	AND	0DFH
	OR	E
	CALL	C3635
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J3572:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J3583
	CALL	C35EF
	LD	A,0DFH
	CALL	C35E4
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J3583:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J359A
	CALL	C35EF
	RRC	E
	LD	A,(RG8SAV)
	AND	0EFH
	OR	E
	CALL	C3635
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J359A:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J35AF
	CALL	C35EF
	RLCA
	RLCA
	RLCA
	LD	E,A
	LD	A,0F7H
	CALL	C35E4
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J35AF:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J35C7
	RST	S.GETBYT
	CP	04H	; 4 
J35B8:	JP	NC,J274A
	CPL
	AND	03H	; 3 
	LD	E,A
	LD	A,0FCH
	CALL	C35E4
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J35C7:	RST	S.SYNCHR
	DEFB	","
	CP	2CH	; ","
	JR	Z,J35DB
	CALL	C35EF
	RLCA
	RLCA
	LD	E,A
	LD	A,0FBH
	CALL	C35E4
	DEC	HL
	RST	S.CHRGTR
	RET	Z
J35DB:	RST	S.SYNCHR
	DEFB	","
	CALL	C35EF
	RRC	E
	LD	A,0EFH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C35E4:	PUSH	HL
	LD	HL,AVCSAV
	AND	(HL)
	OR	E
	LD	(HL),A
	OUT	(0F7H),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C35EF:	RST	S.GETBYT
	CP	02H	; 2 
	JR	NC,J35B8
	AND	A
	RET	Z
	LD	E,20H	; " "
	RET

J35F9:	RST	S.CHRGTR
	JR	Z,J3609
	CP	2CH	; ","
	JR	Z,J3609
	CALL	C35EF
	DEC	A
	JR	NZ,J3609
	LD	E,00H
	DEFB	001H
J3609:	LD	E,02H
	DEC	HL
	RST	S.CHRGTR
	LD	A,0FFH
	JR	Z,J3616
	PUSH	DE
	RST	S.SYNCHR
	DEFB	","
	RST	S.GETBYT
	POP	DE
J3616:	LD	D,A
	LD	A,(RG7SAV)
	PUSH	AF
	LD	A,D
	CALL	C3631
	CALL	C363B
	OR	40H	; "@"
	CALL	C3637
	CALL	C363B
	EI
	AND	0BFH
	CALL	C3637
	POP	AF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3631:	LD	C,07H	; 7 
	JR	C3637


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3635:	LD	C,08H	; 8 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3637:	LD	B,A
	JP	C0688


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C363B:	LD	A,02H	; 2 
	CALL	C2BEF
	AND	40H	; "@"
	JR	Z,C363B
J3644:	LD	A,02H	; 2 
	CALL	C2BEF
	BIT	6,A
	JR	NZ,J3644
	OR	E
	AND	02H	; 2 
	JR	Z,C363B
	LD	A,(RG0SAV)
	LD	C,00H
	RET

C3658:	EI
	INC	A
	JR	NZ,J3662
J365C:	CALL	C38AF
	RET	Z
	SCF
	RET

J3662:	PUSH	HL
	LD	HL,I3671-1
	ADD	A,L
	LD	L,A
	JR	NC,J366B
	INC	H
J366B:	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	EX	(SP),HL
	RET

I3671:	DEFW	C38F6
	DEFW	C397D
	DEFW	C383C
	DEFW	C39A1
	DEFW	C39FF
	DEFW	C381B
	DEFW	C3826
	DEFW	C3839
	DEFW	C385A
	DEFW	C3A4B

C3685:	DEC	HL
	RST	S.CHRGTR
	LD	DE,07FFFH
	JR	Z,J3697
	RST	S.SYNCHR
	DEFB	"("
	CALL	C281E
	JP	M,J274A
	RST	S.SYNCHR
	DEFB	")"
	RET	NZ
J3697:	PUSH	HL
	PUSH	DE
	LD	A,(SLTWRK+0)
	AND	A
	JR	Z,J36A5
	BIT	5,A
	JR	NZ,J36FA
	JR	J36FD

J36A5:	LD	HL,EXPTBL
	LD	BC,00400H
	LD	A,80H
	JR	J36AF
J36AC:	AND	03H	; 3 
	OR	(HL)
J36AF:	PUSH	BC
	PUSH	HL
	LD	H,C
J36B2:	LD	L,10H	; 16 
J36B4:	PUSH	AF
	CALL	C278D			; read slot
	CPL
	LD	E,A
	POP	AF
	PUSH	DE
	PUSH	AF
	CALL	C2793			; write slot
	POP	AF
	POP	DE
	PUSH	AF
	PUSH	DE
	CALL	C278D			; read slot
	POP	BC
	LD	B,A
	LD	A,C
	CPL
	LD	E,A
	POP	AF
	PUSH	AF
	PUSH	BC
	CALL	C2793			; write slot
	POP	BC
	LD	A,C
	CP	B			; writeable (RAM) ?
	JR	NZ,J36E9		; nope, next slot
	POP	AF
	DEC	L
	JR	NZ,J36B4
	INC	H
	INC	H
	INC	H
	INC	H
	JP	P,J36B2
	POP	HL
	POP	HL
	LD	(SLTWRK+0),A
	JR	J36FD

J36E9:	POP	AF
	POP	HL
	POP	BC
	AND	A
	JP	P,J36F6
	ADD	A,04H	; 4 
	CP	90H
	JR	C,J36AF
J36F6:	INC	HL
	INC	A
	DJNZ	J36AC
J36FA:	JP	J274A

J36FD:	BIT	6,A
	JR	Z,J3718
	LD	IX,00100H
	LD	B,20H	; " "
J3707:	CALL	C3A5B
	LD	A,(LINWRK+13)
	AND	A
	JP	NZ,J3B7C
	LD	DE,16
	ADD	IX,DE
	DJNZ	J3707
J3718:	POP	HL
	XOR	A
	LD	DE,003FFH
	SBC	HL,DE
	JR	C,J3787
	INC	H
	PUSH	HL
	LD	B,80H
	LD	C,A
	DEC	A
J3727:	INC	C
	CALL	C3A6F
	DJNZ	J3727
	LD	B,H
	XOR	A
	LD	C,A
J3730:	INC	C
	CALL	C3A6F
	DJNZ	J3730
	LD	HL,LINWRK+0
	LD	DE,LINWRK+1
	LD	C,16-1
	LD	(HL),B
	LDIR
	LD	IX,00100H
	LD	B,20H	; " "
J3747:	CALL	C3A5C
	LD	DE,16
	ADD	IX,DE
	DJNZ	J3747
	LD	HL,SLTWRK+0
	SET	6,(HL)
	POP	HL
	LD	L,B
	PUSH	HL
	CALL	C27E2
	CALL	C3812
	DEFM	' bytes allocated',13,10,0
	POP	HL
	INC	H
	INC	H
	INC	H
	LD	(LINWRK),HL
	LD	HL,LINWRK
	LD	DE,0
	LD	BC,00002H
	CALL	C3AED
	POP	HL
	RET

J3787:	XOR	A
	LD	(SLTWRK+0),A
	CALL	C3812
	DEFM	'No RAM disk',13,10,0
	POP	HL
	RET

C379E:	CALL	C3B80
	CALL	C27C4
	PUSH	HL
	LD	IX,00100H
	LD	BC,2000H
J37AC:	CALL	C3A5B
	LD	HL,LINWRK
	LD	A,(HL)
	AND	A
	JR	Z,J37E4
	INC	C
	PUSH	IX
	PUSH	BC
	LD	B,08H	; 8 
	CALL	C380C
	LD	A,(HL)
	CP	20H	; " "
	JR	Z,J37C6
	LD	A,2EH	; "."
J37C6:	RST	S.OUTDO
	LD	B,03H	; 3 
	CALL	C380C
	LD	A,(LINLEN)
	LD	B,A
	LD	A,(TTYPOS)
	AND	A
	JR	Z,J37E1
	ADD	A,0CH	; 12 
	CP	B
	JR	NC,J37DE
	LD	A,20H	; " "
	RST	S.OUTDO
J37DE:	CALL	NC,C27C4
J37E1:	POP	BC
	POP	IX
J37E4:	LD	DE,16
	ADD	IX,DE
	DJNZ	J37AC
	LD	A,C
	OR	A
	JP	Z,J2762
	CALL	C27C4
	CALL	C385A
	CALL	C27E2
	CALL	C3812
	DEFM	' bytes free',13,10,0
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C380C:	LD	A,(HL)
	INC	HL
	RST	S.OUTDO
	DJNZ	C380C
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3812:	EX	(SP),HL
	LD	A,(HL)
	INC	HL
	EX	(SP),HL
	AND	A
	RET	Z
	RST	S.OUTDO
	JR	C3812

C381B:	PUSH	HL
	POP	IY
	LD	H,(IY+5)
	LD	L,(IY+6)
	JR	J3869

C3826:	CALL	C3A52
	PUSH	HL
	POP	IY
	LD	A,(HL)
	CP	01H	; 1 
	LD	HL,(LINWRK+14)
	JR	Z,J3869
	LD	L,(IY+6)
	JR	J3869

C3839:	LD	A,(HL)
	CP	01H	; 1 
C383C:	LD	E,3DH	; "="
	JP	NZ,J3B88
	PUSH	HL
	POP	IY
	CALL	C3A52
	LD	L,(IY+6)
	LD	H,(IY+5)
	LD	DE,(LINWRK+14)
	RST	S.DCOMPR
	LD	HL,-1
	JR	NC,J3869
	INC	HL
	JR	J3869


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C385A:	LD	BC,07D01H
	LD	HL,0
J3860:	CALL	C3A6E
	JR	NZ,J3866
	INC	H
J3866:	INC	C
	DJNZ	J3860
J3869:	LD	(DAC+2),HL
	LD	A,02H	; 2 
	LD	(VALTYP),A
	RET

C3872:	CALL	C3894
	RST	S.SYNCHR
	DEFB	")"
	CALL	C3B74

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C387A:	LD	(LINWRK),A
	CALL	C3A5C
	LD	A,(LINWRK+11)
	AND	A
	RET	Z
J3885:	LD	C,A
	CALL	C3A6E
	PUSH	AF
	XOR	A
	CALL	C3A6F
	POP	AF
	CP	0FFH
	JR	NZ,J3885
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3894:	RST	S.SYNCHR
	DEFB	"("
	CALL	C3B80

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3899:	CALL	C27D0
	RET	Z
	LD	A,D
	CP	0FCH
	JR	NC,J38AC
	CP	09H	; 9 
	JR	C,J38AC
	PUSH	HL
	CALL	C38AF
	POP	HL
	RET	Z
J38AC:	JP	J2732


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C38AF:	LD	HL,PROCNM
	LD	DE,I38C4
J38B5:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J38BF
	INC	HL
	INC	DE
	OR	A
	JR	NZ,J38B5
	RET

J38BF:	SUB	"0"
	RET	NZ
	OR	(HL)
	RET

I38C4:	DEFB	"MEM0",0

C38C9:	CALL	C3894
	CALL	C3B74
	PUSH	IX
	RST	S.SYNCHR
	DEFB	"A"
	RST	S.SYNCHR
	DEFB	"S"
	CALL	C3899
	RST	S.SYNCHR
	DEFB	")"
	CALL	C3A90
	LD	E,41H	; "A"
	JP	Z,J3B88
	POP	IX
	CALL	C3A5B
J38E7:	PUSH	HL
	LD	DE,LINWRK
	LD	HL,FILNAM
	LD	BC,11
	LDIR
	POP	HL
	JR	J3918

C38F6:	CALL	C3B80
	CALL	C3A90
	PUSH	AF
	LD	A,E
	CP	04H	; 4 
	JP	Z,J2738
	CP	02H	; 2 
	JR	Z,J391B
	CP	08H	; 8 
	JR	Z,J3954
	POP	AF
	JR	NZ,J3955
	OR	A
	JR	NZ,J3959
	CALL	C3B59

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3914:	DEC	A
	LD	(LINWRK+13),A
J3918:	JP	C3A5C

J391B:	POP	AF
	JR	NZ,J3924
	OR	A
	JR	NZ,J3959
	CALL	C387A
J3924:	LD	IX,00100H
	LD	B,20H	; " "
J392A:	CALL	C3A5B
	LD	A,(LINWRK)
	AND	A
	JR	Z,J393F
	LD	DE,16
	ADD	IX,DE
	DJNZ	J392A
	LD	E,43H	; "C"
	JP	J3B88

J393F:	LD	E,02H	; 2 
	CALL	C3B59
	LD	HL,LINWRK
	LD	B,10H	; 16 
J3949:	LD	(HL),A
	INC	HL
	DJNZ	J3949
	DEC	A
	LD	(LINWRK+13),A
	JP	J38E7

J3954:	POP	AF
J3955:	JP	NZ,J2762
	OR	A
J3959:	JP	NZ,J273E
	CALL	C3B59
	LD	HL,(LINWRK+14)
	LD	(IY+5),H
	LD	(IY+6),L
	LD	L,A
	LD	(LINWRK+14),HL
	CALL	C3914
	LD	A,(LINWRK+11)
	AND	A
	RET	Z
	LD	A,(LINWRK+12)
	LD	(IY+7),A
	JP	C3AD4

C397D:	CALL	C3A52
	XOR	A
	LD	(LINWRK+13),A
	CALL	C3A5C
	LD	A,(HL)
	CP	01H	; 1 
	RET	Z
	PUSH	HL
	POP	IY
	LD	A,(IY+6)
	AND	A
	RET	Z
	CALL	C3AD5
	LD	HL,(LINWRK+14)
	LD	L,(IY+6)
	LD	(LINWRK+14),HL
	JR	J39FD

C39A1:	PUSH	HL
	POP	IY
	LD	A,(IY+6)
	AND	A
	JR	NZ,J39E0
	PUSH	HL
	PUSH	BC
	CALL	C3A52
	LD	BC,07D01H
J39B2:	CALL	C3A6E
	JR	Z,J39BF
	INC	C
	DJNZ	J39B2
	LD	E,42H	; "B"
	JP	J3B88

J39BF:	LD	A,(LINWRK+11)
	AND	A
	LD	A,C
	JR	NZ,J39C9
	LD	(LINWRK+11),A
J39C9:	LD	C,(IY+7)
	CALL	NZ,C3A6F
	LD	(LINWRK+12),A
	LD	(IY+7),A
	LD	C,A
	LD	A,0FFH
	CALL	C3A6F
	CALL	C3A5C
	POP	BC
	POP	HL
J39E0:	LD	DE,9
	ADD	HL,DE
	LD	E,(IY+6)
	ADD	HL,DE
	LD	(HL),C
	INC	(IY+6)
	RET	NZ
	CALL	C3AD5
	INC	(IY+5)
	PUSH	IY
	POP	HL
	CALL	C3A52
	LD	HL,LINWRK+15
	INC	(HL)
J39FD:	JR	C3A5C

C39FF:	PUSH	HL
	PUSH	HL
	POP	IY
	CALL	C3A52
	LD	L,(IY+6)
	LD	H,(IY+5)
	LD	DE,(LINWRK+14)
	RST	S.DCOMPR
	POP	HL
	CCF
	RET	C
	LD	A,(IY+3)
	AND	A
	LD	(IY+3),00H
	RET	NZ
	LD	A,(IY+6)
	AND	A
	JR	Z,J3A32
	LD	BC,9
	ADD	HL,BC
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	INC	(IY+6)
	RET	NZ
	INC	(IY+5)
	RET

J3A32:	LD	A,(IY+7)
	AND	A
	LD	C,A
	LD	A,(LINWRK+11)
	CALL	NZ,C3A6E
	LD	(IY+7),A
	CALL	C3AD4
	LD	A,(IY+9)
	INC	(IY+6)
	AND	A
	RET

C3A4B:	PUSH	HL
	POP	IY
	LD	(IY+3),C
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3A52:	INC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	BC
	POP	IX
	DEC	HL
	DEC	HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3A5B:	DEFB	0F6H

C3A5C:	SCF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	IX
	POP	HL
	LD	DE,LINWRK
	JR	NC,J3A69
	EX	DE,HL
J3A69:	LD	BC,16
	JR	J3A85


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3A6E:	DEFB	0F6H

C3A6F:	SCF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,0007FH
	LD	B,00H
	ADD	HL,BC
	LD	DE,LINWRK+16
	POP	AF
	JR	NC,J3A82
	EX	DE,HL
	LD	(HL),A
J3A82:	LD	BC,00001H
J3A85:	CALL	C3AED
	POP	BC
	POP	DE
	POP	HL
	LD	A,(LINWRK+16)
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3A90:	PUSH	HL
	PUSH	DE
	LD	DE,FILNAM
	LD	B,11
J3A97:	LD	A,(DE)
	CP	61H	; "a"
	JR	C,J3AA3
	CP	7BH	; "{"
	JR	NC,J3AA3
	AND	0DFH
	LD	(DE),A
J3AA3:	INC	DE
	DJNZ	J3A97
	LD	IX,00100H
	LD	C,20H	; " "
J3AAC:	CALL	C3A5B
	LD	HL,LINWRK
	LD	A,(HL)
	AND	A
	JR	NZ,J3AC1
J3AB6:	LD	DE,16
	ADD	IX,DE
	DEC	C
	JR	NZ,J3AAC
	INC	C
	JR	J3ACE

J3AC1:	LD	DE,FILNAM
	LD	B,11
J3AC6:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J3AB6
	INC	DE
	INC	HL
	DJNZ	J3AC6
J3ACE:	POP	DE
	POP	HL
	LD	A,(LINWRK+13)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3AD4:	DEFB	0F6H

C3AD5:	SCF
	PUSH	AF
	PUSH	IY
	POP	HL
	LD	BC,9
	ADD	HL,BC
	LD	E,00H
	LD	A,(IY+7)
	ADD	A,02H	; 2 
	LD	D,A
	POP	AF
	JR	C,J3AEA
	EX	DE,HL
J3AEA:	LD	BC,00100H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3AED:	LD	A,H
	AND	A
	JP	P,J3AF3
	LD	A,D
J3AF3:	CP	40H	; "@"
	EXX
	LD	HL,D.FFFF
	LD	A,(SLTWRK+0)
	LD	D,A
	JR	C,J3B3A
	RRCA
	RRCA
	AND	0C0H
	LD	C,A
	RRCA
	RRCA
	RRCA
	RRCA
	OR	C
	LD	C,A
	IN	A,(0A8H)
	LD	B,A
	AND	33H	; "3"
	OR	C
	LD	E,A
	DI
	OUT	(0A8H),A
	LD	A,D
	AND	0CH	; 12 
	LD	D,A
	LD	A,(HL)
	CPL
	LD	C,A
	AND	0F3H
	OR	D
	LD	(HL),A
	LD	A,E
	AND	3FH	; "?"
	LD	D,A
	LD	A,B
	AND	0C0H
	OR	D
	EI
	OUT	(0A8H),A
	EXX
	LDIR
	EXX
	LD	A,E
	DI
	OUT	(0A8H),A
	LD	A,C
	LD	(HL),A
	LD	A,B
	EI
	OUT	(0A8H),A
	EXX
	RET

J3B3A:	RRCA
	RRCA
	AND	0C0H
	LD	C,A
	LD	A,D
	AND	03H	; 3 
	OR	C
	LD	C,A
	IN	A,(0A8H)
	LD	B,A
	AND	3CH	; "<"
	OR	C
	LD	E,A
	LD	A,D
	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	LD	A,E
	DI
	CALL	M51D7
	EI
	EXX
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3B59:	PUSH	HL
	POP	IY
	PUSH	IX
	POP	BC
	LD	(IY+1),C
	LD	(IY+2),B
	XOR	A
	LD	(IY+3),A
	LD	(IY+5),A
	LD	(IY+6),A
	LD	(PTRFIL),HL
	LD	(HL),E
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3B74:	CALL	C3A90
	JP	NZ,J2762
	AND	A
	RET	Z
J3B7C:	LD	E,40H	; "@"
	JR	J3B88


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3B80:	LD	A,(SLTWRK+0)
	BIT	6,A
	RET	NZ
	LD	E,46H	; "F"
J3B88:	XOR	A
	LD	(NLONLY),A
	PUSH	DE
	CALL	C27D6
	POP	DE
	JP	J27DC

I3B94:	LD	BC,I3BB7
J3B97:	LD	A,(BC)
	INC	BC
	OR	A
	RET	Z
	SUB	E
	JR	Z,J3BA2
	INC	BC
	INC	BC
	JR	J3B97

J3BA2:	LD	L,C
	LD	H,B
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,BUF
	PUSH	HL
	LD	(HL),A
J3BAC:	INC	DE
	INC	HL
	LD	A,(DE)
	LD	(HL),A
	OR	A
	JR	NZ,J3BAC
	POP	HL
	LD	E,01H	; 1 
	RET

I3BB7:	DEFB	3DH
	DEFW	I3BCA-1
	DEFB	40H
	DEFW	I3BD8-1
	DEFB	41H
	DEFW	I3BE8-1
	DEFB	42H
	DEFW	I3BFC-1
	DEFB	43H
	DEFW	I3C0A-1
	DEFB	46H
	DEFW	I3C19-1
	DEFB	0

I3BCA:	DEFM	'Bad file mode',00H
I3BD8:	DEFM	'File still open',00H
I3BE8:	DEFM	'File already exists',00H
I3BFC:	DEFM	'RAM disk full',00H
I3C0A:	DEFM	'Too many files',00H
I3C19:	DEFM	'RAM disk offline',00H

; *************************************
; PUTCHR and KYKLOK
; *************************************

	IF	KEYTYP EQ 0

; Japanese version

; routine to handle special keys (non letter) in SHIFT KANA mode

J3C2A:	LD	HL,KANAMD
	INC	(HL)
	DEC	(HL)
	LD	B,08H	; 8 
	LD	DE,I3ED1
	LD	HL,I3EC1
	JR	Z,J3C3C
	LD	HL,I3EC9
J3C3C:	CP	(HL)
	JR	Z,J3C49
	INC	HL
	INC	DE
	DJNZ	J3C3C
J3C43:	CALL	C3E54
	JP	J3D4A

J3C49:	LD	A,(DE)
	JR	J3C43

J3C4C:	PUSH	AF
	CALL	C3E6A
	POP	AF
	JR	Z,J3C58
	LD	HL,MODE
	BIT	0,(HL)
J3C58:	JP	Z,C3E54
	CP	41H	; "A"
	JR	C,J3C2A
	CP	5BH	; "["
	JR	C,J3C6F
	CP	61H	; "a"
	JR	C,J3C2A
	CP	7BH	; "{"
	JR	NC,J3C2A
	RES	7,(HL)
	JR	J3C71

J3C6F:	SET	7,(HL)
J3C71:	CP	61H	; "a"
	JR	C,J3C77
	SUB	20H	; " "
J3C77:	LD	D,A
	CP	58H	; "X"
	JR	Z,J3C98
	LD	A,(CHRCNT)
	OR	A
	JR	NZ,J3C9D
	LD	A,D
	CALL	C3DB2
	LD	A,D
	JP	NZ,C3E39
	CALL	C3DA3
	CP	80H
	RET	NC
	LD	A,D
	LD	(ROMA+0),A
	LD	A,01H	; 1 
	JR	J3CD8

J3C98:	LD	A,0B0H
	JP	J3C43

J3C9D:	DEC	A
	LD	A,D
	JR	NZ,J3CDA
J3CA1:	LD	E,A
	CALL	C3DB2
	LD	A,(ROMA+0)
	JR	Z,J3CAF
	CALL	C3DC0
	JR	J3CBB

J3CAF:	CP	E
	JR	NZ,J3CC2
	CP	4EH	; "N"
	JR	NZ,J3CBE
	LD	A,0FDH
	CALL	C3E3F
J3CBB:	JP	J3D4A

J3CBE:	LD	A,8FH
	JR	J3CD0

J3CC2:	CP	4EH	; "N"
	LD	A,E
	JR	NZ,J3CD3
	CP	59H	; "Y"
	JR	Z,J3CD3
	LD	(ROMA+0),A
	LD	A,0FDH
J3CD0:	JP	C3E3F

J3CD3:	LD	(ROMA+1),A
	LD	A,02H	; 2 
J3CD8:	JR	J3D4B

J3CDA:	LD	HL,ROMA
	LD	D,(HL)
	INC	HL
	LD	B,(HL)
	LD	C,A
	PUSH	BC
	CALL	C3DB2
	POP	BC
	JR	NZ,J3CF5
	LD	A,B
	LD	(ROMA+0),A
	LD	A,01H	; 1 
	LD	(CHRCNT),A
	LD	A,C
	JP	J3CA1

J3CF5:	LD	A,B
	CP	59H	; "Y"
	JR	NZ,J3D20
	LD	A,D
	CP	43H	; "C"
	JR	Z,J3D13
	CP	4CH	; "L"
	JR	Z,J3D44
	CP	46H	; "F"
	JR	Z,J3D1C
	CP	57H	; "W"
	JR	Z,J3D75
	LD	E,49H	; "I"
	PUSH	BC
	CALL	C3DC0
	JR	J3D19

J3D13:	LD	A,0E1H
J3D15:	PUSH	BC
	CALL	C3E3F
J3D19:	POP	BC
	JR	J3D44

J3D1C:	LD	A,0ECH
	JR	J3D15

J3D20:	LD	A,B
	CP	48H	; "H"
	JR	NZ,J3D5F
	LD	A,D
	CP	43H	; "C"
	JR	Z,J3D3A
	CP	44H	; "D"
	JR	Z,J3D4F
	CP	54H	; "T"
	JR	Z,J3D58
	CP	53H	; "S"
	JR	NZ,J3D75
	LD	A,9CH
	JR	J3D3C

J3D3A:	LD	A,0E1H
J3D3C:	CALL	C3E3F
J3D3F:	LD	A,C
	CP	49H	; "I"
	JR	Z,J3D4A
J3D44:	LD	A,4AH	; "J"
	LD	E,C
	CALL	C3E3C
J3D4A:	XOR	A
J3D4B:	LD	(CHRCNT),A
	RET

J3D4F:	LD	A,0E3H
	CALL	C3E3F
	LD	A,0DEH
	JR	J3D5A

J3D58:	LD	A,0E3H
J3D5A:	CALL	C3E3F
	JR	J3D44

J3D5F:	LD	A,D
	CP	54H	; "T"
	JR	NZ,J3D75
	LD	A,B
	CP	53H	; "S"
	JR	NZ,J3D75
	LD	A,C
	CP	55H	; "U"
	JR	NZ,J3D75
	LD	A,0E2H
	CALL	C3E3F
	JR	J3D4A

J3D75:	LD	A,B
	LD	E,C
	CALL	C3DC0
	JR	J3D4A


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3D7C:	CALL	C3DAC
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	LD	D,A
	LD	A,E
	CALL	C3DB2
	ADD	A,D
	LD	L,A
	LD	A,D
	CP	0FH	; 15 
	JR	NC,J3D93
	LD	A,L
	SUB	70H	; "p"
	RET

J3D93:	CP	23H	; "#"
	JR	NC,J3D9B
	LD	A,L
	SUB	30H	; "0"
	RET

J3D9B:	LD	A,L
	SUB	23H	; "#"
	LD	BC,I3EF4
	JR	J3DA6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3DA3:	LD	BC,I3E99
J3DA6:	LD	L,A
	LD	H,00H
	ADD	HL,BC
	LD	A,(HL)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3DAC:	CALL	C3DA3
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3DB2:	CALL	C3DA3
	SUB	14H	; 20 
	CP	01H	; 1 
	JR	C,J3DBE
	CP	06H	; 6 
	RET	C
J3DBE:	XOR	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3DC0:	LD	D,A
	CALL	C3DA3
	CP	0BH	; 11 
	JR	NC,J3DCB
	LD	A,D
	JR	J3E0D

J3DCB:	CP	21H	; "!"
	JR	C,J3DDB
	CP	26H	; "&"
	JR	NC,J3DDB
	LD	A,D
	CALL	C3E3C

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3DD7:	LD	A,0DEH
	JR	C3E3F

J3DDB:	LD	A,D
	CP	50H	; "P"
	JR	NZ,J3DEA
	LD	A,48H	; "H"
	CALL	C3E3C
	LD	A,0DFH
	JP	C3E3F

J3DEA:	CP	4AH	; "J"
	JR	NZ,J3DFC
	LD	A,9CH
	PUSH	DE
	CALL	C3E3F
	CALL	C3DD7
	POP	DE
	LD	C,E
	JP	J3D3F

J3DFC:	CP	46H	; "F"
	JR	NZ,J3E0F
	LD	A,0ECH
	PUSH	DE
	CALL	C3E3F
J3E06:	POP	DE
	LD	A,E
	CP	55H	; "U"
	RET	Z
J3E0B:	LD	A,4CH	; "L"
J3E0D:	JR	C3E3C

J3E0F:	CP	59H	; "Y"
	JR	NZ,J3E19
	CALL	C3E3C
	LD	A,E
	JR	J3E25

J3E19:	CP	57H	; "W"
	JR	NZ,J3E2A
	CALL	C3E3C
	LD	A,E
	CP	49H	; "I"
	JR	Z,J3E0B
J3E25:	CP	45H	; "E"
	RET	NZ
	JR	J3E0B

J3E2A:	CP	56H	; "V"
	JR	NZ,J3E3A
	LD	A,55H	; "U"
	PUSH	DE
	CALL	C3E39
	CALL	C3DD7
	JR	J3E06


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E39:	LD	E,A
J3E3A:	LD	A,51H	; "Q"

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E3C:	CALL	C3D7C

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E3F:	LD	HL,MODE
	BIT	7,(HL)
	JR	Z,C3E54
	CP	0E0H
	JR	C,J3E4E
	SUB	20H	; " "
	JR	C3E54

J3E4E:	CP	0A0H
	JR	NC,C3E54
	ADD	A,20H	; " "

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E54:	LD	HL,(PUTPNT)
	LD	(HL),A
	INC	HL
	LD	A,L
	CP	18H
	JR	NZ,J3E61
	LD	HL,KEYBUF
J3E61:	LD	A,(GETPNT)
	CP	L
	RET	Z
	LD	(PUTPNT),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E6A:	LD	A,(CLIKSW)
	AND	A
	RET	Z
	LD	A,(CLIKFL)
	AND	A
	RET	NZ
	LD	A,0FH	; 15 
	LD	(CLIKFL),A
	DI
	OUT	(0ABH),A
	LD	A,0AH	; 10 
J3E7E:	DEC	A
	JR	NZ,J3E7E
	LD	A,0EH	; 14 
	OUT	(0ABH),A
	EI
	RET

J3E87:	LD	HL,MODE
	BIT	0,(HL)
	JR	Z,J3E93
	RES	0,(HL)
	XOR	A
	JR	J3EAC

J3E93:	LD	A,(KANAST)
	INC	A
	JR	Z,J3EA9
I3E99:	LD	A,(NEWKEY+6)
	RRCA
	JR	C,J3EA7
	XOR	A
	LD	(CHRCNT),A
	SET	0,(HL)
	JR	J3EAC

J3EA7:	LD	A,0FFH
J3EA9:	LD	(KANAST),A
J3EAC:	PUSH	AF
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	LD	B,A
	POP	AF
	OR	A
	LD	A,80H
	JR	Z,J3EBD
	XOR	A
J3EBD:	OR	B
	OUT	(0A1H),A
	RET

I3EC1:	DEFB	2AH,3AH,5DH,5FH,3FH,3EH,7BH,7DH
I3EC9:	DEFB	5CH,40H,3EH,3FH,5BH,3CH,7BH,7DH
I3ED1:	DEFB	0B0H,0DEH,0A1H,0A5H,0DFH,0A4H,0A2H,0A3H
	DEFB	0AH,15H,25H,28H,23H,18H,40H,21H
	DEFB	05H,16H,4BH,01H,0AH,06H,04H,19H
	DEFB	28H,80H,08H,02H,03H,17H,40H,49H
	DEFB	8CH,47H,22H
I3EF4:	DEFB	0FDH,0F4H,92H,0F5H,92H,0F6H,0F7H,0F8H
	DEFB	0F9H,0FAH,0FBH,0FCH,93H,93H,93H,86H
	DEFB	87H,88H,89H,8AH,8BH
	DEFB	8CH,88H,8DH,8AH,8EH


	ENDIF

	IF	KEYTYP NE 0

; International version, officially not needed

;	Subroutine	PUTCHR
;	Inputs		________________________
;	Outputs		________________________

J3C4C:	PUSH	AF
	CALL	C3E78			; keyclick
	POP	AF

;	Subroutine	__________________________
;	Inputs		________________________
;	Outputs		________________________

C3E62:	LD	HL,(PUTPNT)
	LD	(HL),A
	INC	HL
	LD	A,L
	CP	(KEYBUF+40) AND 255
	JR	NZ,J3E6F
	LD	HL,KEYBUF
J3E6F:	LD	A,(GETPNT)
	CP	L
	RET	Z
	LD	(PUTPNT),HL
	RET

;	Subroutine	KYKLOK
;	Inputs		________________________
;	Outputs		________________________

J3E87:	LD	A,(NEWKEY+6)
	LD	E,A
	OR	0FEH			; only SHIFT status remains
	BIT	4,E
	JR	NZ,J3E96		; CODE not pressed,
	AND	0FDH
J3E96:	CPL
	INC	A
	LD	(KANAST),A		; dead status



;	Subroutine	keyclick
;	Inputs		________________________
;	Outputs		________________________

C3E78:	LD	A,(CLIKSW)
	AND	A
	RET	Z
	LD	A,(CLIKFL)
	AND	A
	RET	NZ
	LD	A,0FH
	LD	(CLIKFL),A
	DI
	OUT	(0ABH),A
	LD	A,0AH
J3E8C:	DEC	A
	JR	NZ,J3E8C		; wait 0.05 ms (in Z80 mode!)
	LD	A,0EH
	OUT	(0ABH),A
	EI
	RET

	ENDIF

; *************************************
; End of PUTCHR and KYKLOK
; *************************************

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3F8B:	LD	A,B
	AND	03H			; current primairy slot page 0
	LD	L,A
	RLCA
	RLCA
	OR	L
	LD	L,A			; OR mask page 0 and 3
	LD	A,D
	CPL
	AND	L
	LD	L,A
	LD	A,D			; AND mask page
	AND	B
	OR	L			; select page 0 and 3
	LD	L,A
	LD	A,B
	AND	3FH
	LD	H,A			; current primairy slot page
	LD	A,B
	AND	03H
	RRCA
	RRCA
	OR	H
	LD	H,A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3FA7:	LD	A,E
	RLCA
	RLCA
	OR	E
	RLCA
	RLCA
	LD	C,A
	LD	A,D
	CPL
	AND	C
	LD	C,A
	LD	A,B
	AND	D
	OR	C
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3FB6:	AND	03H
	ADD	A,LOW SLTTBL
	LD	L,A
	LD	H,HIGH SLTTBL
	RET

	DEFS	03FF0H-$,0

C3FF0:	LD	A,(EXPTBL+0)
	ADD	A,A			; MSXUP already initialized ?
	RET	Z			; nope, quit subrom init
	JP	C035A

	DEFS	04000H-$,0

	END
