; Orginal HB-F900 SUBROM (Japanese)
;   MSX2SUB -> Source re-created by Z80DIS 2.2
;      Z80DIS was written by Kenneth Gielow
;                            Palo Alto, CA
	.Z80
	ASEG
	ORG	0000H

I$4000	EQU	4000H	; ----I
I$4055	EQU	4055H	; ----I
I$406A	EQU	406AH	; ----I
I$406D	EQU	406DH	; ----I
I$406F	EQU	406FH	; ----I
I$40FF	EQU	40FFH	; ----I
I.46E6	EQU	46E6H	; ----I
I$475A	EQU	475AH	; ----I
I$4C64	EQU	4C64H	; ----I
I$4FCF	EQU	4FCFH	; ----I
C$51D7	EQU	51D7H	; -C---
I$520F	EQU	520FH	; ----I
I$521C	EQU	521CH	; ----I
I$542F	EQU	542FH	; ----I
I$5439	EQU	5439H	; ----I
I$579C	EQU	579CH	; ----I
I$57AB	EQU	57ABH	; ----I
D$5D3A	EQU	5D3AH	; ---L-
I$5EA4	EQU	5EA4H	; ----I
I$6275	EQU	6275H	; ----I
I$6627	EQU	6627H	; ----I
I$6678	EQU	6678H	; ----I
I$67D0	EQU	67D0H	; ----I
I$6A0E	EQU	6A0EH	; ----I
I$6B24	EQU	6B24H	; ----I
I$6E6B	EQU	6E6BH	; ----I
I$6E6E	EQU	6E6EH	; ----I
I$6E74	EQU	6E74H	; ----I
I$6E86	EQU	6E86H	; ----I
I$7323	EQU	7323H	; ----I
I$7328	EQU	7328H	; ----I
I.7876	EQU	7876H	; ----I
I.7D01	EQU	7D01H	; ----I
I$7EE4	EQU	7EE4H	; ----I
I$7EF2	EQU	7EF2H	; ----I
I$7FFD	EQU	7FFDH	; ----I
I$7FFF	EQU	7FFFH	; ----I
I$8000	EQU	8000H	; ----I
J.A2CD	EQU	0A2CDH	; J----
I.F0FA	EQU	0F0FAH	; ----I
C$F380	EQU	0F380H	; -C---
J$F385	EQU	0F385H	; J----
J.F38C	EQU	0F38CH	; J----
C$F398	EQU	0F398H	; -C---
D.F3AE	EQU	0F3AEH	; --SL-
D.F3AF	EQU	0F3AFH	; --SL-
D.F3B0	EQU	0F3B0H	; --SL-
D.F3B1	EQU	0F3B1H	; ---LI
D$F3B2	EQU	0F3B2H	; --S--
D.F3B3	EQU	0F3B3H	; ---LI
D.F3B5	EQU	0F3B5H	; --SL-
D.F3B7	EQU	0F3B7H	; ---L-
D.F3BD	EQU	0F3BDH	; ---L-
D.F3BF	EQU	0F3BFH	; ---L-
D.F3C1	EQU	0F3C1H	; ---L-
D.F3C3	EQU	0F3C3H	; ---L-
D.F3C5	EQU	0F3C5H	; ---L-
D.F3C7	EQU	0F3C7H	; ---L-
D.F3C9	EQU	0F3C9H	; ---L-
D.F3CB	EQU	0F3CBH	; ---L-
D.F3CD	EQU	0F3CDH	; ---L-
D.F3CF	EQU	0F3CFH	; ---L-
D.F3D1	EQU	0F3D1H	; ---L-
D.F3D5	EQU	0F3D5H	; ---L-
D.F3D7	EQU	0F3D7H	; ---L-
D.F3D9	EQU	0F3D9H	; ---L-
D.F3DB	EQU	0F3DBH	; --SL-
D.F3DC	EQU	0F3DCH	; --SL-
D.F3DE	EQU	0F3DEH	; --SL-
D.F3DF	EQU	0F3DFH	; --SLI
D.F3E0	EQU	0F3E0H	; --SL-
D.F3E1	EQU	0F3E1H	; --SL-
D$F3E2	EQU	0F3E2H	; --S--
D$F3E3	EQU	0F3E3H	; --S--
D$F3E4	EQU	0F3E4H	; --S--
D$F3E5	EQU	0F3E5H	; --S--
D$F3E6	EQU	0F3E6H	; ---L-
D.F3E9	EQU	0F3E9H	; --SL-
D.F3EA	EQU	0F3EAH	; --SLI
D.F3EB	EQU	0F3EBH	; --SL-
D.F3F2	EQU	0F3F2H	; --SL-
D.F3F8	EQU	0F3F8H	; --SL-
D$F3FA	EQU	0F3FAH	; ---L-
D.F3FC	EQU	0F3FCH	; ---LI
I$F401	EQU	0F401H	; ----I
I.F406	EQU	0F406H	; ----I
D.F40B	EQU	0F40BH	; --S--
D.F40D	EQU	0F40DH	; --S--
D.F417	EQU	0F417H	; --SL-
D$F4FD	EQU	0F4FDH	; --S--
D.F55E	EQU	0F55EH	; --SLI
D.F560	EQU	0F560H	; --SL-
D.F561	EQU	0F561H	; --SL-
D.F562	EQU	0F562H	; --SLI
D.F564	EQU	0F564H	; --SL-
D$F565	EQU	0F565H	; --S--
D.F566	EQU	0F566H	; ---LI
D.F568	EQU	0F568H	; --SL-
D.F569	EQU	0F569H	; --S--
D.F56A	EQU	0F56AH	; --SL-
D.F56C	EQU	0F56CH	; --SL-
D.F56F	EQU	0F56FH	; --SL-
D$F570	EQU	0F570H	; --S--
D.F571	EQU	0F571H	; --SL-
D.F573	EQU	0F573H	; --SL-
D.F575	EQU	0F575H	; --S--
I.F577	EQU	0F577H	; ----I
D$F585	EQU	0F585H	; --S--
D.F5A0	EQU	0F5A0H	; --SL-
D.F5A2	EQU	0F5A2H	; --SL-
D.F5A4	EQU	0F5A4H	; --SL-
D.F5A6	EQU	0F5A6H	; --SL-
D.F5A8	EQU	0F5A8H	; --SL-
D$F661	EQU	0F661H	; ---L-
D.F663	EQU	0F663H	; --SL-
D.F666	EQU	0F666H	; --SL-
D.F668	EQU	0F668H	; --SL-
D.F669	EQU	0F669H	; --SL-
D.F66A	EQU	0F66AH	; --SLI
D$F699	EQU	0F699H	; ---L-
D.F6A5	EQU	0F6A5H	; --S--
D.F6C6	EQU	0F6C6H	; --SL-
I$F7F6	EQU	0F7F6H	; ----I
D.F7F8	EQU	0F7F8H	; --SL-
D$F862	EQU	0F862H	; --S--
D$F864	EQU	0F864H	; --S--
I.F866	EQU	0F866H	; ----I
D$F87C	EQU	0F87CH	; --S--
I$F87F	EQU	0F87FH	; ----I
I$F8CF	EQU	0F8CFH	; ----I
D.F91F	EQU	0F91FH	; ---L-
D.F920	EQU	0F920H	; ---L-
D.F922	EQU	0F922H	; --SL-
D.F924	EQU	0F924H	; --SL-
D.F926	EQU	0F926H	; --SL-
D.F928	EQU	0F928H	; --SL-
D.F92A	EQU	0F92AH	; --SL-
D.F92C	EQU	0F92CH	; --SL-
D.F942	EQU	0F942H	; --SL-
D.F944	EQU	0F944H	; --SL-
D.F949	EQU	0F949H	; --SL-
D.F94A	EQU	0F94AH	; --SL-
D.F94B	EQU	0F94BH	; --SL-
D.F94D	EQU	0F94DH	; ---L-
D.F94F	EQU	0F94FH	; ---L-
D.F951	EQU	0F951H	; --SL-
D.F953	EQU	0F953H	; --SL-
D.F954	EQU	0F954H	; --SL-
D.F955	EQU	0F955H	; --SL-
D.FAF5	EQU	0FAF5H	; --SL-
D.FAF6	EQU	0FAF6H	; --SL-
D.FAF7	EQU	0FAF7H	; --S-I
D.FAF8	EQU	0FAF8H	; --SL-
D.FAF9	EQU	0FAF9H	; --SL-
D.FAFA	EQU	0FAFAH	; --SLI
D$FAFB	EQU	0FAFBH	; --S--
D.FAFC	EQU	0FAFCH	; --SLI
D.FAFE	EQU	0FAFEH	; --SL-
D.FAFF	EQU	0FAFFH	; --SLI
D.FB00	EQU	0FB00H	; --SL-
D.FB01	EQU	0FB01H	; --SL-
D.FB02	EQU	0FB02H	; --SL-
I$FBB1	EQU	0FBB1H	; ----I
I$FBB2	EQU	0FBB2H	; ----I
I$FBCA	EQU	0FBCAH	; ----I
D$FBCD	EQU	0FBCDH	; --S--
D.FBD9	EQU	0FBD9H	; --SL-
D.FBEB	EQU	0FBEBH	; ---L-
I$FBF0	EQU	0FBF0H	; ----I
D.FC18	EQU	0FC18H	; --SLI
I$FC19	EQU	0FC19H	; ----I
I.FC1A	EQU	0FC1AH	; ----I
D.FC23	EQU	0FC23H	; --SL-
D.FC24	EQU	0FC24H	; --SL-
D.FC25	EQU	0FC25H	; --SL-
D.FC26	EQU	0FC26H	; --SL-
I$FC27	EQU	0FC27H	; ----I
D.FC28	EQU	0FC28H	; ---LI
I.FC40	EQU	0FC40H	; ----I
D$FC9B	EQU	0FC9BH	; ---L-
I$FCA6	EQU	0FCA6H	; ----I
D.FCAC	EQU	0FCACH	; --SL-
I$FCAD	EQU	0FCADH	; ----I
D.FCAF	EQU	0FCAFH	; --SL-
D.FCB0	EQU	0FCB0H	; --SL-
D.FCB2	EQU	0FCB2H	; --SL-
D.FCB3	EQU	0FCB3H	; --SL-
D.FCB5	EQU	0FCB5H	; --SL-
D.FCB7	EQU	0FCB7H	; --SL-
D.FCB9	EQU	0FCB9H	; --SL-
D$FCC0	EQU	0FCC0H	; ---L-
D.FCC1	EQU	0FCC1H	; ---LI
D.FCC5	EQU	0FCC5H	; --S-I
J$FCFB	EQU	0FCFBH	; J----
D.FD09	EQU	0FD09H	; --SLI
I.FD89	EQU	0FD89H	; ----I
C$FDC7	EQU	0FDC7H	; -C---
J$FDD6	EQU	0FDD6H	; J----
I.FE00	EQU	0FE00H	; ----I
D$FEFD	EQU	0FEFDH	; --S--
D$FEFF	EQU	0FEFFH	; --S--
I$FF08	EQU	0FF08H	; ----I
C$FF48	EQU	0FF48H	; -C---
D$FFA7	EQU	0FFA7H	; ---L-
I$FFDE	EQU	0FFDEH	; ----I
I$FFDF	EQU	0FFDFH	; ----I
D.FFE7	EQU	0FFE7H	; ---LI
D.FFE8	EQU	0FFE8H	; --SLI
D$FFE9	EQU	0FFE9H	; --S--
D$FFEA	EQU	0FFEAH	; --S--
I$FFF0	EQU	0FFF0H	; ----I
D$FFF1	EQU	0FFF1H	; --S--
D.FFF7	EQU	0FFF7H	; --S-I
I$FFF8	EQU	0FFF8H	; ----I
I$FFFD	EQU	0FFFDH	; ----I
D.FFFF	EQU	0FFFFH	; --SLI

	DEFB	"CD"
	DEFW	C0336
	DEFW	C1649
	DEFW	C36D5


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0008:	JP	J$1D32

	DEFS	00010H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0010:	JP	J.1D3A

	DEFS	00014H-$,0

I$0014:	JP	C.0218

	DEFS	00018H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0018:	JP	J$0577

	DEFS	0001CH-$,0

?.001C:	JP	C.0262

	DEFS	00020H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0020:	LD	A,H
	SUB	D
	RET	NZ
	LD	A,L
	SUB	E
	RET

	DEFS	00028H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0028:	JP	C.060E

	DEFS	00030H-$,0

?.0030:	JP	J$0246

	DEFS	00038H-$,0

I$0038:	EX	AF,AF'
	EXX
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	AF,AF'
	EXX
	PUSH	IX
	PUSH	IY
	LD	IX,I$0038
	LD	IY,(D$FCC0)
	CALL	C.058D
	POP	IY
	POP	IX
	EX	AF,AF'
	EXX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	EXX
	EI
	RETI

	DEFS	00066H-$,0

?.0066:	JP	J$FDD6

?.0069:	EI
	JP	J$2651

FCB2:	EI
	JP	J$2556

?.0071:	EI
	JP	C.256F

?.0075:	EI
	JP	J$2607

?.0079:	EI
	JP	J$262A

?.007D:	EI
	JP	J.263F

DBUF.1:	EI
	JP	J.2648

?.0085:	EI
	JP	C.2823

?.0089:	EI
	JP	J$110E

?.008D:	EI
	JP	C.12C4

?.0091:	EI
	JP	C.1342

?.0095:	EI
	JP	C.1384

?.0099:	EI
	JP	C.13AD

?.009D:	EI
	JP	C.13B5

?.00A1:	EI
	JP	C.1426

?.00A5:	EI
	JP	J.1439

?.00A9:	EI
	JP	C.13E7

?.00AD:	EI
	JP	J$144B

?.00B1:	EI
	JP	C.13FC

?.00B5:	EI
	JP	J$148C

?.00B9:	EI
	JP	C.1414

I$00BD:	EI
	JP	J$1498

?.00C1:	EI
	JP	C.14DB

?.00C5:	EI
	JP	C.158F

I$00C9:	EI
	JP	C.27E7

?.00CD:	EI
	JP	C.2898

?.00D1:	EI
	JP	J$09C3

?.00D5:	EI
	JP	J$09E5

?.00D9:	EI
	JP	C.0A1A

?.00DD:	EI
	JP	J$0A48

?.00E1:	EI
	JP	J$0A98

?.00E5:	EI
	JP	C.0B42

?.00E9:	EI
	JP	C.0B9C

?.00ED:	EI
	JP	C.0BD2

?.00F1:	EI
	JP	C.0C22

?.00F5:	EI
	JP	C.06F5

?.00F9:	EI
	JP	J$0755

?.00FD:	EI
	JP	C.076A

I$0101:	EI
	JP	C.077F

?.0105:	EI
	JP	C.07D9

?.0109:	EI
	JP	C.08CB

?.010D:	EI
	JP	C.08D6

?.0111:	EI
	JP	C.0953

?.0115:	EI
	JP	C.07FE

?.0119:	EI
	JP	C.0864

?.011D:	EI
	JP	J$0D52

?.0121:	EI
	JP	J$0E0F

?.0125:	EI
	JP	J$0E5D

?.0129:	EI
	JP	J$0F16

?.012D:	EI
	JP	C.0647

?.0131:	EI
	JP	C.298B

?.0135:	EI
	JP	J$3F04

?.0139:	EI
	JP	J$3CC9

?.013D:	EI
J$013E:	JP	C.06A8

I$0141:	EI
	JP	J.0F9F

?.0145:	EI
	JP	J.0F7E

?.0149:	EI
	JP	C.0F6A

?.014D:	EI
	JP	C.0FD3

?.0151:	EI
	JP	J$208F

?.0155:	EI
	JP	J$1DF6

?.0159:	EI
	JP	J$1EE5

?.015D:	EI
	JP	J$1FDF

?.0161:	EI
	JP	J$21C6

?.0165:	EI
	JP	J$21E5

?.0169:	EI
	JP	J$2220

?.016D:	EI
	JP	J$2297

?.0171:	EI
	JP	J$22F4

?.0175:	EI
	JP	J$2307

?.0179:	EI
	JP	J$1833

?.017D:	EI
	JP	J.1A62

?.0181:	EI
	JP	J$1B4E

?.0185:	EI
	JP	J$0480

?.0189:	EI
	JP	J$0470

?.018D:	EI
	JP	J$2342

?.0191:	EI
	JP	J.2EB9

?.0195:	EI
	JP	J.2F42

?.0199:	EI
	JP	J.2EDF

?.019D:	EI
	JP	J.30A8

?.01A1:	EI
	JP	J.31B4

?.01A5:	EI
I$01A6:	JP	J.306F

?.01A9:	EI
	JP	J.307C

?.01AD:	EI
	JP	J$34DD

?.01B1:	EI
	JP	J$1683

?.01B5:	EI
	JP	C.09BF

?.01B9:	EI
	JP	0

?.01BD:	EI
	JP	J.1049

J$01C1:	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL
	LD	C,A
	AND	D
	LD	E,A
	LD	(D.FFFF),A
	LD	A,B
	AND	D
	OUT	(0A8H),A
	LD	A,E
	LD	(D.FCC5),A
	PUSH	BC
	EXX
	EX	AF,AF'
	CALL	C$F398
	DI
	EX	AF,AF'
	EXX
	POP	BC
	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FCC5),A
	EX	AF,AF'
	EXX
	RET

?.01F5:	EI
	JP	J$1D08

?.01F9:	EI
	JP	J$1D10


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$01FD:	CALL	C.02DD
I.0200:	JP	M,J$020D
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	CALL	C$F380
	LD	A,E
	RET

J$020D:	PUSH	HL
	CALL	C.0302
	EX	(SP),HL
	PUSH	BC
	CALL	C$01FD
	JR	J$0233


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0218:	PUSH	DE
	CALL	C.02DD
	JP	M,J$0228
	POP	DE
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	JP	J$F385

J$0228:	EX	(SP),HL
	PUSH	HL
	CALL	C.0302
	POP	DE
	EX	(SP),HL
	PUSH	BC
	CALL	C.0218
J$0233:	POP	BC
	EX	(SP),HL
	PUSH	AF
	LD	A,B
	AND	3FH	; "?"
	OR	C
	OUT	(0A8H),A
	LD	A,L
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	POP	AF
	POP	HL
	RET

J$0246:	EX	(SP),HL
	PUSH	AF
	PUSH	DE
	LD	A,(HL)
	PUSH	AF
	POP	IY
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	DE
	POP	IX
	POP	DE
	POP	AF
	EX	(SP),HL
J$0258:	EXX
	LD	D,0FCH
	JR	J.0265

?.025D:	EXX
	LD	D,0F3H
	JR	J.0265


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0262:	EXX
	LD	D,0F0H
J.0265:	EX	AF,AF'
	DI
	LD	A,(D.FCC1)
	AND	A
	IN	A,(0A8H)
	JP	M,J$0276
	PUSH	AF
	AND	D
	EXX
	JP	J.F38C

J$0276:	LD	B,A
	LD	A,(D.FAF8)
	AND	03H	; 3 
	JR	NZ,J$0284
	LD	A,D
	CP	0F3H
	JP	NZ,J$01C1
J$0284:	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL
	LD	C,A
	AND	D
	LD	(D.FFFF),A
	LD	E,A
	LD	A,B
	OUT	(0A8H),A
	LD	A,E
	LD	(D.FCC5),A
	LD	A,B
	PUSH	BC
	LD	HL,I$02A6
	PUSH	HL
	PUSH	AF
	AND	D
	EXX
	JP	J.F38C

I$02A6:	DI
	EXX
	EX	AF,AF'
	POP	BC
	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FCC5),A
	EX	AF,AF'
	EXX
	RET

J$02BD:	CALL	C.02DD
	JP	M,J$02CA
	IN	A,(0A8H)
	AND	C
	OR	B
	OUT	(0A8H),A
	RET

J$02CA:	PUSH	HL
	CALL	C.0302
	LD	C,A
	LD	B,00H
	LD	A,L
	AND	H
	OR	D
	LD	HL,D.FCC5
	ADD	HL,BC
	LD	(HL),A
	POP	HL
	LD	A,C
	JR	J$02BD


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.02DD:	DI
	PUSH	AF
	LD	A,H
	RLCA
	RLCA
	AND	03H	; 3 
	LD	E,A
	LD	A,0C0H
J$02E7:	RLCA
	RLCA
	DEC	E
	JP	P,J$02E7
	LD	E,A
	CPL
	LD	C,A
	POP	AF
	PUSH	AF
	AND	03H	; 3 
	INC	A
	LD	B,A
	LD	A,0ABH
J$02F8:	ADD	A,55H	; "U"
	DJNZ	J$02F8
	LD	D,A
	AND	E
	LD	B,A
	POP	AF
I$0300:	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0302:	PUSH	AF
	LD	A,D
	AND	0C0H
	LD	C,A
	POP	AF
	PUSH	AF
	LD	D,A
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	OR	C
	OUT	(0A8H),A
	LD	A,D
	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	LD	A,0ABH
J$031A:	ADD	A,55H	; "U"
	DEC	D
	JP	P,J$031A
	AND	E
	LD	D,A
	LD	A,E
	CPL
	LD	H,A
	LD	A,(D.FFFF)
	CPL
	LD	L,A
	AND	H
	OR	D
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	POP	AF
	AND	03H	; 3 
	RET

?.0336:	LD	HL,I$29F6
	LD	DE,D.F3DF
	LD	BC,C.0008
	LDIR
	LD	DE,D.FFE7
	LD	BC,C.0010
	LDIR
	XOR	A
	LD	(D.FAF5),A
	LD	(D.FAF6),A
	CALL	C$0512
	LD	(D.FAF8),A
	LD	H,A
	LD	L,0F7H
	LD	(D$FEFD),HL
	LD	HL,I$3C11
	LD	(D$FEFF),HL
	LD	A,(D.FCC1)
	LD	(D.FFF7),A
	LD	A,2CH	; ","
	LD	(D.FAFF),A
	LD	A,26H	; "&"
	LD	(D.FB01),A
	LD	A,0D3H			; no external audio mixing, video input 21 pin, internal sync, AV control=1, Ym control=full, S1=0, S0=0
	OUT	(0F7H),A		; initialize digitizer hardware
	LD	(D.FAF7),A
	XOR	A
	LD	C,0FFH
	OUT	(0D8H),A
	LD	A,02H	; 2 
	OUT	(0D9H),A
	LD	HL,I$050A
	LD	B,08H	; 8 
J$0387:	IN	A,(0D9H)
	CP	(HL)
	JR	NZ,J$0391
	INC	HL
	DJNZ	J$0387
	RES	0,C
J$0391:	IN	A,(0C0H)
	CP	0FFH
	JR	Z,J$0399
	RES	2,C
J$0399:	IN	A,(0F7H)
	AND	77H			; b6-b4, b2-b0 are outputs which are readback, b7 and b3 are I/O with different input function
	CP	77H
	JR	Z,J$03A3
	RES	3,C
J$03A3:	IN	A,(0C8H)
	CP	0FFH
	JR	Z,J$03AB
	RES	4,C
J$03AB:	XOR	A
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	LD	A,40H	; "@"
	OUT	(81H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(81H)
I$03C0:	AND	3FH	; "?"
	CP	05H	; 5 
	JR	NZ,J$03C8
	RES	5,C
J$03C8:	IN	A,(0BBH)
	CP	0FFH
	JR	Z,J$03D0
	RES	6,C
J$03D0:	LD	A,C
	OUT	(0F5H),A
	CALL	C.1CF7
	LD	B,00H
	CALL	C.1CD2
	CP	0AH	; 10 
	JR	Z,J$03E2
J.03DF:	CALL	C$0431
J$03E2:	CALL	C.1CF7
	LD	B,03H	; 3 
	CALL	C.1CD2
	AND	01H	; 1 
	PUSH	AF
	CALL	C.1CDB
	POP	BC
	CP	51H	; "Q"
	JP	NC,J.03DF
	OR	A
	JP	Z,J.03DF
	DEC	B
	JR	NZ,J$0402
	CP	21H	; "!"
I$03FF:	JP	NC,J.03DF
J$0402:	CALL	C.1CF7
	LD	B,01H	; 1 
	CALL	C.1CD2
	LD	D,A
	CALL	C.1CD2
	LD	E,A
	CALL	C.17F8
	CALL	C$2A0E
	LD	B,02H	; 2 
	LD	HL,J.0000
J.041A:	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J.041A
	DJNZ	J.041A
	CALL	C.063C
	XOR	A
	LD	BC,I$4000
	CALL	C.0977
	CALL	C.0A1A
	JP	J.0F9F


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0431:	LD	HL,I$04FF
	LD	C,02H	; 2 
J$0436:	LD	B,0DH	; 13 
	LD	A,04H	; 4 
	SUB	C
	CALL	C.1A59
J$043E:	LD	B,0DH	; 13 
J$0440:	LD	A,0DH	; 13 
	SUB	B
	OUT	(0B4H),A
	LD	A,(HL)
	INC	HL
	CP	0FFH
	JR	NZ,J$044D
	DEC	HL
	XOR	A
J$044D:	OUT	(0B5H),A
	DJNZ	J$0440
	DEC	C
	JR	NZ,J$0436
	LD	B,0DH	; 13 
	LD	A,08H	; 8 
	CALL	C.1A59
	XOR	A
	CALL	C.1A59
	LD	A,0DH	; 13 
	CALL	C.1A59
	LD	A,01H	; 1 
	CALL	C.1CF9
	LD	B,0AH	; 10 
	LD	A,01H	; 1 
	JP	C.1A59

J$0470:	SCF
	CALL	C$0481
	LD	HL,I$7EF2
	CALL	C.05F6
	LD	HL,I$7EE4
	JP	C.05F6

J$0480:	XOR	A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0481:	PUSH	AF
	CALL	C.1CF7
	LD	B,03H	; 3 
	CALL	C.1CD2
	LD	C,A
	AND	01H	; 1 
	POP	DE
	PUSH	AF
	PUSH	DE
	PUSH	BC
	LD	A,C
	RLCA
	RLCA
	AND	08H	; 8 
	LD	C,A
	LD	A,(D.FFE8)
	AND	0F7H
	OR	C
	LD	B,A
	LD	C,09H	; 9 
	CALL	C.0647
	POP	BC
	CALL	C.1CDB
	LD	E,A
	POP	AF
	PUSH	DE
	PUSH	AF
	CALL	C.1CD2
	LD	(D.F3E9),A
	LD	(D.F3F2),A
	CALL	C.1CD2
	LD	(D.F3EA),A
	CALL	C.1CD2
	LD	(D.F3EB),A
	CALL	C.1CD2
	LD	C,A
	RRC	C
	SBC	A,A
	LD	B,A
	POP	AF
	JR	NC,J$04CC
	LD	A,B
J$04CC:	LD	(D.F3DE),A
	RRC	C
	SBC	A,A
	LD	(D.F3DB),A
	RRC	C
	PUSH	BC
	LD	BC,BDOS
	LD	HL,D.F3FC
	JR	NC,J$04E3
	LD	HL,I$F401
J$04E3:	LD	DE,I.F406
	LDIR
	POP	BC
	RRC	C
	SBC	A,A
	LD	(D.F417),A
	POP	DE
	POP	AF
	LD	(D.FCB0),A
	LD	(D.FCAF),A
	PUSH	DE
	CALL	C.09BF
	POP	DE
	JP	J$1FFF

I$04FF:	DEFB	0AH
I$0500:	DEFB	00H,00H,01H,0DH,01H,0FH,04H,07H
	DEFB	03H,0FFH

I$050A:	DEFB	00H,40H,20H,10H,08H,04H,02H,01H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0512:	PUSH	BC
	PUSH	HL
	IN	A,(0A8H)
	AND	03H	; 3 
	LD	C,A
	LD	B,00H
	LD	HL,D.FCC1
	ADD	HL,BC
	OR	(HL)
	LD	C,A
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	AND	03H	; 3 
	RLCA
	RLCA
	OR	C
	POP	HL
	POP	BC
	RET

J.052E:	LD	IX,I$6E6B
	JR	J.0562

J$0534:	LD	IX,I$6E86
	JR	J.0562

J$053A:	LD	IX,I$6E6E
	JR	J.0562

J.0540:	LD	IX,I$4055
	JR	J.0562

J.0546:	LD	IX,I$475A
	JR	J.0562

J$054C:	LD	IX,I$406A
	JR	J.0562

J$0552:	LD	IX,I$406D
	JR	J.0562

J$0558:	LD	IX,I$6275
	JR	J.0562

J.055E:	LD	IX,I$6E74
J.0562:	JP	J.0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0565:	LD	IX,I$009F
	JR	C.058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$056B:	LD	IX,I.0090
	JR	C.058D

J$0571:	LD	IX,I$00C9
	JR	C.058D

J$0577:	LD	IX,C.0018
	JR	C.058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.057D:	LD	IX,I$000C
	JR	C.058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0583:	LD	IX,I$0014
	JR	C.058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0589:	LD	IX,I$00BD

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.058D:	JP	J$0258


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0590:	LD	IX,I$0141
	JR	C.058D

J$0596:	LD	IX,I$0168
	JR	C.058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.059C:	LD	IX,I$579C
	JR	J.0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05A2:	LD	IX,I$57AB
	JR	J.0618

J$05A8:	LD	IX,I$7328
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05AE:	LD	IX,I$7323
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$05B4:	LD	IX,I$5439
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05BA:	LD	IX,I$6A0E
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$05C0:	LD	IX,I$6B24
	JR	J.05F4

J.05C6:	LD	IX,I$406F
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05CC:	LD	IX,I$3412
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$05D2:	LD	IX,J.3058
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05D8:	LD	IX,I$5EA4
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05DE:	LD	IX,I$3236
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05E4:	LD	IX,I$4FCF
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$05EA:	LD	IX,I$6627
	JR	J.05F4

J$05F0:	LD	IX,J.2F92
J.05F4:	JR	J.0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05F6:	LD	IX,I$6678
	JR	J.05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.05FC:	LD	IX,I$4C64
I.0600:	JR	J.0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0602:	LD	IX,I$542F
	JR	J.0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0608:	LD	IX,I$520F
	JR	J.0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.060E:	LD	IX,I$521C
	JR	J.0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0614:	LD	IX,I$67D0
J.0618:	CALL	C.0262
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$061D:	LD	(D.F3DE),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0620:	LD	A,(D.FCAF)
	CP	02H	; 2 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0626:	LD	A,(D.FCAF)
	CP	04H	; 4 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.062C:	LD	A,(D.FCAF)
	CP	05H	; 5 
	RET

J.0632:	CALL	C.1034
	LD	A,(D.F3E0)
	OR	60H	; "`"
	JR	J$0644


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.063C:	CALL	C.1034
	LD	A,(D.F3E0)
	AND	3FH	; "?"
J$0644:	LD	B,A
	LD	C,01H	; 1 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0647:	LD	A,I
	PUSH	AF
	PUSH	HL
	LD	A,C
	AND	A
	JR	NZ,J.0680
	LD	A,B
	LD	HL,D.F3DF
	XOR	(HL)
	AND	01H	; 1 
	JR	Z,J.0680
	LD	HL,D.FFE8
	LD	A,(HL)
	AND	0CFH
	LD	(HL),A
	LD	A,B
	AND	01H	; 1 
	RRCA
	RRCA
	RRCA
	RRCA
	OR	(HL)
	PUSH	BC
	LD	B,A
	LD	C,09H	; 9 
	LD	HL,D.FAF7
	LD	A,(HL)
	AND	3FH	; "?"
	LD	(HL),A
	LD	A,B
	RLCA
	RLCA
	CPL
	AND	0C0H
	OR	(HL)
	OUT	(0F7H),A
	LD	(HL),A
	CALL	C.0647
	POP	BC
J.0680:	LD	A,B
	DI
	OUT	(99H),A
	LD	A,C
	OR	80H
	OUT	(99H),A
	PUSH	BC
	PUSH	DE
	LD	D,B
	LD	A,C
	LD	B,00H
	CP	08H	; 8 
	JR	NC,J$0698
	LD	HL,D.F3DF
	JR	J$069F

J$0698:	CP	18H
	JR	NC,J$06A1
	LD	HL,I$FFDF
J$069F:	ADD	HL,BC
	LD	(HL),D
J$06A1:	POP	DE
	POP	BC
	POP	HL
	POP	AF
	RET	PO
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.06A8:	LD	A,(D.FCAF)
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	DI
	LD	HL,I$06B8
	CALL	C$09C9
	JR	J$06F0

I$06B8:	DEFW	0B42H
	DEFW	0B9CH
	DEFW	0BD2H
	DEFW	0C22H
	DEFW	0BD9H
	DEFW	0C56H
	DEFW	0C80H
	DEFW	0C97H
	DEFW	0CC7H

J.06CA:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	DI
	XOR	A
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	CALL	C.1034
	LD	HL,D.F3DF
	LD	B,08H	; 8 
J$06DE:	LD	A,(HL)
	INC	HL
	OUT	(9BH),A
	DJNZ	J$06DE
	LD	HL,D.FFE7
	LD	B,10H	; 16 
J$06E9:	LD	A,(HL)
	INC	HL
	OUT	(9BH),A
	DJNZ	J$06E9
	EI
J$06F0:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.06F5:	CALL	C$0701
	PUSH	HL
	LD	HL,J.0000
	CALL	C.08E3
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0701:	LD	A,(D.F3E0)
	LD	B,A
I$0705:	LD	C,01H	; 1 
	CALL	C.0647
	LD	HL,(D.F926)
	LD	BC,I.0800
	XOR	A
	CALL	C.0977

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0714:	LD	A,(D.F3E9)
	LD	E,A
	LD	HL,(D.F928)
	LD	BC,I.2000
J$071E:	CALL	C.0626
	LD	A,0D1H
	JR	C,J$0727
	LD	A,0D9H
J$0727:	CALL	C.08CB
	INC	HL
	INC	HL
	LD	A,C
	CALL	C.08CB
	INC	HL
	INC	C
	LD	A,(D.F3E0)
	RRCA
	RRCA
	JR	NC,J$073C
	INC	C
	INC	C
	INC	C
J$073C:	LD	A,E
	CALL	C.08CB
	INC	HL
	DJNZ	J$071E
	CALL	C.0626
	RET	C
	LD	HL,(D.F928)
	LD	BC,I.0200
	SBC	HL,BC
	LD	A,(D.F3E9)
	JP	C.0977

J$0755:	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	CALL	C.077F
	CP	08H	; 8 
	JR	Z,J$0764
	ADD	HL,HL
	ADD	HL,HL
J$0764:	EX	DE,HL
	LD	HL,(D.F926)
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.076A:	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL
	LD	HL,(D.F928)
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0775:	ADD	A,A
	ADD	A,A
I$0777:	CALL	C.076A
	LD	DE,I.FE00
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.077F:	LD	A,(D.F3E0)
	RRCA
	RRCA
	LD	A,08H	; 8 
	RET	NC
	LD	A,20H	; " "
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$078A:	CALL	C$FDC7
	LD	HL,(D.F924)
	CALL	C.08E3
	LD	A,(D.F91F)
	LD	HL,(D.F920)
	LD	BC,I.0800
	PUSH	AF
J$079D:	POP	AF
	PUSH	AF
	PUSH	BC
	DI
	CALL	C.057D
	EI
	POP	BC
	OUT	(98H),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$079D
	POP	AF
	RET

?.07B0:	CALL	C.08F1
	LD	A,C
	OR	A
	LD	A,B
	LD	B,C
	LD	C,98H
	EX	DE,HL
	JR	Z,J.07BD
	INC	A
J.07BD:	INIR
	DEC	A
	JR	NZ,J.07BD
	EX	DE,HL
	RET

?.07C4:	EX	DE,HL
	CALL	C.08E3
	EX	DE,HL
	LD	A,C
	OR	A
	LD	A,B
	LD	B,C
	LD	C,98H
	JR	Z,J.07D2
	INC	A
J.07D2:	OTIR
	DEC	A
	JR	NZ,J.07D2
	EX	DE,HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.07D9:	LD	H,00H
	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL
	LD	HL,(D.F920)
	ADD	HL,DE
	LD	DE,I.FC40
	LD	B,08H	; 8 
	LD	A,(D.F91F)
J$07EC:	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	C.057D
	EI
	POP	BC
	POP	DE
	POP	HL
	LD	(DE),A
	INC	DE
	INC	HL
	POP	AF
	DJNZ	J$07EC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.07FE:	CALL	C.0626
	JP	Z,C.0895
	JR	NC,C.0811
	CALL	C.0620
	JP	Z,C.0895
	JP	NC,C.08AD
	JR	C.0864


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0811:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.2980
	LD	A,(D.F3EA)
	CALL	C$084B
	CALL	C.29EB
	XOR	A
	LD	H,A
	LD	L,A
	CALL	C.29A5
	XOR	A
	CALL	C.29DB
	LD	A,(D.FCAF)
	AND	02H	; 2 
	LD	DE,I.0100
	JR	Z,J$0838
	LD	DE,I.0200
J$0838:	LD	HL,I.00D4
	CALL	C.29C4
	LD	A,0C0H
	CALL	C.29E3
	CALL	C.2980
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$084B:	LD	B,A
	LD	A,(D.FCAF)
	CP	08H	; 8 
	LD	A,B
	RET	Z
	RLCA
	RLCA
	RLCA
	RLCA
	OR	B
	LD	B,A
	LD	A,(D.FCAF)
	CP	06H	; 6 
	LD	A,B
	RET	NZ
	RRCA
	RRCA
	OR	B
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0864:	LD	A,(D.FCAF)
	AND	A
	LD	HL,(D.F922)
	JR	NZ,J$087E
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J$0879
	LD	BC,I$03C0
	JR	J.0881

J$0879:	LD	BC,I$0780
	JR	J.0881

J$087E:	LD	BC,I$0300
J.0881:	LD	A,20H	; " "
	CALL	C.0977
	CALL	C$08C1
	LD	HL,I$FBB2
	LD	B,18H
J$088E:	LD	(HL),B
	INC	HL
	DJNZ	J$088E
	JP	J$0571


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0895:	CALL	C.099C
	LD	BC,I$1800
	PUSH	BC
	LD	HL,(D.F3C9)
	LD	A,(D.F3EA)
	CALL	C.0977
	LD	HL,(D.F3CB)
	POP	BC
	XOR	A
J$08AA:	JP	C.0977


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.08AD:	CALL	C.099C
	LD	HL,D.F3EA
	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	LD	HL,(D.F3D5)
	LD	BC,I.0600
	JR	J$08AA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$08C1:	LD	HL,I$0101
	LD	(D.F3DC),HL
	RET

?.08C8:	CALL	C.08DC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.08CB:	PUSH	AF
	CALL	C.08E3
	POP	AF
	OUT	(98H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$08D3:	CALL	C.08DC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.08D6:	CALL	C.08F1
	IN	A,(98H)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.08DC:	PUSH	AF
	LD	A,H
	AND	3FH	; "?"
	LD	H,A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.08E3:	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	CALL	C.0914
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	JR	J$08FB


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.08F1:	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	CALL	C.0914
	LD	A,H
	AND	3FH	; "?"
J$08FB:	PUSH	AF
	LD	A,H
	AND	0C0H
	OR	D
	RLCA
	RLCA
	DI
	OUT	(99H),A
	LD	A,8EH
	OUT	(99H),A
	LD	A,L
	OUT	(99H),A
	POP	AF
	OUT	(99H),A
	EI
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0914:	LD	A,(D.FCAF)
	LD	C,A
	LD	A,(D.FAF6)
	AND	A
	LD	HL,I$0925
	JP	NZ,J$09CA
	EX	DE,HL
	LD	D,A
	RET

I$0925:	DEFW	0937H
	DEFW	0945H
	DEFW	0945H
	DEFW	0945H
	DEFW	0945H
	DEFW	0944H
	DEFW	0944H
	DEFW	0943H
	DEFW	0943H

?.0937:	LD	A,(D.F3B0)
	CP	29H	; ")"
	LD	A,(D.FAF6)
	JR	C,J$0947
	JR	J$0946

?.0943:	ADD	A,A
	ADD	A,A
	ADD	A,A
J$0946:	ADD	A,A
J$0947:	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	H,A
	LD	A,00H
	LD	L,A
	ADC	A,A
	ADD	HL,DE
	LD	D,A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0953:	CALL	C.062C
	JP	NC,J$0997
	CALL	C.09A5
	DEC	A
	JP	M,J$098A
	PUSH	AF
	CALL	C.099C
	POP	AF
	RET	NZ
	LD	HL,D.F3EA
	LD	A,(D.F3E9)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	LD	HL,(D.F3BF)
	LD	BC,C.0020

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0977:	PUSH	AF
	CALL	C.08E3
	LD	A,C
	OR	A
	JR	Z,J$0980
	INC	B
J$0980:	POP	AF
J.0981:	OUT	(98H),A
	DEC	C
	JP	NZ,J.0981
	DJNZ	J.0981
	RET

J$098A:	LD	HL,D.F3EA
	LD	A,(D.F3E9)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	JR	J$099F

J$0997:	CP	08H	; 8 
	CALL	NZ,C.09A5

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.099C:	LD	A,(D.F3EB)
J$099F:	LD	B,A
	LD	C,07H	; 7 
	JP	C.0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.09A5:	PUSH	AF
	LD	A,(D.F3EA)
	AND	0FH	; 15 
	LD	(D.F3EA),A
	LD	A,(D.F3E9)
	AND	0FH	; 15 
	LD	(D.F3E9),A
	POP	AF
	RET

?.09B8:	RET	NZ
	PUSH	HL
	CALL	C.07FE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.09BF:	LD	HL,J.0F9F
	PUSH	HL
J$09C3:	CP	09H	; 9 
	RET	NC
	LD	HL,I$09D3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$09C9:	LD	C,A
J$09CA:	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,C
	JP	(HL)

I$09D3:	DEFW	09E5H
	DEFW	0A1AH
	DEFW	0A48H
	DEFW	0A98H
	DEFW	0A71H
	DEFW	0AD6H
	DEFW	0AE3H
	DEFW	0AF0H
	DEFW	0AFDH

J$09E5:	XOR	A
	LD	(D.FCB0),A
	CALL	C.0B22
	LD	A,(D.F3AE)
	LD	(D.F3B0),A
	LD	HL,I.0800
	LD	(D.F3B5),HL
	LD	HL,(D.F3B3)
	LD	(D.F922),HL
	LD	HL,(D.F3B7)
	CP	29H	; ")"
	JR	C,J$0A08
	LD	HL,I.1000
J$0A08:	LD	(D.F924),HL
	CALL	C.0B42
J$0A0E:	CALL	C.0953
	CALL	C.0864
	CALL	C$078A
	JP	J.0632


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0A1A:	LD	A,01H	; 1 
	LD	(D.FCB0),A
	CALL	C.0B22
	LD	A,(D.F3AF)
	LD	(D.F3B0),A
	LD	HL,(D.F3BD)
	LD	(D.F922),HL
	LD	HL,(D.F3C1)
	LD	(D.F924),HL
	LD	HL,(D.F3C5)
	LD	(D.F926),HL
	LD	HL,(D.F3C3)
	LD	(D.F928),HL
	CALL	C.0B9C
	CALL	C.0714
	JR	J$0A0E

J$0A48:	LD	A,02H	; 2 
	CALL	C.0B22
	LD	HL,(D.F3CD)
	CALL	C.0A82
	PUSH	HL
	CALL	C.0BD2
J$0A57:	POP	HL
	CALL	C.08E3
	XOR	A
	LD	B,03H	; 3 
J.0A5E:	OUT	(98H),A
	INC	A
	JR	NZ,J.0A5E
	DJNZ	J.0A5E
	CALL	C.0895
J$0A68:	CALL	C.0953
	CALL	C.0714
	JP	J.0632

?.0A71:	LD	A,04H	; 4 
	CALL	C.0B22
	LD	HL,I$1E00
	CALL	C.0A82
	PUSH	HL
	CALL	C$0BD9
	JR	J$0A57


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0A82:	LD	(D.F928),HL
	LD	HL,(D.F3CF)
	LD	(D.F926),HL
	LD	HL,(D.F3CB)
	LD	(D.F924),HL
	LD	HL,(D.F3C7)
	LD	(D.F922),HL
	RET

J$0A98:	LD	A,03H	; 3 
	CALL	C.0B22
	LD	HL,(D.F3D9)
	LD	(D.F926),HL
	LD	HL,(D.F3D7)
	LD	(D.F928),HL
	LD	HL,(D.F3D5)
	LD	(D.F924),HL
	LD	HL,(D.F3D1)
	LD	(D.F922),HL
	PUSH	HL
	CALL	C.0C22
	POP	HL
	CALL	C.08E3
	LD	DE,CPMADR
J$0AC0:	LD	C,04H	; 4 
J$0AC2:	LD	A,D
	LD	B,20H	; " "
J$0AC5:	OUT	(98H),A
	INC	A
	DJNZ	J$0AC5
	DEC	C
	JR	NZ,J$0AC2
	LD	D,A
	DEC	E
	JR	NZ,J$0AC0
	CALL	C.08AD
	JR	J$0A68

?.0AD6:	LD	A,05H	; 5 
	LD	DE,I.7876
	CALL	C.0B14
	CALL	C$0C56
	JR	J.0B08

?.0AE3:	LD	A,06H	; 6 
	LD	DE,I.7876
	CALL	C.0B14
	CALL	C$0C80
	JR	J.0B08

?.0AF0:	LD	A,07H	; 7 
	LD	DE,I.F0FA
	CALL	C.0B14
	CALL	C$0C97
	JR	J.0B08

?.0AFD:	LD	A,08H	; 8 
	LD	DE,I.F0FA
	CALL	C.0B14
	CALL	C$0CC7
J.0B08:	CALL	C.0953
	CALL	C.0811
	CALL	C.0714
	JP	J.0632


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0B14:	LD	L,00H
	LD	H,D
	LD	(D.F926),HL
	LD	H,E
	LD	(D.F928),HL
	LD	H,L
	LD	(D.F922),HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0B22:	LD	(D.FCAF),A
	XOR	A
	LD	(D.FAF5),A
	LD	(D.FAF6),A
	LD	HL,I.0100
	LD	(D.F40B),HL
	LD	(D.F40D),HL
	CALL	C.2980
	CALL	C.063C
	LD	B,00H
	LD	C,17H
	JP	C.0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0B42:	CALL	C.0D2D
	LD	A,(D.F3B0)
	CP	29H	; ")"
	LD	B,00H
	JR	C,J$0B50
	LD	B,04H	; 4 
J$0B50:	LD	C,10H	; 16 
	CALL	C.0D3F
	LD	A,(D.F3B0)
	CP	29H	; ")"
	LD	A,(D.FAF5)
	JR	NC,J$0B72
	ADD	A,A
	LD	HL,(D.F3B7)
	LD	B,00H
	CALL	C.0CE6
	ADD	A,A
	LD	HL,(D.F3B3)
	CALL	C.0CDA
	JP	J.06CA

J$0B72:	LD	A,(D.FAF5)
	PUSH	AF
	ADD	A,A
	ADD	A,A
	LD	B,00H
	LD	HL,(D.F924)
	CALL	C.0CE6
	ADD	A,A
	LD	B,03H	; 3 
	LD	HL,(D.F3B3)
	CALL	C.0CDA
	POP	AF
	LD	HL,(D.F3B5)
	LD	E,00H
	SRL	A
	RR	E
	LD	D,A
	LD	B,07H	; 7 
	CALL	C.0CF4
	JP	J.06CA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0B9C:	CALL	C.0D2D
	LD	BC,J.0000
	CALL	C.0D3F
	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	LD	HL,(D.F3C1)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C.0CE6
	LD	HL,(D.F3C5)
	CALL	C.0D20
	LD	HL,(D.F3BD)
	ADD	A,A
	CALL	C.0CDA
	LD	E,B
	LD	D,C
	LD	HL,(D.F3BF)
	CALL	C.0CF4
	SRL	D
	RR	E
	LD	HL,(D.F3C3)
	JR	J.0C1C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0BD2:	XOR	A
	PUSH	AF
	LD	BC,I.0200
	JR	J$0BE0


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0BD9:	LD	A,03H	; 3 
	OR	A
	PUSH	AF
	LD	BC,I.0400
J$0BE0:	CALL	C.0D3F
	CALL	C.0D2D
	LD	A,(D.FAF5)
	LD	C,A
	LD	B,03H	; 3 
	LD	HL,(D.F3CB)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C.0CE6
	LD	HL,(D.F3CF)
	CALL	C.0D20
	LD	HL,(D.F3C7)
	ADD	A,A
	LD	B,00H
	CALL	C.0CDA
	LD	E,B
	LD	D,C
	LD	B,7FH
	LD	HL,(D.F3C9)
	CALL	C.0CF4
	SRL	D
	RR	E
	POP	AF
	LD	B,A
	LD	HL,(D.F3CD)
	JR	Z,J.0C1C
	LD	HL,(D.F928)
J.0C1C:	CALL	C$0D0B
	JP	J.06CA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0C22:	CALL	C.0D2D
	LD	BC,C.0008
	CALL	C.0D3F
	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	LD	HL,(D.F3D5)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C.0CE6
	LD	HL,(D.F3D9)
	CALL	C.0D20
	LD	HL,(D.F3D1)
	ADD	A,A
	LD	B,00H
	CALL	C.0CDA
	LD	E,B
	LD	D,C
	SRL	D
	RR	E
	LD	B,00H
	LD	HL,(D.F3D7)
	JR	J.0C1C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0C56:	CALL	C.0D36
	LD	BC,I.0600
	CALL	C.0D3F
J$0C5F:	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C.0D1D
	LD	HL,(D.F922)
	ADD	A,A
	LD	B,1FH
	CALL	C.0CDA
	LD	D,C
J$0C76:	LD	E,00H
	LD	B,03H	; 3 
	CALL	C$0D08
	JP	J.06CA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0C80:	CALL	C.0D36
	LD	BC,I.0800
	CALL	C.0D3F
	LD	HL,I.0200
	LD	(D.F40B),HL
	LD	HL,DBUF
	LD	(D.F40D),HL
	JR	J$0C5F


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0C97:	CALL	C.0D36
	LD	BC,I$0A00
	CALL	C.0D3F
	LD	HL,I.0200
	LD	(D.F40B),HL
	LD	HL,DBUF
	LD	(D.F40D),HL
J$0CAC:	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	RRCA
	RRCA
	RRCA
	AND	0E0H
	CALL	C.0D1D
	LD	HL,(D.F922)
	LD	B,1FH
	CALL	C.0CDA
	LD	A,C
	ADD	A,A
	LD	D,A
	JR	J$0C76


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0CC7:	CALL	C.0D36
	LD	BC,I.0E00
	CALL	C.0D3F
	LD	A,(D.F3E1)
	SRL	A
	LD	(D.F3E1),A
	JR	J$0CAC


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0CDA:	LD	L,A
	SRL	H
	SRL	H
	ADD	A,H
	OR	B
	LD	(D.F3E1),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0CE6:	LD	L,A
	SRL	H
	SRL	H
	SRL	H
	ADD	A,H
	OR	B
	LD	(D$F3E3),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0CF4:	PUSH	AF
	XOR	A
	ADD	HL,HL
	ADC	A,A
	ADD	HL,HL
	ADC	A,A
	LD	L,H
	LD	H,A
	ADD	HL,DE
	LD	A,L
	OR	B
	LD	(D$F3E2),A
	LD	A,H
	LD	(D$FFE9),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0D08:	LD	HL,(D.F928)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$0D0B:	PUSH	AF
	XOR	A
	ADD	HL,HL
	ADC	A,A
	LD	L,H
	LD	H,A
	ADD	HL,DE
	LD	A,L
	OR	B
	LD	(D$F3E4),A
	LD	A,H
	LD	(D$FFEA),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0D1D:	LD	HL,(D.F926)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0D20:	LD	L,A
	SRL	H
	SRL	H
	SRL	H
	ADD	A,H
	LD	(D$F3E5),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0D2D:	LD	A,(D.FFE8)
	AND	7FH
	LD	(D.FFE8),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0D36:	LD	A,(D.FFE8)
	OR	80H
	LD	(D.FFE8),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0D3F:	LD	A,(D.F3DF)
	AND	0F1H
	OR	B
	LD	(D.F3DF),A
	LD	A,(D.F3E0)
	AND	0E7H
	OR	C
	LD	(D.F3E0),A
	RET

J$0D52:	LD	A,0FFH
	CALL	C$061D
	RET	NC
	PUSH	HL
	LD	A,(D.F3DC)
	LD	HL,D.F3B1
	CP	(HL)
	LD	A,0AH	; 10 
	JR	NZ,J$0D65
	RST	18H
J$0D65:	LD	A,(D.FBEB)
	RRCA
	LD	HL,I$F87F
	LD	A,01H	; 1 
	JR	C,J$0D74
	LD	HL,I$F8CF
	XOR	A
J$0D74:	LD	(D$FBCD),A
	CALL	C.0DE2
	LD	C,05H	; 5 
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J$0DA2
	CALL	C.0DF0
	JR	C,J$0D9A
J$0D88:	PUSH	BC
	LD	C,00H
J$0D8B:	CALL	C.0DFE
	DJNZ	J$0D8B
	LD	A,10H	; 16 
	SUB	C
	LD	C,A
	ADD	HL,BC
	INC	DE
	POP	BC
	DEC	C
	JR	NZ,J$0D88
J$0D9A:	LD	HL,(D.F3B1)
	CALL	C.0ED7
	POP	HL
	RET

J$0DA2:	PUSH	AF
	CALL	C.0DF0
	POP	AF
	SUB	28H	; "("
J$0DA9:	PUSH	BC
	LD	C,00H
J$0DAC:	EX	AF,AF'
	CALL	C.0DFE
	EX	AF,AF'
	DEC	A
	CALL	Z,C.0DD2
	DJNZ	J$0DAC
	DEC	A
	JR	NZ,J$0DBE
	CALL	C.0DD2
	DEC	DE
J$0DBE:	EX	AF,AF'
	LD	A,10H	; 16 
	SUB	C
	LD	C,A
	ADD	HL,BC
	EX	AF,AF'
	INC	DE
	POP	BC
	DEC	C
	JR	NZ,J$0DA9
	LD	HL,(D.F3B1)
	CALL	C.0EF2
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0DD2:	PUSH	BC
	PUSH	HL
	LD	HL,(D.F3B1)
	CALL	C.0ED8
	CALL	C.0DE2
	POP	HL
	POP	BC
	LD	A,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0DE2:	LD	DE,D.FC18
	PUSH	DE
	LD	B,28H	; "("
	LD	A,20H	; " "
J$0DEA:	LD	(DE),A
	INC	DE
	DJNZ	J$0DEA
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0DF0:	SUB	04H	; 4 
	RET	C
	LD	B,0FFH
J$0DF5:	INC	B
	SUB	05H	; 5 
	JR	NC,J$0DF5
	LD	A,B
	SUB	01H	; 1 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0DFE:	LD	A,(HL)
	INC	HL
I.0E00:	INC	C
	CALL	C.12A5
	JR	NC,C.0DFE
	JR	NZ,J$0E0C
	CP	20H	; " "
	JR	C,J$0E0D
J$0E0C:	LD	(DE),A
J$0E0D:	INC	DE
	RET

J$0E0F:	CALL	C.0F00
	SUB	L
	RET	C
	JP	Z,J.0EA9
	PUSH	HL
	PUSH	AF
	LD	C,A
	LD	B,00H
	CALL	C.0F0A
	LD	L,E
	LD	H,D
	INC	HL
	LDIR
	LD	HL,I$FBCA
	DEC	(HL)
	POP	AF
	POP	HL
	PUSH	AF
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J$0E43
	POP	AF
J$0E33:	PUSH	AF
	INC	L
	CALL	C.0EAE
	DEC	L
	CALL	C.0ED7
	INC	L
	POP	AF
	DEC	A
	JR	NZ,J$0E33
	JR	J$0E5A

J$0E43:	POP	AF
J$0E44:	PUSH	AF
	INC	L
	CALL	C.0EAF
	DEC	L
	CALL	C.0ED8
	INC	L
	CALL	C.0EC8
	DEC	L
	CALL	C.0EF2
	INC	L
	POP	AF
	DEC	A
	JR	NZ,J$0E44
J$0E5A:	JP	J.0EA9

J$0E5D:	CALL	C.0F00
	LD	H,A
	SUB	L
	RET	C
	JP	Z,J.0EA9
	LD	L,H
	PUSH	HL
	PUSH	AF
	LD	C,A
	LD	B,00H
	CALL	C.0F0A
	LD	L,E
	LD	H,D
	PUSH	HL
	DEC	HL
	LDDR
	POP	HL
	LD	(HL),H
	POP	AF
	POP	HL
	PUSH	AF
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J$0E92
	POP	AF
J$0E82:	PUSH	AF
	DEC	L
	CALL	C.0EAE
	INC	L
	CALL	C.0ED7
	DEC	L
	POP	AF
	DEC	A
	JR	NZ,J$0E82
	JR	J.0EA9

J$0E92:	POP	AF
J$0E93:	PUSH	AF
	DEC	L
	CALL	C.0EAF
	INC	L
	CALL	C.0ED8
	DEC	L
	CALL	C.0EC8
	INC	L
	CALL	C.0EF2
	DEC	L
	POP	AF
	DEC	A
	JR	NZ,J$0E93
J.0EA9:	LD	H,01H	; 1 
	JP	J$0596


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0EAE:	DEFB	0F6H

C.0EAF:	XOR	A
	PUSH	HL
	PUSH	AF
	LD	H,01H	; 1 
	CALL	C.0F35
	POP	AF
	LD	A,(D.F3B0)
	JR	NZ,J$0EBF
	SUB	28H	; "("
J$0EBF:	LD	B,A
J$0EC0:	LD	DE,D.FC18
	CALL	C.0F22
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0EC8:	PUSH	HL
	LD	A,(D.F3B0)
	SUB	28H	; "("
	INC	A
	LD	H,A
	CALL	C.0F35
	LD	B,28H	; "("
	JR	J$0EC0


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0ED7:	DEFB	0F6H

C.0ED8:	XOR	A
	PUSH	HL
	PUSH	AF
	LD	H,01H	; 1 
	CALL	C.0F35
	POP	AF
	LD	A,(D.F3B0)
	JR	NZ,J$0EE8
	SUB	28H	; "("
J$0EE8:	LD	B,A
J$0EE9:	EX	DE,HL
	LD	HL,D.FC18
	CALL	C.0F2B
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0EF2:	PUSH	HL
	LD	A,(D.F3B0)
	SUB	27H	; "'"
	LD	H,A
	CALL	C.0F35
	LD	B,28H	; "("
	JR	J$0EE9


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0F00:	LD	A,(D.F3DE)
	PUSH	HL
	LD	HL,D.F3B1
	ADD	A,(HL)
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0F0A:	PUSH	HL
	LD	DE,I$FBB1
	LD	H,00H
	ADD	HL,DE
	LD	A,(HL)
	EX	DE,HL
	POP	HL
	AND	A
	RET

J$0F16:	PUSH	HL
	CALL	C.0F35
	CALL	C.08E3
	LD	A,C
	OUT	(98H),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0F22:	CALL	C.08F1
	EX	DE,HL
	LD	C,98H
	INIR
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0F2B:	EX	DE,HL
	CALL	C.08E3
	EX	DE,HL
	LD	C,98H
	OTIR
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0F35:	PUSH	BC
	DEC	H
	DEC	L
	LD	E,H
	LD	H,00H
	LD	D,H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	LD	C,L
	LD	B,H
	ADD	HL,HL
	ADD	HL,HL
	LD	A,(D.FCAF)
	AND	A
	LD	A,(D.F3B0)
	JR	Z,J$0F50
	SUB	22H	; """
	JR	J.0F5D

J$0F50:	CP	29H	; ")"
	JR	C,J$0F5A
	ADD	HL,BC
	ADD	HL,HL
	SUB	52H	; "R"
	JR	J.0F5D

J$0F5A:	ADD	HL,BC
	SUB	2AH	; "*"
J.0F5D:	ADD	HL,DE
	CPL
	AND	A
	RRA
	LD	E,A
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(D.F922)
	ADD	HL,DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0F6A:	PUSH	HL
	LD	D,A
	CALL	C.0FF9
	CALL	C.08F1
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(98H)
	LD	B,A
	DEFB	0,0
	IN	A,(98H)
	LD	C,A
	POP	HL
	RET

J.0F7E:	PUSH	HL
	LD	D,00H
	CALL	C.0FF9
	CALL	C.08F1
	LD	B,D
	LD	C,10H	; 16 
	CALL	C.0647
	LD	B,10H	; 16 
J$0F8F:	IN	A,(98H)
	NOP
	OUT	(9AH),A
	NOP
	IN	A,(98H)
	NOP
	OUT	(9AH),A
	NOP
	DJNZ	J$0F8F
	POP	HL
	RET

J.0F9F:	PUSH	HL
	LD	HL,I$0FB3
	LD	B,10H	; 16 
	LD	D,00H
J$0FA7:	LD	A,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	CALL	C.0FD3
	INC	D
	DJNZ	J$0FA7
	POP	HL
	RET

I$0FB3:	DEFB	00H,00H,00H,00H,11H,06H,33H,07H
	DEFB	17H,01H,27H,03H,51H,01H,27H,06H
	DEFB	71H,01H,73H,03H,61H,06H,64H,06H
	DEFB	11H,04H,65H,02H,55H,05H,77H,07H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0FD3:	PUSH	BC
	PUSH	HL
	LD	B,D
	LD	C,10H	; 16 
	PUSH	AF
	CALL	C.0647
	POP	AF
	LD	C,9AH
	OUT	(C),A
	PUSH	AF
	POP	AF
	OUT	(C),E
	CALL	C.0FF9
	PUSH	AF
	CALL	C.08E3
	EX	(SP),HL
	EX	(SP),HL
	POP	AF
	OUT	(98H),A
	PUSH	AF
	POP	AF
	LD	A,E
	OUT	(98H),A
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.0FF9:	PUSH	AF
	LD	A,(D.FCAF)
	LD	HL,I$1020
I.1000:	PUSH	BC
	INC	A
	LD	C,A
	LD	B,00H
	DEC	A
	JR	NZ,J.1010
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J.1010
	DEC	C
J.1010:	ADD	HL,BC
	ADD	HL,BC
	POP	BC
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	DE
	LD	E,D
	LD	D,00H
	ADD	HL,DE
	ADD	HL,DE
	POP	DE
	POP	AF
	RET

I$1020:	DEFW	0400H
	DEFW	0F00H
	DEFW	2020H
	DEFW	1B80H
	DEFW	2020H
	DEFW	1B80H
	DEFW	7680H
	DEFW	7680H
	DEFW	0FA80H
	DEFW	0FA80H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1034:	LD	A,02H	; 2 
	CALL	C.298B
	AND	40H	; "@"
	JR	NZ,C.1034
J$103D:	LD	A,02H	; 2 
	CALL	C.298B
	AND	40H	; "@"
	JR	Z,J$103D
	RET

J.1047:	POP	AF
	RET

J.1049:	PUSH	AF
	LD	A,B
	CP	21H	; "!"
	JR	C,J.1047
	CP	28H	; "("
	JR	C,J$105B
	CP	30H	; "0"
	JR	C,J.1047
	CP	50H	; "P"
	JR	NC,J.1047
J$105B:	LD	A,C
	CP	21H	; "!"
	JR	C,J.1047
	CP	7FH
	JR	NC,J.1047
	POP	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	A,C
	SUB	20H	; " "
	LD	E,A
	LD	D,00H
	LD	A,B
	SUB	20H	; " "
	LD	L,A
	LD	H,D
	LD	C,L
	LD	B,H
	ADD	HL,HL
	ADD	HL,BC
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	CP	10H	; 16 
	JR	C,J$1084
	DEC	H
	DEC	H
J$1084:	LD	A,L
	OUT	(0D8H),A
	ADD	HL,HL
	ADD	HL,HL
	LD	A,H
	OUT	(0D9H),A
	LD	BC,I$20D9
	LD	HL,D.FC18
	INIR
	POP	AF
	PUSH	AF
	AND	A
	LD	C,02H	; 2 
	JR	Z,J$10C5
	LD	HL,D.FC18
	LD	E,L
	LD	D,H
	DEC	A
	JR	Z,J$10A4
	INC	HL
J$10A4:	LD	C,02H	; 2 
J$10A6:	LD	B,08H	; 8 
J$10A8:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	HL
	INC	DE
	LD	A,B
	CP	05H	; 5 
	JR	NZ,J$10B8
	PUSH	BC
	LD	BC,C.0008
	ADD	HL,BC
	POP	BC
J$10B8:	DJNZ	J$10A8
	PUSH	BC
	LD	BC,I$FFF0
	ADD	HL,BC
	POP	BC
	DEC	C
	JR	NZ,J$10A6
	LD	C,01H	; 1 
J$10C5:	LD	HL,(D.FCB7)
	PUSH	HL
	LD	HL,(D.FCB9)
	PUSH	HL
	LD	DE,D.FC18
J$10D0:	LD	HL,(D.FCB9)
	PUSH	HL
	LD	HL,(D.FCB7)
	PUSH	HL
	LD	B,02H	; 2 
J$10DA:	PUSH	BC
	EX	DE,HL
	LD	DE,I.FC40
	LD	BC,C.0008
	LDIR
	PUSH	HL
	CALL	C$112D
	POP	DE
	POP	BC
	DJNZ	J$10DA
	POP	HL
	LD	(D.FCB7),HL
	POP	HL
	PUSH	BC
	LD	BC,C.0008
	ADD	HL,BC
	POP	BC
	LD	(D.FCB9),HL
	DEC	C
	JR	NZ,J$10D0
	POP	HL
	LD	(D.FCB9),HL
	POP	HL
	LD	BC,C.0010
	ADD	HL,BC
	LD	(D.FCB7),HL
I.1109:	POP	AF
	POP	BC
	POP	DE
	POP	HL
	RET

J$110E:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I.1109
	PUSH	HL
	CALL	C.12A5
	RET	NC
	JR	NZ,J$1124
	CP	0DH	; 13 
	JP	Z,J.1210
	CP	20H	; " "
	RET	C
J$1124:	CALL	C.07D9
	LD	A,(D.F3E9)
	LD	(D.F3F2),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$112D:	LD	HL,(D.FCB9)
	EX	DE,HL
	LD	BC,(D.FCB7)
	CALL	C.12C4
	RET	NC
	CALL	C.1342
	LD	DE,I.FC40
	CALL	C.2980
	PUSH	DE
	XOR	A
	CALL	C.29DB
	CALL	C.1376
	LD	E,A
	CALL	C.29A5
	LD	A,E
	SUB	0CDH
	LD	L,08H	; 8 
	JR	C,J$115A
	LD	L,A
	LD	A,07H	; 7 
	SUB	L
	LD	L,A
J$115A:	LD	B,L
	LD	DE,C.0008
	LD	H,D
	CALL	C.29C4
	POP	DE
	LD	A,(D.F3F2)
	LD	L,A
	LD	A,(D.F3EA)
	LD	H,A
	LD	A,(DE)
	ADD	A,A
	LD	C,A
	LD	A,H
	JR	NC,J$1172
	LD	A,L
J$1172:	CALL	C.29EB
	LD	A,(D.FB02)
	AND	0FH	; 15 
	OR	0B0H
	CALL	C.29E3
	DI
	LD	A,0ACH
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,C
	LD	C,9BH
	DI
	JR	J.11A3

J$118E:	DI
	LD	A,0ACH
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	INC	DE
	LD	A,(DE)
	RLCA
	JR	NC,J$11A1
	OUT	(C),L
	JP	J.11A3

J$11A1:	OUT	(C),H
J.11A3:	RLCA
	JR	NC,J$11AB
	OUT	(C),L
	JP	J$11AD

J$11AB:	OUT	(C),H
J$11AD:	RLCA
	JR	NC,J$11B5
	OUT	(C),L
	JP	J$11B7

J$11B5:	OUT	(C),H
J$11B7:	RLCA
	JR	NC,J$11BF
	OUT	(C),L
	JP	J$11C1

J$11BF:	OUT	(C),H
J$11C1:	RLCA
	JR	NC,J$11C9
	OUT	(C),L
	JP	J$11CB

J$11C9:	OUT	(C),H
J$11CB:	RLCA
	JR	NC,J$11D3
	OUT	(C),L
	JP	J$11D5

J$11D3:	OUT	(C),H
J$11D5:	RLCA
	JR	NC,J$11DD
	OUT	(C),L
	JP	J$11DF

J$11DD:	OUT	(C),H
J$11DF:	RLCA
	JR	NC,J$11E7
	OUT	(C),L
	JP	J$11E9

J$11E7:	OUT	(C),H
J$11E9:	EI
	DJNZ	J$118E
	LD	A,(D.FCAF)
	AND	0FEH
	CP	06H	; 6 
	JR	Z,J$1200
	LD	A,(D.FCB7)
	ADD	A,08H	; 8 
	JR	C,J.1210
	LD	(D.FCB7),A
	RET

J$1200:	LD	HL,(D.FCB7)
	LD	BC,C.0008
	ADD	HL,BC
	LD	A,H
	AND	0FEH
	JR	NZ,J.1210
	LD	(D.FCB7),HL
	RET

J.1210:	LD	HL,J.0000
	LD	(D.FCB7),HL
	LD	A,(D.FCB9)
	ADD	A,08H	; 8 
	CP	0D4H
	JR	C,J$1220
	XOR	A
J$1220:	LD	(D.FCB9),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1224:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I.1109
	PUSH	HL
	CALL	C.12A5
	RET	NC
	JR	NZ,J$123A
	CP	07H	; 7 
	JP	Z,J.1A62
	CP	20H	; " "
	RET	C
J$123A:	CALL	C.07D9
	LD	DE,I.FC40
	PUSH	DE
	CALL	C.2980
	XOR	A
	CALL	C.29DB
	CALL	C.1376
	CALL	C.29A5
	LD	HL,C.0008
	LD	DE,C.0010
	CALL	C.29C4
	POP	DE
	LD	HL,I$0103
	LD	A,(DE)
	ADD	A,A
	LD	C,A
	LD	A,H
	JR	NC,J$1262
	LD	A,L
J$1262:	PUSH	AF
	CALL	C.29EB
	LD	A,0B0H
	CALL	C.29E3
	DI
	LD	A,0ACH
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	POP	AF
	OUT	(9BH),A
	LD	A,C
	LD	C,9BH
	LD	B,08H	; 8 
	PUSH	BC
	DEC	B
	JR	J.1285

J$1280:	INC	DE
	LD	A,(DE)
	PUSH	BC
	LD	B,08H	; 8 
J.1285:	RLCA
	JR	NC,J$1290
	OUT	(C),L
	PUSH	AF
	POP	AF
	OUT	(C),L
	JR	J$1296

J$1290:	OUT	(C),H
	PUSH	AF
	POP	AF
	OUT	(C),H
J$1296:	DJNZ	J.1285
	POP	BC
	DJNZ	J$1280
	LD	HL,(D.F92A)
	LD	BC,C.0010
	ADD	HL,BC
	JP	J.1372


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.12A5:	PUSH	HL
	PUSH	AF
	LD	HL,I$FCA6
	XOR	A
	CP	(HL)
	LD	(HL),A
	JR	Z,J$12BC
	POP	AF
	SUB	40H	; "@"
	CP	20H	; " "
	JR	C,J$12BA
	ADD	A,40H	; "@"
J$12B8:	CP	A
	SCF
J$12BA:	POP	HL
	RET

J$12BC:	POP	AF
	CP	01H	; 1 
	JR	NZ,J$12B8
	LD	(HL),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.12C4:	CALL	C.062C
	JP	NC,J$1305
	PUSH	HL
	PUSH	BC
	LD	B,01H	; 1 
	EX	DE,HL
	LD	A,H
	ADD	A,A
	JR	NC,J$12D8
	LD	HL,J.0000
	JR	J$12E0

J$12D8:	LD	DE,I$00C0
	RST	20H
	JR	C,J$12E2
	EX	DE,HL
	DEC	HL
J$12E0:	LD	B,00H
J$12E2:	EX	(SP),HL
	LD	A,H
	ADD	A,A
	JR	NC,J$12EC
	LD	HL,J.0000
	JR	J$12F4

J$12EC:	LD	DE,I.0100
	RST	20H
	JR	C,J$12F6
	EX	DE,HL
	DEC	HL
J$12F4:	LD	B,00H
J$12F6:	POP	DE
	SRL	L
	SRL	L
	SRL	E
	SRL	E
	LD	A,B
	RRCA
	LD	C,L
	LD	B,H
	POP	HL
	RET

J$1305:	PUSH	HL
	PUSH	BC
	LD	B,01H	; 1 
	EX	DE,HL
	LD	A,H
	ADD	A,A
	JR	NC,J$1313
	LD	HL,J.0000
	JR	J$131B

J$1313:	LD	DE,I.00D4
	RST	20H
	JR	C,J$131D
	EX	DE,HL
	DEC	HL
J$131B:	LD	B,00H
J$131D:	EX	(SP),HL
	LD	A,H
	ADD	A,A
	JR	NC,J$1327
	LD	HL,J.0000
	JR	J$1339

J$1327:	LD	A,(D.FCAF)
	AND	02H	; 2 
	LD	DE,I.0200
	JR	NZ,J$1334
	LD	DE,I.0100
J$1334:	RST	20H
	JR	C,J$133B
	EX	DE,HL
	DEC	HL
J$1339:	LD	B,00H
J$133B:	LD	A,B
	RRCA
	LD	B,H
	LD	C,L
	POP	DE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1342:	CALL	C.062C
	JR	C,J$134F
	LD	H,B
	LD	L,C
	LD	A,E
	LD	(D.F92C),A
	JR	J.1372

J$134F:	PUSH	BC
	LD	A,C
	RRCA
	LD	A,0F0H
	JR	NC,J$1358
	LD	A,0FH	; 15 
J$1358:	LD	(D.F92C),A
	LD	A,C
	ADD	A,A
	ADD	A,A
	AND	0F8H
	LD	C,A
	LD	A,E
	AND	07H	; 7 
	OR	C
	LD	C,A
	LD	A,E
	RRCA
	RRCA
	RRCA
	AND	07H	; 7 
	LD	B,A
	LD	HL,(D.F3D5)
	ADD	HL,BC
	POP	BC
J.1372:	LD	(D.F92A),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1376:	LD	A,(D.F92C)
	LD	HL,(D.F92A)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.137D:	LD	(D.F92C),A
	LD	(D.F92A),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1384:	CALL	C.062C
	JP	NC,J$13A1
	PUSH	BC
	PUSH	HL
	CALL	C.1376
	LD	B,A
	CALL	C$08D3
	INC	B
	DEC	B
	JP	P,J$139C
	RRCA
	RRCA
	RRCA
	RRCA
J$139C:	AND	0FH	; 15 
	POP	HL
	POP	BC
	RET

J$13A1:	PUSH	HL
	LD	HL,(D.F92A)
	LD	A,(D.F92C)
	CALL	C$2949
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.13AD:	CALL	C.1E47
	RET	C
	LD	(D.F3F2),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.13B5:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C.062C
	LD	A,(D.F92C)
	LD	HL,(D.F92A)
	JR	C,J$13CA
	CALL	C$2961
	POP	HL
	POP	DE
	POP	BC
	RET

J$13CA:	LD	B,A
	CALL	C.08D6
	LD	C,A
	LD	A,B
	CPL
	AND	C
	LD	C,A
	LD	A,(D.F3F2)
	INC	B
	DEC	B
	JP	P,J$13DF
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
J$13DF:	OR	C
	CALL	C.08CB
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.13E7:	PUSH	HL
	CALL	C.062C
	CALL	C.1376
	JP	C,J$1466
	DEC	HL
	LD	A,H
	OR	A
	JP	M,J.1471
	LD	(D.F92A),HL
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.13FC:	PUSH	HL
	CALL	C.062C
	CALL	C.1376
	JP	C,J$1474
	LD	A,(D.F92C)
	CP	0D3H
	JR	NC,J.1471
	INC	A
	LD	(D.F92C),A
	POP	HL
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1414:	CALL	C.062C
	JP	C,J$14AE
	LD	A,(D.F92C)
	OR	A
	SCF
	RET	Z
	DEC	A
	LD	(D.F92C),A
	OR	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1426:	PUSH	HL
	CALL	C.1376
	AND	A
	LD	A,0FH	; 15 
	JP	M,J.1460
	LD	A,L
	AND	0F8H
	CP	0F8H
	JR	NZ,J$1443
	JR	J.1471

J.1439:	PUSH	HL
	CALL	C.1376
	AND	A
	LD	A,0FH	; 15 
	JP	M,J.1460
J$1443:	PUSH	DE
	LD	DE,C.0008
	LD	A,0F0H
	JR	J$145B

J$144B:	PUSH	HL
	CALL	C.1376
	AND	A
	LD	A,0F0H
	JP	P,J.1460
J$1455:	PUSH	DE
	LD	DE,I$FFF8
	LD	A,0FH	; 15 
J$145B:	ADD	HL,DE
	LD	(D.F92A),HL
	POP	DE
J.1460:	LD	(D.F92C),A
	AND	A
	POP	HL
	RET

J$1466:	AND	A
	LD	A,0F0H
	JP	P,J.1460
	LD	A,L
	AND	0F8H
	JR	NZ,J$1455
J.1471:	SCF
	POP	HL
	RET

J$1474:	PUSH	DE
	PUSH	HL
	LD	HL,(D.F3D5)
	LD	DE,I$0500
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	20H
	JR	C,J.148E
	LD	A,L
	INC	A
	AND	07H	; 7 
	JR	NZ,J.148E
	SCF
	POP	DE
	POP	HL
	RET

J$148C:	PUSH	HL
	PUSH	DE
J.148E:	CALL	C.1376
	INC	HL
	LD	A,L
	LD	DE,I$00F8
	JR	J$14A2

J$1498:	PUSH	HL
	PUSH	DE
J.149A:	CALL	C.1376
	LD	A,L
	DEC	HL
	LD	DE,I$FF08
J$14A2:	AND	07H	; 7 
	JR	NZ,J$14A7
	ADD	HL,DE
J$14A7:	LD	(D.F92A),HL
	AND	A
	POP	DE
	POP	HL
	RET

J$14AE:	PUSH	HL
	PUSH	DE
	LD	HL,(D.F3D5)
	LD	DE,I.0100
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(D.F92A)
	RST	20H
	JR	NC,J.149A
	LD	A,L
	AND	07H	; 7 
	JR	NZ,J.149A
	SCF
	POP	DE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$14C7:	AND	A
	PUSH	AF
	LD	A,(D.FCAF)
	CP	08H	; 8 
	JR	Z,J$14D8
	POP	AF
	CP	10H	; 16 
	CCF
J$14D4:	LD	(D.FCB2),A
	RET

J$14D8:	POP	AF
	JR	J$14D4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.14DB:	LD	HL,J.0000
	LD	C,L
	CALL	C.062C
	JP	C,J.1566
	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	HL,(D.F92A)
	LD	A,(D.F92C)
	LD	E,A
	LD	D,00H
	LD	A,(D.FCB2)
	CALL	C.28E0
	JR	C,J$14FF
	POP	DE
J.14FA:	POP	BC
	POP	HL
	LD	D,H
	LD	E,H
	RET

J$14FF:	POP	DE
	PUSH	HL
	LD	HL,(D.F92A)
	ADD	HL,DE
	POP	DE
	OR	A
	SBC	HL,DE
	JR	C,J.14FA
	JR	Z,J.14FA
	POP	BC
	POP	BC
	PUSH	HL
	EX	DE,HL
	LD	(D.F942),HL
	LD	A,(D.F92C)
	LD	(D.F944),A
	LD	E,A
	LD	D,00H
	LD	A,(D.FCB2)
	CALL	C$28E4
	PUSH	AF
	JR	C,J.1533
	LD	A,(D.FCAF)
	AND	02H	; 2 
	LD	HL,I$01FF
	JR	NZ,J.1533
	LD	HL,I.00FF
J.1533:	LD	(D.F92A),HL
	POP	AF
	JR	C,J$153A
	INC	HL
J$153A:	PUSH	HL
	EX	DE,HL
	LD	HL,(D.F942)
	EX	DE,HL
	OR	A
	SBC	HL,DE
	EX	(SP),HL
	PUSH	HL
	EX	DE,HL
	LD	A,(D.F944)
	LD	E,A
	LD	D,00H
	LD	A,(D.F3F2)
	CALL	C.28E0
	POP	DE
	JR	NC,J.1561
	RST	20H
	JR	NC,J.1561
	POP	DE
	LD	HL,(D.F942)
	CALL	C$15DB
	POP	DE
	RET

J.1561:	LD	C,00H
	POP	HL
	POP	DE
	RET

J.1566:	CALL	C.1633
	JR	NC,J$1578
	DEC	DE
	LD	A,D
	OR	E
	RET	Z
	CALL	C.1426
	JR	NC,J.1566
	LD	DE,J.0000
	RET

J$1578:	CALL	C.1376
	LD	(D.F942),HL
	LD	(D.F944),A
	LD	HL,J.0000
J$1584:	INC	HL
	CALL	C.1426
	RET	C
	CALL	C.1633
	JR	NC,J$1584
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.158F:	LD	HL,J.0000
	LD	C,L
	CALL	C.062C
	JP	C,J.1626
	CALL	C.13E7
	RET	C
	LD	HL,(D.F92A)
	PUSH	HL
	LD	A,(D.F92C)
	LD	E,A
	LD	D,00H
	LD	A,(D.FCB2)
	CALL	C$28D8
	PUSH	AF
	JR	C,J$15B3
	LD	HL,D.FFFF
J$15B3:	INC	HL
	LD	(D.F92A),HL
	EX	DE,HL
	POP	HL
	EX	(SP),HL
	PUSH	HL
	OR	A
	SBC	HL,DE
	INC	HL
	EX	(SP),HL
	PUSH	DE
	LD	A,(D.F92C)
	LD	E,A
	LD	D,00H
	LD	A,(D.F3F2)
	CALL	C$28DC
	JR	NC,J$161B
	POP	DE
	POP	BC
	POP	AF
	PUSH	BC
	PUSH	DE
	JR	NC,J$15D9
	RST	20H
	JR	C,J$1621
J$15D9:	POP	HL
	POP	DE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$15DB:	LD	A,24H	; "$"
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	LD	A,(D.F92C)
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	LD	A,E
	OUT	(9BH),A
	LD	A,D
	OUT	(9BH),A
	LD	A,01H	; 1 
	OUT	(9BH),A
	XOR	A
	OUT	(9BH),A
	LD	A,(D.F3F2)
	OUT	(9BH),A
	XOR	A
	OUT	(9BH),A
	LD	A,(D.FCAF)
	CP	08H	; 8 
	LD	A,80H
	JR	NZ,J$1614
	LD	A,0C0H
J$1614:	OUT	(9BH),A
	EI
	EX	DE,HL
	LD	C,0FFH
	RET

J$161B:	POP	DE
	POP	HL
	POP	DE
	LD	C,00H
	RET

J$1621:	POP	DE
	POP	HL
	LD	C,00H
	RET

J.1626:	CALL	C.13E7
	RET	C
	CALL	C.1633
	JP	C,J.1439
	INC	HL
	JR	J.1626


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1633:	CALL	C.1384
	LD	B,A
	LD	A,(D.FCB2)
	SUB	B
	SCF
	RET	Z
	LD	A,(D.F3F2)
	CP	B
	RET	Z
	CALL	C.13B5
	LD	C,01H	; 1 
	AND	A
	RET

?.1649:	EI
	LD	DE,I$1660
	PUSH	HL
	LD	HL,I.FD89
	CALL	C.16AD
	POP	HL
	RET	C
	SCF
	RET	NZ
	CALL	C.165E
	EI
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.165E:	PUSH	DE
	RET

I$1660:	DEFM	'MEMINI',00H
	DEFB	02H
	DEFM	'7MKILL',00H
	DEFM	'o'+80H
	DEFM	'8MNAME',00H
	DEFM	'F'
	DEFM	'9MFILES',00H
	DEFB	1BH
	DEFM	'8',0FFH

J$1683:	PUSH	AF
	PUSH	HL
	LD	DE,I$1699
	CALL	C.16AD
	JR	C,J$1695
	POP	AF
	POP	AF
	DEC	HL
	CALL	C.165E
	AND	A
	RET

J$1695:	POP	HL
	POP	AF
	SCF
	RET

I$1699:	DEFM	'K'+80H
	DEFB	00H
	DEFM	'['+80H
	DEFB	16H
	DEFM	'DATE',00H
	DEFM	'a'+80H
	DEFB	16H
	DEFM	'KANJI',00H
	DEFB	95H
	DEFM	'!',0FFH


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.16AD:	PUSH	HL
	LD	A,(DE)
	INC	A
	JR	Z,J$16C6
	CALL	C.16C9
	JR	Z,J$16BD
	INC	DE
	INC	DE
	INC	DE
	POP	HL
	JR	C.16AD

J$16BD:	LD	A,(HL)
	EX	(SP),HL
	EX	DE,HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	AND	A
	JR	C,J.16FE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.16C9:	LD	A,(DE)
	OR	A
	RET	Z
	CP	(HL)
	JR	NZ,J.16D3
	INC	DE
	INC	HL
	JR	C.16C9

J.16D3:	LD	A,(DE)
	AND	A
	INC	DE
	JR	NZ,J.16D3
	DEC	DE
	DEC	A
	RET

?.16DB:	DEC	B
	LD	BC,I$174B
	JR	J$16E5

?.16E1:	DEC	B
	LD	BC,I$1767
J$16E5:	JP	P,J.0546
	RST	10H
	PUSH	BC
	CALL	C.05D8
	CALL	C$05D2
	DEC	HL
	RST	10H
	JR	Z,J.16FE
	RST	08H
	INC	L
	RST	08H
	LD	B,C
	EX	(SP),HL
	LD	BC,I$000E
	ADD	HL,BC
	EX	(SP),HL
J.16FE:	POP	BC
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	A,08H	; 8 
	CALL	C$05EA
	LD	HL,(D$F699)
	POP	DE
	PUSH	HL
	LD	A,(DE)
	RLCA
	AND	01H	; 1 
	LD	B,A
	LD	C,04H	; 4 
	CALL	C.194B
	LD	C,02H	; 2 
J$1718:	LD	B,02H	; 2 
J$171A:	LD	A,(DE)
	INC	A
	JR	Z,J$1723
	DEC	A
	OUT	(0B4H),A
	IN	A,(0B5H)
J$1723:	INC	DE
	EX	DE,HL
	ADD	A,(HL)
	EX	DE,HL
	DEC	DE
	DAA
	AND	0FH	; 15 
	OR	30H	; "0"
	LD	(HL),A
	INC	DE
	INC	DE
	INC	HL
	DJNZ	J$171A
	INC	C
	DEC	C
	JR	Z,J$173E
	LD	A,(DE)
	LD	(HL),A
	INC	DE
	INC	HL
	DEC	C
	JR	J$1718

J$173E:	CALL	C$1947
	POP	DE
	POP	HL
	LD	(HL),08H	; 8 
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	HL
	RET

I$174B:	DEFB	05H,00H,04H,00H,3AH,03H,00H,02H
	DEFB	00H,3AH,01H,00H,00H,00H,85H,00H
	DEFB	84H,00H,3AH,83H,00H,82H,00H,3AH
	DEFB	81H,00H,80H,00H
I$1767:	DEFB	0CH,08H,0BH,00H,2FH,0AH,00H,09H
	DEFB	00H,2FH,08H,00H,07H,00H,0FFH,00H
	DEFB	0FFH,00H,2FH,0FFH
	DEFB	00H,0FFH,00H,2FH,88H,00H,87H,00H

J$1783:	RST	10H
	PUSH	HL
	CALL	C.1CF7
	LD	B,03H	; 3 
	LD	A,(D.FCB0)
	LD	C,A
	LD	A,(D.FFE8)
	RRCA
	RRCA
	AND	02H	; 2 
	OR	C
	CALL	C.1A59
	LD	A,(D.F3B0)
	CALL	C.1A50
	LD	A,(D.F3E9)
	CALL	C.1A59
	LD	A,(D.F3EA)
	CALL	C.1A59
	LD	A,(D.F3EB)
	CALL	C.1A59
	LD	C,00H
	LD	A,(D.F3DE)
	OR	A
	JR	Z,J$17BB
	SET	0,C
J$17BB:	LD	A,(D.F3DB)
	OR	A
	JR	Z,J$17C3
	SET	1,C
J$17C3:	LD	A,(D.F417)
	OR	A
	JR	Z,J$17CB
	SET	2,C
J$17CB:	LD	A,(D.F3FC)
	LD	HL,I.F406
	CP	(HL)
	JR	Z,J$17D6
	SET	3,C
J$17D6:	LD	A,C
	JP	J$1A8C

?.17DA:	RST	08H
	JR	Z,J$17AA
	DEC	C
	JR	J$185B

?.17E0:	PUSH	AF
	RST	08H
	INC	L
	CALL	C$180D
	RST	08H
	ADD	HL,HL
	POP	AF
	AND	0FH	; 15 
	LD	D,A
	CALL	C.17F8
	CALL	C.1CF7
	LD	B,01H	; 1 
	LD	A,D
	JP	C.1A50


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.17F8:	LD	A,E
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0F0H
	OR	D
I$1800:	LD	D,A
	LD	(D$FFF1),A
	DI
	OUT	(99H),A
	LD	A,92H
	EI
	OUT	(99H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$180D:	CALL	C.0608
	PUSH	HL
	EX	DE,HL
	CALL	C.25DC
	EX	DE,HL
	LD	HL,I$0007
	RST	20H
	JR	NC,J$1823
	LD	HL,D.FFF7
	RST	20H
	JP	NC,J.0546
J$1823:	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1825:	CALL	C.05FC
	PUSH	HL
	CALL	C.0614
	LD	A,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	POP	HL
	RET

J$1833:	CP	0C5H
	JP	Z,J$1783
	CP	0CBH
	JP	Z,J$188A
	CP	0C0H
	JP	Z,J$19A6
	LD	DE,I$184F
	CALL	C.16AD
	JP	C,J.0540
	DEC	HL
	RST	10H
	PUSH	DE
	RET

I$184F:	DEFM	'PAGE',00H
	DEFM	'1'+80H
	DEFB	1FH
	DEFM	'VIDEO'
J$185B:	DEFB	00H
	DEFM	'/'+80H
	DEFM	'5ADJUST',00H
	DEFM	'Z'+80H
	DEFB	17H
	DEFM	'TITLE',00H
	DEFB	80H
	DEFB	19H
	DEFM	'PASSW','w'+80H
	DEFM	'D',00H
	DEFM	']'+80H
	DEFB	19H
	DEFM	'PROMPT'
	DEFB	00H
	DEFM	'a'+80H
	DEFB	19H
	DEFM	'DATE',00H
	DEFB	8EH
	DEFB	18H
	DEFB	0FFH

J$188A:	RST	10H
	LD	A,3AH	; ":"
	LD	BC,I$2F3E
	PUSH	AF
	CALL	C.1825
	POP	IX
	CP	08H	; 8 
	JP	NZ,J.0540
	PUSH	HL
	EX	DE,HL
	CALL	C$195E
	JR	Z,J$18A6
	CP	24H	; "$"
	JR	NC,J.18C0
J$18A6:	LD	B,A
	CALL	C.1956
	JR	Z,J$18B0
	CP	60H	; "`"
	JR	J$18B2

J$18B0:	CP	13H	; 19 
J$18B2:	JR	NC,J.18C0
	LD	C,A
	CALL	C.1956
	JR	Z,J$18BE
	CP	60H	; "`"
	JR	J.18C0

J$18BE:	CP	32H	; "2"
J.18C0:	JP	NC,J.0546
	LD	D,A
	POP	HL
	PUSH	IX
	DEC	HL
	RST	10H
	POP	IX
	LD	A,00H
	JR	Z,J$18D9
	PUSH	IX
	RST	08H
	INC	L
	RST	08H
	LD	B,C
	POP	IX
	OR	01H	; 1 
J$18D9:	PUSH	HL
	PUSH	AF
	PUSH	BC
	PUSH	DE
	JR	NZ,J$18EA
	LD	BC,I.0004
	CALL	C.194B
	LD	BC,I.0E00
	JR	J$18F8

J$18EA:	LD	BC,I$0108
	CALL	C.194B
	CALL	C.196C
	JR	Z,J$18FD
	LD	BC,I$0D00
J$18F8:	LD	A,0FH	; 15 
	CALL	C$194D
J$18FD:	POP	DE
	LD	B,00H
	CALL	C.196C
	JR	NZ,J$1907
	LD	B,07H	; 7 
J$1907:	LD	A,D
	CALL	C.1A50
	POP	DE
	POP	AF
	PUSH	AF
	JR	Z,J$1915
	CALL	C.196C
	JR	Z,J$1941
J$1915:	LD	A,E
	CALL	C.1A50
	LD	A,D
	CALL	C.196C
	JR	NZ,J$193E
	PUSH	AF
	PUSH	BC
	BIT	4,A
	JR	Z,J$1927
	ADD	A,02H	; 2 
J$1927:	AND	03H	; 3 
	PUSH	AF
	LD	A,01H	; 1 
	CALL	C.1CF9
	POP	AF
	LD	B,0BH	; 11 
	CALL	C.1A59
	XOR	A
	CALL	C.1CF9
	POP	BC
	POP	AF
	SUB	80H
	DAA
J$193E:	CALL	C.1A50
J$1941:	POP	AF
	POP	HL
	LD	B,04H	; 4 
	JR	NZ,J$1949

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$1947:	LD	B,08H	; 8 
J$1949:	LD	C,0FH	; 15 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.194B:	LD	A,0DH	; 13 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$194D:	OUT	(0B4H),A
	IN	A,(0B5H)
	AND	C
	OR	B
	OUT	(0B5H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1956:	PUSH	IX
	POP	AF
	CP	(HL)
	INC	HL
	JP	NZ,J.0540

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$195E:	CALL	C.1974
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0F0H
	LD	E,A
	CALL	C.1974
	OR	E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.196C:	PUSH	BC
	PUSH	IX
	POP	BC
	BIT	4,B
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1974:	LD	A,(HL)
	INC	HL
	SUB	30H	; "0"
	JR	C,J.197D
	CP	0AH	; 10 
	RET	C
J.197D:	JP	J.0546

?.1980:	CP	2CH	; ","
	JR	Z,J$198B
	XOR	A
	CALL	C.19EC
	DEC	HL
	RST	10H
	RET	Z
J$198B:	RST	08H
	INC	L
	RST	28H
	RET	NZ
	DEC	A
	CP	04H	; 4 
	JR	NC,J.197D
	PUSH	AF
	CALL	C.1CF7
	LD	B,0BH	; 11 
	CALL	C.1CD2
	AND	0CH	; 12 
	LD	C,A
	POP	AF
	OR	C
	DEC	B
	JP	C.1A59

J$19A6:	CALL	C.1CF7
	LD	B,0AH	; 10 
	CALL	C.1CD2
	PUSH	AF
	RST	10H
	CP	2CH	; ","
	JR	Z,J$19C8
	RST	28H
	DEC	A
	CP	04H	; 4 
	JR	NC,J$19CE
	RLCA
	RLCA
	AND	0CH	; 12 
	LD	B,A
	POP	AF
	AND	03H	; 3 
	OR	B
	PUSH	AF
	DEC	HL
	RST	10H
	JR	Z,J$19D7
J$19C8:	RST	08H
	INC	L
	RST	28H
	DEC	A
	CP	04H	; 4 
J$19CE:	JP	NC,J.0546
	LD	B,A
	POP	AF
	AND	0CH	; 12 
	OR	B
	PUSH	AF
J$19D7:	LD	B,0AH	; 10 
	POP	AF
	JP	C.1A59

?.19DD:	LD	A,01H	; 1 
	JR	J$19E3

?.19E1:	LD	A,02H	; 2 
J$19E3:	CALL	C.19EC
	DEC	HL
	RST	10H
	JP	NZ,J.0540
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.19EC:	PUSH	AF
	CALL	C.1825
	LD	C,A
	CALL	C.1CF3
	LD	B,0CH	; 12 
	XOR	A
J$19F7:	CALL	C.1A59
	DEC	B
	DJNZ	J$19F7
	POP	AF
	CALL	C.1A59
	PUSH	HL
	EX	DE,HL
	DEC	A
	JR	Z,J$1A17
	LD	E,06H	; 6 
J$1A08:	DEC	C
	INC	C
	JR	Z,J.1A15
	LD	A,(HL)
	INC	HL
	CALL	C.1A50
	DEC	C
	DEC	E
	JR	NZ,J$1A08
J.1A15:	POP	HL
	RET

J$1A17:	LD	A,21H	; "!"
	CALL	C.1A50
	LD	A,03H	; 3 
	CALL	C.1A59
	LD	A,C
	PUSH	AF
	CALL	C$1CA5
	LD	B,04H	; 4 
	LD	A,E
	CALL	C.1A50
	LD	A,D
	CALL	C.1A50
	POP	AF
	LD	C,A
	XOR	A
	OUT	(7FH),A
	IN	A,(7FH)
	CP	0AAH
	JR	NZ,J.1A15
	LD	A,C
	OR	A
	LD	A,01H	; 1 
	JR	Z,J$1A42
	INC	A
J$1A42:	CALL	C.1A59
	PUSH	BC
	CALL	C.1C97
	POP	BC
	LD	A,E
	CALL	C.1A50
	LD	A,D
	POP	HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1A50:	PUSH	AF
	CALL	C.1A59
	POP	AF
	RRCA
	RRCA
	RRCA
	RRCA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1A59:	PUSH	AF
	LD	A,B
	OUT	(0B4H),A
	INC	B
	POP	AF
	OUT	(0B5H),A
	RET

J.1A62:	PUSH	HL
	CALL	C$1AD0
	PUSH	AF
	DEC	B
	JR	Z,J$1A90
	DEC	B
	JR	Z,J$1AAD
	DEC	B
	JR	Z,J$1ABC
	LD	E,55H	; "U"
	CALL	C.1B11
	CALL	C.1B1A
	CALL	C.1B32
	LD	A,08H	; 8 
	CALL	C.1B1E
	LD	BC,I$07D0
	CALL	C.1B28
J$1A86:	CALL	C$056B
	POP	AF
	LD	B,0DH	; 13 
J$1A8C:	POP	HL
	JP	C.1A59

J$1A90:	LD	HL,I.1B3E
	LD	E,0B8H
	CALL	C$1B1C
	LD	E,0A7H
	LD	A,02H	; 2 
	CALL	C.1B12
	LD	E,0A8H
	LD	A,04H	; 4 
	CALL	C.1B12
	LD	E,0A6H
J.1AA8:	CALL	C.1AEA
	JR	J$1A86

J$1AAD:	LD	HL,I.1B3E
	CALL	C.1B1A
	LD	E,2AH	; "*"
	CALL	C.1AEA
	LD	E,35H	; "5"
	JR	J.1AA8

J$1ABC:	LD	HL,I$1B46
	CALL	C.1B1A
	LD	E,6BH	; "k"
	CALL	C.1AEA
	LD	E,47H	; "G"
	CALL	C.1AEA
	LD	E,55H	; "U"
	JR	J.1AA8


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$1AD0:	LD	B,0DH	; 13 
	CALL	C.1CD2
	PUSH	AF
	CALL	C.1CF7
	LD	B,0AH	; 10 
	CALL	C.1CD2
	LD	C,A
	RRCA
	RRCA
	AND	03H	; 3 
	LD	B,A
	LD	A,C
	AND	03H	; 3 
	LD	C,A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1AEA:	CALL	C.1B11
	PUSH	BC
	PUSH	HL
	CALL	C.1B32
	POP	HL
	PUSH	HL
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
J$1AF9:	LD	A,08H	; 8 
	CALL	C.1B1E
	LD	A,09H	; 9 
	CALL	C.1B1E
	LD	A,0AH	; 10 
	CALL	C.1B1E
	CALL	C.1B28
	DEC	E
	JR	NZ,J$1AF9
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1B11:	XOR	A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1B12:	CALL	C.1B1E
	LD	E,00H
	INC	A
	JR	C.1B1E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1B1A:	LD	E,0BEH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$1B1C:	LD	A,07H	; 7 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1B1E:	DI
	OUT	(0A0H),A
	PUSH	AF
	LD	A,E
	EI
	OUT	(0A1H),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1B28:	PUSH	BC
J$1B29:	DEC	BC
	EX	(SP),HL
	EX	(SP),HL
	LD	A,B
	OR	C
	JR	NZ,J$1B29
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1B32:	LD	B,00H
	LD	HL,I$1B3A
	ADD	HL,BC
	LD	E,(HL)
	RET

I$1B3A:	DEFB	04H,07H,0AH,0FH
I.1B3E:	DEFW	10D8H
	DEFW	09A0H
	DEFW	06BDH
	DEFW	047EH
I$1B46:	DEFW	059DH
	DEFW	0335H
	DEFW	023FH
	DEFW	017FH

J$1B4E:	CALL	C.05AE
	CALL	C.1CF3
	CALL	C.1CD0
	CP	02H	; 2 
	LD	HL,I$3FD7
	JP	NZ,C.05F6
J$1B5F:	CALL	C.1CDB
	JR	Z,J$1B6A
	RST	18H
	LD	A,B
	CP	0DH	; 13 
	JR	C,J$1B5F
J$1B6A:	JP	J$05A8

J$1B6D:	CALL	C.1C73
	LD	C,A
	CPL
	CALL	C.1C74
	CALL	C.1C73
	CPL
	CP	C
	LD	A,C
	CALL	C.1C74
	LD	HL,I$1C64
	LD	C,04H	; 4 
	JR	Z,J$1B8A
	LD	HL,I$1C68
	LD	C,02H	; 2 
J$1B8A:	PUSH	HL
	LD	A,(D.FAFC)
	AND	0F9H
	OR	C
	LD	(D.FAFC),A
	LD	HL,I.0090
	LD	A,0B4H
	CALL	C.1D2B
	LD	HL,I$1C5E
	CALL	C.1C4B
	POP	HL
	CALL	C.1C4B
	LD	HL,I$1C6C
	CALL	C.1C4B
	XOR	A
	OUT	(99H),A
	OUT	(99H),A
	OUT	(99H),A
	LD	A,8EH
	OUT	(99H),A
	CALL	C.1CF3
	CALL	C.1CD0
	JR	Z,J$1C35
	DEC	A
	RET	NZ
	CALL	C.1CD2
	CP	01H	; 1 
	RET	NZ
	CALL	C.1CD2
	CP	02H	; 2 
	RET	NZ
	CALL	C.1CD2
	CP	03H	; 3 
	RET	NZ
	LD	B,08H	; 8 
	CALL	C.1CD2
	JR	Z,J.1BEF
	XOR	A
	OUT	(7FH),A
	IN	A,(7FH)
	CP	0AAH
	JR	NZ,J.1BEF
	PUSH	BC
	CALL	C.1C97
	POP	BC
	CALL	C.1CEA
	RST	20H
	RET	Z
	JR	J.1C00

J.1BEF:	LD	A,06H	; 6 
	CALL	C.0590
	AND	04H	; 4 
	JR	NZ,J.1C00
	LD	A,07H	; 7 
	CALL	C.0590
	AND	10H	; 16 
	RET	Z
J.1C00:	LD	HL,I$0032
	LD	A,0D0H
	CALL	C.1D2B
	LD	HL,I$1C54
	CALL	C.1C4B
	LD	B,08H	; 8 
	CALL	C.1CD2
	DEC	A
J$1C14:	JR	Z,J$1C14
J$1C16:	LD	HL,D.F55E
	LD	B,0FFH
J$1C1B:	CALL	C.0565
	CP	0DH	; 13 
	JR	Z,J$1C26
	LD	(HL),A
	INC	HL
	DJNZ	J$1C1B
J$1C26:	LD	A,0FFH
	SUB	B
	CALL	C$1CA2
	LD	B,04H	; 4 
	CALL	C.1CEA
	RST	20H
	RET	Z
	JR	J$1C16

J$1C35:	LD	HL,I$00C8
	LD	A,L
	CALL	C.1D2B
J$1C3C:	CALL	C.1CDB
	RET	Z
	CALL	C.1224
	LD	A,B
	CP	0DH	; 13 
	JR	C,J$1C3C
	JP	C.0565


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1C4B:	LD	A,(HL)
	INC	HL
	OR	A
	RET	Z
	CALL	C.1224
	JR	C.1C4B

I$1C54:	DEFM	'Password:',00H
I$1C5E:	DEFM	'VRAM:',00H
I$1C64:	DEFM	'128',00H
I$1C68:	DEFM	' 64',00H
I$1C6C:	DEFM	'Kbytes',00H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1C73:	DEFB	0F6H

C.1C74:	SCF
	PUSH	AF
	LD	A,07H	; 7 
	OUT	(99H),A
	LD	A,8EH
	OUT	(99H),A
	LD	A,0FFH
	OUT	(99H),A
	POP	AF
	PUSH	AF
	LD	A,7FH
	JR	C,J$1C8A
	LD	A,3FH	; "?"
J$1C8A:	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	POP	AF
	JR	C,J$1C94
	IN	A,(98H)
	RET

J$1C94:	OUT	(98H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1C97:	IN	A,(7FH)
	LD	L,A
	IN	A,(7FH)
	LD	H,A
	LD	(D.F55E),HL
	LD	A,02H	; 2 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$1CA2:	LD	HL,D.F55E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$1CA5:	LD	DE,J.0000
	LD	C,A
	OR	A
	RET	Z
	SCF
J$1CAC:	PUSH	AF
J$1CAD:	LD	B,08H	; 8 
J$1CAF:	POP	AF
	PUSH	AF
	JR	NC,J$1CB5
	RLC	(HL)
J$1CB5:	RL	E
	RL	D
	JR	NC,J$1CC3
	LD	A,D
	XOR	80H
	LD	D,A
	LD	A,E
	XOR	05H	; 5 
	LD	E,A
J$1CC3:	DJNZ	J$1CAF
	INC	HL
	DEC	C
	JR	NZ,J$1CAD
	POP	AF
	RET	NC
	OR	A
	LD	C,02H	; 2 
	JR	J$1CAC


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1CD0:	LD	B,00H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1CD2:	LD	A,B
	OUT	(0B4H),A
	INC	B
	IN	A,(0B5H)
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1CDB:	PUSH	DE
	CALL	C.1CD2
	LD	D,A
	CALL	C.1CD2
	RLCA
	RLCA
	RLCA
	RLCA
	OR	D
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1CEA:	CALL	C.1CDB
	LD	L,A
	CALL	C.1CDB
	LD	H,A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1CF3:	LD	A,03H	; 3 
	JR	C.1CF9


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1CF7:	LD	A,02H	; 2 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1CF9:	PUSH	BC
	PUSH	AF
	LD	B,0DH	; 13 
	CALL	C.1CD2
	AND	0CH	; 12 
	POP	BC
	OR	B
	OUT	(0B5H),A
	POP	BC
	RET

J$1D08:	CALL	C.1D1A
	IN	A,(0B5H)
	AND	0FH	; 15 
	RET

J$1D10:	PUSH	AF
	CALL	C.1D1A
	POP	AF
	AND	0FH	; 15 
	OUT	(0B5H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1D1A:	LD	A,C
	PUSH	AF
	AND	30H	; "0"
	RRCA
	RRCA
	RRCA
	RRCA
	CALL	C.1CF9
	POP	AF
	AND	0FH	; 15 
	OUT	(0B4H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1D2B:	LD	(D.F92A),HL
	LD	(D.F92C),A
	RET

J$1D32:	LD	A,(HL)
	EX	(SP),HL
	CP	(HL)
	JP	NZ,J.0540
	INC	HL
	EX	(SP),HL
J.1D3A:	CALL	C$FF48
	INC	HL
J.1D3E:	LD	A,(HL)
	CP	3AH	; ":"
	RET	NC
	CP	20H	; " "
	JR	Z,J.1D3A
	JR	NC,J$1DB1
	OR	A
	RET	Z
	CP	0BH	; 11 
	JR	C,J$1DAC
	CP	1EH
	JR	NZ,J$1D57
	LD	A,(D.F668)
	OR	A
	RET

J$1D57:	CP	10H	; 16 
	JR	Z,J$1D8F
	PUSH	AF
	INC	HL
	LD	(D.F668),A
	SUB	1CH
	JR	NC,J$1D94
	SUB	0F5H
	JR	NC,J$1D6E
	CP	0FEH
	JR	NZ,J$1D82
	LD	A,(HL)
	INC	HL
J$1D6E:	LD	(D.F666),HL
	LD	H,00H
J$1D73:	LD	L,A
	LD	(D.F66A),HL
	LD	A,02H	; 2 
	LD	(D.F669),A
	LD	HL,I.46E6
	POP	AF
	OR	A
	RET

J$1D82:	LD	A,(HL)
	INC	HL
	INC	HL
	LD	(D.F666),HL
	DEC	HL
	LD	H,(HL)
	JR	J$1D73

?.1D8C:	CALL	C$1DB7
J$1D8F:	LD	HL,(D.F666)
	JR	J.1D3E

J$1D94:	INC	A
	RLCA
	LD	(D.F669),A
	PUSH	DE
	PUSH	BC
	LD	DE,D.F66A
	CALL	C.1DF0
	POP	BC
	POP	DE
	LD	(D.F666),HL
	POP	AF
	LD	HL,I.46E6
	OR	A
	RET

J$1DAC:	CP	09H	; 9 
	JP	NC,J.1D3A
J$1DB1:	CP	30H	; "0"
	CCF
	INC	A
	DEC	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$1DB7:	LD	A,(D.F668)
	CP	0FH	; 15 
	JR	NC,J.1DD1
	CP	0DH	; 13 
	JR	C,J.1DD1
	LD	HL,(D.F66A)
	JR	NZ,J$1DCE
	INC	HL
	INC	HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
J$1DCE:	JP	C.05DE

J.1DD1:	LD	A,(D.F669)
	LD	(D.F663),A
	CP	02H	; 2 
	JR	NZ,J$1DE1
	LD	HL,(D.F66A)
	LD	(D.F7F8),HL
J$1DE1:	LD	HL,D.F66A
	LD	DE,I$F7F6
	LD	A,(D.F663)
	CP	04H	; 4 
	JR	NC,C.1DF0
	INC	DE
	INC	DE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1DF0:	LD	C,A
	LD	B,00H
	LDIR
	RET

J$1DF6:	JP	Z,J$1ED5
	CP	0EFH
	JP	Z,J$1ECA
	CP	0C7H
I$1E00:	JP	Z,J$2040
	LD	DE,(D.F3E9)
	PUSH	DE
	CP	2CH	; ","
	JR	Z,J$1E17
	RST	28H
	CALL	C.1E40
	POP	DE
	LD	E,A
	PUSH	DE
	DEC	HL
	RST	10H
	JR	Z,J.1E33
J$1E17:	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$1E28
	RST	28H
	CALL	C.1E40
	POP	DE
	LD	D,A
	PUSH	DE
	DEC	HL
	RST	10H
	JR	Z,J.1E33
J$1E28:	RST	08H
	INC	L
	RST	28H
	CALL	C.1E40
	LD	(D.F3EB),A
	DEC	HL
	RST	10H
J.1E33:	EX	(SP),HL
	LD	(D.F3E9),HL
	LD	A,L
	LD	(D.F3F2),A
	CALL	C.0953
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1E40:	CALL	C.1E47
	RET	NC
	JP	J.0546


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1E47:	PUSH	AF
	LD	A,(D.FCAF)
	CP	06H	; 6 
	JR	Z,J$1E5B
	CP	08H	; 8 
	JR	Z,J$1E58
	POP	AF
	CP	10H	; 16 
	CCF
	RET

J$1E58:	POP	AF
	AND	A
	RET

J$1E5B:	POP	AF
	CP	20H	; " "
	CCF
	RET	C
	CP	10H	; 16 
	JR	C,J$1E67
	AND	0FH	; 15 
	RET

J$1E67:	AND	03H	; 3 
	PUSH	BC
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	POP	BC
	RET

J$1E70:	RST	10H
	LD	A,0FH	; 15 
	CALL	C.1EDC
	PUSH	AF
	CALL	C.0F6A
	PUSH	BC
	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$1E98
	LD	A,07H	; 7 
	CALL	C.1EDC
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	E,A
	POP	BC
	LD	A,B
	AND	0FH	; 15 
	OR	E
	LD	B,A
	PUSH	BC
	DEC	HL
	RST	10H
	CP	29H	; ")"
	JR	Z,J.1EBA
J$1E98:	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$1EAC
	LD	A,07H	; 7 
	CALL	C.1EDC
	POP	BC
	LD	C,A
	PUSH	BC
	DEC	HL
	RST	10H
	CP	29H	; ")"
	JR	Z,J.1EBA
J$1EAC:	RST	08H
	INC	L
	LD	A,07H	; 7 
	CALL	C.1EDC
	POP	BC
	LD	A,B
	AND	0F0H
	OR	E
	LD	B,A
	PUSH	BC
J.1EBA:	RST	08H
	ADD	HL,HL
	POP	BC
	LD	A,B
	LD	E,C
	POP	BC
	LD	D,B
	PUSH	AF
	CALL	C.1034
	POP	AF
	CALL	C.0FD3
	RET

J$1ECA:	RST	10H
	CP	28H	; "("
	JR	Z,J$1E70
	CP	8CH
	JR	Z,J$1ED8
	RST	08H
	SUB	H
J$1ED5:	JP	J.0F9F

J$1ED8:	RST	10H
	JP	J.0F7E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1EDC:	PUSH	AF
	RST	28H
	POP	AF
	CP	E
	LD	A,E
	RET	NC
	JP	J.0546

J$1EE5:	CP	2CH	; ","
	JR	Z,J$1F1D
	RST	28H
	CP	09H	; 9 
	JP	NC,J.0546
	CP	05H	; 5 
	JR	C,J$1F0E
	PUSH	AF
	LD	A,(D.FAFC)
	RRCA
	AND	03H	; 3 
	LD	C,A
	POP	AF
	CP	07H	; 7 
	PUSH	AF
	LD	A,C
	JR	NC,J$1F08
	CP	01H	; 1 
	JR	C,J$1F0A
	JR	J$1F0D

J$1F08:	CP	02H	; 2 
J$1F0A:	JP	C,J.0546
J$1F0D:	POP	AF
J$1F0E:	PUSH	HL
	CALL	C.09BF
	LD	A,(D.F3B0)
	LD	E,A
	CALL	C.2033
	POP	HL
	DEC	HL
	RST	10H
	RET	Z
J$1F1D:	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$1F3A
	RST	28H
	CP	04H	; 4 
	JP	NC,J.0546
	LD	A,(D.F3E0)
	AND	0FCH
	OR	E
	LD	(D.F3E0),A
	PUSH	HL
	CALL	C.06F5
	POP	HL
	DEC	HL
	RST	10H
	RET	Z
J$1F3A:	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$1F45
	RST	28H
	LD	(D.F3DB),A
	RET	Z
J$1F45:	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$1F51
	CALL	C$1F7A
	DEC	HL
	RST	10H
	RET	Z
J$1F51:	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$1F5C
	RST	28H
	LD	(D.F417),A
	RET	Z
J$1F5C:	RST	08H
	INC	L
	RST	28H
	CP	04H	; 4 
	JP	NC,J.0546
	ADD	A,A
	BIT	1,A
	JR	Z,J$1F6B
	SET	3,A
J$1F6B:	AND	0CH	; 12 
	LD	B,A
	LD	A,(D.FFE8)
	AND	0F3H
	OR	B
	LD	C,09H	; 9 
J$1F76:	LD	B,A
	JP	C.0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$1F7A:	RST	28H
	DEC	A
	CP	02H	; 2 
	JP	NC,J.0546
	PUSH	HL
	LD	BC,BDOS
	AND	A
	LD	HL,D.F3FC
	JR	Z,J$1F8C
	ADD	HL,BC
J$1F8C:	LD	DE,I.F406
	LDIR
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.1F93:	PUSH	BC
	LD	B,A
	CALL	C.062C
	JR	C,J$1FAE
	CP	07H	; 7 
	LD	A,01H	; 1 
	JR	NC,J.1FAD
	LD	A,(D.FAFC)
	AND	06H	; 6 
	CP	04H	; 4 
	LD	A,01H	; 1 
	JR	C,J.1FAD
	LD	A,03H	; 3 
J.1FAD:	CP	B
J$1FAE:	LD	A,B
	POP	BC
	RET

?.1FB1:	LD	DE,(D.FAF5)
	CP	2CH	; ","
	JR	Z,J$1FC7
	PUSH	DE
	RST	28H
	POP	DE
	CALL	C.1F93
J$1FBF:	JP	C,J.0546
	LD	E,A
	DEC	HL
	RST	10H
	JR	Z,J$1FD2
J$1FC7:	PUSH	DE
	RST	08H
	INC	L
	RST	28H
	POP	DE
	CALL	C.1F93
	JR	C,J$1FBF
	LD	D,A
J$1FD2:	LD	(D.FAF5),DE
	PUSH	HL
	CALL	C.2980
	CALL	C.06A8
	POP	HL
	RET

J$1FDF:	JP	Z,J.0546
	LD	A,(D.FCB0)
	AND	A
	LD	A,E
	JR	Z,J$1FEE
	CP	21H	; "!"
	JP	NC,J.0546
J$1FEE:	CP	29H	; ")"
	JR	C,J$1FF7
	CP	51H	; "Q"
	JP	NC,J.0546
J$1FF7:	LD	A,(D.F3B0)
	CP	E
	RET	Z
	LD	A,0CH	; 12 
	RST	18H
J$1FFF:	LD	A,E
I.2000:	LD	(D.F3B0),A
	CALL	C.2033
	LD	A,(D.FCB0)
	DEC	A
	LD	A,E
	JR	NZ,J$2014
	LD	(D.F3AF),A
	LD	A,0CH	; 12 
	RST	18H
	RET

J$2014:	LD	C,29H	; ")"
	LD	A,(D.F3AE)
	CP	C
	LD	A,E
	LD	(D.F3AE),A
	PUSH	AF
	LD	A,0CH	; 12 
	RST	18H
	POP	AF
	JR	C,J$2028
	CP	C
	RET	NC
	LD	C,A
J$2028:	CP	C
	RET	C
	PUSH	AF
	PUSH	HL
	XOR	A
	CALL	C.09BF
	POP	HL
	POP	AF
	LD	E,A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2033:	SUB	0EH	; 14 
	JR	NC,C.2033
	ADD	A,1CH
	CPL
	INC	A
	ADD	A,E
	LD	(D$F3B2),A
	RET

J$2040:	CALL	C.0626
	JP	C,J.0546
	RST	10H
	CP	24H	; "$"
	JR	Z,J$2065
	LD	A,1FH
	CALL	C.2318
	PUSH	HL
	CALL	C.0775
	EX	(SP),HL
	RST	08H
	RST	28H
	RST	28H
	AND	A
	JP	M,J.0546
	LD	BC,C.0010
	EX	(SP),HL
	CALL	C.0977
	POP	HL
	RET

J$2065:	RST	08H
	INC	H
	LD	A,1FH
	CALL	C.2318
	PUSH	HL
	CALL	C.0775
	EX	(SP),HL
	RST	08H
	RST	28H
	CALL	C.05FC
	PUSH	HL
	CALL	C.0614
	LD	A,(HL)
	CP	11H	; 17 
	JR	C,J$2081
	LD	A,10H	; 16 
J$2081:	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	POP	HL
	EX	(SP),HL
	AND	A
	LD	B,A
	EX	DE,HL
	CALL	NZ,C.0F2B
	POP	HL
	RET

J$208F:	RST	10H
	RST	28H
	CP	20H	; " "
	JP	NC,J.0546
	LD	(D.F560),A
	PUSH	HL
	PUSH	AF
	CALL	C.0775
	LD	(D.FC18),HL
	LD	DE,I.FC1A
	LD	B,10H	; 16 
	CALL	C.0F22
	POP	AF
	PUSH	AF
	CALL	C.076A
	LD	(D.F55E),HL
	POP	AF
	LD	B,A
	LD	A,20H	; " "
	SUB	B
	LD	B,A
	LD	(D.F561),A
	LD	DE,D.F562
	PUSH	DE
	CALL	C.0F22
	POP	HL
	EX	(SP),HL
	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$20F5
	CALL	C.059C
	EX	(SP),HL
	LD	(HL),E
	INC	HL
	LD	A,B
	ADD	A,A
	LD	A,C
	LD	C,00H
	JR	NC,J$20DA
	ADD	A,20H	; " "
	LD	C,80H
J$20DA:	LD	(HL),A
	PUSH	HL
	LD	HL,I.FC1A
I$20DF:	LD	B,10H	; 16 
J$20E1:	LD	A,(HL)
	AND	7FH
	OR	C
	LD	(HL),A
	INC	HL
	DJNZ	J$20E1
	CALL	C.217A
	POP	HL
	INC	HL
	EX	(SP),HL
	DEC	HL
	RST	10H
	POP	BC
	JR	Z,J.212E
	PUSH	BC
J$20F5:	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J$2119
	RST	28H
	AND	A
	JP	M,J.0546
	PUSH	HL
	LD	HL,I.FC1A
	LD	C,A
	LD	B,10H	; 16 
J$2107:	LD	A,(HL)
	AND	80H
	OR	C
	LD	(HL),A
	INC	HL
	DJNZ	J$2107
	CALL	C.217A
	POP	HL
	DEC	HL
	RST	10H
	POP	BC
	JR	Z,J.212E
	PUSH	BC
J$2119:	RST	08H
	INC	L
	RST	28H
	CALL	C.077F
	LD	A,E
	JR	NC,J$2129
	CP	40H	; "@"
	JP	NC,J.0546
	ADD	A,A
	ADD	A,A
J$2129:	EX	(SP),HL
	LD	(HL),A
	LD	B,H
	LD	C,L
	POP	HL
J.212E:	PUSH	HL
	LD	A,(D.F560)
	SUB	1FH
	JR	Z,J.216A
	LD	HL,(D.FC18)
	LD	A,(D.F561)
	LD	B,A
J$213D:	LD	DE,C.0010
	ADD	HL,DE
	PUSH	HL
	PUSH	BC
	LD	DE,I.FC1A
	LD	B,10H	; 16 
	CALL	C.0F22
	CALL	C$2187
	POP	BC
	POP	HL
	JR	Z,J$2154
	DJNZ	J$213D
J$2154:	LD	A,(D.F561)
	SUB	B
	JR	Z,J.216A
	LD	B,A
	LD	HL,D.F566
	LD	DE,(D.F562)
J$2162:	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	INC	HL
	INC	HL
	DJNZ	J$2162
J.216A:	INC	A
	ADD	A,A
	ADD	A,A
	LD	B,A
	LD	HL,D.F562
	LD	DE,(D.F55E)
	CALL	C.0F2B
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.217A:	LD	HL,I.FC1A
	LD	DE,(D.FC18)
	LD	B,10H	; 16 
	CALL	C.0F2B
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2187:	LD	HL,I.FC1A
	LD	B,10H	; 16 
J$218C:	LD	A,(HL)
	AND	40H	; "@"
	RET	NZ
	INC	HL
	DJNZ	J$218C
	XOR	A
	RET

?.2195:	DEC	B
	JP	M,J.0540
	LD	A,(D.FCAF)
	CP	05H	; 5 
	JP	C,J.0546
	RST	10H
	CP	2CH	; ","
	CALL	NZ,C.059C
	RST	08H
	INC	L
	CALL	C.0608
	PUSH	DE
	CALL	C.256F
	CALL	C.2594
	DEC	HL
	RST	10H
	CP	2CH	; ","
	LD	A,00H
	JR	NZ,J$21C2
	RST	10H
	RST	28H
	CP	03H	; 3 
	JP	NC,J.0546
J$21C2:	POP	BC
	JP	J.1049

J$21C6:	LD	A,2FH	; "/"
	CALL	C.2318
	CP	08H	; 8 
	JR	C,J.21DD
	JP	Z,J.0546
	DEC	E
	DEC	A
	CP	18H
	JR	C,J.21DD
	CP	20H	; " "
	JP	C,J.0546
J.21DD:	PUSH	DE
	RST	08H
	RST	28H
	RST	28H
	POP	BC
	JP	J$1F76

J$21E5:	RST	10H
	RST	08H
	JR	Z,J$21B6
	EX	AF,AF'
	LD	B,0CFH
	ADD	HL,HL
	PUSH	HL
	LD	A,D
	RLCA
	JR	C,J$220E
	AND	A
	JR	NZ,J$21F8
	LD	A,E
	CP	19H
J$21F8:	JP	NC,J.0546
	CP	09H	; 9 
	JR	NC,J$2204
	LD	HL,D.F3DF
	JR	J$2207

J$2204:	LD	HL,I$FFDE
J$2207:	ADD	HL,DE
	LD	A,(HL)
J$2209:	CALL	C.05E4
	POP	HL
	RET

J$220E:	EX	DE,HL
	CALL	C.25DC
	EX	DE,HL
	LD	HL,I.0009
	RST	20H
	JP	C,J.0546
	LD	A,E
	CALL	C.298B
	JR	J$2209

J$2220:	LD	A,13H	; 19 
	CALL	C.2318
	LD	D,00H
	PUSH	DE
	RST	08H
	RST	28H
	CALL	C.0608
	CP	40H	; "@"
	JP	NC,J.0546
	EX	(SP),HL
	PUSH	HL
	LD	C,E
	LD	B,D
	POP	HL
	LD	A,L
	PUSH	AF
	ADD	HL,HL
	EX	DE,HL
	LD	HL,I$226F
	ADD	HL,DE
	LD	A,C
	AND	(HL)
	JR	NZ,J$2246
	INC	HL
	LD	A,B
	AND	(HL)
J$2246:	JP	NZ,J.0546
	LD	HL,D.F3B3
	ADD	HL,DE
	LD	(HL),C
	INC	HL
	LD	(HL),B
	POP	AF
	LD	E,0FFH
J$2253:	INC	E
	SUB	05H	; 5 
	JR	NC,J$2253
	LD	A,(D.FCAF)
	CP	E
	CALL	Z,C$2261
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2261:	DEC	A
	JP	M,C.0B42
	JP	Z,C.0B9C
	DEC	A
	JP	Z,C.0BD2
	JP	C.0C22

I$226F:	DEFW	03FFH
	DEFW	003FH
	DEFW	07FFH
	DEFW	007FH
	DEFW	07FFH
	DEFW	03FFH
	DEFW	003FH
	DEFW	07FFH
	DEFW	007FH
	DEFW	07FFH
	DEFW	03FFH
	DEFW	1FFFH
	DEFW	1FFFH
	DEFW	007FH
	DEFW	07FFH
	DEFW	03FFH
	DEFW	003FH
	DEFW	07FFH
	DEFW	007FH
	DEFW	07FFH

J$2297:	RST	10H
	LD	A,2CH	; ","
	CALL	C.2318
	CP	14H	; 20 
	JR	NC,J$22C2
	PUSH	HL
J$22A2:	CP	02H	; 2 
	JR	NZ,J.22B2
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	C,J.22B2
	LD	HL,I.1000
	JR	J.22BD

J.22B2:	LD	HL,D.F3B3
	LD	D,00H
	ADD	HL,DE
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
J.22BD:	CALL	C.05DE
	POP	HL
	RET

J$22C2:	PUSH	HL
	SUB	19H
	JR	NC,J$22D3
	ADD	A,0FH	; 15 
	LD	E,A
	CP	0DH	; 13 
	JR	NZ,J$22A2
	LD	HL,(D$22DE)
	JR	J.22BD

J$22D3:	LD	D,00H
	LD	E,A
	LD	HL,I$22E0
	ADD	HL,DE
	LD	H,(HL)
	LD	L,D
	JR	J.22BD

D$22DE:	DEFW	1E00H
I$22E0:	DEFB	00H,00H,00H,76H,78H,00H,00H,00H
	DEFB	76H,78H,00H,00H,00H,0FAH,0F0H,00H
	DEFB	00H,00H,0FAH,0F0H

J$22F4:	CALL	C$0602
	PUSH	DE
	RST	08H
	INC	L
	RST	28H
	EX	(SP),HL
	CALL	C.08CB
	LD	HL,J.0000
	CALL	C.08D6
	POP	HL
	RET

J$2307:	CALL	C$05B4
	CALL	C.08D6
	PUSH	AF
	LD	HL,J.0000
	CALL	C.08D6
	POP	AF
	JP	C.05E4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2318:	PUSH	AF
	RST	08H
	JR	Z,J$230B
	POP	AF
	CP	E
	JP	C,J.0546
	RST	08H
	ADD	HL,HL
	LD	A,E
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2325:	LD	A,(D.F663)
	CP	08H	; 8 
	JR	NC,J$2331
	SUB	03H	; 3 
	OR	A
	SCF
	RET

J$2331:	SUB	03H	; 3 
	OR	A
	RET

?.2335:	CALL	C$2325
	LD	HL,(D.F7F8)
	RET	M
	JP	Z,J$0552
	JP	J$05F0

J$2342:	CP	0C5H
	JP	Z,J$3676
	LD	(D.F55E),HL
	CP	28H	; "("
	JR	Z,J$23C3
	CALL	C.24F6
	LD	(D.F562),DE
	LD	(D.F564),BC
	JR	NC,J$238C
	DEC	HL
	RST	10H
	JP	Z,J.254D
	CP	0D9H
	JR	NZ,J$236F
	RST	10H
	CP	28H	; "("
	JR	NZ,J$2378
	XOR	A
	LD	(D.F56F),A
	JR	J$2372

J$236F:	CALL	C.252B
J$2372:	PUSH	HL
	LD	HL,J.30A8
	JR	J$23A4

J$2378:	CALL	C.24F6
	JP	C,J.254D
	LD	(D.F566),DE
	LD	(D.F568),BC
	PUSH	HL
	LD	HL,J.306F
	JR	J$23BD

J$238C:	DEC	HL
	RST	10H
	CP	0D9H
	JR	NZ,J$239D
	RST	10H
	CP	28H	; "("
	JR	NZ,J$23AB
	XOR	A
	LD	(D.F56F),A
	JR	J$23A0

J$239D:	CALL	C.252B
J$23A0:	PUSH	HL
	LD	HL,J.2F42
J$23A4:	LD	(D.F560),HL
	POP	HL
	JP	J.24A9

J$23AB:	CALL	C.24F6
	JP	NC,J.0540
	LD	(D.F566),DE
	LD	(D.F568),BC
	PUSH	HL
	LD	HL,J.307C
J$23BD:	LD	(D.F560),HL
	JP	J$24E4

J$23C3:	PUSH	HL
	LD	HL,J.2EB9
	LD	(D.F560),HL
	POP	HL
	CALL	C.059C
	PUSH	BC
	PUSH	DE
	RST	08H
	JP	P,J.A2CD
	DEC	B
	DEC	HL
	RST	10H
	CP	0D9H
	LD	A,(D.FAF6)
	JR	Z,J$23E1
	RST	08H
	INC	L
	RST	28H
J$23E1:	CALL	C.1F93
	JP	C,J.0546
	LD	(D$F565),A
	POP	DE
	POP	BC
	RST	08H
	EXX
	PUSH	HL
	CALL	C.12C4
	LD	(D.F562),BC
	LD	A,E
	LD	(D.F564),A
	CALL	C.25F1
	CALL	C.12C4
	CALL	C.25F1
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C.25D5
	JR	NC,J$240F
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J$240F:	INC	HL
	LD	(D.F56A),HL
	CALL	C.25E6
	JR	NC,J$241C
	EX	AF,AF'
	OR	08H	; 8 
	EX	AF,AF'
J$241C:	INC	HL
	LD	(D.F56C),HL
	EX	AF,AF'
	LD	(D.F56F),A
	EX	AF,AF'
	PUSH	BC
	PUSH	DE
	LD	BC,(D.F56A)
	LD	E,L
	LD	D,H
	CALL	C.3376
	JP	C,J.0546
	POP	DE
	POP	BC
	POP	HL
	DEC	HL
	RST	10H
	CP	28H	; "("
	JR	Z,J.24A9
	CALL	C.24F6
	LD	(D.F566),DE
	LD	(D.F568),BC
	JR	NC,J$2450
	PUSH	HL
	LD	HL,J.31B4
	JP	J$24A4

J$2450:	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	BC,(D.F56A)
	LD	DE,(D.F56C)
	CALL	C.3052
	LD	A,00H
	ADD	A,A
	LD	E,A
	CALL	C$253B
	DEC	B
	JR	Z,J.248D
	DEC	B
	JR	Z,J$2480
	LD	BC,I$0003
	ADD	HL,BC
	LD	A,E
	ADC	A,00H
	SRL	A
	RR	H
	RR	L
	SRL	A
	RR	H
	RR	L
	JR	J.248D

J$2480:	LD	BC,I.0001
	ADD	HL,BC
	LD	A,E
	ADC	A,00H
	SRL	A
	RR	H
	RR	L
J.248D:	POP	DE
	ADD	HL,DE
	JR	C,J.249E
	NOP
	LD	DE,I.0004
	ADD	HL,DE
	JR	C,J.249E
	NOP
	POP	DE
	EX	DE,HL
	AND	A
	SBC	HL,DE
J.249E:	JP	C,J.0546
	LD	HL,J.2EDF
J$24A4:	LD	(D.F560),HL
	JR	J$24DE

J.24A9:	CALL	C.05A2
	PUSH	HL
	CALL	C.12C4
	LD	(D.F566),BC
	LD	A,E
	LD	(D.F568),A
	POP	HL
	XOR	A
	LD	(D.F569),A
	DEC	HL
	RST	10H
	LD	A,(D.FAF6)
	JR	Z,J$24CE
	RST	08H
	INC	L
	CP	2CH	; ","
	LD	A,(D.FAF6)
	CALL	NZ,C.060E
J$24CE:	CALL	C.1F93
	JP	C,J.0546
	LD	(D.F569),A
	CALL	C.2594
	LD	(D$F570),A
	PUSH	HL
J$24DE:	CALL	C.062C
	JP	C,J.0546
J$24E4:	LD	HL,I$24F0
	PUSH	HL
	LD	HL,(D.F560)
	PUSH	HL
	LD	HL,D.F562
	RET

I$24F0:	POP	HL
	JP	C,J.0546
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.24F6:	PUSH	HL
	CALL	C.05FC
	LD	A,(D.F663)
	CP	03H	; 3 
	JR	Z,J$2523
	POP	HL
	LD	A,01H	; 1 
	LD	(D.F6A5),A
	CALL	C.05D8
	JP	NZ,J.0546
	LD	(D.F6A5),A
	PUSH	HL
	LD	H,B
	LD	L,C
	EX	DE,HL
	ADD	HL,DE
	DEC	HL
	PUSH	HL
	LD	A,(BC)
	ADD	A,A
	LD	L,A
	LD	H,00H
	INC	BC
	ADD	HL,BC
	EX	DE,HL
	POP	BC
	POP	HL
	AND	A
	RET

J$2523:	PUSH	HL
	CALL	C.0614
	POP	HL
	POP	DE
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.252B:	RST	08H
	INC	L
	RST	28H
	CP	04H	; 4 
	JP	NC,J.0546
	ADD	A,A
	ADD	A,A
	LD	(D.F56F),A
	RST	08H
	EXX
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$253B:	LD	B,01H	; 1 
	LD	A,(D.FCAF)
	CP	08H	; 8 
	RET	Z
	INC	B
	CP	05H	; 5 
	RET	Z
	CP	07H	; 7 
	RET	Z
	INC	B
	INC	B
	RET

J.254D:	XOR	A
	LD	(D.F6A5),A
	LD	HL,(D.F55E)
	SCF
	RET

J$2556:	PUSH	AF
	CALL	C.05A2
	POP	AF
	CALL	C$2572
	CALL	C.2594
	PUSH	HL
	CALL	C.12C4
	JR	NC,J$256D
	CALL	C.1342
	CALL	C.13B5
J$256D:	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.256F:	LD	A,(D.F3E9)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2572:	PUSH	BC
	PUSH	DE
	LD	E,A
	CALL	C.0620
	JP	C,J.0546
	DEC	HL
	RST	10H
	JR	Z,J.2586
	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J.2586
	RST	28H
J.2586:	LD	A,E
	PUSH	HL
	CALL	C.13AD
	JP	C,J.0546
	POP	HL
	POP	DE
	POP	BC
	JP	J.1D3E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2594:	LD	A,00H
	PUSH	DE
	LD	D,00H
	LD	E,A
	DEC	HL
	RST	10H
	JR	Z,J.25CC
	RST	08H
	INC	L
	JP	Z,J$054C
	CP	2CH	; ","
	JR	Z,J.25CC
	LD	E,A
	CP	54H	; "T"
	JR	Z,J$25C4
	CP	0D9H
	JR	Z,J$25BC
	INC	A
	JR	NZ,J$25CB
	RST	10H
	RST	08H
	ADC	A,L
	RST	08H
	LD	B,H
	LD	E,0F6H
	JR	J$25C1

J$25BC:	RST	10H
	RST	08H
	LD	D,D
	LD	E,0F7H
J$25C1:	DEC	HL
	JR	J$25C9

J$25C4:	RST	10H
	JP	Z,J.0540
	LD	E,A
J$25C9:	LD	D,08H	; 8 
J$25CB:	RST	10H
J.25CC:	LD	A,E
	CALL	C$27B6
	JP	C,J.0540
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.25D5:	LD	HL,(D.FCB3)
	AND	A
	SBC	HL,BC
J$25DB:	RET	NC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.25DC:	XOR	A
	SUB	L
	LD	L,A
	SBC	A,H
	SUB	L
	LD	H,A
	XOR	A
	SUB	01H	; 1 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.25E6:	LD	HL,(D.FCB5)
	AND	A
	SBC	HL,DE
	JR	J$25DB


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.25EE:	CALL	C.12C4

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.25F1:	CALL	C.2600

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$25F4:	PUSH	HL
	PUSH	BC
	LD	HL,(D.FCB3)
	EX	(SP),HL
	LD	(D.FCB3),HL
	POP	BC
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2600:	PUSH	HL
	LD	HL,(D.FCB5)
	EX	DE,HL
	JR	J$263A

J$2607:	CALL	C.059C
	PUSH	BC
	PUSH	DE
	RST	08H
	JP	P,J.A2CD
	DEC	B
	CALL	C.256F
	POP	DE
	POP	BC
	DEC	HL
	RST	10H
	JR	Z,J.263F
	RST	08H
	INC	L
	CP	2CH	; ","
	JR	Z,J.263F
	RST	08H
	LD	B,D
	JR	Z,J.2648
	CP	2CH	; ","
	JR	Z,J.2648
	RST	08H
	LD	B,(HL)
J$262A:	CALL	C.2594
	PUSH	HL
	CALL	C.2898
J.2631:	LD	HL,(D.FCB7)
	LD	(D.FCB3),HL
	LD	HL,(D.FCB9)
J$263A:	LD	(D.FCB5),HL
	POP	HL
	RET

J.263F:	CALL	C.2594
	PUSH	HL
	CALL	C.2823
	JR	J.2631

J.2648:	CALL	C.2594
	PUSH	HL
	CALL	C.27E7
	JR	J.2631

J$2651:	CALL	C.059C
	PUSH	BC
	PUSH	DE
	CALL	C.256F
	LD	A,(D.F3F2)
	LD	E,A
	DEC	HL
	RST	10H
	JR	Z,J$2664
	RST	08H
	INC	L
	RST	28H
J$2664:	LD	A,E
	AND	A
	CALL	C$14C7
	JP	C,J.0546
	POP	DE
	POP	BC
	PUSH	HL
	CALL	C$27AD
	CALL	C.1342
	LD	DE,I.0001
	CALL	C.277E
	JR	Z,J.2691
	PUSH	HL
	CALL	C.278F
	POP	DE
	ADD	HL,DE
	EX	DE,HL
	XOR	A
	CALL	C.275B
	LD	A,40H	; "@"
	CALL	C.275B
	LD	B,0C0H
	JR	J$26B3

J.2691:	POP	HL
	RET

J$2693:	LD	A,(D$FC9B)
	OR	A
	CALL	NZ,C$0589
	LD	A,(D.F94A)
	OR	A
	JR	Z,J.26AC
	LD	HL,(D.F94B)
	PUSH	HL
	LD	HL,(D.F949)
	PUSH	HL
	LD	HL,(D.F94D)
	PUSH	HL
J.26AC:	POP	DE
	POP	BC
	POP	HL
	LD	A,C
	CALL	C.137D
J$26B3:	LD	A,B
	LD	(D.F953),A
	ADD	A,A
	JR	Z,J.2691
	PUSH	DE
	JR	NC,J$26C2
	CALL	C.1414
	JR	J$26C5

J$26C2:	CALL	C.13FC
J$26C5:	POP	DE
	JR	C,J.26AC
	CALL	C.277E
	JP	Z,J.26AC
	XOR	A
	LD	(D.F94A),A
	CALL	C.278F
	LD	E,L
	LD	D,H
	OR	A
	JR	Z,J.26F4
	DEC	HL
	DEC	HL
	LD	A,H
	ADD	A,A
	JR	C,J.26F4
	LD	(D.F94D),DE
	CALL	C.1376
	LD	(D.F94B),HL
	LD	(D.F949),A
	LD	A,(D.F953)
	CPL
	LD	(D.F94A),A
J.26F4:	LD	HL,(D.F951)
	ADD	HL,DE
	EX	DE,HL
	CALL	C$274F
	LD	HL,(D.F942)
	LD	A,(D.F944)
	CALL	C.137D
J.2705:	LD	HL,(D.F94F)
	LD	DE,(D.F951)
	OR	A
	SBC	HL,DE
	JR	Z,J.274C
	JR	C,J$272F
	EX	DE,HL
	LD	B,01H	; 1 
	CALL	C.277E
	JR	Z,J.274C
	OR	A
	JR	Z,J.2705
	EX	DE,HL
	LD	HL,(D.F942)
	LD	A,(D.F944)
	LD	C,A
	LD	A,(D.F953)
	LD	B,A
	CALL	C$2760
	JR	J.2705

J$272F:	CALL	C.25DC
	DEC	HL
	DEC	HL
	LD	A,H
	ADD	A,A
	JR	C,J.274C
	INC	HL
	PUSH	HL
	EX	DE,HL
	LD	HL,(D.F92A)
	OR	A
	SBC	HL,DE
	LD	(D.F92A),HL
	POP	DE
	LD	A,(D.F953)
	CPL
	CALL	C.275B
J.274C:	JP	J$2693


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$274F:	LD	A,(D.F954)
	LD	C,A
	LD	A,(D.F955)
	OR	C
	RET	Z
	LD	A,(D.F953)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.275B:	LD	B,A
	CALL	C.1376
	LD	C,A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2760:	EX	(SP),HL
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	C,02H	; 2 
	PUSH	HL
	LD	HL,(D.F6C6)
	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	A,88H
	SUB	L
	LD	L,A
	LD	A,0FFH
	SBC	A,H
	LD	H,A
	JR	C,J$277B
	ADD	HL,SP
	POP	HL
	RET	C
J$277B:	JP	J$0558


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.277E:	CALL	C.14DB
	LD	(D.F94F),DE
	LD	(D.F951),HL
	LD	A,H
	OR	L
	LD	A,C
	LD	(D.F955),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.278F:	CALL	C.1376
	PUSH	HL
	PUSH	AF
	LD	HL,(D.F942)
	LD	A,(D.F944)
	CALL	C.137D
	POP	AF
	POP	HL
	LD	(D.F942),HL
	LD	(D.F944),A
	CALL	C.158F
	LD	A,C
	LD	(D.F954),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$27AD:	PUSH	HL
	CALL	C.12C4
	JP	NC,J.0546
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$27B6:	AND	A
	JR	Z,J$27E2
	PUSH	BC
	LD	B,A
	CALL	C.062C
	LD	A,B
	POP	BC
	RET	C
	CP	0F8H
	JR	Z,J$27E0
	CP	0F7H
	JR	Z,J$27DD
	CP	0F6H
	JR	Z,J$27DA
	CP	0C3H
	JR	Z,J$27D7
	CP	0C2H
	SCF
	RET	NZ
	XOR	A
	JP	NZ,J$043E
J$27D7	EQU	$-2
	JP	NZ,J$013E
J$27DA	EQU	$-2
	JP	NZ,J$023E
J$27DD	EQU	$-2
	JP	NZ,J$033E
J$27E0	EQU	$-2
J$27E2:	OR	D
	LD	(D.FB02),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.27E7:	CALL	C.25EE
	CALL	C.25EE
	CALL	C.25D5
	JR	Z,C.2823
	CALL	C,C$25F4
	CALL	C.25E6
	JR	Z,C.2823
	CALL	C,C.2600
	LD	HL,(D.FCB5)
	PUSH	HL
	PUSH	DE
	EX	DE,HL
	CALL	C.2823
	POP	HL
	LD	(D.FCB5),HL
	EX	DE,HL
	CALL	C.2823
	POP	HL
	DEC	HL
	INC	DE
	LD	(D.FCB5),HL
	LD	HL,(D.FCB3)
	PUSH	BC
	LD	C,L
	LD	B,H
	CALL	C.2823
	POP	HL
	LD	(D.FCB3),HL
	LD	C,L
	LD	B,H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2823:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(D.FCB5)
	PUSH	HL
	LD	HL,(D.FCB3)
	PUSH	HL
	CALL	C.25EE
	CALL	C.12C4
	CALL	C.25E6
	CALL	C,C.25F1
	PUSH	DE
	PUSH	HL
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C.25D5
	EX	DE,HL
	JR	NC,J$2849
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J$2849:	POP	HL
	RST	20H
	JR	C,J$2852
	EX	DE,HL
	EX	AF,AF'
	OR	01H	; 1 
	EX	AF,AF'
J$2852:	EX	(SP),HL
	CALL	C.2980
	LD	A,24H	; "$"
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,C
	OUT	(9BH),A
	LD	A,B
	OUT	(9BH),A
	LD	A,L
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	LD	A,E
	OUT	(9BH),A
	LD	A,D
	OUT	(9BH),A
	POP	HL
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	LD	A,(D.F3F2)
	OUT	(9BH),A
	EX	AF,AF'
	OUT	(9BH),A
	LD	A,(D.FB02)
	AND	0FH	; 15 
	OR	70H	; "p"
	OUT	(9BH),A
	EI
	POP	HL
	LD	(D.FCB3),HL
	POP	HL
	LD	(D.FCB5),HL
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2898:	CALL	C.12C4
	LD	L,C
	LD	H,B
	LD	A,E
	CALL	C.29A5
	CALL	C.25F1
	CALL	C.25EE
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C.25D5
	JR	NC,J$28B3
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J$28B3:	INC	HL
	PUSH	HL
	CALL	C.25E6
	JR	NC,J$28BE
	EX	AF,AF'
	OR	08H	; 8 
	EX	AF,AF'
J$28BE:	INC	HL
	POP	DE
	CALL	C.29C4
	EX	AF,AF'
	CALL	C.29DB
	EX	AF,AF'
	LD	A,(D.F3F2)
	CALL	C.29EB
	LD	A,(D.FB02)
	AND	0FH	; 15 
	ADD	A,80H
	CALL	C.29E3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$28D8:	LD	B,04H	; 4 
	JR	J.28E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$28DC:	LD	B,06H	; 6 
	JR	J.28E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.28E0:	LD	B,02H	; 2 
	JR	J.28E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$28E4:	LD	B,00H
J.28E6:	PUSH	BC
	CALL	C$2925
	POP	AF
	DI
	OUT	(99H),A
	LD	A,0ADH
	OUT	(99H),A
	LD	A,60H	; "`"
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	CALL	C.2980
	AND	10H	; 16 
	RET	Z
	LD	A,08H	; 8 
	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	IN	A,(99H)
	LD	L,A
	LD	A,09H	; 9 
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	IN	A,(99H)
	PUSH	AF
	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	EI
	POP	AF
	AND	01H	; 1 
	LD	H,A
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2925:	PUSH	AF
	CALL	C.2980
	LD	A,20H	; " "
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	LD	A,E
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0ACH
	OUT	(99H),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2949:	PUSH	DE
	CALL	C$29A0
	XOR	A
	CALL	C.29DB
	LD	A,40H	; "@"
	CALL	C.29E3
	CALL	C.2980
	LD	A,07H	; 7 
	CALL	C.298B
	EI
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2961:	CALL	C.29A5
	LD	A,2CH	; ","
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,(D.F3F2)
	OUT	(9BH),A
	XOR	A
	OUT	(9BH),A
	LD	A,(D.FB02)
	AND	0FH	; 15 
	OR	50H	; "P"
	OUT	(9BH),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2980:	LD	A,02H	; 2 
	CALL	C.298B
	EI
	RRCA
	JR	C,C.2980
	RLCA
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.298B:	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
	POP	HL
	IN	A,(99H)
	PUSH	AF
	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$29A0:	PUSH	AF
	LD	A,20H	; " "
	JR	J$29A8


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.29A5:	PUSH	AF
	LD	A,24H	; "$"
J$29A8:	PUSH	AF
	CALL	C.2980
	DI
	POP	AF
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	POP	AF
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.29C4:	LD	A,28H	; "("
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,E
	OUT	(9BH),A
	LD	A,D
	OUT	(9BH),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.29DB:	PUSH	AF
	DI
	OUT	(99H),A
	LD	A,0ADH
	JR	J.29F1


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.29E3:	PUSH	AF
	DI
	OUT	(99H),A
	LD	A,0AEH
	JR	J.29F1


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.29EB:	PUSH	AF
	DI
	OUT	(99H),A
	LD	A,0ACH
J.29F1:	OUT	(99H),A
	EI
	POP	AF
	RET

I$29F6:	DEFB	00H,20H,00H,00H,00H,00H,00H,00H
	DEFB	08H,00H,00H,00H,00H,00H,00H,00H
	DEFB	00H,00H,00H,00H,00H,3BH,05H,00H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2A0E:	CALL	C$2A14
	JP	J$1B6D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2A14:	CALL	C$2B40
	DI
	LD	A,55H	; "U"
	LD	HL,J.0000
	LD	BC,I$8000
	CALL	C.0977
	CALL	C$2AFF
	LD	DE,I$0705
	CALL	C.2AC2
	LD	DE,I$2D00
	CALL	C.2AC2
	LD	D,2AH	; "*"
	CALL	C.2AC2
	INC	D
	CALL	C.2AC2
	LD	D,27H	; "'"
	CALL	C.2AC2
	LD	E,37H	; "7"
	LD	HL,I$2BF6
	EXX
	LD	HL,I$2B6F
	EXX
	LD	DE,I$0160
	CALL	C.2AC2
	LD	A,0F0H
	LD	(D.F55E),A
J$2A55:	DI
	CALL	C.1034
	LD	A,(D.F55E)
	LD	B,A
	LD	C,17H
	CALL	C.0647
	LD	A,B
	INC	A
	LD	(D.F55E),A
	EI
	LD	A,03H	; 3 
	PUSH	AF
	LD	BC,I$002D
	LD	D,26H	; "&"
	CALL	C.2AC2
	EXX
	LD	B,08H	; 8 
	LD	C,(HL)
	INC	HL
	EXX
J.2A79:	CALL	C.2AD8
	LD	A,(HL)
	INC	HL
	CP	0FEH
	JR	Z,J$2AB9
	PUSH	HL
	PUSH	BC
	LD	BC,I$01A6
	JR	NC,J$2A8C
	LD	B,00H
	LD	C,A
J$2A8C:	CALL	C$2AD4
	POP	HL
	ADD	HL,BC
	LD	C,L
	LD	B,H
	POP	HL
	POP	AF
	XOR	03H	; 3 
	CALL	C.2AE3
	PUSH	AF
	CALL	C$2AEC
	EXX
	SLA	C
	DJNZ	J$2AA7
	LD	B,08H	; 8 
	LD	C,(HL)
	INC	HL
J$2AA7:	EXX
	JR	NC,J.2A79
	DEC	BC
	CALL	C.2AD8
	INC	BC
	LD	A,02H	; 2 
	CALL	C.2AE3
	CALL	C$2AFA
	JR	J.2A79

J$2AB9:	INC	E
	POP	AF
	LD	A,(HL)
	CP	0FEH
	JR	NZ,J$2A55
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2AC2:	PUSH	BC
	PUSH	AF
	DI
	LD	C,99H
	OUT	(C),E
	LD	A,D
	OR	80H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(C),A
	EI
	POP	AF
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2AD4:	LD	D,28H	; "("
	JR	J$2ADA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2AD8:	LD	D,24H	; "$"
J$2ADA:	PUSH	DE
	LD	E,C
	CALL	C.2AC2
	LD	E,B
	INC	D
	JR	J$2AE7


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2AE3:	PUSH	DE
	LD	E,A
	LD	D,2CH	; ","
J$2AE7:	CALL	C.2AC2
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2AEC:	PUSH	DE
	LD	E,70H	; "p"
J$2AEF:	LD	D,2EH	; "."
	CALL	C.2AC2
	CALL	C.2980
	DI
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2AFA:	PUSH	DE
	LD	E,50H	; "P"
	JR	J$2AEF


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2AFF:	LD	A,02H	; 2 
	CALL	C.1CF9
	LD	B,0BH	; 11 
	CALL	C.1CD2
	RLCA
	RLCA
	AND	0CH	; 12 
	LD	C,A
	LD	B,00H
	LD	HL,I$2B5F
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	BC
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	LD	DE,I.1000
	CALL	C.2AC2
	CALL	C.2B33
	POP	HL
	CALL	C.2B33
	LD	HL,I$0444
	CALL	C.2B33
	LD	HL,I$0777

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.2B33:	PUSH	BC
	LD	C,9AH
	DI
	OUT	(C),L
	EX	(SP),HL
	EX	(SP),HL
	OUT	(C),H
	EI
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2B40:	LD	B,08H	; 8 
	LD	HL,I$2B4F
J$2B45:	LD	D,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	CALL	C.2AC2
	DJNZ	J$2B45
	RET

I$2B4F:	DEFB	00H,08H,01H,20H,08H,2AH,09H,00H
	DEFB	02H,1FH,05H,0F7H,0BH,00H,06H,0EH
I$2B5F:	DEFB	07H,00H,00H,00H,20H,04H,27H,02H
	DEFB	72H,02H,56H,00H,70H,05H,70H,00H
I$2B6F:	DEFB	00H,00H,00H,00H,00H,00H,00H,00H
	DEFB	00H,6EH,00H,9FH,00H,6FH,00H,9FH
	DEFB	00H,6FH,00H,9FH,00H,6FH,00H,9FH
	DEFB	00H,6FH,00H,9FH,00H,6FH,00H,9FH
	DEFB	00H,6FH,00H,0FFH,00H,07H,00H,0FCH
	DEFB	07H,00H,0F7H,00H,07H,00H,0F3H,00H
	DEFB	07H,00H,0F7H,00H,07H,00H,0FFH,00H
	DEFB	07H,00H,0FFH,00H,0FH,00H,0FCH,3CH
	DEFB	0FCH,3CH,0FCH,3CH,87H,0C0H,7BH,0C0H
	DEFB	87H,0C0H,7BH,0C0H,86H,0C0H,7BH,0C0H
	DEFB	86H,0C0H,7AH,0C0H,86H,0C0H,78H,0C0H
	DEFB	86H,90H,7AH,0F0H,86H,0F0H,7FH,0C0H
	DEFB	83H,0C0H,7FH,0C0H,0D7H,0C0H,2FH,0C0H
	DEFB	0D7H,0C0H,2FH,0C0H,0D7H,0C0H,2FH,0C0H
	DEFB	0D7H,0C0H,2FH,0C0H,0D7H,0C0H,2FH,0C0H
	DEFB	0D7H,0C0H,2FH,0C0H,0D5H,80H,00H,00H
	DEFB	00H,00H,00H,00H,00H,00H,00H
I$2BF6:	DEFB	0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,44H,1DH,1DH,1CH,2FH,68H,2BH
	DEFB	28H,22H,0FEH,44H,1DH,1CH,1EH,2AH
	DEFB	6DH,29H,29H,22H,0FEH,43H,1FH,1BH
	DEFB	1EH,26H,73H,25H,29H,24H,0FEH,43H
	DEFB	1FH,1AH,20H,22H,77H,23H,29H,25H
	DEFB	0FEH,42H,21H,19H,20H,1FH,7CH,1FH
	DEFB	29H,27H,0FEH,42H,21H,18H,22H,1BH
	DEFB	80H,1DH,29H,28H,0FEH,41H,23H,17H
	DEFB	22H,19H,84H,1AH,28H,2AH,0FEH,41H
	DEFB	23H,16H,24H,17H,86H,17H,29H,2BH
	DEFB	0FEH,40H,25H,15H,24H,15H,8AH,14H
	DEFB	28H,2DH,0FEH,40H,25H,14H,26H,13H
	DEFB	8CH,11H,29H,2EH,0FEH,3FH,27H,13H
	DEFB	26H,12H,8FH,0EH,29H,2FH,0FEH,3FH
	DEFB	27H,12H,28H,10H,91H,0CH,28H,31H
	DEFB	0FEH,3EH,29H,11H,28H,0FH,94H,08H
	DEFB	29H,32H,0FEH,3EH,2AH,0FH,2AH,0DH
	DEFB	96H,06H,28H,34H,0FEH,3DH,2BH,0EH
	DEFB	2BH,0CH,99H,02H,29H,35H,0FEH,3DH
	DEFB	2CH,0DH,2CH,0BH,0C2H,37H,0FEH,3CH
	DEFB	2DH,0CH,2DH,0AH,26H,4CH,50H,38H
	DEFB	0FEH,3CH,2EH,0BH,2EH,09H,23H,51H
	DEFB	4CH,3AH,0FEH,3BH,2FH,0AH,2FH,09H
	DEFB	21H,54H,4AH,3BH,0FEH,3BH,30H,09H
	DEFB	30H,08H,20H,57H,46H,3DH,0FEH,3AH
	DEFB	31H,08H,31H,08H,21H,57H,44H,3EH
	DEFB	0FEH,3AH,32H,07H,32H,07H,23H,57H
	DEFB	41H,3FH,0FEH,39H,33H,06H,33H,07H
	DEFB	26H,55H,3EH,41H,0FEH,39H,34H,05H
	DEFB	34H,07H,47H,35H,3BH,42H,0FEH,38H
	DEFB	35H,04H,35H,07H,4BH,32H,38H,44H
	DEFB	0FEH
I$2D00:	DEFB	38H,36H,03H,36H,07H,4EH,30H,35H
	DEFB	45H,0FEH,37H,37H,02H,37H,08H,50H
	DEFB	2EH,32H,47H,0FEH,37H,71H,08H
	DEFB	52H,2DH,2FH,48H,0FEH,36H,72H,09H
	DEFB	54H,2BH,2CH,4AH,0FEH,36H,73H,09H
	DEFB	55H,2BH,29H,4BH,0FEH,35H,74H,0AH
	DEFB	55H,29H,2AH,4BH,0FEH,35H,75H,0BH
	DEFB	55H,25H,2DH,4AH,0FEH,34H,76H,0CH
	DEFB	55H,23H,30H,48H,0FEH,34H,1FH,01H
	DEFB	37H,01H,1FH,0DH,54H,20H,33H,47H
	DEFB	0FEH,33H,20H,02H,36H,02H,1EH,10H
	DEFB	52H,1EH,36H,45H,0FEH,33H,1FH,03H
	DEFB	35H,03H,1FH,12H,50H,1BH,39H,44H
	DEFB	0FEH,32H,20H,04H,34H,04H,1EH,15H
	DEFB	4EH,19H,3CH,42H,0FEH,32H,1FH,05H
	DEFB	33H,05H,1FH,18H,4AH,18H,3EH,41H
	DEFB	0FEH,31H,20H,06H,32H,06H,1EH,1CH
	DEFB	47H,15H,42H,3FH,0FEH,31H,1FH,07H
	DEFB	31H,07H,1FH,3CH,26H,14H,44H,3EH
	DEFB	0FEH,30H,20H,08H,30H,08H,1EH,40H
	DEFB	22H,12H,48H,3CH,0FEH,30H,1FH,09H
	DEFB	2FH,09H,1FH,41H,20H,11H,4AH,3BH
	DEFB	0FEH,2FH,20H,0AH,2EH,0AH,1EH,41H
	DEFB	20H,0FH,4EH,39H,0FEH,2FH,1FH,0BH
	DEFB	2DH,0BH,1FH,40H,20H,0EH,28H,01H
	DEFB	27H,38H,0FEH,2EH,20H,0CH,2CH,0CH
	DEFB	1EH,3EH,22H,0CH,29H,04H,27H,36H
	DEFB	0FEH,2EH,1FH,0DH,2BH,0DH,1FH,39H
	DEFB	26H,0BH,29H,06H,27H,35H,0FEH,2DH
	DEFB	20H,0EH,2AH,0EH,7DH,0AH,28H,0AH
	DEFB	27H,33H,0FEH,2DH,1FH,0FH,29H,0FH
	DEFB	7CH,09H,29H,0CH,27H,32H,0FEH,2CH
	DEFB	20H,10H,28H,10H,7BH,08H,28H,10H
	DEFB	27H,30H,0FEH,2CH,1FH,11H,27H,11H
	DEFB	7AH,07H,29H,12H,27H,2FH,0FEH,2BH
	DEFB	1FH,13H,25H,13H,78H,07H,28H,16H
	DEFB	27H,2DH,0FEH,2BH,1FH,13H,25H,13H
	DEFB	77H,06H,29H,18H,27H,2CH,0FEH,2AH
	DEFB	1FH,15H,23H,15H,75H,06H,28H,1CH
	DEFB	27H,2AH,0FEH,2AH,1FH,15H,23H,15H
	DEFB	74H,06H,27H,1FH,27H,29H,0FEH,29H
	DEFB	1FH,17H,21H,17H,71H,06H,28H,22H
	DEFB	27H,27H,0FEH,29H,1FH,17H,21H,17H
	DEFB	70H,06H,27H,25H,27H,26H,0FEH,28H
	DEFB	1FH,19H,1FH,19H,6DH,06H,28H,28H
	DEFB	27H,24H,0FEH,28H,1FH,19H,1FH,19H
	DEFB	6AH,08H,27H,2BH,27H,23H,0FEH,27H
	DEFB	1FH,1BH,1DH,1BH,66H,09H,28H,2EH
	DEFB	27H,21H,0FEH,27H,1FH,1BH,1DH,1BH
	DEFB	63H,0BH,27H,31H,27H,20H,0FEH,26H
	DEFB	1FH,1DH,1BH,1DH,5FH,0CH,28H,34H
	DEFB	27H,1EH,0FEH,26H,1FH,1DH,1BH,1DH
	DEFB	5BH,0EH,28H,37H,27H,1DH,0FEH,0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,0FEH

J.2EB9:	LD	BC,(D.F56A)
	LD	DE,(D.F56C)
	CALL	C.3376
	RET	C
	CALL	C.2980
	LD	A,20H	; " "
	CALL	C.336E
	LD	HL,D.F562
	LD	BC,I.0E9B
	OTIR
	LD	A,(HL)
	AND	0FH	; 15 
	OR	90H
	OUT	(C),A
	EI
	AND	A
	RET

J.2EDF:	CALL	C.3320
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J.2EFA
	JR	Z,J.2F1B
	DEC	A
	JR	Z,J.2EFA
J$2EEE:	CALL	C.3354
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J$2EEE
	RET

J.2EFA:	LD	D,02H	; 2 
	LD	(HL),00H
J$2EFE:	CALL	C$2F13
	CALL	C.3354
	OR	(HL)
	LD	(HL),A
	DEC	BC
	LD	A,C
	OR	B
	JR	Z,J$2F11
	DEC	D
	JR	NZ,J$2EFE
	INC	HL
	JR	J.2EFA

J$2F11:	DEC	D
	RET	Z

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$2F13:	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	(HL),A
	AND	A
	RET

J.2F1B:	LD	D,04H	; 4 
	LD	(HL),00H
J$2F1F:	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	LD	(HL),A
	CALL	C.3354
	OR	(HL)
	LD	(HL),A
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$2F31
	OR	E
	JR	Z,J$2F37
	DEC	E
J$2F31:	DEC	D
	JR	NZ,J$2F1F
	INC	HL
	JR	J.2F1B

J$2F37:	DEC	D
	RET	Z
	LD	A,(HL)
J$2F3A:	ADD	A,A
	ADD	A,A
	DEC	D
	JR	NZ,J$2F3A
	LD	(HL),A
	AND	A
	RET

J.2F42:	CALL	C.32C9
	RET	C
	CALL	C.2980
	LD	A,20H	; " "
	CALL	C.336E
	PUSH	BC
	LD	HL,D.F562
	LD	BC,I.0E9B
	OTIR
	POP	BC
	LD	A,(HL)
	AND	0FH	; 15 
	OR	0B0H
	POP	HL
	PUSH	AF
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J.2F92
	JR	Z,J$2FD4
	DEC	A
	JR	Z,J.2F92
	CALL	C.336C
	LD	A,(D.F5A8)
	LD	E,A
	AND	A
	CALL	NZ,C.33A2
	LD	A,(HL)
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J.2F81:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	INC	HL
	LD	A,E
	AND	A
	CALL	NZ,C.33A2
	JR	C,J.2F81
	LD	A,(HL)
	OUT	(9BH),A
	JR	J.2F81

J.2F92:	CALL	C.336C
	LD	D,0FH	; 15 
	LD	A,(D.F5A8)
	LD	E,A
	AND	A
	CALL	NZ,C.33A2
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J.2FAF:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	LD	A,E
	AND	A
	CALL	NZ,C.33A2
	JR	C,J$2FBE
	LD	A,(HL)
	AND	D
	OUT	(9BH),A
J$2FBE:	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	LD	A,E
	AND	A
	CALL	NZ,C.33A2
	JR	C,J.2FAF
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
	JR	J.2FAF

J$2FD4:	CALL	C.336C
	LD	D,03H	; 3 
	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C.33A2
	LD	A,(HL)
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J.2FEE:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J$2FF7
	OR	E
	RET	Z
	DEC	E
J$2FF7:	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C.33A2
	JR	C,J$3008
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
J$3008:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J$3011
	OR	E
	RET	Z
	DEC	E
J$3011:	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C.33A2
	JR	C,J$3020
	LD	A,(HL)
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
J$3020:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J$3029
	OR	E
	RET	Z
	DEC	E
J$3029:	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C.33A2
	JR	C,J$3036
	LD	A,(HL)
	AND	D
	OUT	(9BH),A
J$3036:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J$303F
	OR	E
	RET	Z
	DEC	E
J$303F:	INC	HL
	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C.33A2
	JR	C,J.2FEE
	LD	A,(HL)
	RLCA
	RLCA
	AND	D
	OUT	(9BH),A
	JP	J.2FEE


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3052:	LD	HL,J.0000
	LD	A,10H	; 16 
	AND	A
J.3058:	PUSH	AF
	ADD	HL,HL
	JR	NC,J$305F
	POP	AF
	SCF
	PUSH	AF
J$305F:	EX	DE,HL
	ADD	HL,HL
	EX	DE,HL
	JR	NC,J.306A
	ADD	HL,BC
	JR	NC,J.306A
	POP	AF
	SCF
	PUSH	AF
J.306A:	POP	AF
	DEC	A
	JR	NZ,J.3058
	RET

J.306F:	PUSH	HL
	CALL	C.32BB
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	E,00H
	JR	J$3087

J.307C:	PUSH	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	CALL	C.32BB
	POP	HL
	LD	E,01H	; 1 
J$3087:	PUSH	DE
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	AND	A
	SBC	HL,BC
	INC	HL
	POP	DE
	PUSH	DE
	CALL	C.33C7
	POP	DE
	DEC	E
	PUSH	AF
	CALL	NZ,C.3444
	POP	AF
	CALL	Z,C$3433
	CALL	C.3457
	AND	A
	RET

J.30A8:	PUSH	HL
	CALL	C.32BB
	LD	HL,J.0000
	LD	E,L
	CALL	C.33C7
	CALL	C.3444
	LD	(D.F575),HL
	LD	DE,(D.F571)
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	DEC	HL
	CALL	C.32C9
	JR	C,J$30F3
	CALL	C.2980
	LD	A,20H	; " "
	CALL	C.336E
	PUSH	BC
	LD	HL,D.F562
	LD	BC,I.0E9B
	OTIR
	POP	BC
	LD	A,(HL)
	AND	0FH	; 15 
	OR	0B0H
	LD	HL,I$30F2
	EX	(SP),HL
	PUSH	AF
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J.311C
	JP	Z,J$315C
	DEC	A
	JR	Z,J.311C
	JR	J$30F9

I$30F2:	AND	A
J$30F3:	PUSH	AF
	CALL	C.3457
	POP	AF
	RET

J$30F9:	CALL	C.336C
	CALL	C.339D
	LD	A,(HL)
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J.310A:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	INC	HL
	CALL	C.3279
	CALL	C.339D
	JR	C,J.310A
	LD	A,(HL)
	OUT	(9BH),A
	JR	J.310A

J.311C:	CALL	C.336C
	LD	D,00H
	CALL	C.339D
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	0FH	; 15 
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J.3135:	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$313E
	OR	E
	RET	Z
	DEC	E
J$313E:	CALL	C.3279
	LD	A,D
	RRCA
	LD	A,(HL)
	INC	HL
	JR	C,J$314C
	DEC	HL
	RRCA
	RRCA
	RRCA
	RRCA
J$314C:	PUSH	AF
	CALL	C.339D
	JR	C,J$3159
	POP	AF
	AND	0FH	; 15 
	OUT	(9BH),A
	JR	J.3135

J$3159:	POP	AF
	JR	J.3135

J$315C:	CALL	C.336C
	LD	D,00H
	CALL	C.339D
	LD	A,(HL)
	RRCA
	RRCA
	AND	03H	; 3 
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J.3173:	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$317C
	OR	E
	RET	Z
	DEC	E
J$317C:	CALL	C.3279
	LD	A,D
	AND	03H	; 3 
	JR	Z,J$3197
	DEC	A
	JR	Z,J$319F
	DEC	A
	JR	Z,J$319A
	CALL	C.339D
	JR	C,J$3194
	LD	A,(HL)
	AND	03H	; 3 
	OUT	(9BH),A
J$3194:	INC	HL
	JR	J.3173

J$3197:	LD	A,(HL)
	JR	J$31A2

J$319A:	LD	A,(HL)
	RRCA
	RRCA
	JR	J$31A4

J$319F:	LD	A,(HL)
	RLCA
	RLCA
J$31A2:	RLCA
	RLCA
J$31A4:	PUSH	AF
	CALL	C.339D
	JR	C,J$31B1
	POP	AF
	AND	03H	; 3 
	OUT	(9BH),A
	JR	J.3173

J$31B1:	POP	AF
	JR	J.3173

J.31B4:	PUSH	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	PUSH	HL
	CALL	C.32BB
	LD	HL,J.0000
	LD	E,01H	; 1 
	CALL	C.33C7
	LD	DE,(D.F571)
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	HL
	CALL	C.3320
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J.31ED
	JR	Z,J$3227
	DEC	A
	JR	Z,J.31ED
J$31DD:	CALL	C.3292
	CALL	C.3354
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J$31DD
	JP	J.3270

J.31ED:	LD	D,00H
J.31EF:	CALL	C.3292
	LD	A,07H	; 7 
	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
	POP	HL
	LD	A,D
	RRCA
	IN	A,(99H)
	JR	NC,J$3208
	OR	(HL)
	LD	(HL),A
	INC	HL
	JR	J$320D

J$3208:	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	(HL),A
J$320D:	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	EI
	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J.31EF
	OR	E
	JR	Z,J$3221
	DEC	E
	JR	J.31EF

J$3221:	LD	A,D
	RRCA
	JR	C,J.3271
	JR	J.3270

J$3227:	LD	D,00H
J.3229:	CALL	C.3292
	LD	A,07H	; 7 
	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
I$3236:	POP	HL
	LD	A,D
	AND	03H	; 3 
	JR	Z,J$3249
	DEC	A
	JR	Z,J$324F
	DEC	A
	IN	A,(99H)
	JR	Z,J$3253
	OR	(HL)
	LD	(HL),A
	INC	HL
	JR	J$3257

J$3249:	IN	A,(99H)
	RRCA
	RRCA
	JR	J$3256

J$324F:	IN	A,(99H)
	RLCA
	RLCA
J$3253:	RLCA
	RLCA
	OR	(HL)
J$3256:	LD	(HL),A
J$3257:	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	EI
	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J.3229
	OR	E
	JR	Z,J$326B
	DEC	E
	JR	J.3229

J$326B:	LD	A,D
	AND	03H	; 3 
	JR	NZ,J.3271
J.3270:	DEC	HL
J.3271:	CALL	C$32B0
	CALL	C.3457
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3279:	PUSH	DE
	PUSH	HL
	LD	HL,(D.F571)
	LD	DE,(D.F575)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	20H
	POP	DE
	RET	C
	PUSH	BC
	PUSH	DE
	CALL	C.3444
	LD	(D.F575),HL
	JR	J$32AA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3292:	PUSH	DE
	PUSH	HL
	LD	HL,(D.F571)
	LD	DE,(D.F573)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	20H
	POP	DE
	RET	C
	LD	HL,(D.F573)
	PUSH	BC
	PUSH	DE
	CALL	C.3436
	AND	A
J$32AA:	POP	DE
	POP	BC
	LD	HL,(D.F571)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$32B0:	LD	DE,(D.F571)
	AND	A
	SBC	HL,DE
	INC	HL
	JP	C.3436


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.32BB:	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	CALL	C.05BA
	LD	A,D
	CP	09H	; 9 
	RET	C
	JP	J.052E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.32C9:	LD	HL,(D.F562)
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	CALL	C.3376
	RET	C
	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	HL,(D.F566)
	LD	A,(D.F56F)
	AND	04H	; 4 
	JR	NZ,J$32ED
	EX	DE,HL
	CALL	C.3390
	AND	A
	SBC	HL,DE
	LD	A,23H	; "#"
J$32ED	EQU	$-1
	LD	(D.F5A0),HL
	LD	(D.F5A2),HL
	LD	D,B
	LD	E,C
	EX	DE,HL
	SBC	HL,DE
	JR	NC,J$32FE
	LD	HL,J.0000
J$32FE:	LD	(D.F5A4),HL
	LD	(D.F5A6),HL
	LD	A,H
	OR	L
	LD	(D.F5A8),A
	POP	DE
	POP	BC
	LD	(D.F56A),BC
	LD	(D.F56C),DE
	CALL	C.3052
	LD	B,H
	LD	C,L
	LD	A,00H
	ADC	A,A
	LD	E,A
	AND	A
	POP	HL
	EX	(SP),HL
	JP	(HL)


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3320:	CALL	C.2980
	LD	A,20H	; " "
	CALL	C.336E
	LD	HL,D.F562
	LD	BC,I.0E9B
	OTIR
	LD	A,0A0H
	OUT	(C),A
	EI
	LD	BC,(D.F56A)
	LD	DE,(D.F56C)
	LD	HL,(D.F566)
	LD	(HL),C
	INC	HL
	LD	(HL),B
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	PUSH	HL
	CALL	C.3052
	LD	B,H
	LD	C,L
	LD	A,00H
	ADC	A,A
	LD	E,A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3354:	DI
	LD	A,07H	; 7 
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
	POP	HL
	IN	A,(99H)
	PUSH	AF
	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	POP	AF
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.336C:	LD	A,0ACH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.336E:	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3376:	LD	A,B
	OR	C
	SCF
	RET	Z
	LD	A,D
	OR	E
	SCF
	RET	Z
	PUSH	HL
	PUSH	DE
	LD	E,C
	LD	D,B
	CALL	C.3390
	RST	20H
	POP	DE
	POP	HL
	RET	C
	PUSH	HL
	LD	HL,I.00D4
	RST	20H
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3390:	LD	HL,I.0100
	LD	A,(D.FCAF)
	AND	06H	; 6 
	CP	06H	; 6 
	RET	NZ
	INC	H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.339D:	LD	A,(D.F5A8)
	AND	A
	RET	Z

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.33A2:	PUSH	HL
	LD	HL,(D.F5A2)
	LD	A,L
	OR	H
	JR	Z,J$33B0
	DEC	HL
	LD	(D.F5A2),HL
	POP	HL
	RET

J$33B0:	LD	HL,(D.F5A6)
	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J$33C1
	LD	HL,(D.F5A0)
	LD	(D.F5A2),HL
	LD	HL,(D.F5A4)
J$33C1:	LD	(D.F5A6),HL
	POP	HL
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.33C7:	LD	A,(D$FFA7)
	CP	0C9H
	JP	Z,J.0546
	PUSH	BC
	PUSH	HL
	LD	HL,I.F577
	PUSH	HL
	LD	(HL),D
	LD	A,E
	AND	A
	PUSH	AF
	EX	DE,HL
	INC	DE
	LD	HL,I.F866
	LD	BC,I.000B
	LDIR
	XOR	A
	LD	B,19H
J$33E6:	LD	(DE),A
	INC	DE
	DJNZ	J$33E6
	POP	AF
	POP	DE
	PUSH	AF
	LD	C,0FH	; 15 
	JR	Z,J$33F3
	LD	C,16H
J$33F3:	CALL	C.345C
	INC	A
	JR	NZ,J$3401
	POP	AF
	JP	Z,J.055E
	LD	E,43H	; "C"
	JR	J.3454

J$3401:	LD	HL,I.0001
	LD	(D$F585),HL
	POP	AF
	POP	HL
	POP	DE
	LD	A,H
	OR	L
	JR	NZ,J.3428
	LD	HL,I.FE00
	ADD	HL,SP
I$3412:	JR	NC,J.3421
	LD	DE,(D.F6C6)
	AND	A
	SBC	HL,DE
	JR	C,J.3421
	LD	A,H
	AND	A
	JR	NZ,J.3428
J.3421:	LD	DE,(D$F862)
	LD	HL,I.0100
J.3428:	LD	(D.F571),DE
	LD	(D.F573),HL
	LD	C,1AH
	JR	C.345C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$3433:	LD	HL,(D.F573)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3436:	LD	DE,I.F577
	LD	C,26H	; "&"
	CALL	C.345C
	AND	A
	RET	Z
	LD	E,42H	; "B"
	JR	J.3454


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3444:	LD	HL,(D.F573)
	LD	DE,I.F577
	LD	C,27H	; "'"
	CALL	C.345C
	LD	A,L
	OR	H
	RET	NZ
	LD	E,37H	; "7"
J.3454:	JP	J.05C6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3457:	LD	DE,I.F577
	LD	C,10H	; 16 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.345C:	LD	IX,I$7FFD
	JP	C.0262


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3463:	LD	B,00H
	AND	7FH
	LD	C,A
	SBC	HL,BC
	RET

J$346B:	IN	A,(0BAH)
	CPL
	AND	08H	; 8 
	RET	Z
	LD	A,0FFH
	RET

J$3474:	LD	HL,D.FAFF
	XOR	A
	BIT	7,(HL)
	RET	Z
	RES	7,(HL)
	IN	A,(0BAH)
	AND	07H	; 7 
	LD	D,A
	IN	A,(0B8H)
	LD	L,A
	LD	H,00H
	IN	A,(0B9H)
	SRL	D
	RRA
	LD	E,A
	RL	H
	PUSH	HL
	PUSH	DE
	LD	BC,I$FFFD
	ADD	HL,BC
	EX	DE,HL
	LD	C,0EEH
	ADD	HL,BC
	LD	A,E
	OUT	(0B8H),A
	RR	D
	ADC	HL,HL
	LD	A,L
	OUT	(0B9H),A
	LD	A,H
	OUT	(0BAH),A
	POP	DE
	POP	HL
	IN	A,(0BAH)
	AND	20H	; " "
	RET	Z
	LD	A,(D.FB01)
	CALL	C.3463
	LD	BC,I$00D3
	CALL	C$34C7
	LD	A,L
	LD	(D.FB00),A
	EX	DE,HL
	LD	A,(D.FAFF)
	CALL	C.3463
	LD	BC,I.00FF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$34C7:	LD	A,H
	RLA
	JR	C,J$34D4
	PUSH	HL
	SBC	HL,BC
	POP	HL
	JR	C,J$34D6
	LD	L,C
	LD	H,B
	JP	C,J$002E
J$34D4	EQU	$-2
J$34D6:	LD	A,L
	LD	(D.FAFE),A
	LD	A,0FFH
	RET

J$34DD:	CP	08H	; 8 
	JR	Z,J$3474
	CP	0BH	; 11 
	JR	Z,J$346B
	LD	E,0FH	; 15 
	LD	BC,I$00BF
	LD	HL,I$10EF
	CP	0CH	; 12 
	JR	Z,J.3509
	LD	BC,I$40FF
	LD	HL,I$20DF
	CP	10H	; 16 
	JR	Z,J.3509
	AND	03H	; 3 
	SUB	02H	; 2 
	LD	A,(D.FAFE)
	RET	M
	LD	A,(D.FB00)
	RET	Z
	XOR	A
	RET

J.3509:	DI
	CALL	C.357F
	CALL	C$359A
	PUSH	AF
	CALL	C.3585
	CALL	C.3591
	PUSH	AF
	CALL	C.357F
	CALL	C.3597
	PUSH	AF
	CALL	C.3585
	CALL	C.3597
	PUSH	AF
	CALL	C.357F
	CALL	C.3597
	PUSH	AF
	CALL	C.3585
	CALL	C.3591
	PUSH	AF
	CALL	C.357F
	CALL	C.35AA
	CALL	C.3585
	CALL	C.35AA
	CALL	C.357F
	EI
	POP	AF
	POP	HL
	POP	DE
	POP	BC
	XOR	08H	; 8 
	SUB	02H	; 2 
	CP	0DH	; 13 
	JR	C,J$355D
	POP	AF
	CALL	C.3577
	LD	(D.FB00),A
	POP	AF
	CALL	C.3577
	JR	J$3571

J$355D:	LD	A,D
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	H
	NEG
	LD	(D.FB00),A
	POP	AF
	POP	DE
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	B
	NEG
J$3571:	LD	(D.FAFE),A
	LD	A,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3577:	XOR	08H	; 8 
	BIT	3,A
	RET	Z
	OR	0F0H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.357F:	CALL	C.35A2
	AND	L
	JR	J$3589


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3585:	CALL	C.35A2
	OR	H
J$3589:	PUSH	AF
	LD	A,E
	OUT	(0A0H),A
	POP	AF
	OUT	(0A1H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3591:	CALL	C.35AA
	CALL	C.35AA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3597:	CALL	C.35AA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$359A:	LD	A,0EH	; 14 
	CALL	C$35A3
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.35A2:	LD	A,E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$35A3:	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	C
	OR	B
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.35AA:	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	RET

C.35AF:	CP	","
	JR	Z,J$35EF
	RST	28H			; evaluate mode parameter
	CP	4
	JR	NC,J.3635
	AND	A
	JR	Z,J.35C2
	CP	1
	JR	Z,J.35C2
	LD	E,0
	DEC	A
J.35C2:	PUSH	DE
	RRCA
	RRCA
	LD	D,A
	RRCA
	RRCA
	LD	E,A
	LD	A,(D.FFE8)
	AND	0CFH
	OR	E
	LD	C,9
	CALL	C.36B4
	LD	A,D
	XOR	0C0H
	LD	E,A			; b7,b6
	LD	A,3FH			; leave b5-b0
	CALL	C.3661
	POP	DE
	LD	A,E
	RRCA
	RRCA
	RRCA
	LD	E,A
	LD	A,(D.FFE7)
	AND	0DFH
	OR	E
	CALL	C.36B2
	DEC	HL
	RST	10H
	RET	Z
J$35EF:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J$3600
	CALL	C.366C			; evaluate intensity parameter
	LD	A,0DFH			; leave b7,b6, b4-b0
	CALL	C.3661
	DEC	HL
	RST	10H
	RET	Z
J$3600:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J$3617
	CALL	C.366C			; evaluate color direction parameter
	RRC	E
	LD	A,(D.FFE7)
	AND	0EFH
	OR	E
	CALL	C.36B2
	DEC	HL
	RST	10H
	RET	Z
J$3617:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J$362C
	CALL	C.366C			; evaluate synchronization parameter
	RLCA
	RLCA
	RLCA
	LD	E,A			; b3
	LD	A,0F7H			; leave b7-b4, b2-b0
	CALL	C.3661
	DEC	HL
	RST	10H
	RET	Z
J$362C:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J$3644
	RST	28H			; evaluate audiomix parameter
	CP	4
J.3635:	JP	NC,J.0546
	CPL
	AND	03H
	LD	E,A			; b1, b0
	LD	A,0FCH			; leave b7-b2
	CALL	C.3661
	DEC	HL
	RST	10H
	RET	Z
J$3644:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J$3658
	CALL	C.366C			; evaluate external videoinput parameter
	RLCA
	RLCA
	LD	E,A			; b2
	LD	A,0FBH			; leave b7-b3, b1-b0
	CALL	C.3661
	DEC	HL
	RST	10H
	RET	Z
J$3658:	RST	08H
	DEFB	","
	CALL	C.366C			; evaluate external videooutput parameter
	RRC	E			; b4
	LD	A,0EFH			; leave b7-b5, b3-b0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3661:	PUSH	HL
	LD	HL,D.FAF7
	AND	(HL)
	OR	E
	LD	(HL),A
	OUT	(0F7H),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.366C:	RST	28H
	CP	02H	; 2 
	JR	NC,J.3635
	AND	A
	RET	Z
	LD	E,20H	; " "
	RET

J$3676:	RST	10H
	JR	Z,J.3686
	CP	2CH	; ","
	JR	Z,J.3686
	CALL	C.366C
	DEC	A
	JR	NZ,J.3686
	LD	E,00H
	LD	BC,I$021E
J.3686	EQU	$-2
	DEC	HL
	RST	10H
	LD	A,0FFH
	JR	Z,J$3693
	PUSH	DE
	RST	08H
	INC	L
	RST	28H
	POP	DE
J$3693:	LD	D,A
	LD	A,(D$F3E6)
	PUSH	AF
	LD	A,D
	CALL	C$36AE
	CALL	C.36B8
	OR	40H	; "@"
	CALL	C.36B4
	CALL	C.36B8
	EI
	AND	0BFH
	CALL	C.36B4
	POP	AF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$36AE:	LD	C,07H	; 7 
	JR	C.36B4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.36B2:	LD	C,08H	; 8 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.36B4:	LD	B,A
	JP	C.0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.36B8:	LD	A,02H	; 2 
	CALL	C.298B
	AND	40H	; "@"
	JR	Z,C.36B8
J$36C1:	LD	A,02H	; 2 
	CALL	C.298B
	BIT	6,A
	JR	NZ,J$36C1
	OR	E
	AND	02H	; 2 
	JR	Z,C.36B8
	LD	A,(D.F3DF)
	LD	C,00H
	RET

?.36D5:	EI
	INC	A
	JR	NZ,J$36DF
J$36D9:	CALL	C.392C
	RET	Z
	SCF
	RET

J$36DF:	PUSH	HL
	LD	HL,I$36ED
	ADD	A,L
	LD	L,A
	JR	NC,J$36E8
	INC	H
J$36E8:	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	EX	(SP),HL
I$36ED:	RET

?.36EE:	DEFW	3973H
	DEFW	39FAH
	DEFW	38B9H
	DEFW	3A1EH
	DEFW	3A7CH
	DEFW	3898H
	DEFW	38A3H
	DEFW	38B6H
	DEFW	38D7H
	DEFW	3AC8H

?.3702:	DEC	HL
	RST	10H
	LD	DE,I$7FFF
	JR	Z,J$3714
	RST	08H
	JR	Z,J$36D9
	EX	AF,AF'
	LD	B,0FAH
	LD	B,(HL)
	DEC	B
	RST	08H
	ADD	HL,HL
	RET	NZ
J$3714:	PUSH	HL
	PUSH	DE
	LD	A,(D.FD09)
	AND	A
	JR	Z,J$3722
	BIT	5,A
	JR	NZ,J$3777
	JR	J.377A

J$3722:	LD	HL,D.FCC1
	LD	BC,I.0400
	XOR	A
J$3729:	AND	03H	; 3 
	OR	(HL)
J$372C:	PUSH	BC
	PUSH	HL
	LD	H,C
J$372F:	LD	L,10H	; 16 
J$3731:	PUSH	AF
	CALL	C.057D
	CPL
	LD	E,A
	POP	AF
	PUSH	DE
	PUSH	AF
	CALL	C.0583
	POP	AF
	POP	DE
	PUSH	AF
	PUSH	DE
	CALL	C.057D
	POP	BC
	LD	B,A
	LD	A,C
	CPL
	LD	E,A
	POP	AF
	PUSH	AF
	PUSH	BC
	CALL	C.0583
	POP	BC
	LD	A,C
	CP	B
	JR	NZ,J$3766
	POP	AF
	DEC	L
	JR	NZ,J$3731
	INC	H
	INC	H
	INC	H
	INC	H
	JP	P,J$372F
	POP	HL
	POP	HL
	LD	(D.FD09),A
	JR	J.377A

J$3766:	POP	AF
	POP	HL
	POP	BC
	AND	A
	JP	P,J$3773
	ADD	A,04H	; 4 
	CP	90H
	JR	C,J$372C
J$3773:	INC	HL
	INC	A
	DJNZ	J$3729
J$3777:	JP	J.0546

J.377A:	BIT	6,A
	JR	Z,J$3795
	LD	IX,I.0100
	LD	B,20H	; " "
J$3784:	CALL	C.3AD8
	LD	A,(D.FC25)
	AND	A
	JP	NZ,J$3BF9
	LD	DE,C.0010
	ADD	IX,DE
	DJNZ	J$3784
J$3795:	POP	HL
	XOR	A
	LD	DE,I$03FF
	SBC	HL,DE
	JR	C,J$3804
	INC	H
	PUSH	HL
	LD	B,80H
	LD	C,A
	DEC	A
J$37A4:	INC	C
	CALL	C.3AEC
	DJNZ	J$37A4
	LD	B,H
	XOR	A
	LD	C,A
J$37AD:	INC	C
	CALL	C.3AEC
	DJNZ	J$37AD
	LD	HL,D.FC18
	LD	DE,I$FC19
	LD	C,0FH	; 15 
	LD	(HL),B
	LDIR
	LD	IX,I.0100
	LD	B,20H	; " "
J$37C4:	CALL	C.3AD9
	LD	DE,C.0010
	ADD	IX,DE
	DJNZ	J$37C4
	LD	HL,D.FD09
	SET	6,(HL)
	POP	HL
	LD	L,B
	PUSH	HL
	CALL	C.05CC
	CALL	C.388F
	JR	NZ,J$3840
	LD	A,C
	LD	(HL),H
	LD	H,L
	LD	(HL),E
	JR	NZ,J$3845
	LD	L,H
	LD	L,H
	LD	L,A
	LD	H,E
	LD	H,C
	LD	(HL),H
	LD	H,L
	LD	H,H
	DEC	C
	LD	A,(BC)
	NOP
	POP	HL
	INC	H
	INC	H
	INC	H
	LD	(D.FC18),HL
	LD	HL,D.FC18
	LD	DE,J.0000
	LD	BC,I$0002
	CALL	C.3B6A
	POP	HL
	RET

J$3804:	XOR	A
	LD	(D.FD09),A
	CALL	C.388F
	LD	C,(HL)
	LD	L,A
	JR	NZ,J.3861
	LD	B,C
	LD	C,L
	JR	NZ,J$3877
	LD	L,C
	LD	(HL),E
	LD	L,E
	DEC	C
	LD	A,(BC)
	NOP
	POP	HL
	RET

?.381B:	CALL	C.3BFD
	CALL	C.05AE
	PUSH	HL
	LD	IX,I.0100
	LD	BC,I.2000
J$3829:	CALL	C.3AD8
	LD	HL,D.FC18
	LD	A,(HL)
	AND	A
	JR	Z,J.3861
	INC	C
	PUSH	IX
	PUSH	BC
	LD	B,08H	; 8 
	CALL	C.3889
	LD	A,(HL)
	CP	20H	; " "
	JR	Z,J$3843
	LD	A,2EH	; "."
J$3843:	RST	18H
	LD	B,03H	; 3 
	CALL	C.3889
	LD	A,(D.F3B0)
	LD	B,A
	LD	A,(D$F661)
	AND	A
	JR	Z,J$385E
	ADD	A,0CH	; 12 
	CP	B
	JR	NC,J$385B
	LD	A,20H	; " "
	RST	18H
J$385B:	CALL	NC,C.05AE
J$385E:	POP	BC
	POP	IX
J.3861:	LD	DE,C.0010
	ADD	IX,DE
	DJNZ	J$3829
	LD	A,C
	OR	A
	JP	Z,J.055E
	CALL	C.05AE
	CALL	C$38D7
	CALL	C.05CC
	CALL	C.388F
	JR	NZ,J.38DD
	LD	A,C
	LD	(HL),H
	LD	H,L
	LD	(HL),E
	JR	NZ,J$38E7
	LD	(HL),D
	LD	H,L
	LD	H,L
	DEC	C
	LD	A,(BC)
	NOP
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3889:	LD	A,(HL)
	INC	HL
	RST	18H
	DJNZ	C.3889
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.388F:	EX	(SP),HL
	LD	A,(HL)
	INC	HL
	EX	(SP),HL
	AND	A
	RET	Z
	RST	18H
	JR	C.388F

?.3898:	PUSH	HL
	POP	IY
	LD	H,(IY+5)
	LD	L,(IY+6)
	JR	J.38E6

?.38A3:	CALL	C.3ACF
	PUSH	HL
	POP	IY
	LD	A,(HL)
	CP	01H	; 1 
	LD	HL,(D.FC26)
	JR	Z,J.38E6
	LD	L,(IY+6)
	JR	J.38E6

?.38B6:	LD	A,(HL)
	CP	01H	; 1 
	LD	E,3DH	; "="
	JP	NZ,J.3C05
	PUSH	HL
	POP	IY
	CALL	C.3ACF
	LD	L,(IY+6)
	LD	H,(IY+5)
	LD	DE,(D.FC26)
	RST	20H
	LD	HL,D.FFFF
	JR	NC,J.38E6
	INC	HL
	JR	J.38E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$38D7:	LD	BC,I.7D01
	LD	HL,J.0000
J.38DD:	CALL	C.3AEB
	JR	NZ,J$38E3
	INC	H
J$38E3:	INC	C
	DJNZ	J.38DD
J.38E6:	LD	(D.F7F8),HL
	LD	A,02H	; 2 
	LD	(D.F663),A
	RET

?.38EF:	CALL	C.3911
	RST	08H
	ADD	HL,HL
	CALL	C.3BF1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$38F7:	LD	(D.FC18),A
	CALL	C.3AD9
	LD	A,(D.FC23)
	AND	A
	RET	Z
J$3902:	LD	C,A
	CALL	C.3AEB
	PUSH	AF
	XOR	A
	CALL	C.3AEC
	POP	AF
	CP	0FFH
	JR	NZ,J$3902
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3911:	RST	08H
	JR	Z,J$38E1
	DEFB	0FDH		; << Illegal Op Code Byte >>

	DEC	SP

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$3916:	CALL	C.05BA
	RET	Z
	LD	A,D
	CP	0FCH
	JR	NC,J.3929
	CP	09H	; 9 
	JR	C,J.3929
	PUSH	HL
	CALL	C.392C
	POP	HL
	RET	Z
J.3929:	JP	J.052E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.392C:	LD	HL,I.FD89
	LD	DE,I$3941
J$3932:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J$393C
	INC	HL
	INC	DE
	OR	A
	JR	NZ,J$3932
	RET

J$393C:	SUB	30H	; "0"
	RET	NZ
	OR	(HL)
	RET

I$3941:	LD	C,L
	LD	B,L
	LD	C,L
	JR	NC,J$3946
J$3946:	CALL	C.3911
	CALL	C.3BF1
	PUSH	IX
	RST	08H
	LD	B,C
	RST	08H
	LD	D,E
	CALL	C$3916
	RST	08H
	ADD	HL,HL
	CALL	C.3B0D
	LD	E,41H	; "A"
	JP	Z,J.3C05
	POP	IX
	CALL	C.3AD8
J$3964:	PUSH	HL
	LD	DE,D.FC18
	LD	HL,I.F866
	LD	BC,I.000B
	LDIR
	POP	HL
	JR	J$3995

?.3973:	CALL	C.3BFD
	CALL	C.3B0D
	PUSH	AF
	LD	A,E
	CP	04H	; 4 
	JP	Z,J$0534
	CP	02H	; 2 
	JR	Z,J$3998
	CP	08H	; 8 
	JR	Z,J$39D1
	POP	AF
	JR	NZ,J$39D2
	OR	A
	JR	NZ,J.39D6
	CALL	C.3BD6

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$3991:	DEC	A
	LD	(D.FC25),A
J$3995:	JP	C.3AD9

J$3998:	POP	AF
	JR	NZ,J$39A1
	OR	A
	JR	NZ,J.39D6
	CALL	C$38F7
J$39A1:	LD	IX,I.0100
	LD	B,20H	; " "
J$39A7:	CALL	C.3AD8
	LD	A,(D.FC18)
	AND	A
	JR	Z,J$39BC
	LD	DE,C.0010
	ADD	IX,DE
	DJNZ	J$39A7
	LD	E,43H	; "C"
	JP	J.3C05

J$39BC:	LD	E,02H	; 2 
	CALL	C.3BD6
	LD	HL,D.FC18
	LD	B,10H	; 16 
J$39C6:	LD	(HL),A
	INC	HL
	DJNZ	J$39C6
	DEC	A
	LD	(D.FC25),A
	JP	J$3964

J$39D1:	POP	AF
J$39D2:	JP	NZ,J.055E
	OR	A
J.39D6:	JP	NZ,J$053A
	CALL	C.3BD6
	LD	HL,(D.FC26)
	LD	(IY+5),H
	LD	(IY+6),L
	LD	L,A
	LD	(D.FC26),HL
	CALL	C$3991
	LD	A,(D.FC23)
	AND	A
	RET	Z
	LD	A,(D.FC24)
	LD	(IY+7),A
	JP	C.3B51

?.39FA:	CALL	C.3ACF
	XOR	A
	LD	(D.FC25),A
	CALL	C.3AD9
	LD	A,(HL)
	CP	01H	; 1 
	RET	Z
	PUSH	HL
	POP	IY
	LD	A,(IY+6)
	AND	A
	RET	Z
	CALL	C.3B52
	LD	HL,(D.FC26)
	LD	L,(IY+6)
	LD	(D.FC26),HL
	JR	J$3A7A

?.3A1E:	PUSH	HL
	POP	IY
	LD	A,(IY+6)
	AND	A
	JR	NZ,J$3A5D
	PUSH	HL
	PUSH	BC
	CALL	C.3ACF
	LD	BC,I.7D01
J$3A2F:	CALL	C.3AEB
	JR	Z,J$3A3C
	INC	C
	DJNZ	J$3A2F
	LD	E,42H	; "B"
	JP	J.3C05

J$3A3C:	LD	A,(D.FC23)
	AND	A
	LD	A,C
	JR	NZ,J$3A46
	LD	(D.FC23),A
J$3A46:	LD	C,(IY+7)
	CALL	NZ,C.3AEC
	LD	(D.FC24),A
	LD	(IY+7),A
	LD	C,A
	LD	A,0FFH
	CALL	C.3AEC
	CALL	C.3AD9
	POP	BC
	POP	HL
J$3A5D:	LD	DE,I.0009
	ADD	HL,DE
	LD	E,(IY+6)
	ADD	HL,DE
	LD	(HL),C
	INC	(IY+6)
	RET	NZ
	CALL	C.3B52
	INC	(IY+5)
	PUSH	IY
	POP	HL
	CALL	C.3ACF
	LD	HL,I$FC27
	INC	(HL)
J$3A7A:	JR	C.3AD9

?.3A7C:	PUSH	HL
	PUSH	HL
	POP	IY
	CALL	C.3ACF
	LD	L,(IY+6)
	LD	H,(IY+5)
	LD	DE,(D.FC26)
	RST	20H
	POP	HL
	CCF
	RET	C
	LD	A,(IY+3)
	AND	A
	LD	(IY+3),00H
	RET	NZ
	LD	A,(IY+6)
	AND	A
	JR	Z,J$3AAF
	LD	BC,I.0009
	ADD	HL,BC
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	INC	(IY+6)
	RET	NZ
	INC	(IY+5)
	RET

J$3AAF:	LD	A,(IY+7)
	AND	A
	LD	C,A
	LD	A,(D.FC23)
	CALL	NZ,C.3AEB
	LD	(IY+7),A
	CALL	C.3B51
	LD	A,(IY+9)
	INC	(IY+6)
	AND	A
	RET

?.3AC8:	PUSH	HL
	POP	IY
	LD	(IY+3),C
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3ACF:	INC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	BC
	POP	IX
	DEC	HL
	DEC	HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3AD8:	DEFB	0F6H

C.3AD9:	SCF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	IX
	POP	HL
	LD	DE,D.FC18
	JR	NC,J$3AE6
	EX	DE,HL
J$3AE6:	LD	BC,C.0010
	JR	J$3B02


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3AEB:	DEFB	0F6H

C.3AEC:	SCF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I$007F
	LD	B,00H
	ADD	HL,BC
	LD	DE,D.FC28
	POP	AF
	JR	NC,J$3AFF
	EX	DE,HL
	LD	(HL),A
J$3AFF:	LD	BC,I.0001
J$3B02:	CALL	C.3B6A
	POP	BC
	POP	DE
	POP	HL
	LD	A,(D.FC28)
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3B0D:	PUSH	HL
	PUSH	DE
	LD	DE,I.F866
	LD	B,0BH	; 11 
J$3B14:	LD	A,(DE)
	CP	61H	; "a"
	JR	C,J.3B20
	CP	7BH	; "{"
	JR	NC,J.3B20
	AND	0DFH
	LD	(DE),A
J.3B20:	INC	DE
	DJNZ	J$3B14
	LD	IX,I.0100
	LD	C,20H	; " "
J$3B29:	CALL	C.3AD8
	LD	HL,D.FC18
	LD	A,(HL)
	AND	A
	JR	NZ,J$3B3E
J$3B33:	LD	DE,C.0010
	ADD	IX,DE
	DEC	C
	JR	NZ,J$3B29
	INC	C
	JR	J$3B4B

J$3B3E:	LD	DE,I.F866
	LD	B,0BH	; 11 
J$3B43:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J$3B33
	INC	DE
	INC	HL
	DJNZ	J$3B43
J$3B4B:	POP	DE
	POP	HL
	LD	A,(D.FC25)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3B51:	DEFB	0F6H

C.3B52:	SCF
	PUSH	AF
	PUSH	IY
	POP	HL
	LD	BC,I.0009
	ADD	HL,BC
	LD	E,00H
	LD	A,(IY+7)
	ADD	A,02H	; 2 
	LD	D,A
	POP	AF
	JR	C,J$3B67
	EX	DE,HL
J$3B67:	LD	BC,I.0100

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3B6A:	LD	A,H
	AND	A
	JP	P,J$3B70
	LD	A,D
J$3B70:	CP	40H	; "@"
	EXX
	LD	HL,D.FFFF
	LD	A,(D.FD09)
	LD	D,A
	JR	C,J$3BB7
	RRCA
	RRCA
	AND	0C0H
	LD	C,A
	RRCA
	RRCA
	RRCA
	RRCA
	OR	C
	LD	C,A
	IN	A,(0A8H)
	LD	B,A
	AND	33H	; "3"
	OR	C
	LD	E,A
	DI
	OUT	(0A8H),A
	LD	A,D
	AND	0CH	; 12 
	LD	D,A
	LD	A,(HL)
	CPL
	LD	C,A
	AND	0F3H
	OR	D
	LD	(HL),A
	LD	A,E
	AND	3FH	; "?"
	LD	D,A
	LD	A,B
	AND	0C0H
	OR	D
	EI
	OUT	(0A8H),A
	EXX
	LDIR
	EXX
	LD	A,E
	DI
	OUT	(0A8H),A
	LD	A,C
	LD	(HL),A
	LD	A,B
	EI
	OUT	(0A8H),A
	EXX
	RET

J$3BB7:	RRCA
	RRCA
	AND	0C0H
	LD	C,A
	LD	A,D
	AND	03H	; 3 
	OR	C
	LD	C,A
	IN	A,(0A8H)
	LD	B,A
	AND	3CH	; "<"
	OR	C
	LD	E,A
	LD	A,D
	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	LD	A,E
	DI
	CALL	C$51D7
	EI
	EXX
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3BD6:	PUSH	HL
	POP	IY
	PUSH	IX
	POP	BC
	LD	(IY+1),C
	LD	(IY+2),B
	XOR	A
	LD	(IY+3),A
	LD	(IY+5),A
	LD	(IY+6),A
	LD	(D$F864),HL
	LD	(HL),E
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3BF1:	CALL	C.3B0D
	JP	NZ,J.055E
	AND	A
	RET	Z
J$3BF9:	LD	E,40H	; "@"
	JR	J.3C05


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3BFD:	LD	A,(D.FD09)
	BIT	6,A
	RET	NZ
	LD	E,46H	; "F"
J.3C05:	XOR	A
	LD	(D$F87C),A
	PUSH	DE
	CALL	C$05C0
	POP	DE
	JP	J.05C6

I$3C11:	LD	BC,I$3C34
J$3C14:	LD	A,(BC)
	INC	BC
	OR	A
	RET	Z
	SUB	E
	JR	Z,J$3C1F
	INC	BC
	INC	BC
	JR	J$3C14

J$3C1F:	LD	L,C
	LD	H,B
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,D.F55E
	PUSH	HL
	LD	(HL),A
J$3C29:	INC	DE
	INC	HL
	LD	A,(DE)
	LD	(HL),A
	OR	A
	JR	NZ,J$3C29
	POP	HL
	LD	E,01H	; 1 
	RET

I$3C34:	DEC	A
	LD	B,(HL)
	INC	A
	LD	B,B
	LD	D,H
	INC	A
	LD	B,C
	LD	H,H
	INC	A
	LD	B,D
	LD	A,B
	INC	A
	LD	B,E
	ADD	A,(HL)
	INC	A
	LD	B,(HL)
	SUB	L
	INC	A
	NOP
	LD	B,D
	LD	H,C
	LD	H,H
	JR	NZ,J$3CB2
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$3CBE
	LD	L,A
	LD	H,H
	LD	H,L
	NOP
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$3CCE
	LD	(HL),H
	LD	L,C
	LD	L,H
	LD	L,H
	JR	NZ,J$3CD0
	LD	(HL),B
	LD	H,L
	LD	L,(HL)
	NOP
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J$3CCC
	LD	L,H
	LD	(HL),D
	LD	H,L
	LD	H,C
	LD	H,H
	LD	A,C
	JR	NZ,J$3CD8
	LD	A,B
	LD	L,C
	LD	(HL),E
	LD	(HL),H
	LD	(HL),E
	NOP
	LD	D,D
	LD	B,C
	LD	C,L
	JR	NZ,J$3CE2
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$3CE9
	LD	(HL),L
	LD	L,H
	LD	L,H
	NOP
	LD	D,H
	LD	L,A
	LD	L,A
	JR	NZ,J$3CF9
	LD	H,C
	LD	L,(HL)
	LD	A,C
	JR	NZ,J$3CF7
	LD	L,C
	LD	L,H
	LD	H,L
	LD	(HL),E
	NOP
	LD	D,D
	LD	B,C
	LD	C,L
	JR	NZ,J$3CFF
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J$3D0F
	LD	H,(HL)
	LD	H,(HL)
	LD	L,H
	LD	L,C
	LD	L,(HL)
	LD	H,L
	NOP
J.3CA7:	LD	HL,I$FCAD
	INC	(HL)
	DEC	(HL)
	LD	B,08H	; 8 
	LD	DE,I$3F4E
	LD	HL,I$3F3E
J$3CB2	EQU	$-2
	JR	Z,J.3CB9
	LD	HL,I$3F46
J.3CB9:	CP	(HL)
	JR	Z,J$3CC6
	INC	HL
	INC	DE
J$3CBE:	DJNZ	J.3CB9
J.3CC0:	CALL	C.3ED1
	JP	J.3DC7

J$3CC6:	LD	A,(DE)
	JR	J.3CC0

J$3CC9:	PUSH	AF
	CALL	C$3EE7
	POP	AF
J$3CCE:	JR	Z,J$3CD5
J$3CD0:	LD	HL,D.FAFC
	BIT	0,(HL)
J$3CD5:	JP	Z,C.3ED1
J$3CD8:	CP	41H	; "A"
	JR	C,J.3CA7
	CP	5BH	; "["
	JR	C,J$3CEC
	CP	61H	; "a"
J$3CE2:	JR	C,J.3CA7
	CP	7BH	; "{"
	JR	NC,J.3CA7
	RES	7,(HL)
	JR	J$3CEE

J$3CEC:	SET	7,(HL)
J$3CEE:	CP	61H	; "a"
	JR	C,J$3CF4
	SUB	20H	; " "
J$3CF4:	LD	D,A
	CP	58H	; "X"
J$3CF7:	JR	Z,J$3D15
J$3CF9:	LD	A,(D.FAF9)
	OR	A
	JR	NZ,J$3D1A
J$3CFF:	LD	A,D
	CALL	C.3E2F
	LD	A,D
	JP	NZ,C.3EB6
	CALL	C.3E20
	CP	80H
	RET	NC
	LD	A,D
	LD	(D.FAFA),A
	LD	A,01H	; 1 
	JR	J$3D55

J$3D15:	LD	A,0B0H
	JP	J.3CC0

J$3D1A:	DEC	A
	LD	A,D
	JR	NZ,J$3D57
J$3D1E:	LD	E,A
	CALL	C.3E2F
	LD	A,(D.FAFA)
	JR	Z,J$3D2C
	CALL	C.3E3D
	JR	J$3D38

J$3D2C:	CP	E
	JR	NZ,J$3D3F
	CP	4EH	; "N"
	JR	NZ,J$3D3B
	LD	A,0FDH
	CALL	C.3EBC
J$3D38:	JP	J.3DC7

J$3D3B:	LD	A,8FH
	JR	J$3D4D

J$3D3F:	CP	4EH	; "N"
	LD	A,E
	JR	NZ,J.3D50
	CP	59H	; "Y"
	JR	Z,J.3D50
	LD	(D.FAFA),A
	LD	A,0FDH
J$3D4D:	JP	C.3EBC

J.3D50:	LD	(D$FAFB),A
	LD	A,02H	; 2 
J$3D55:	JR	J$3DC8

J$3D57:	LD	HL,D.FAFA
	LD	D,(HL)
	INC	HL
	LD	B,(HL)
	LD	C,A
	PUSH	BC
	CALL	C.3E2F
	POP	BC
	JR	NZ,J$3D72
	LD	A,B
	LD	(D.FAFA),A
	LD	A,01H	; 1 
	LD	(D.FAF9),A
	LD	A,C
	JP	J$3D1E

J$3D72:	LD	A,B
	CP	59H	; "Y"
	JR	NZ,J$3D9D
	LD	A,D
	CP	43H	; "C"
	JR	Z,J$3D90
	CP	4CH	; "L"
	JR	Z,J.3DC1
	CP	46H	; "F"
	JR	Z,J$3D99
	CP	57H	; "W"
	JR	Z,J.3DF2
	LD	E,49H	; "I"
	PUSH	BC
	CALL	C.3E3D
	JR	J$3D96

J$3D90:	LD	A,0E1H
J$3D92:	PUSH	BC
	CALL	C.3EBC
J$3D96:	POP	BC
	JR	J.3DC1

J$3D99:	LD	A,0ECH
	JR	J$3D92

J$3D9D:	LD	A,B
	CP	48H	; "H"
	JR	NZ,J$3DDC
	LD	A,D
	CP	43H	; "C"
	JR	Z,J$3DB7
	CP	44H	; "D"
	JR	Z,J$3DCC
	CP	54H	; "T"
	JR	Z,J$3DD5
	CP	53H	; "S"
	JR	NZ,J.3DF2
	LD	A,9CH
	JR	J$3DB9

J$3DB7:	LD	A,0E1H
J$3DB9:	CALL	C.3EBC
J$3DBC:	LD	A,C
	CP	49H	; "I"
	JR	Z,J.3DC7
J.3DC1:	LD	A,4AH	; "J"
	LD	E,C
	CALL	C.3EB9
J.3DC7:	XOR	A
J$3DC8:	LD	(D.FAF9),A
	RET

J$3DCC:	LD	A,0E3H
	CALL	C.3EBC
	LD	A,0DEH
	JR	J$3DD7

J$3DD5:	LD	A,0E3H
J$3DD7:	CALL	C.3EBC
	JR	J.3DC1

J$3DDC:	LD	A,D
	CP	54H	; "T"
	JR	NZ,J.3DF2
	LD	A,B
	CP	53H	; "S"
	JR	NZ,J.3DF2
	LD	A,C
	CP	55H	; "U"
	JR	NZ,J.3DF2
	LD	A,0E2H
	CALL	C.3EBC
	JR	J.3DC7

J.3DF2:	LD	A,B
	LD	E,C
	CALL	C.3E3D
	JR	J.3DC7


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$3DF9:	CALL	C$3E29
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	LD	D,A
	LD	A,E
	CALL	C.3E2F
	ADD	A,D
	LD	L,A
	LD	A,D
	CP	0FH	; 15 
	JR	NC,J$3E10
	LD	A,L
	SUB	70H	; "p"
	RET

J$3E10:	CP	23H	; "#"
	JR	NC,J$3E18
	LD	A,L
	SUB	30H	; "0"
	RET

J$3E18:	LD	A,L
	SUB	23H	; "#"
	LD	BC,I$3F71
	JR	J$3E23


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3E20:	LD	BC,I$3F16
J$3E23:	LD	L,A
	LD	H,00H
	ADD	HL,BC
	LD	A,(HL)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$3E29:	CALL	C.3E20
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3E2F:	CALL	C.3E20
	SUB	14H	; 20 
	CP	01H	; 1 
	JR	C,J$3E3B
	CP	06H	; 6 
	RET	C
J$3E3B:	XOR	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3E3D:	LD	D,A
	CALL	C.3E20
	CP	0BH	; 11 
	JR	NC,J$3E48
	LD	A,D
	JR	J$3E8A

J$3E48:	CP	21H	; "!"
	JR	C,J.3E58
	CP	26H	; "&"
	JR	NC,J.3E58
	LD	A,D
	CALL	C.3EB9

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3E54:	LD	A,0DEH
	JR	C.3EBC

J.3E58:	LD	A,D
	CP	50H	; "P"
	JR	NZ,J$3E67
	LD	A,48H	; "H"
	CALL	C.3EB9
	LD	A,0DFH
	JP	C.3EBC

J$3E67:	CP	4AH	; "J"
	JR	NZ,J$3E79
	LD	A,9CH
	PUSH	DE
	CALL	C.3EBC
	CALL	C.3E54
	POP	DE
	LD	C,E
	JP	J$3DBC

J$3E79:	CP	46H	; "F"
	JR	NZ,J$3E8C
	LD	A,0ECH
	PUSH	DE
	CALL	C.3EBC
J$3E83:	POP	DE
	LD	A,E
	CP	55H	; "U"
	RET	Z
J.3E88:	LD	A,4CH	; "L"
J$3E8A:	JR	C.3EB9

J$3E8C:	CP	59H	; "Y"
	JR	NZ,J$3E96
	CALL	C.3EB9
	LD	A,E
	JR	J$3EA2

J$3E96:	CP	57H	; "W"
	JR	NZ,J$3EA7
	CALL	C.3EB9
	LD	A,E
	CP	49H	; "I"
	JR	Z,J.3E88
J$3EA2:	CP	45H	; "E"
	RET	NZ
	JR	J.3E88

J$3EA7:	CP	56H	; "V"
	JR	NZ,J$3EB7
	LD	A,55H	; "U"
	PUSH	DE
	CALL	C.3EB6
	CALL	C.3E54
	JR	J$3E83


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3EB6:	LD	E,A
J$3EB7:	LD	A,51H	; "Q"

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3EB9:	CALL	C$3DF9

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3EBC:	LD	HL,D.FAFC
	BIT	7,(HL)
	JR	Z,C.3ED1
	CP	0E0H
	JR	C,J$3ECB
	SUB	20H	; " "
	JR	C.3ED1

J$3ECB:	CP	0A0H
	JR	NC,C.3ED1
	ADD	A,20H	; " "

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C.3ED1:	LD	HL,(D.F3F8)
	LD	(HL),A
	INC	HL
	LD	A,L
	CP	18H
	JR	NZ,J$3EDE
	LD	HL,I$FBF0
J$3EDE:	LD	A,(D$F3FA)
	CP	L
	RET	Z
	LD	(D.F3F8),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C$3EE7:	LD	A,(D.F3DB)
	AND	A
	RET	Z
	LD	A,(D.FBD9)
	AND	A
	RET	NZ
	LD	A,0FH	; 15 
	LD	(D.FBD9),A
	DI
	OUT	(0ABH),A
	LD	A,0AH	; 10 
J$3EFB:	DEC	A
	JR	NZ,J$3EFB
	LD	A,0EH	; 14 
	OUT	(0ABH),A
	EI
	RET

J$3F04:	LD	HL,D.FAFC
	BIT	0,(HL)
	JR	Z,J$3F10
	RES	0,(HL)
	XOR	A
	JR	J.3F29

J$3F10:	LD	A,(D.FCAC)
	INC	A
	JR	Z,J$3F26
I$3F16:	LD	A,(D.FBEB)
	RRCA
	JR	C,J$3F24
	XOR	A
	LD	(D.FAF9),A
	SET	0,(HL)
	JR	J.3F29

J$3F24:	LD	A,0FFH
J$3F26:	LD	(D.FCAC),A
J.3F29:	PUSH	AF
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	LD	B,A
	POP	AF
	OR	A
	LD	A,80H
	JR	Z,J$3F3A
	XOR	A
J$3F3A:	OR	B
	OUT	(0A1H),A
	RET

I$3F3E:	LD	HL,(D$5D3A)
	LD	E,A
	CCF
	LD	A,7BH	; "{"
	LD	A,L
I$3F46:	LD	E,H
	LD	B,B
	LD	A,3FH	; "?"
	LD	E,E
	INC	A
	LD	A,E
	LD	A,L
I$3F4E:	OR	B
	SBC	A,0A1H
	AND	L
	RST	18H
	AND	H
	AND	D
	AND	E
	LD	A,(BC)
	DEC	D
	DEC	H
	JR	Z,J$3F7E
	JR	J$3F9D

?.3F5D:	LD	HL,I$1605
	LD	C,E
	LD	BC,I$060A
	INC	B
	ADD	HL,DE
	JR	Z,J$3FE8
	EX	AF,AF'
	LD	(BC),A
	INC	BC
	RLA
	LD	B,B
	LD	C,C
	ADC	A,H
	LD	B,A
	LD	(D$F4FD),HL
	SUB	D
	PUSH	AF
	SUB	D
	OR	0F7H
	RET	M
	LD	SP,HL
	JP	M,J$FCFB
	SUB	E
J$3F7E:	SUB	E
	SUB	E
	ADD	A,(HL)
	ADD	A,A
	ADC	A,B
	ADC	A,C
	ADC	A,D
	ADC	A,E
	ADC	A,H
	ADC	A,B
	ADC	A,L
	ADC	A,D
	ADC	A,(HL)



	END
