; SUBROM.MAC

; MSX SUBROM, SONY HB-F1 (version 2.0)

; Source re-created by Z80DIS 2.2
; Z80DIS was written by Kenneth Gielow, Palo Alto, CA

; Code Copyrighted by ASCII and maybe others
; Source comments by Arjen Zeilemaker

; Sourcecode supplied for STUDY ONLY
; Recreation NOT permitted without authorisation of the copyrightholders

	.Z80
	ASEG
	ORG	0000H

RDSLT	EQU	0000CH
WRSLT	EQU	00014H
OUTDO	EQU	00018H
KEYINT	EQU	00038H
GICINI	EQU	00090H
CHGET	EQU	0009FH
CKCNTC	EQU	000BDH
SNSMAT	EQU	00141H
EOL	EQU	00168H

M2F92	EQU	2F92H
M3058	EQU	3058H
M3236	EQU	3236H
M3412	EQU	3412H
M4055	EQU	4055H	; ----I
M406A	EQU	406AH	; ----I
M406D	EQU	406DH	; ----I
M406F	EQU	406FH	; ----I
M46E6	EQU	46E6H	; ----I
M475A	EQU	475AH	; ----I
M4C64	EQU	4C64H	; ----I
M4FCF	EQU	4FCFH	; ----I
M51D7	EQU	51D7H	; -C---
M520F	EQU	520FH	; ----I
M521C	EQU	521CH	; ----I
M542F	EQU	542FH	; ----I
M5439	EQU	5439H	; ----I
M579C	EQU	579CH	; ----I
M57AB	EQU	57ABH	; ----I
M5EA4	EQU	5EA4H	; ----I
M6275	EQU	6275H	; ----I
M6627	EQU	6627H	; ----I
M6678	EQU	6678H	; ----I
M67D0	EQU	67D0H	; ----I
M6A0E	EQU	6A0EH	; ----I
M6B24	EQU	6B24H	; ----I
M6E6B	EQU	6E6BH	; ----I
M6E6E	EQU	6E6EH	; ----I
M6E74	EQU	6E74H	; ----I
M6E86	EQU	6E86H	; ----I
M7323	EQU	7323H	; ----I
M7328	EQU	7328H	; ----I
M7EE4	EQU	7EE4H	; ----I
M7EF2	EQU	7EF2H	; ----I
M7FFD	EQU	7FFDH	; ----I

C$F380	EQU	0F380H	; -C---
J$F385	EQU	0F385H	; J----
J.F38C	EQU	0F38CH	; J----
C$F398	EQU	0F398H	; -C---
D.F3AE	EQU	0F3AEH	; --SL-
D.F3AF	EQU	0F3AFH	; --SL-
D.F3B0	EQU	0F3B0H	; --SL-
D.F3B1	EQU	0F3B1H	; ---LI
D$F3B2	EQU	0F3B2H	; --S--
D.F3B3	EQU	0F3B3H	; ---LI
D.F3B5	EQU	0F3B5H	; --SL-
D.F3B7	EQU	0F3B7H	; ---L-
D.F3BD	EQU	0F3BDH	; ---L-
D.F3BF	EQU	0F3BFH	; ---L-
D.F3C1	EQU	0F3C1H	; ---L-
D.F3C3	EQU	0F3C3H	; ---L-
D.F3C5	EQU	0F3C5H	; ---L-
D.F3C7	EQU	0F3C7H	; ---L-
D.F3C9	EQU	0F3C9H	; ---L-
D.F3CB	EQU	0F3CBH	; ---L-
D.F3CD	EQU	0F3CDH	; ---L-
D.F3CF	EQU	0F3CFH	; ---L-
D.F3D1	EQU	0F3D1H	; ---L-
D.F3D5	EQU	0F3D5H	; ---L-
D.F3D7	EQU	0F3D7H	; ---L-
D.F3D9	EQU	0F3D9H	; ---L-
D.F3DB	EQU	0F3DBH	; --SL-
D.F3DC	EQU	0F3DCH	; --SL-
D.F3DE	EQU	0F3DEH	; --SL-
D.F3DF	EQU	0F3DFH	; --SLI
D.F3E0	EQU	0F3E0H	; --SL-
D.F3E1	EQU	0F3E1H	; --SL-
D$F3E2	EQU	0F3E2H	; --S--
D$F3E3	EQU	0F3E3H	; --S--
D$F3E4	EQU	0F3E4H	; --S--
D$F3E5	EQU	0F3E5H	; --S--
D$F3E6	EQU	0F3E6H	; ---L-
D.F3E9	EQU	0F3E9H	; --SL-
D.F3EA	EQU	0F3EAH	; --SLI
D.F3EB	EQU	0F3EBH	; --SL-
D.F3F2	EQU	0F3F2H	; --SL-
D.F3F8	EQU	0F3F8H	; --SL-
D$F3FA	EQU	0F3FAH	; ---L-
D.F3FC	EQU	0F3FCH	; ---LI
I$F401	EQU	0F401H	; ----I
I.F406	EQU	0F406H	; ----I
D.F40B	EQU	0F40BH	; --S--
D.F40D	EQU	0F40DH	; --S--
D.F417	EQU	0F417H	; --SL-
D$F4FD	EQU	0F4FDH	; --S--
D.F55E	EQU	0F55EH	; --SLI
D.F560	EQU	0F560H	; --SL-
D.F561	EQU	0F561H	; --SL-
D.F562	EQU	0F562H	; --SLI
D.F564	EQU	0F564H	; --SL-
D$F565	EQU	0F565H	; --S--
D.F566	EQU	0F566H	; ---LI
D.F568	EQU	0F568H	; --SL-
D.F569	EQU	0F569H	; --S--
D.F56A	EQU	0F56AH	; --SL-
D.F56C	EQU	0F56CH	; --SL-
D.F56F	EQU	0F56FH	; --SL-
D$F570	EQU	0F570H	; --S--
D.F571	EQU	0F571H	; --SL-
D.F573	EQU	0F573H	; --SL-
D.F575	EQU	0F575H	; --S--
I.F577	EQU	0F577H	; ----I
D$F585	EQU	0F585H	; --S--
D.F5A0	EQU	0F5A0H	; --SL-
D.F5A2	EQU	0F5A2H	; --SL-
D.F5A4	EQU	0F5A4H	; --SL-
D.F5A6	EQU	0F5A6H	; --SL-
D.F5A8	EQU	0F5A8H	; --SL-
D$F661	EQU	0F661H	; ---L-
D.F663	EQU	0F663H	; --SL-
D.F666	EQU	0F666H	; --SL-
D.F668	EQU	0F668H	; --SL-
D.F669	EQU	0F669H	; --SL-
D.F66A	EQU	0F66AH	; --SLI
D$F699	EQU	0F699H	; ---L-
D.F6A5	EQU	0F6A5H	; --S--
D.F6C6	EQU	0F6C6H	; --SL-
I$F7F6	EQU	0F7F6H	; ----I
D.F7F8	EQU	0F7F8H	; --SL-
D$F862	EQU	0F862H	; --S--
D$F864	EQU	0F864H	; --S--
I.F866	EQU	0F866H	; ----I
D$F87C	EQU	0F87CH	; --S--
I$F87F	EQU	0F87FH	; ----I
I$F8CF	EQU	0F8CFH	; ----I
D.F91F	EQU	0F91FH	; ---L-
D.F920	EQU	0F920H	; ---L-
D.F922	EQU	0F922H	; --SL-
D.F924	EQU	0F924H	; --SL-
D.F926	EQU	0F926H	; --SL-
D.F928	EQU	0F928H	; --SL-
D.F92A	EQU	0F92AH	; --SL-
D.F92C	EQU	0F92CH	; --SL-
D.F942	EQU	0F942H	; --SL-
D.F944	EQU	0F944H	; --SL-
D.F949	EQU	0F949H	; --SL-
D.F94A	EQU	0F94AH	; --SL-
D.F94B	EQU	0F94BH	; --SL-
D.F94D	EQU	0F94DH	; ---L-
D.F94F	EQU	0F94FH	; ---L-
D.F951	EQU	0F951H	; --SL-
D.F953	EQU	0F953H	; --SL-
D.F954	EQU	0F954H	; --SL-
D.F955	EQU	0F955H	; --SL-
D.FAF5	EQU	0FAF5H	; --SL-
D.FAF6	EQU	0FAF6H	; --SL-
D.FAF7	EQU	0FAF7H	; --S-I
D.FAF8	EQU	0FAF8H	; --SL-
D.FAF9	EQU	0FAF9H	; --SL-
D.FAFA	EQU	0FAFAH	; --SLI
D$FAFB	EQU	0FAFBH	; --S--
D.FAFC	EQU	0FAFCH	; --SLI
XSAVE	EQU	0FAFEH
DFAFF	EQU	0FAFFH		; X border skip lightpen
YSAVE	EQU	0FB00H
DFB01	EQU	0FB01H		; Y border skip lightpen
LOGOPR	EQU	0FB02H
I$FBB1	EQU	0FBB1H	; ----I
I$FBB2	EQU	0FBB2H	; ----I
I$FBCA	EQU	0FBCAH	; ----I
D$FBCD	EQU	0FBCDH	; --S--
D.FBD9	EQU	0FBD9H	; --SL-
D.FBEB	EQU	0FBEBH	; ---L-
I$FBF0	EQU	0FBF0H	; ----I
D.FC18	EQU	0FC18H	; --SLI
I$FC19	EQU	0FC19H	; ----I
I.FC1A	EQU	0FC1AH	; ----I
D.FC23	EQU	0FC23H	; --SL-
D.FC24	EQU	0FC24H	; --SL-
D.FC25	EQU	0FC25H	; --SL-
D.FC26	EQU	0FC26H	; --SL-
I$FC27	EQU	0FC27H	; ----I
D.FC28	EQU	0FC28H	; ---LI
I.FC40	EQU	0FC40H	; ----I
D$FC9B	EQU	0FC9BH	; ---L-
I$FCA6	EQU	0FCA6H	; ----I
D.FCAC	EQU	0FCACH	; --SL-
I$FCAD	EQU	0FCADH	; ----I
D.FCAF	EQU	0FCAFH	; --SL-
D.FCB0	EQU	0FCB0H	; --SL-
D.FCB2	EQU	0FCB2H	; --SL-
D.FCB3	EQU	0FCB3H	; --SL-
D.FCB5	EQU	0FCB5H	; --SL-
D.FCB7	EQU	0FCB7H	; --SL-
D.FCB9	EQU	0FCB9H	; --SL-
EXPTBL	EQU	0FCC1H	; ---LI
SLTTBL	EQU	0FCC5H	; --S-I
SLTWRK	EQU	0FD09H	; --SLI
PROCNM	EQU	0FD89H	; ----I

H.INIP	EQU	0FDC7H	; -C---
H.NMI	EQU	0FDD6H	; J----
H.ERRP	EQU	0FEFDH	; --S--
H.CHRG	EQU	0FF48H	; -C---
H.PHYD	EQU	0FFA7H	; ---L-
RG8SAV	EQU	0FFE7H	; ----I
RG9SAV	EQU	0FFE8H	; --SLI
RG10SA	EQU	0FFE9H	; --S--
RG11SA	EQU	0FFEAH	; --S--
RG18SA	EQU	0FFF1H	; --S--
D.FFF7	EQU	0FFF7H	; --S-I
D.FFFF	EQU	0FFFFH	; --SLI

	DEFB	"CD"
	DEFW	C0336
	DEFW	C1649
	DEFW	C36D5


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0008:	JP	J1D32

	DEFS	00010H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0010:	JP	J1D3A

	DEFS	00014H-$,0

?0014:	JP	C0218

	DEFS	00018H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

?0018:	JP	J0577

	DEFS	0001CH-$,0

?001C:	JP	C0262

	DEFS	00020H-$,0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0020:	LD	A,H
	SUB	D
	RET	NZ
	LD	A,L
	SUB	E
	RET

	DEFS	00028H-$,0

;	  Subroutine evaluate byte operand
;	     Inputs  ________________________
;	     Outputs ________________________

C0028:	JP	C060E

	DEFS	00030H-$,0

?0030:	JP	J0246

	DEFS	00038H-$,0

?0038:	EX	AF,AF'
	EXX
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	AF,AF'
	EXX
	PUSH	IX
	PUSH	IY
	LD	IX,KEYINT
	LD	IY,(EXPTBL+0-1)
	CALL	C058D
	POP	IY
	POP	IX
	EX	AF,AF'
	EXX
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	EX	AF,AF'
	EXX
	EI
	RETI

	DEFS	00066H-$,0

?0066:	JP	H.NMI

?0069:	EI
	JP	J2651

?006D:	EI
	JP	J2556

?0071:	EI
	JP	C256F

?0075:	EI
	JP	J2607

?0079:	EI
	JP	J262A

?007D:	EI
	JP	J263F

?0081:	EI
	JP	J2648

?0085:	EI
	JP	C2823

?0089:	EI
	JP	J110E

?008D:	EI
	JP	C12C4

?0091:	EI
	JP	C1342

?0095:	EI
	JP	C1384

?0099:	EI
	JP	C13AD

?009D:	EI
	JP	C13B5

?00A1:	EI
	JP	C1426

?00A5:	EI
	JP	J1439

?00A9:	EI
	JP	C13E7

?00AD:	EI
	JP	J144B

?00B1:	EI
	JP	C13FC

?00B5:	EI
	JP	J148C

?00B9:	EI
	JP	C1414

?00BD:	EI
	JP	J1498

?00C1:	EI
	JP	C14DB

?00C5:	EI
	JP	C158F

?00C9:	EI
	JP	C27E7

?00CD:	EI
	JP	C2898

?00D1:	EI
	JP	J09C3

?00D5:	EI
	JP	C09E5

?00D9:	EI
	JP	C0A1A

?00DD:	EI
	JP	C0A48

?00E1:	EI
	JP	C0A98

?00E5:	EI
	JP	C0B42

?00E9:	EI
	JP	C0B9C

?00ED:	EI
	JP	C0BD2

?00F1:	EI
	JP	C0C22

?00F5:	EI
	JP	C06F5

?00F9:	EI
	JP	J0755

?00FD:	EI
	JP	C076A

I0101:	EI
	JP	C077F

?0105:	EI
	JP	C07D9

?0109:	EI
	JP	C08CB

?010D:	EI
	JP	C08D6

?0111:	EI
	JP	C0953

?0115:	EI
	JP	C07FE

?0119:	EI
	JP	C0864

?011D:	EI
	JP	J0D52

?0121:	EI
	JP	J0E0F

?0125:	EI
	JP	J0E5D

?0129:	EI
	JP	J0F16

?012D:	EI
	JP	C0647

?0131:	EI
	JP	C298B

?0135:	EI
	JP	J3F04

?0139:	EI
	JP	J3CC9

?013D:	EI
J013E:	JP	C06A8

?0141:	EI
	JP	J0F9F

?0145:	EI
	JP	J0F7E

?0149:	EI
	JP	C0F6A

?014D:	EI
	JP	C0FD3

?0151:	EI
	JP	J208F

?0155:	EI
	JP	J1DF6

?0159:	EI
	JP	J1EE5

?015D:	EI
	JP	J1FDF

?0161:	EI
	JP	J21C6

?0165:	EI
	JP	J21E5

?0169:	EI
	JP	J2220

?016D:	EI
	JP	J2297

?0171:	EI
	JP	J22F4

?0175:	EI
	JP	J2307

?0179:	EI
	JP	J1833

?017D:	EI
	JP	J1A62

?0181:	EI
	JP	J1B4E

?0185:	EI
	JP	J0480

?0189:	EI
	JP	J0470

?018D:	EI
	JP	J2342

?0191:	EI
	JP	J2EB9

?0195:	EI
	JP	J2F42

?0199:	EI
	JP	J2EDF

?019D:	EI
	JP	J30A8

?01A1:	EI
	JP	J31B4

?01A5:	EI
I01A6:	JP	J306F

?01A9:	EI
	JP	J307C

?01AD:	EI
	JP	J34DD

?01B1:	EI
	JP	J1683

?01B5:	EI
	JP	C09BF

?01B9:	EI
	JP	0

?01BD:	EI
	JP	J1049

J01C1:	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL
	LD	C,A
	AND	D
	LD	E,A
	LD	(D.FFFF),A
	LD	A,B
	AND	D
	OUT	(0A8H),A
	LD	A,E
	LD	(SLTTBL+0),A
	PUSH	BC
	EXX
	EX	AF,AF'
	CALL	C$F398
	DI
	EX	AF,AF'
	EXX
	POP	BC
	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,C
	LD	(SLTTBL+0),A
	EX	AF,AF'
	EXX
	RET

?01F5:	EI
	JP	J1D08

?01F9:	EI
	JP	J1D10


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C01FD:	CALL	C02DD
I0200:	JP	M,J020D
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	CALL	C$F380
	LD	A,E
	RET

J020D:	PUSH	HL
	CALL	C0302
	EX	(SP),HL
	PUSH	BC
	CALL	C01FD
	JR	J0233


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0218:	PUSH	DE
	CALL	C02DD
	JP	M,J0228
	POP	DE
	IN	A,(0A8H)
	LD	D,A
	AND	C
	OR	B
	JP	J$F385

J0228:	EX	(SP),HL
	PUSH	HL
	CALL	C0302
	POP	DE
	EX	(SP),HL
	PUSH	BC
	CALL	C0218
J0233:	POP	BC
	EX	(SP),HL
	PUSH	AF
	LD	A,B
	AND	3FH	; "?"
	OR	C
	OUT	(0A8H),A
	LD	A,L
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	POP	AF
	POP	HL
	RET

J0246:	EX	(SP),HL
	PUSH	AF
	PUSH	DE
	LD	A,(HL)
	PUSH	AF
	POP	IY
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	PUSH	DE
	POP	IX
	POP	DE
	POP	AF
	EX	(SP),HL
J0258:	EXX
	LD	D,0FCH
	JR	J0265

?025D:	EXX
	LD	D,0F3H
	JR	J0265


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0262:	EXX
	LD	D,0F0H
J0265:	EX	AF,AF'
	DI
	LD	A,(EXPTBL+0)
	AND	A
	IN	A,(0A8H)
	JP	M,J0276
	PUSH	AF
	AND	D
	EXX
	JP	J.F38C

J0276:	LD	B,A
	LD	A,(D.FAF8)
	AND	03H	; 3 
	JR	NZ,J0284
	LD	A,D
	CP	0F3H
	JP	NZ,J01C1
J0284:	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,(D.FFFF)
	CPL
	LD	C,A
	AND	D
	LD	(D.FFFF),A
	LD	E,A
	LD	A,B
	OUT	(0A8H),A
	LD	A,E
	LD	(SLTTBL+0),A
	LD	A,B
	PUSH	BC
	LD	HL,I02A6
	PUSH	HL
	PUSH	AF
	AND	D
	EXX
	JP	J.F38C

I02A6:	DI
	EXX
	EX	AF,AF'
	POP	BC
	LD	A,B
	AND	3FH	; "?"
	OUT	(0A8H),A
	LD	A,C
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	LD	A,C
	LD	(SLTTBL+0),A
	EX	AF,AF'
	EXX
	RET

J02BD:	CALL	C02DD
	JP	M,J02CA
	IN	A,(0A8H)
	AND	C
	OR	B
	OUT	(0A8H),A
	RET

J02CA:	PUSH	HL
	CALL	C0302
	LD	C,A
	LD	B,00H
	LD	A,L
	AND	H
	OR	D
	LD	HL,SLTTBL
	ADD	HL,BC
	LD	(HL),A
	POP	HL
	LD	A,C
	JR	J02BD


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C02DD:	DI
	PUSH	AF
	LD	A,H
	RLCA
	RLCA
	AND	03H	; 3 
	LD	E,A
	LD	A,0C0H
J02E7:	RLCA
	RLCA
	DEC	E
	JP	P,J02E7
	LD	E,A
	CPL
	LD	C,A
	POP	AF
	PUSH	AF
	AND	03H	; 3 
	INC	A
	LD	B,A
	LD	A,0ABH
J02F8:	ADD	A,55H	; "U"
	DJNZ	J02F8
	LD	D,A
	AND	E
	LD	B,A
	POP	AF
I0300:	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0302:	PUSH	AF
	LD	A,D
	AND	0C0H
	LD	C,A
	POP	AF
	PUSH	AF
	LD	D,A
	IN	A,(0A8H)
	LD	B,A
	AND	3FH	; "?"
	OR	C
	OUT	(0A8H),A
	LD	A,D
	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	LD	A,0ABH
J031A:	ADD	A,55H	; "U"
	DEC	D
	JP	P,J031A
	AND	E
	LD	D,A
	LD	A,E
	CPL
	LD	H,A
	LD	A,(D.FFFF)
	CPL
	LD	L,A
	AND	H
	OR	D
	LD	(D.FFFF),A
	LD	A,B
	OUT	(0A8H),A
	POP	AF
	AND	03H	; 3 
	RET

C0336:	LD	HL,I29F6
	LD	DE,D.F3DF
	LD	BC,C0008
	LDIR
	LD	DE,RG8SAV
	LD	BC,C0010
	LDIR
	XOR	A
	LD	(D.FAF5),A
	LD	(D.FAF6),A
	CALL	C0512
	LD	(D.FAF8),A
	LD	H,A
	LD	L,0F7H
	LD	(H.ERRP+0),HL
	LD	HL,I3C11
	LD	(H.ERRP+2),HL
	LD	A,(EXPTBL+0)
	LD	(D.FFF7),A
	LD	A,2CH
	LD	(DFAFF),A		; initialize X border skip lightpen
	LD	A,26H
	LD	(DFB01),A		; initialize Y border skip lightpen
	LD	A,0D3H			; no external audio mixing, video input 21 pin, internal sync, AV control=1, Ym control=full, S1=0, S0=0
	OUT	(0F7H),A		; initialize digitizer hardware
	LD	(D.FAF7),A
	XOR	A
	LD	C,0FFH
	OUT	(0D8H),A
	LD	A,02H	; 2 
	OUT	(0D9H),A
	LD	HL,I050A
	LD	B,08H	; 8 
J0387:	IN	A,(0D9H)
	CP	(HL)
	JR	NZ,J0391
	INC	HL
	DJNZ	J0387
	RES	0,C
J0391:	IN	A,(0C0H)
	CP	0FFH
	JR	Z,J0399
	RES	2,C
J0399:	IN	A,(0F7H)
	AND	77H			; b6-b4, b2-b0 are outputs which are readback, b7 and b3 are I/O with different input function
	CP	77H
	JR	Z,J03A3
	RES	3,C
J03A3:	IN	A,(0C8H)
	CP	0FFH
	JR	Z,J03AB
	RES	4,C
J03AB:	XOR	A
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	OUT	(81H),A
	PUSH	AF
	POP	AF
	LD	A,40H	; "@"
	OUT	(81H),A
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(81H)
I03C0:	AND	3FH	; "?"
	CP	05H	; 5 
	JR	NZ,J03C8
	RES	5,C
J03C8:	IN	A,(0BBH)
	CP	0FFH
	JR	Z,J03D0
	RES	6,C
J03D0:	LD	A,C
	OUT	(0F5H),A
	CALL	C1CF7
	LD	B,00H
	CALL	C1CD2
	CP	0AH	; 10 
	JR	Z,J03E2
J03DF:	CALL	C0431
J03E2:	CALL	C1CF7
	LD	B,03H	; 3 
	CALL	C1CD2
	AND	01H	; 1 
	PUSH	AF
	CALL	C1CDB
	POP	BC
	CP	51H	; "Q"
	JP	NC,J03DF
	OR	A
	JP	Z,J03DF
	DEC	B
	JR	NZ,J0402
	CP	21H	; "!"
I03FF:	JP	NC,J03DF
J0402:	CALL	C1CF7
	LD	B,01H	; 1 
	CALL	C1CD2
	LD	D,A
	CALL	C1CD2
	LD	E,A
	CALL	C17F8
	CALL	C2A0E
	LD	B,02H	; 2 
	LD	HL,J0000
J041A:	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J041A
	DJNZ	J041A
	CALL	C063C
	XOR	A
	LD	BC,04000H
	CALL	C0977
	CALL	C0A1A
	JP	J0F9F


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0431:	LD	HL,I04FF
	LD	C,02H	; 2 
J0436:	LD	B,0DH	; 13 
	LD	A,04H	; 4 
	SUB	C
	CALL	C1A59
J043E:	LD	B,0DH	; 13 
J0440:	LD	A,0DH	; 13 
	SUB	B
	OUT	(0B4H),A
	LD	A,(HL)
	INC	HL
	CP	0FFH
	JR	NZ,J044D
	DEC	HL
	XOR	A
J044D:	OUT	(0B5H),A
	DJNZ	J0440
	DEC	C
	JR	NZ,J0436
	LD	B,0DH	; 13 
	LD	A,08H	; 8 
	CALL	C1A59
	XOR	A
	CALL	C1A59
	LD	A,0DH	; 13 
	CALL	C1A59
	LD	A,01H	; 1 
	CALL	C1CF9
	LD	B,0AH	; 10 
	LD	A,01H	; 1 
	JP	C1A59

J0470:	SCF
	CALL	C0481
	LD	HL,M7EF2
	CALL	C05F6			; message to interpreter output
	LD	HL,M7EE4
	JP	C05F6			; message to interpreter output

J0480:	XOR	A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0481:	PUSH	AF
	CALL	C1CF7
	LD	B,03H	; 3 
	CALL	C1CD2
	LD	C,A
	AND	01H	; 1 
	POP	DE
	PUSH	AF
	PUSH	DE
	PUSH	BC
	LD	A,C
	RLCA
	RLCA
	AND	08H	; 8 
	LD	C,A
	LD	A,(RG9SAV)
	AND	0F7H
	OR	C
	LD	B,A
	LD	C,09H	; 9 
	CALL	C0647
	POP	BC
	CALL	C1CDB
	LD	E,A
	POP	AF
	PUSH	DE
	PUSH	AF
	CALL	C1CD2
	LD	(D.F3E9),A
	LD	(D.F3F2),A
	CALL	C1CD2
	LD	(D.F3EA),A
	CALL	C1CD2
	LD	(D.F3EB),A
	CALL	C1CD2
	LD	C,A
	RRC	C
	SBC	A,A
	LD	B,A
	POP	AF
	JR	NC,J04CC
	LD	A,B
J04CC:	LD	(D.F3DE),A
	RRC	C
	SBC	A,A
	LD	(D.F3DB),A
	RRC	C
	PUSH	BC
	LD	BC,BDOS
	LD	HL,D.F3FC
	JR	NC,J04E3
	LD	HL,I$F401
J04E3:	LD	DE,I.F406
	LDIR
	POP	BC
	RRC	C
	SBC	A,A
	LD	(D.F417),A
	POP	DE
	POP	AF
	LD	(D.FCB0),A
	LD	(D.FCAF),A
	PUSH	DE
	CALL	C09BF
	POP	DE
	JP	J1FFF

I04FF:	DEFB	0AH
I0500:	DEFB	00H,00H,01H,0DH,01H,0FH,04H,07H
	DEFB	03H,0FFH

I050A:	DEFB	00H,40H,20H,10H,08H,04H,02H,01H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0512:	PUSH	BC
	PUSH	HL
	IN	A,(0A8H)
	AND	03H	; 3 
	LD	C,A
	LD	B,00H
	LD	HL,EXPTBL
	ADD	HL,BC
	OR	(HL)
	LD	C,A
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	A,(HL)
	AND	03H	; 3 
	RLCA
	RLCA
	OR	C
	POP	HL
	POP	BC
	RET

J052E:	LD	IX,M6E6B
	JR	J0562

J0534:	LD	IX,M6E86
	JR	J0562

J053A:	LD	IX,M6E6E
	JR	J0562

J0540:	LD	IX,M4055
	JR	J0562

J0546:	LD	IX,M475A
	JR	J0562

J054C:	LD	IX,M406A
	JR	J0562

J0552:	LD	IX,M406D
	JR	J0562

J0558:	LD	IX,M6275
	JR	J0562

J055E:	LD	IX,M6E74
J0562:	JP	J0618

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0565:	LD	IX,CHGET
	JR	C058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C056B:	LD	IX,GICINI
	JR	C058D

J0571:	LD	IX,FNKSB
	JR	C058D

J0577:	LD	IX,OUTDO
	JR	C058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C057D:	LD	IX,RDSLT
	JR	C058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0583:	LD	IX,WRSLT
	JR	C058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0589:	LD	IX,CKCNTC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C058D:	JP	J0258


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0590:	LD	IX,SNSMAT
	JR	C058D

J0596:	LD	IX,EOL
	JR	C058D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C059C:	LD	IX,M579C
	JR	J0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05A2:	LD	IX,M57AB
	JR	J0618

J05A8:	LD	IX,M7328
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05AE:	LD	IX,M7323
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05B4:	LD	IX,M5439
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05BA:	LD	IX,M6A0E
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05C0:	LD	IX,M6B24
	JR	J05F4

J05C6:	LD	IX,M406F
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05CC:	LD	IX,M3412
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05D2:	LD	IX,M3058
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05D8:	LD	IX,M5EA4
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05DE:	LD	IX,M3236
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05E4:	LD	IX,M4FCF
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05EA:	LD	IX,M6627
	JR	J05F4

J05F0:	LD	IX,M2F92
J05F4:	JR	J0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05F6:	LD	IX,M6678
	JR	J05F4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C05FC:	LD	IX,M4C64
I0600:	JR	J0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0602:	LD	IX,M542F
	JR	J0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0608:	LD	IX,M520F
	JR	J0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C060E:	LD	IX,M521C
	JR	J0618


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0614:	LD	IX,M67D0
J0618:	CALL	C0262
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C061D:	LD	(D.F3DE),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0620:	LD	A,(D.FCAF)
	CP	02H	; 2 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0626:	LD	A,(D.FCAF)
	CP	04H	; 4 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C062C:	LD	A,(D.FCAF)
	CP	05H	; 5 
	RET

J0632:	CALL	C1034
	LD	A,(D.F3E0)
	OR	60H	; "`"
	JR	J0644


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C063C:	CALL	C1034
	LD	A,(D.F3E0)
	AND	3FH	; "?"
J0644:	LD	B,A
	LD	C,01H	; 1 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0647:	LD	A,I
	PUSH	AF
	PUSH	HL
	LD	A,C
	AND	A
	JR	NZ,J0680
	LD	A,B
	LD	HL,D.F3DF
	XOR	(HL)
	AND	01H	; 1 
	JR	Z,J0680
	LD	HL,RG9SAV
	LD	A,(HL)
	AND	0CFH
	LD	(HL),A
	LD	A,B
	AND	01H	; 1 
	RRCA
	RRCA
	RRCA
	RRCA
	OR	(HL)
	PUSH	BC
	LD	B,A
	LD	C,09H	; 9 
	LD	HL,D.FAF7
	LD	A,(HL)
	AND	3FH	; "?"
	LD	(HL),A
	LD	A,B
	RLCA
	RLCA
	CPL
	AND	0C0H
	OR	(HL)
	OUT	(0F7H),A
	LD	(HL),A
	CALL	C0647
	POP	BC
J0680:	LD	A,B
	DI
	OUT	(99H),A
	LD	A,C
	OR	80H
	OUT	(99H),A
	PUSH	BC
	PUSH	DE
	LD	D,B
	LD	A,C
	LD	B,00H
	CP	08H	; 8 
	JR	NC,J0698
	LD	HL,D.F3DF
	JR	J069F

J0698:	CP	18H
	JR	NC,J06A1
	LD	HL,RG8SAV-8
J069F:	ADD	HL,BC
	LD	(HL),D
J06A1:	POP	DE
	POP	BC
	POP	HL
	POP	AF
	RET	PO
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C06A8:	LD	A,(D.FCAF)
	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	DI
	LD	HL,I06B8
	CALL	C09C9
	JR	J06F0

I06B8:	DEFW	C0B42
	DEFW	C0B9C
	DEFW	C0BD2
	DEFW	C0C22
	DEFW	C0BD9
	DEFW	C0C56
	DEFW	C0C80
	DEFW	C0C97
	DEFW	C0CC7

J06CA:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	DI
	XOR	A
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	CALL	C1034
	LD	HL,D.F3DF
	LD	B,08H	; 8 
J06DE:	LD	A,(HL)
	INC	HL
	OUT	(9BH),A
	DJNZ	J06DE
	LD	HL,RG8SAV
	LD	B,10H	; 16 
J06E9:	LD	A,(HL)
	INC	HL
	OUT	(9BH),A
	DJNZ	J06E9
	EI
J06F0:	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C06F5:	CALL	C0701
	PUSH	HL
	LD	HL,J0000
	CALL	C08E3
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0701:	LD	A,(D.F3E0)
	LD	B,A
I0705:	LD	C,01H	; 1 
	CALL	C0647
	LD	HL,(D.F926)
	LD	BC,I0800
	XOR	A
	CALL	C0977

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0714:	LD	A,(D.F3E9)
	LD	E,A
	LD	HL,(D.F928)
	LD	BC,I2000
J071E:	CALL	C0626
	LD	A,0D1H
	JR	C,J0727
	LD	A,0D9H
J0727:	CALL	C08CB
	INC	HL
	INC	HL
	LD	A,C
	CALL	C08CB
	INC	HL
	INC	C
	LD	A,(D.F3E0)
	RRCA
	RRCA
	JR	NC,J073C
	INC	C
	INC	C
	INC	C
J073C:	LD	A,E
	CALL	C08CB
	INC	HL
	DJNZ	J071E
	CALL	C0626
	RET	C
	LD	HL,(D.F928)
	LD	BC,I0200
	SBC	HL,BC
	LD	A,(D.F3E9)
	JP	C0977

J0755:	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	CALL	C077F
	CP	08H	; 8 
	JR	Z,J0764
	ADD	HL,HL
	ADD	HL,HL
J0764:	EX	DE,HL
	LD	HL,(D.F926)
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C076A:	LD	L,A
	LD	H,00H
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL
	LD	HL,(D.F928)
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0775:	ADD	A,A
	ADD	A,A
I0777:	CALL	C076A
	LD	DE,-256
	ADD	HL,DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C077F:	LD	A,(D.F3E0)
	RRCA
	RRCA
	LD	A,08H	; 8 
	RET	NC
	LD	A,20H	; " "
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C078A:	CALL	H.INIP
	LD	HL,(D.F924)
	CALL	C08E3
	LD	A,(D.F91F)
	LD	HL,(D.F920)
	LD	BC,I0800
	PUSH	AF
J079D:	POP	AF
	PUSH	AF
	PUSH	BC
	DI
	CALL	C057D
	EI
	POP	BC
	OUT	(98H),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J079D
	POP	AF
	RET

?07B0:	CALL	C08F1
	LD	A,C
	OR	A
	LD	A,B
	LD	B,C
	LD	C,98H
	EX	DE,HL
	JR	Z,J07BD
	INC	A
J07BD:	INIR
	DEC	A
	JR	NZ,J07BD
	EX	DE,HL
	RET

?07C4:	EX	DE,HL
	CALL	C08E3
	EX	DE,HL
	LD	A,C
	OR	A
	LD	A,B
	LD	B,C
	LD	C,98H
	JR	Z,J07D2
	INC	A
J07D2:	OTIR
	DEC	A
	JR	NZ,J07D2
	EX	DE,HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C07D9:	LD	H,00H
	LD	L,A
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	EX	DE,HL
	LD	HL,(D.F920)
	ADD	HL,DE
	LD	DE,I.FC40
	LD	B,08H	; 8 
	LD	A,(D.F91F)
J07EC:	PUSH	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	CALL	C057D
	EI
	POP	BC
	POP	DE
	POP	HL
	LD	(DE),A
	INC	DE
	INC	HL
	POP	AF
	DJNZ	J07EC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C07FE:	CALL	C0626
	JP	Z,C0895
	JR	NC,C0811
	CALL	C0620
	JP	Z,C0895
	JP	NC,C08AD
	JR	C0864


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0811:	PUSH	AF
	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C2980
	LD	A,(D.F3EA)
	CALL	C084B
	CALL	C29EB
	XOR	A
	LD	H,A
	LD	L,A
	CALL	C29A5
	XOR	A
	CALL	C29DB
	LD	A,(D.FCAF)
	AND	02H	; 2 
	LD	DE,I0100
	JR	Z,J0838
	LD	DE,I0200
J0838:	LD	HL,I00D4
	CALL	C29C4
	LD	A,0C0H
	CALL	C29E3
	CALL	C2980
	POP	HL
	POP	DE
	POP	BC
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C084B:	LD	B,A
	LD	A,(D.FCAF)
	CP	08H	; 8 
	LD	A,B
	RET	Z
	RLCA
	RLCA
	RLCA
	RLCA
	OR	B
	LD	B,A
	LD	A,(D.FCAF)
	CP	06H	; 6 
	LD	A,B
	RET	NZ
	RRCA
	RRCA
	OR	B
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0864:	LD	A,(D.FCAF)
	AND	A
	LD	HL,(D.F922)
	JR	NZ,J087E
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J0879
	LD	BC,I03C0
	JR	J0881

J0879:	LD	BC,I0780
	JR	J0881

J087E:	LD	BC,I0300
J0881:	LD	A,20H	; " "
	CALL	C0977
	CALL	C08C1
	LD	HL,I$FBB2
	LD	B,18H
J088E:	LD	(HL),B
	INC	HL
	DJNZ	J088E
	JP	J0571

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0895:	CALL	C099C
	LD	BC,I1800
	PUSH	BC
	LD	HL,(D.F3C9)
	LD	A,(D.F3EA)
	CALL	C0977
	LD	HL,(D.F3CB)
	POP	BC
	XOR	A
J08AA:	JP	C0977


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08AD:	CALL	C099C
	LD	HL,D.F3EA
	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	LD	HL,(D.F3D5)
	LD	BC,I0600
	JR	J08AA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08C1:	LD	HL,I0101
	LD	(D.F3DC),HL
	RET

?08C8:	CALL	C08DC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08CB:	PUSH	AF
	CALL	C08E3
	POP	AF
	OUT	(98H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08D3:	CALL	C08DC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08D6:	CALL	C08F1
	IN	A,(98H)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08DC:	PUSH	AF
	LD	A,H
	AND	3FH	; "?"
	LD	H,A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08E3:	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	CALL	C0914
	LD	A,H
	AND	3FH	; "?"
	OR	40H	; "@"
	JR	J08FB


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C08F1:	PUSH	BC
	PUSH	DE
	PUSH	HL
	EX	DE,HL
	CALL	C0914
	LD	A,H
	AND	3FH	; "?"
J08FB:	PUSH	AF
	LD	A,H
	AND	0C0H
	OR	D
	RLCA
	RLCA
	DI
	OUT	(99H),A
	LD	A,8EH
	OUT	(99H),A
	LD	A,L
	OUT	(99H),A
	POP	AF
	OUT	(99H),A
	EI
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0914:	LD	A,(D.FCAF)
	LD	C,A
	LD	A,(D.FAF6)
	AND	A
	LD	HL,I0925
	JP	NZ,J09CA
	EX	DE,HL
	LD	D,A
	RET

I0925:	DEFW	C0937
	DEFW	C0945
	DEFW	C0945
	DEFW	C0945
	DEFW	C0945
	DEFW	C0944
	DEFW	C0944
	DEFW	C0943
	DEFW	C0943

C0937:	LD	A,(D.F3B0)
	CP	29H	; ")"
	LD	A,(D.FAF6)
	JR	C,J0947
	JR	J0946

C0943:	ADD	A,A
C0944:	ADD	A,A
C0945:	ADD	A,A
J0946:	ADD	A,A
J0947:	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	H,A
	LD	A,00H
	LD	L,A
	ADC	A,A
	ADD	HL,DE
	LD	D,A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0953:	CALL	C062C
	JP	NC,J0997
	CALL	C09A5
	DEC	A
	JP	M,J098A
	PUSH	AF
	CALL	C099C
	POP	AF
	RET	NZ
	LD	HL,D.F3EA
	LD	A,(D.F3E9)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	LD	HL,(D.F3BF)
	LD	BC,C0020

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0977:	PUSH	AF
	CALL	C08E3
	LD	A,C
	OR	A
	JR	Z,J0980
	INC	B
J0980:	POP	AF
J0981:	OUT	(98H),A
	DEC	C
	JP	NZ,J0981
	DJNZ	J0981
	RET

J098A:	LD	HL,D.F3EA
	LD	A,(D.F3E9)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	(HL)
	JR	J099F

J0997:	CP	08H	; 8 
	CALL	NZ,C09A5

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C099C:	LD	A,(D.F3EB)
J099F:	LD	B,A
	LD	C,07H	; 7 
	JP	C0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C09A5:	PUSH	AF
	LD	A,(D.F3EA)
	AND	0FH	; 15 
	LD	(D.F3EA),A
	LD	A,(D.F3E9)
	AND	0FH	; 15 
	LD	(D.F3E9),A
	POP	AF
	RET

?09B8:	RET	NZ
	PUSH	HL
	CALL	C07FE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C09BF:	LD	HL,J0F9F
	PUSH	HL
J09C3:	CP	09H	; 9 
	RET	NC
	LD	HL,I09D3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C09C9:	LD	C,A
J09CA:	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,C
	JP	(HL)

I09D3:	DEFW	C09E5
	DEFW	C0A1A
	DEFW	C0A48
	DEFW	C0A98
	DEFW	C0A71
	DEFW	C0AD6
	DEFW	C0AE3
	DEFW	C0AF0
	DEFW	C0AFD

C09E5:	XOR	A
	LD	(D.FCB0),A
	CALL	C0B22
	LD	A,(D.F3AE)
	LD	(D.F3B0),A
	LD	HL,I0800
	LD	(D.F3B5),HL
	LD	HL,(D.F3B3)
	LD	(D.F922),HL
	LD	HL,(D.F3B7)
	CP	29H	; ")"
	JR	C,J0A08
	LD	HL,I1000
J0A08:	LD	(D.F924),HL
	CALL	C0B42
J0A0E:	CALL	C0953
	CALL	C0864
	CALL	C078A
	JP	J0632


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0A1A:	LD	A,01H	; 1 
	LD	(D.FCB0),A
	CALL	C0B22
	LD	A,(D.F3AF)
	LD	(D.F3B0),A
	LD	HL,(D.F3BD)
	LD	(D.F922),HL
	LD	HL,(D.F3C1)
	LD	(D.F924),HL
	LD	HL,(D.F3C5)
	LD	(D.F926),HL
	LD	HL,(D.F3C3)
	LD	(D.F928),HL
	CALL	C0B9C
	CALL	C0714
	JR	J0A0E

C0A48:	LD	A,02H	; 2 
	CALL	C0B22
	LD	HL,(D.F3CD)
	CALL	C0A82
	PUSH	HL
	CALL	C0BD2
J0A57:	POP	HL
	CALL	C08E3
	XOR	A
	LD	B,03H	; 3 
J0A5E:	OUT	(98H),A
	INC	A
	JR	NZ,J0A5E
	DJNZ	J0A5E
	CALL	C0895
J0A68:	CALL	C0953
	CALL	C0714
	JP	J0632

C0A71:	LD	A,04H	; 4 
	CALL	C0B22
	LD	HL,I1E00
	CALL	C0A82
	PUSH	HL
	CALL	C0BD9
	JR	J0A57


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0A82:	LD	(D.F928),HL
	LD	HL,(D.F3CF)
	LD	(D.F926),HL
	LD	HL,(D.F3CB)
	LD	(D.F924),HL
	LD	HL,(D.F3C7)
	LD	(D.F922),HL
	RET

C0A98:	LD	A,03H	; 3 
	CALL	C0B22
	LD	HL,(D.F3D9)
	LD	(D.F926),HL
	LD	HL,(D.F3D7)
	LD	(D.F928),HL
	LD	HL,(D.F3D5)
	LD	(D.F924),HL
	LD	HL,(D.F3D1)
	LD	(D.F922),HL
	PUSH	HL
	CALL	C0C22
	POP	HL
	CALL	C08E3
	LD	DE,CPMADR
J0AC0:	LD	C,04H	; 4 
J0AC2:	LD	A,D
	LD	B,20H	; " "
J0AC5:	OUT	(98H),A
	INC	A
	DJNZ	J0AC5
	DEC	C
	JR	NZ,J0AC2
	LD	D,A
	DEC	E
	JR	NZ,J0AC0
	CALL	C08AD
	JR	J0A68

C0AD6:	LD	A,05H	; 5 
	LD	DE,07876H
	CALL	C0B14
	CALL	C0C56
	JR	J0B08

C0AE3:	LD	A,06H	; 6 
	LD	DE,07876H
	CALL	C0B14
	CALL	C0C80
	JR	J0B08

C0AF0:	LD	A,07H	; 7 
	LD	DE,0F0FAH
	CALL	C0B14
	CALL	C0C97
	JR	J0B08

C0AFD:	LD	A,08H	; 8 
	LD	DE,0F0FAH
	CALL	C0B14
	CALL	C0CC7
J0B08:	CALL	C0953
	CALL	C0811
	CALL	C0714
	JP	J0632


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0B14:	LD	L,00H
	LD	H,D
	LD	(D.F926),HL
	LD	H,E
	LD	(D.F928),HL
	LD	H,L
	LD	(D.F922),HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0B22:	LD	(D.FCAF),A
	XOR	A
	LD	(D.FAF5),A
	LD	(D.FAF6),A
	LD	HL,I0100
	LD	(D.F40B),HL
	LD	(D.F40D),HL
	CALL	C2980
	CALL	C063C
	LD	B,00H
	LD	C,17H
	JP	C0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0B42:	CALL	C0D2D
	LD	A,(D.F3B0)
	CP	29H	; ")"
	LD	B,00H
	JR	C,J0B50
	LD	B,04H	; 4 
J0B50:	LD	C,10H	; 16 
	CALL	C0D3F
	LD	A,(D.F3B0)
	CP	29H	; ")"
	LD	A,(D.FAF5)
	JR	NC,J0B72
	ADD	A,A
	LD	HL,(D.F3B7)
	LD	B,00H
	CALL	C0CE6
	ADD	A,A
	LD	HL,(D.F3B3)
	CALL	C0CDA
	JP	J06CA

J0B72:	LD	A,(D.FAF5)
	PUSH	AF
	ADD	A,A
	ADD	A,A
	LD	B,00H
	LD	HL,(D.F924)
	CALL	C0CE6
	ADD	A,A
	LD	B,03H	; 3 
	LD	HL,(D.F3B3)
	CALL	C0CDA
	POP	AF
	LD	HL,(D.F3B5)
	LD	E,00H
	SRL	A
	RR	E
	LD	D,A
	LD	B,07H	; 7 
	CALL	C0CF4
	JP	J06CA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0B9C:	CALL	C0D2D
	LD	BC,J0000
	CALL	C0D3F
	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	LD	HL,(D.F3C1)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0CE6
	LD	HL,(D.F3C5)
	CALL	C0D20
	LD	HL,(D.F3BD)
	ADD	A,A
	CALL	C0CDA
	LD	E,B
	LD	D,C
	LD	HL,(D.F3BF)
	CALL	C0CF4
	SRL	D
	RR	E
	LD	HL,(D.F3C3)
	JR	J0C1C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0BD2:	XOR	A
	PUSH	AF
	LD	BC,I0200
	JR	J0BE0


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0BD9:	LD	A,03H	; 3 
	OR	A
	PUSH	AF
	LD	BC,I0400
J0BE0:	CALL	C0D3F
	CALL	C0D2D
	LD	A,(D.FAF5)
	LD	C,A
	LD	B,03H	; 3 
	LD	HL,(D.F3CB)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0CE6
	LD	HL,(D.F3CF)
	CALL	C0D20
	LD	HL,(D.F3C7)
	ADD	A,A
	LD	B,00H
	CALL	C0CDA
	LD	E,B
	LD	D,C
	LD	B,7FH
	LD	HL,(D.F3C9)
	CALL	C0CF4
	SRL	D
	RR	E
	POP	AF
	LD	B,A
	LD	HL,(D.F3CD)
	JR	Z,J0C1C
	LD	HL,(D.F928)
J0C1C:	CALL	C0D0B
	JP	J06CA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0C22:	CALL	C0D2D
	LD	BC,C0008
	CALL	C0D3F
	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	LD	HL,(D.F3D5)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0CE6
	LD	HL,(D.F3D9)
	CALL	C0D20
	LD	HL,(D.F3D1)
	ADD	A,A
	LD	B,00H
	CALL	C0CDA
	LD	E,B
	LD	D,C
	SRL	D
	RR	E
	LD	B,00H
	LD	HL,(D.F3D7)
	JR	J0C1C


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0C56:	CALL	C0D36
	LD	BC,I0600
	CALL	C0D3F
J0C5F:	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	CALL	C0D1D
	LD	HL,(D.F922)
	ADD	A,A
	LD	B,1FH
	CALL	C0CDA
	LD	D,C
J0C76:	LD	E,00H
	LD	B,03H	; 3 
	CALL	C0D08
	JP	J06CA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0C80:	CALL	C0D36
	LD	BC,I0800
	CALL	C0D3F
	LD	HL,I0200
	LD	(D.F40B),HL
	LD	HL,DBUF
	LD	(D.F40D),HL
	JR	J0C5F


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0C97:	CALL	C0D36
	LD	BC,I0A00
	CALL	C0D3F
	LD	HL,I0200
	LD	(D.F40B),HL
	LD	HL,DBUF
	LD	(D.F40D),HL
J0CAC:	LD	A,(D.FAF5)
	LD	C,A
	LD	B,00H
	RRCA
	RRCA
	RRCA
	AND	0E0H
	CALL	C0D1D
	LD	HL,(D.F922)
	LD	B,1FH
	CALL	C0CDA
	LD	A,C
	ADD	A,A
	LD	D,A
	JR	J0C76


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0CC7:	CALL	C0D36
	LD	BC,I0E00
	CALL	C0D3F
	LD	A,(D.F3E1)
	SRL	A
	LD	(D.F3E1),A
	JR	J0CAC


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0CDA:	LD	L,A
	SRL	H
	SRL	H
	ADD	A,H
	OR	B
	LD	(D.F3E1),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0CE6:	LD	L,A
	SRL	H
	SRL	H
	SRL	H
	ADD	A,H
	OR	B
	LD	(D$F3E3),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0CF4:	PUSH	AF
	XOR	A
	ADD	HL,HL
	ADC	A,A
	ADD	HL,HL
	ADC	A,A
	LD	L,H
	LD	H,A
	ADD	HL,DE
	LD	A,L
	OR	B
	LD	(D$F3E2),A
	LD	A,H
	LD	(RG10SA),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D08:	LD	HL,(D.F928)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D0B:	PUSH	AF
	XOR	A
	ADD	HL,HL
	ADC	A,A
	LD	L,H
	LD	H,A
	ADD	HL,DE
	LD	A,L
	OR	B
	LD	(D$F3E4),A
	LD	A,H
	LD	(RG11SA),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D1D:	LD	HL,(D.F926)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D20:	LD	L,A
	SRL	H
	SRL	H
	SRL	H
	ADD	A,H
	LD	(D$F3E5),A
	LD	A,L
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D2D:	LD	A,(RG9SAV)
	AND	7FH
	LD	(RG9SAV),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D36:	LD	A,(RG9SAV)
	OR	80H
	LD	(RG9SAV),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0D3F:	LD	A,(D.F3DF)
	AND	0F1H
	OR	B
	LD	(D.F3DF),A
	LD	A,(D.F3E0)
	AND	0E7H
	OR	C
	LD	(D.F3E0),A
	RET

J0D52:	LD	A,0FFH
	CALL	C061D
	RET	NC
	PUSH	HL
	LD	A,(D.F3DC)
	LD	HL,D.F3B1
	CP	(HL)
	LD	A,0AH	; 10 
	JR	NZ,J0D65
	RST	18H
J0D65:	LD	A,(D.FBEB)
	RRCA
	LD	HL,I$F87F
	LD	A,01H	; 1 
	JR	C,J0D74
	LD	HL,I$F8CF
	XOR	A
J0D74:	LD	(D$FBCD),A
	CALL	C0DE2
	LD	C,05H	; 5 
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J0DA2
	CALL	C0DF0
	JR	C,J0D9A
J0D88:	PUSH	BC
	LD	C,00H
J0D8B:	CALL	C0DFE
	DJNZ	J0D8B
	LD	A,10H	; 16 
	SUB	C
	LD	C,A
	ADD	HL,BC
	INC	DE
	POP	BC
	DEC	C
	JR	NZ,J0D88
J0D9A:	LD	HL,(D.F3B1)
	CALL	C0ED7
	POP	HL
	RET

J0DA2:	PUSH	AF
	CALL	C0DF0
	POP	AF
	SUB	28H	; "("
J0DA9:	PUSH	BC
	LD	C,00H
J0DAC:	EX	AF,AF'
	CALL	C0DFE
	EX	AF,AF'
	DEC	A
	CALL	Z,C0DD2
	DJNZ	J0DAC
	DEC	A
	JR	NZ,J0DBE
	CALL	C0DD2
	DEC	DE
J0DBE:	EX	AF,AF'
	LD	A,10H	; 16 
	SUB	C
	LD	C,A
	ADD	HL,BC
	EX	AF,AF'
	INC	DE
	POP	BC
	DEC	C
	JR	NZ,J0DA9
	LD	HL,(D.F3B1)
	CALL	C0EF2
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DD2:	PUSH	BC
	PUSH	HL
	LD	HL,(D.F3B1)
	CALL	C0ED8
	CALL	C0DE2
	POP	HL
	POP	BC
	LD	A,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DE2:	LD	DE,D.FC18
	PUSH	DE
	LD	B,28H	; "("
	LD	A,20H	; " "
J0DEA:	LD	(DE),A
	INC	DE
	DJNZ	J0DEA
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DF0:	SUB	04H	; 4 
	RET	C
	LD	B,0FFH
J0DF5:	INC	B
	SUB	05H	; 5 
	JR	NC,J0DF5
	LD	A,B
	SUB	01H	; 1 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0DFE:	LD	A,(HL)
	INC	HL
I0E00:	INC	C
	CALL	C12A5
	JR	NC,C0DFE
	JR	NZ,J0E0C
	CP	20H	; " "
	JR	C,J0E0D
J0E0C:	LD	(DE),A
J0E0D:	INC	DE
	RET

J0E0F:	CALL	C0F00
	SUB	L
	RET	C
	JP	Z,J0EA9
	PUSH	HL
	PUSH	AF
	LD	C,A
	LD	B,00H
	CALL	C0F0A
	LD	L,E
	LD	H,D
	INC	HL
	LDIR
	LD	HL,I$FBCA
	DEC	(HL)
	POP	AF
	POP	HL
	PUSH	AF
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J0E43
	POP	AF
J0E33:	PUSH	AF
	INC	L
	CALL	C0EAE
	DEC	L
	CALL	C0ED7
	INC	L
	POP	AF
	DEC	A
	JR	NZ,J0E33
	JR	J0E5A

J0E43:	POP	AF
J0E44:	PUSH	AF
	INC	L
	CALL	C0EAF
	DEC	L
	CALL	C0ED8
	INC	L
	CALL	C0EC8
	DEC	L
	CALL	C0EF2
	INC	L
	POP	AF
	DEC	A
	JR	NZ,J0E44
J0E5A:	JP	J0EA9

J0E5D:	CALL	C0F00
	LD	H,A
	SUB	L
	RET	C
	JP	Z,J0EA9
	LD	L,H
	PUSH	HL
	PUSH	AF
	LD	C,A
	LD	B,00H
	CALL	C0F0A
	LD	L,E
	LD	H,D
	PUSH	HL
	DEC	HL
	LDDR
	POP	HL
	LD	(HL),H
	POP	AF
	POP	HL
	PUSH	AF
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J0E92
	POP	AF
J0E82:	PUSH	AF
	DEC	L
	CALL	C0EAE
	INC	L
	CALL	C0ED7
	DEC	L
	POP	AF
	DEC	A
	JR	NZ,J0E82
	JR	J0EA9

J0E92:	POP	AF
J0E93:	PUSH	AF
	DEC	L
	CALL	C0EAF
	INC	L
	CALL	C0ED8
	DEC	L
	CALL	C0EC8
	INC	L
	CALL	C0EF2
	DEC	L
	POP	AF
	DEC	A
	JR	NZ,J0E93
J0EA9:	LD	H,01H	; 1 
	JP	J0596


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0EAE:	DEFB	0F6H

C0EAF:	XOR	A
	PUSH	HL
	PUSH	AF
	LD	H,01H	; 1 
	CALL	C0F35
	POP	AF
	LD	A,(D.F3B0)
	JR	NZ,J0EBF
	SUB	28H	; "("
J0EBF:	LD	B,A
J0EC0:	LD	DE,D.FC18
	CALL	C0F22
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0EC8:	PUSH	HL
	LD	A,(D.F3B0)
	SUB	28H	; "("
	INC	A
	LD	H,A
	CALL	C0F35
	LD	B,28H	; "("
	JR	J0EC0


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0ED7:	DEFB	0F6H

C0ED8:	XOR	A
	PUSH	HL
	PUSH	AF
	LD	H,01H	; 1 
	CALL	C0F35
	POP	AF
	LD	A,(D.F3B0)
	JR	NZ,J0EE8
	SUB	28H	; "("
J0EE8:	LD	B,A
J0EE9:	EX	DE,HL
	LD	HL,D.FC18
	CALL	C0F2B
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0EF2:	PUSH	HL
	LD	A,(D.F3B0)
	SUB	27H	; "'"
	LD	H,A
	CALL	C0F35
	LD	B,28H	; "("
	JR	J0EE9


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F00:	LD	A,(D.F3DE)
	PUSH	HL
	LD	HL,D.F3B1
	ADD	A,(HL)
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F0A:	PUSH	HL
	LD	DE,I$FBB1
	LD	H,00H
	ADD	HL,DE
	LD	A,(HL)
	EX	DE,HL
	POP	HL
	AND	A
	RET

J0F16:	PUSH	HL
	CALL	C0F35
	CALL	C08E3
	LD	A,C
	OUT	(98H),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F22:	CALL	C08F1
	EX	DE,HL
	LD	C,98H
	INIR
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F2B:	EX	DE,HL
	CALL	C08E3
	EX	DE,HL
	LD	C,98H
	OTIR
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F35:	PUSH	BC
	DEC	H
	DEC	L
	LD	E,H
	LD	H,00H
	LD	D,H
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	LD	C,L
	LD	B,H
	ADD	HL,HL
	ADD	HL,HL
	LD	A,(D.FCAF)
	AND	A
	LD	A,(D.F3B0)
	JR	Z,J0F50
	SUB	22H	; """
	JR	J0F5D

J0F50:	CP	29H	; ")"
	JR	C,J0F5A
	ADD	HL,BC
	ADD	HL,HL
	SUB	52H	; "R"
	JR	J0F5D

J0F5A:	ADD	HL,BC
	SUB	2AH	; "*"
J0F5D:	ADD	HL,DE
	CPL
	AND	A
	RRA
	LD	E,A
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(D.F922)
	ADD	HL,DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0F6A:	PUSH	HL
	LD	D,A
	CALL	C0FF9
	CALL	C08F1
	EX	(SP),HL
	EX	(SP),HL
	IN	A,(98H)
	LD	B,A
	DEFB	0,0
	IN	A,(98H)
	LD	C,A
	POP	HL
	RET

J0F7E:	PUSH	HL
	LD	D,00H
	CALL	C0FF9
	CALL	C08F1
	LD	B,D
	LD	C,10H	; 16 
	CALL	C0647
	LD	B,10H	; 16 
J0F8F:	IN	A,(98H)
	NOP
	OUT	(9AH),A
	NOP
	IN	A,(98H)
	NOP
	OUT	(9AH),A
	NOP
	DJNZ	J0F8F
	POP	HL
	RET

J0F9F:	PUSH	HL
	LD	HL,I0FB3
	LD	B,10H	; 16 
	LD	D,00H
J0FA7:	LD	A,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	CALL	C0FD3
	INC	D
	DJNZ	J0FA7
	POP	HL
	RET

I0FB3:	DEFB	00H,00H,00H,00H,11H,06H,33H,07H
	DEFB	17H,01H,27H,03H,51H,01H,27H,06H
	DEFB	71H,01H,73H,03H,61H,06H,64H,06H
	DEFB	11H,04H,65H,02H,55H,05H,77H,07H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0FD3:	PUSH	BC
	PUSH	HL
	LD	B,D
	LD	C,10H	; 16 
	PUSH	AF
	CALL	C0647
	POP	AF
	LD	C,9AH
	OUT	(C),A
	PUSH	AF
	POP	AF
	OUT	(C),E
	CALL	C0FF9
	PUSH	AF
	CALL	C08E3
	EX	(SP),HL
	EX	(SP),HL
	POP	AF
	OUT	(98H),A
	PUSH	AF
	POP	AF
	LD	A,E
	OUT	(98H),A
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C0FF9:	PUSH	AF
	LD	A,(D.FCAF)
	LD	HL,I1020
I1000:	PUSH	BC
	INC	A
	LD	C,A
	LD	B,00H
	DEC	A
	JR	NZ,J1010
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	NC,J1010
	DEC	C
J1010:	ADD	HL,BC
	ADD	HL,BC
	POP	BC
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	PUSH	DE
	LD	E,D
	LD	D,00H
	ADD	HL,DE
	ADD	HL,DE
	POP	DE
	POP	AF
	RET

I1020:	DEFW	00400H
	DEFW	00F00H
	DEFW	02020H
	DEFW	01B80H
	DEFW	02020H
	DEFW	01B80H
	DEFW	07680H
	DEFW	07680H
	DEFW	0FA80H
	DEFW	0FA80H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1034:	LD	A,02H	; 2 
	CALL	C298B
	AND	40H	; "@"
	JR	NZ,C1034
J103D:	LD	A,02H	; 2 
	CALL	C298B
	AND	40H	; "@"
	JR	Z,J103D
	RET

J1047:	POP	AF
	RET

J1049:	PUSH	AF
	LD	A,B
	CP	21H	; "!"
	JR	C,J1047
	CP	28H	; "("
	JR	C,J105B
	CP	30H	; "0"
	JR	C,J1047
	CP	50H	; "P"
	JR	NC,J1047
J105B:	LD	A,C
	CP	21H	; "!"
	JR	C,J1047
	CP	7FH
	JR	NC,J1047
	POP	AF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	A,C
	SUB	20H	; " "
	LD	E,A
	LD	D,00H
	LD	A,B
	SUB	20H	; " "
	LD	L,A
	LD	H,D
	LD	C,L
	LD	B,H
	ADD	HL,HL
	ADD	HL,BC
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,HL
	ADD	HL,DE
	CP	10H	; 16 
	JR	C,J1084
	DEC	H
	DEC	H
J1084:	LD	A,L
	OUT	(0D8H),A
	ADD	HL,HL
	ADD	HL,HL
	LD	A,H
	OUT	(0D9H),A
	LD	BC,I20D9
	LD	HL,D.FC18
	INIR
	POP	AF
	PUSH	AF
	AND	A
	LD	C,02H	; 2 
	JR	Z,J10C5
	LD	HL,D.FC18
	LD	E,L
	LD	D,H
	DEC	A
	JR	Z,J10A4
	INC	HL
J10A4:	LD	C,02H	; 2 
J10A6:	LD	B,08H	; 8 
J10A8:	LD	A,(HL)
	LD	(DE),A
	INC	HL
	INC	HL
	INC	DE
	LD	A,B
	CP	05H	; 5 
	JR	NZ,J10B8
	PUSH	BC
	LD	BC,C0008
	ADD	HL,BC
	POP	BC
J10B8:	DJNZ	J10A8
	PUSH	BC
	LD	BC,-16
	ADD	HL,BC
	POP	BC
	DEC	C
	JR	NZ,J10A6
	LD	C,01H	; 1 
J10C5:	LD	HL,(D.FCB7)
	PUSH	HL
	LD	HL,(D.FCB9)
	PUSH	HL
	LD	DE,D.FC18
J10D0:	LD	HL,(D.FCB9)
	PUSH	HL
	LD	HL,(D.FCB7)
	PUSH	HL
	LD	B,02H	; 2 
J10DA:	PUSH	BC
	EX	DE,HL
	LD	DE,I.FC40
	LD	BC,C0008
	LDIR
	PUSH	HL
	CALL	C112D
	POP	DE
	POP	BC
	DJNZ	J10DA
	POP	HL
	LD	(D.FCB7),HL
	POP	HL
	PUSH	BC
	LD	BC,C0008
	ADD	HL,BC
	POP	BC
	LD	(D.FCB9),HL
	DEC	C
	JR	NZ,J10D0
	POP	HL
	LD	(D.FCB9),HL
	POP	HL
	LD	BC,C0010
	ADD	HL,BC
	LD	(D.FCB7),HL
I1109:	POP	AF
	POP	BC
	POP	DE
	POP	HL
	RET

J110E:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I1109
	PUSH	HL
	CALL	C12A5
	RET	NC
	JR	NZ,J1124
	CP	0DH	; 13 
	JP	Z,J1210
	CP	20H	; " "
	RET	C
J1124:	CALL	C07D9
	LD	A,(D.F3E9)
	LD	(D.F3F2),A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C112D:	LD	HL,(D.FCB9)
	EX	DE,HL
	LD	BC,(D.FCB7)
	CALL	C12C4
	RET	NC
	CALL	C1342
	LD	DE,I.FC40
	CALL	C2980
	PUSH	DE
	XOR	A
	CALL	C29DB
	CALL	C1376
	LD	E,A
	CALL	C29A5
	LD	A,E
	SUB	0CDH
	LD	L,08H	; 8 
	JR	C,J115A
	LD	L,A
	LD	A,07H	; 7 
	SUB	L
	LD	L,A
J115A:	LD	B,L
	LD	DE,C0008
	LD	H,D
	CALL	C29C4
	POP	DE
	LD	A,(D.F3F2)
	LD	L,A
	LD	A,(D.F3EA)
	LD	H,A
	LD	A,(DE)
	ADD	A,A
	LD	C,A
	LD	A,H
	JR	NC,J1172
	LD	A,L
J1172:	CALL	C29EB
	LD	A,(LOGOPR)
	AND	0FH
	OR	0B0H
	CALL	C29E3
	DI
	LD	A,0ACH
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,C
	LD	C,9BH
	DI
	JR	J11A3

J118E:	DI
	LD	A,0ACH
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	INC	DE
	LD	A,(DE)
	RLCA
	JR	NC,J11A1
	OUT	(C),L
	JP	J11A3

J11A1:	OUT	(C),H
J11A3:	RLCA
	JR	NC,J11AB
	OUT	(C),L
	JP	J11AD

J11AB:	OUT	(C),H
J11AD:	RLCA
	JR	NC,J11B5
	OUT	(C),L
	JP	J11B7

J11B5:	OUT	(C),H
J11B7:	RLCA
	JR	NC,J11BF
	OUT	(C),L
	JP	J11C1

J11BF:	OUT	(C),H
J11C1:	RLCA
	JR	NC,J11C9
	OUT	(C),L
	JP	J11CB

J11C9:	OUT	(C),H
J11CB:	RLCA
	JR	NC,J11D3
	OUT	(C),L
	JP	J11D5

J11D3:	OUT	(C),H
J11D5:	RLCA
	JR	NC,J11DD
	OUT	(C),L
	JP	J11DF

J11DD:	OUT	(C),H
J11DF:	RLCA
	JR	NC,J11E7
	OUT	(C),L
	JP	J11E9

J11E7:	OUT	(C),H
J11E9:	EI
	DJNZ	J118E
	LD	A,(D.FCAF)
	AND	0FEH
	CP	06H	; 6 
	JR	Z,J1200
	LD	A,(D.FCB7)
	ADD	A,08H	; 8 
	JR	C,J1210
	LD	(D.FCB7),A
	RET

J1200:	LD	HL,(D.FCB7)
	LD	BC,C0008
	ADD	HL,BC
	LD	A,H
	AND	0FEH
	JR	NZ,J1210
	LD	(D.FCB7),HL
	RET

J1210:	LD	HL,J0000
	LD	(D.FCB7),HL
	LD	A,(D.FCB9)
	ADD	A,08H	; 8 
	CP	0D4H
	JR	C,J1220
	XOR	A
J1220:	LD	(D.FCB9),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1224:	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I1109
	PUSH	HL
	CALL	C12A5
	RET	NC
	JR	NZ,J123A
	CP	07H	; 7 
	JP	Z,J1A62
	CP	20H	; " "
	RET	C
J123A:	CALL	C07D9
	LD	DE,I.FC40
	PUSH	DE
	CALL	C2980
	XOR	A
	CALL	C29DB
	CALL	C1376
	CALL	C29A5
	LD	HL,C0008
	LD	DE,C0010
	CALL	C29C4
	POP	DE
	LD	HL,I0103
	LD	A,(DE)
	ADD	A,A
	LD	C,A
	LD	A,H
	JR	NC,J1262
	LD	A,L
J1262:	PUSH	AF
	CALL	C29EB
	LD	A,0B0H
	CALL	C29E3
	DI
	LD	A,0ACH
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	POP	AF
	OUT	(9BH),A
	LD	A,C
	LD	C,9BH
	LD	B,08H	; 8 
	PUSH	BC
	DEC	B
	JR	J1285

J1280:	INC	DE
	LD	A,(DE)
	PUSH	BC
	LD	B,08H	; 8 
J1285:	RLCA
	JR	NC,J1290
	OUT	(C),L
	PUSH	AF
	POP	AF
	OUT	(C),L
	JR	J1296

J1290:	OUT	(C),H
	PUSH	AF
	POP	AF
	OUT	(C),H
J1296:	DJNZ	J1285
	POP	BC
	DJNZ	J1280
	LD	HL,(D.F92A)
	LD	BC,C0010
	ADD	HL,BC
	JP	J1372


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C12A5:	PUSH	HL
	PUSH	AF
	LD	HL,I$FCA6
	XOR	A
	CP	(HL)
	LD	(HL),A
	JR	Z,J12BC
	POP	AF
	SUB	40H	; "@"
	CP	20H	; " "
	JR	C,J12BA
	ADD	A,40H	; "@"
J12B8:	CP	A
	SCF
J12BA:	POP	HL
	RET

J12BC:	POP	AF
	CP	01H	; 1 
	JR	NZ,J12B8
	LD	(HL),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C12C4:	CALL	C062C
	JP	NC,J1305
	PUSH	HL
	PUSH	BC
	LD	B,01H	; 1 
	EX	DE,HL
	LD	A,H
	ADD	A,A
	JR	NC,J12D8
	LD	HL,J0000
	JR	J12E0

J12D8:	LD	DE,I00C0
	RST	20H
	JR	C,J12E2
	EX	DE,HL
	DEC	HL
J12E0:	LD	B,00H
J12E2:	EX	(SP),HL
	LD	A,H
	ADD	A,A
	JR	NC,J12EC
	LD	HL,J0000
	JR	J12F4

J12EC:	LD	DE,I0100
	RST	20H
	JR	C,J12F6
	EX	DE,HL
	DEC	HL
J12F4:	LD	B,00H
J12F6:	POP	DE
	SRL	L
	SRL	L
	SRL	E
	SRL	E
	LD	A,B
	RRCA
	LD	C,L
	LD	B,H
	POP	HL
	RET

J1305:	PUSH	HL
	PUSH	BC
	LD	B,01H	; 1 
	EX	DE,HL
	LD	A,H
	ADD	A,A
	JR	NC,J1313
	LD	HL,J0000
	JR	J131B

J1313:	LD	DE,I00D4
	RST	20H
	JR	C,J131D
	EX	DE,HL
	DEC	HL
J131B:	LD	B,00H
J131D:	EX	(SP),HL
	LD	A,H
	ADD	A,A
	JR	NC,J1327
	LD	HL,J0000
	JR	J1339

J1327:	LD	A,(D.FCAF)
	AND	02H	; 2 
	LD	DE,I0200
	JR	NZ,J1334
	LD	DE,I0100
J1334:	RST	20H
	JR	C,J133B
	EX	DE,HL
	DEC	HL
J1339:	LD	B,00H
J133B:	LD	A,B
	RRCA
	LD	B,H
	LD	C,L
	POP	DE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1342:	CALL	C062C
	JR	C,J134F
	LD	H,B
	LD	L,C
	LD	A,E
	LD	(D.F92C),A
	JR	J1372

J134F:	PUSH	BC
	LD	A,C
	RRCA
	LD	A,0F0H
	JR	NC,J1358
	LD	A,0FH	; 15 
J1358:	LD	(D.F92C),A
	LD	A,C
	ADD	A,A
	ADD	A,A
	AND	0F8H
	LD	C,A
	LD	A,E
	AND	07H	; 7 
	OR	C
	LD	C,A
	LD	A,E
	RRCA
	RRCA
	RRCA
	AND	07H	; 7 
	LD	B,A
	LD	HL,(D.F3D5)
	ADD	HL,BC
	POP	BC
J1372:	LD	(D.F92A),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1376:	LD	A,(D.F92C)
	LD	HL,(D.F92A)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C137D:	LD	(D.F92C),A
	LD	(D.F92A),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1384:	CALL	C062C
	JP	NC,J13A1
	PUSH	BC
	PUSH	HL
	CALL	C1376
	LD	B,A
	CALL	C08D3
	INC	B
	DEC	B
	JP	P,J139C
	RRCA
	RRCA
	RRCA
	RRCA
J139C:	AND	0FH	; 15 
	POP	HL
	POP	BC
	RET

J13A1:	PUSH	HL
	LD	HL,(D.F92A)
	LD	A,(D.F92C)
	CALL	C2949
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C13AD:	CALL	C1E47
	RET	C
	LD	(D.F3F2),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C13B5:	PUSH	BC
	PUSH	DE
	PUSH	HL
	CALL	C062C
	LD	A,(D.F92C)
	LD	HL,(D.F92A)
	JR	C,J13CA
	CALL	C2961
	POP	HL
	POP	DE
	POP	BC
	RET

J13CA:	LD	B,A
	CALL	C08D6
	LD	C,A
	LD	A,B
	CPL
	AND	C
	LD	C,A
	LD	A,(D.F3F2)
	INC	B
	DEC	B
	JP	P,J13DF
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
J13DF:	OR	C
	CALL	C08CB
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C13E7:	PUSH	HL
	CALL	C062C
	CALL	C1376
	JP	C,J1466
	DEC	HL
	LD	A,H
	OR	A
	JP	M,J1471
	LD	(D.F92A),HL
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C13FC:	PUSH	HL
	CALL	C062C
	CALL	C1376
	JP	C,J1474
	LD	A,(D.F92C)
	CP	0D3H
	JR	NC,J1471
	INC	A
	LD	(D.F92C),A
	POP	HL
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1414:	CALL	C062C
	JP	C,J14AE
	LD	A,(D.F92C)
	OR	A
	SCF
	RET	Z
	DEC	A
	LD	(D.F92C),A
	OR	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1426:	PUSH	HL
	CALL	C1376
	AND	A
	LD	A,0FH	; 15 
	JP	M,J1460
	LD	A,L
	AND	0F8H
	CP	0F8H
	JR	NZ,J1443
	JR	J1471

J1439:	PUSH	HL
	CALL	C1376
	AND	A
	LD	A,0FH	; 15 
	JP	M,J1460
J1443:	PUSH	DE
	LD	DE,C0008
	LD	A,0F0H
	JR	J145B

J144B:	PUSH	HL
	CALL	C1376
	AND	A
	LD	A,0F0H
	JP	P,J1460
J1455:	PUSH	DE
	LD	DE,-8
	LD	A,0FH	; 15 
J145B:	ADD	HL,DE
	LD	(D.F92A),HL
	POP	DE
J1460:	LD	(D.F92C),A
	AND	A
	POP	HL
	RET

J1466:	AND	A
	LD	A,0F0H
	JP	P,J1460
	LD	A,L
	AND	0F8H
	JR	NZ,J1455
J1471:	SCF
	POP	HL
	RET

J1474:	PUSH	DE
	PUSH	HL
	LD	HL,(D.F3D5)
	LD	DE,I0500
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	20H
	JR	C,J148E
	LD	A,L
	INC	A
	AND	07H	; 7 
	JR	NZ,J148E
	SCF
	POP	DE
	POP	HL
	RET

J148C:	PUSH	HL
	PUSH	DE
J148E:	CALL	C1376
	INC	HL
	LD	A,L
	LD	DE,I00F8
	JR	J14A2

J1498:	PUSH	HL
	PUSH	DE
J149A:	CALL	C1376
	LD	A,L
	DEC	HL
	LD	DE,0FF08H
J14A2:	AND	07H	; 7 
	JR	NZ,J14A7
	ADD	HL,DE
J14A7:	LD	(D.F92A),HL
	AND	A
	POP	DE
	POP	HL
	RET

J14AE:	PUSH	HL
	PUSH	DE
	LD	HL,(D.F3D5)
	LD	DE,I0100
	ADD	HL,DE
	EX	DE,HL
	LD	HL,(D.F92A)
	RST	20H
	JR	NC,J149A
	LD	A,L
	AND	07H	; 7 
	JR	NZ,J149A
	SCF
	POP	DE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C14C7:	AND	A
	PUSH	AF
	LD	A,(D.FCAF)
	CP	08H	; 8 
	JR	Z,J14D8
	POP	AF
	CP	10H	; 16 
	CCF
J14D4:	LD	(D.FCB2),A
	RET

J14D8:	POP	AF
	JR	J14D4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C14DB:	LD	HL,J0000
	LD	C,L
	CALL	C062C
	JP	C,J1566
	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	HL,(D.F92A)
	LD	A,(D.F92C)
	LD	E,A
	LD	D,00H
	LD	A,(D.FCB2)
	CALL	C28E0
	JR	C,J14FF
	POP	DE
J14FA:	POP	BC
	POP	HL
	LD	D,H
	LD	E,H
	RET

J14FF:	POP	DE
	PUSH	HL
	LD	HL,(D.F92A)
	ADD	HL,DE
	POP	DE
	OR	A
	SBC	HL,DE
	JR	C,J14FA
	JR	Z,J14FA
	POP	BC
	POP	BC
	PUSH	HL
	EX	DE,HL
	LD	(D.F942),HL
	LD	A,(D.F92C)
	LD	(D.F944),A
	LD	E,A
	LD	D,00H
	LD	A,(D.FCB2)
	CALL	C28E4
	PUSH	AF
	JR	C,J1533
	LD	A,(D.FCAF)
	AND	02H	; 2 
	LD	HL,I01FF
	JR	NZ,J1533
	LD	HL,I00FF
J1533:	LD	(D.F92A),HL
	POP	AF
	JR	C,J153A
	INC	HL
J153A:	PUSH	HL
	EX	DE,HL
	LD	HL,(D.F942)
	EX	DE,HL
	OR	A
	SBC	HL,DE
	EX	(SP),HL
	PUSH	HL
	EX	DE,HL
	LD	A,(D.F944)
	LD	E,A
	LD	D,00H
	LD	A,(D.F3F2)
	CALL	C28E0
	POP	DE
	JR	NC,J1561
	RST	20H
	JR	NC,J1561
	POP	DE
	LD	HL,(D.F942)
	CALL	C15DB
	POP	DE
	RET

J1561:	LD	C,00H
	POP	HL
	POP	DE
	RET

J1566:	CALL	C1633
	JR	NC,J1578
	DEC	DE
	LD	A,D
	OR	E
	RET	Z
	CALL	C1426
	JR	NC,J1566
	LD	DE,J0000
	RET

J1578:	CALL	C1376
	LD	(D.F942),HL
	LD	(D.F944),A
	LD	HL,J0000
J1584:	INC	HL
	CALL	C1426
	RET	C
	CALL	C1633
	JR	NC,J1584
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C158F:	LD	HL,J0000
	LD	C,L
	CALL	C062C
	JP	C,J1626
	CALL	C13E7
	RET	C
	LD	HL,(D.F92A)
	PUSH	HL
	LD	A,(D.F92C)
	LD	E,A
	LD	D,00H
	LD	A,(D.FCB2)
	CALL	C28D8
	PUSH	AF
	JR	C,J15B3
	LD	HL,-1
J15B3:	INC	HL
	LD	(D.F92A),HL
	EX	DE,HL
	POP	HL
	EX	(SP),HL
	PUSH	HL
	OR	A
	SBC	HL,DE
	INC	HL
	EX	(SP),HL
	PUSH	DE
	LD	A,(D.F92C)
	LD	E,A
	LD	D,00H
	LD	A,(D.F3F2)
	CALL	C28DC
	JR	NC,J161B
	POP	DE
	POP	BC
	POP	AF
	PUSH	BC
	PUSH	DE
	JR	NC,J15D9
	RST	20H
	JR	C,J1621
J15D9:	POP	HL
	POP	DE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C15DB:	LD	A,24H	; "$"
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	LD	A,(D.F92C)
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	LD	A,E
	OUT	(9BH),A
	LD	A,D
	OUT	(9BH),A
	LD	A,01H	; 1 
	OUT	(9BH),A
	XOR	A
	OUT	(9BH),A
	LD	A,(D.F3F2)
	OUT	(9BH),A
	XOR	A
	OUT	(9BH),A
	LD	A,(D.FCAF)
	CP	08H	; 8 
	LD	A,80H
	JR	NZ,J1614
	LD	A,0C0H
J1614:	OUT	(9BH),A
	EI
	EX	DE,HL
	LD	C,0FFH
	RET

J161B:	POP	DE
	POP	HL
	POP	DE
	LD	C,00H
	RET

J1621:	POP	DE
	POP	HL
	LD	C,00H
	RET

J1626:	CALL	C13E7
	RET	C
	CALL	C1633
	JP	C,J1439
	INC	HL
	JR	J1626


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1633:	CALL	C1384
	LD	B,A
	LD	A,(D.FCB2)
	SUB	B
	SCF
	RET	Z
	LD	A,(D.F3F2)
	CP	B
	RET	Z
	CALL	C13B5
	LD	C,01H	; 1 
	AND	A
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1649:	EI
	LD	DE,I1660
	PUSH	HL
	LD	HL,PROCNM
	CALL	C16AD
	POP	HL
	RET	C
	SCF
	RET	NZ
	CALL	C165E
	EI
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C165E:	PUSH	DE
	RET

I1660:	DEFM	'MEMINI',00H
	DEFB	02H
	DEFM	'7MKILL',00H
	DEFM	'o'+80H
	DEFM	'8MNAME',00H
	DEFM	'F'
	DEFM	'9MFILES',00H
	DEFB	1BH
	DEFM	'8',0FFH

J1683:	PUSH	AF
	PUSH	HL
	LD	DE,I1699
	CALL	C16AD
	JR	C,J1695
	POP	AF
	POP	AF
	DEC	HL
	CALL	C165E
	AND	A
	RET

J1695:	POP	HL
	POP	AF
	SCF
	RET

I1699:	DEFM	'K'+80H
	DEFB	00H
	DEFM	'['+80H
	DEFB	16H
	DEFM	'DATE',00H
	DEFM	'a'+80H
	DEFB	16H
	DEFM	'KANJI',00H
	DEFB	95H
	DEFM	'!',0FFH


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C16AD:	PUSH	HL
	LD	A,(DE)
	INC	A
	JR	Z,J16C6
	CALL	C16C9
	JR	Z,J16BD
	INC	DE
	INC	DE
	INC	DE
	POP	HL
	JR	C16AD

J16BD:	LD	A,(HL)
	EX	(SP),HL
	EX	DE,HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	AND	A
	JR	C,J16FE
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C16C9:	LD	A,(DE)
	OR	A
	RET	Z
	CP	(HL)
	JR	NZ,J16D3
	INC	DE
	INC	HL
	JR	C16C9

J16D3:	LD	A,(DE)
	AND	A
	INC	DE
	JR	NZ,J16D3
	DEC	DE
	DEC	A
	RET

?16DB:	DEC	B
	LD	BC,I174B
	JR	J16E5

?16E1:	DEC	B
	LD	BC,I1767
J16E5:	JP	P,J0546			; illegal function call error
	RST	10H
	PUSH	BC
	CALL	C05D8			; locate variable
	CALL	C05D2			; check for string
	DEC	HL
	RST	10H
	JR	Z,J16FE
	RST	08H
	DEFB	","
	RST	08H
	DEFB	"A"
	EX	(SP),HL
	LD	BC,I000E
	ADD	HL,BC
	EX	(SP),HL
J16FE:	POP	BC
	PUSH	HL
	PUSH	DE
	PUSH	BC
	LD	A,08H	; 8 
	CALL	C05EA			; allocate temporary string
	LD	HL,(D$F699)
	POP	DE
	PUSH	HL
	LD	A,(DE)
	RLCA
	AND	01H	; 1 
	LD	B,A
	LD	C,04H	; 4 
	CALL	C194B
	LD	C,02H	; 2 
J1718:	LD	B,02H	; 2 
J171A:	LD	A,(DE)
	INC	A
	JR	Z,J1723
	DEC	A
	OUT	(0B4H),A
	IN	A,(0B5H)
J1723:	INC	DE
	EX	DE,HL
	ADD	A,(HL)
	EX	DE,HL
	DEC	DE
	DAA
	AND	0FH	; 15 
	OR	30H	; "0"
	LD	(HL),A
	INC	DE
	INC	DE
	INC	HL
	DJNZ	J171A
	INC	C
	DEC	C
	JR	Z,J173E
	LD	A,(DE)
	LD	(HL),A
	INC	DE
	INC	HL
	DEC	C
	JR	J1718

J173E:	CALL	C1947
	POP	DE
	POP	HL
	LD	(HL),08H	; 8 
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	HL
	RET

I174B:	DEFB	05H,00H,04H,00H,3AH,03H,00H,02H
	DEFB	00H,3AH,01H,00H,00H,00H,85H,00H
	DEFB	84H,00H,3AH,83H,00H,82H,00H,3AH
	DEFB	81H,00H,80H,00H
I1767:	DEFB	0CH,08H,0BH,00H,2FH,0AH,00H,09H
	DEFB	00H,2FH,08H,00H,07H,00H,0FFH,00H
	DEFB	0FFH,00H,2FH,0FFH
	DEFB	00H,0FFH,00H,2FH,88H,00H,87H,00H

J1783:	RST	10H
	PUSH	HL
	CALL	C1CF7
	LD	B,03H	; 3 
	LD	A,(D.FCB0)
	LD	C,A
	LD	A,(RG9SAV)
	RRCA
	RRCA
	AND	02H	; 2 
	OR	C
	CALL	C1A59
	LD	A,(D.F3B0)
	CALL	C1A50
	LD	A,(D.F3E9)
	CALL	C1A59
	LD	A,(D.F3EA)
	CALL	C1A59
	LD	A,(D.F3EB)
	CALL	C1A59
	LD	C,00H
	LD	A,(D.F3DE)
	OR	A
	JR	Z,J17BB
	SET	0,C
J17BB:	LD	A,(D.F3DB)
	OR	A
	JR	Z,J17C3
	SET	1,C
J17C3:	LD	A,(D.F417)
	OR	A
	JR	Z,J17CB
	SET	2,C
J17CB:	LD	A,(D.F3FC)
	LD	HL,I.F406
	CP	(HL)
	JR	Z,J17D6
	SET	3,C
J17D6:	LD	A,C
	JP	J1A8C

?17DA:	RST	08H
	DEFB	"("
	CALL	C180D
	LD	A,E
	PUSH	AF
	RST	08H
	DEFB	","
	CALL	C180D
	RST	08H
	DEFB	")"
	POP	AF
	AND	0FH	; 15 
	LD	D,A
	CALL	C17F8
	CALL	C1CF7
	LD	B,01H	; 1 
	LD	A,D
	JP	C1A50


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C17F8:	LD	A,E
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0F0H
	OR	D
I1800:	LD	D,A
	LD	(RG18SA),A
	DI
	OUT	(99H),A
	LD	A,92H
	EI
	OUT	(99H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C180D:	CALL	C0608			; evaluate integer operand
	PUSH	HL
	EX	DE,HL
	CALL	C25DC
	EX	DE,HL
	LD	HL,I0007
	RST	20H
	JR	NC,J1823
	LD	HL,0FFF7H
	RST	20H
	JP	NC,J0546		; illegal function call error
J1823:	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1825:	CALL	C05FC			; evaluate expression
	PUSH	HL
	CALL	C0614			; free temporary string with type check
	LD	A,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	POP	HL
	RET

J1833:	CP	0C5H
	JP	Z,J1783
	CP	0CBH
	JP	Z,J188A
	CP	0C0H
	JP	Z,J19A6
	LD	DE,I184F
	CALL	C16AD
	JP	C,J0540			; syntax error
	DEC	HL
	RST	10H
	PUSH	DE
	RET

I184F:	DEFM	'PAGE',00H
	DEFM	'1'+80H
	DEFB	1FH
	DEFM	'VIDEO'
J185B:	DEFB	00H
	DEFM	'/'+80H
	DEFM	'5ADJUST',00H
	DEFM	'Z'+80H
	DEFB	17H
	DEFM	'TITLE',00H
	DEFB	80H
	DEFB	19H
	DEFM	'PASSW','w'+80H
	DEFM	'D',00H
	DEFM	']'+80H
	DEFB	19H
	DEFM	'PROMPT'
	DEFB	00H
	DEFM	'a'+80H
	DEFB	19H
	DEFM	'DATE',00H
	DEFB	8EH
	DEFB	18H
	DEFB	0FFH

J188A:	RST	10H
	LD	A,3AH	; ":"
	LD	BC,I2F3E
	PUSH	AF
	CALL	C1825
	POP	IX
	CP	08H	; 8 
	JP	NZ,J0540		; syntax error
	PUSH	HL
	EX	DE,HL
	CALL	C195E
	JR	Z,J18A6
	CP	24H	; "$"
	JR	NC,J18C0
J18A6:	LD	B,A
	CALL	C1956
	JR	Z,J18B0
	CP	60H	; "`"
	JR	J18B2

J18B0:	CP	13H	; 19 
J18B2:	JR	NC,J18C0
	LD	C,A
	CALL	C1956
	JR	Z,J18BE
	CP	60H	; "`"
	JR	J18C0

J18BE:	CP	32H	; "2"
J18C0:	JP	NC,J0546		; illegal function call error
	LD	D,A
	POP	HL
	PUSH	IX
	DEC	HL
	RST	10H
	POP	IX
	LD	A,00H
	JR	Z,J18D9
	PUSH	IX
	RST	08H
	DEFB	","
	RST	08H
	DEFB	"A"
	POP	IX
	OR	01H	; 1 
J18D9:	PUSH	HL
	PUSH	AF
	PUSH	BC
	PUSH	DE
	JR	NZ,J18EA
	LD	BC,I0004
	CALL	C194B
	LD	BC,I0E00
	JR	J18F8

J18EA:	LD	BC,I0108
	CALL	C194B
	CALL	C196C
	JR	Z,J18FD
	LD	BC,I0D00
J18F8:	LD	A,0FH	; 15 
	CALL	C194D
J18FD:	POP	DE
	LD	B,00H
	CALL	C196C
	JR	NZ,J1907
	LD	B,07H	; 7 
J1907:	LD	A,D
	CALL	C1A50
	POP	DE
	POP	AF
	PUSH	AF
	JR	Z,J1915
	CALL	C196C
	JR	Z,J1941
J1915:	LD	A,E
	CALL	C1A50
	LD	A,D
	CALL	C196C
	JR	NZ,J193E
	PUSH	AF
	PUSH	BC
	BIT	4,A
	JR	Z,J1927
	ADD	A,02H	; 2 
J1927:	AND	03H	; 3 
	PUSH	AF
	LD	A,01H	; 1 
	CALL	C1CF9
	POP	AF
	LD	B,0BH	; 11 
	CALL	C1A59
	XOR	A
	CALL	C1CF9
	POP	BC
	POP	AF
	SUB	80H
	DAA
J193E:	CALL	C1A50
J1941:	POP	AF
	POP	HL
	LD	B,04H	; 4 
	JR	NZ,J1949

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1947:	LD	B,08H	; 8 
J1949:	LD	C,0FH	; 15 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C194B:	LD	A,0DH	; 13 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C194D:	OUT	(0B4H),A
	IN	A,(0B5H)
	AND	C
	OR	B
	OUT	(0B5H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1956:	PUSH	IX
	POP	AF
	CP	(HL)
	INC	HL
	JP	NZ,J0540		; syntax error

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C195E:	CALL	C1974
	RLCA
	RLCA
	RLCA
	RLCA
	AND	0F0H
	LD	E,A
	CALL	C1974
	OR	E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C196C:	PUSH	BC
	PUSH	IX
	POP	BC
	BIT	4,B
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1974:	LD	A,(HL)
	INC	HL
	SUB	30H	; "0"
	JR	C,J197D
	CP	0AH	; 10 
	RET	C
J197D:	JP	J0546			; illegal function call error

?1980:	CP	2CH	; ","
	JR	Z,J198B
	XOR	A
	CALL	C19EC
	DEC	HL
	RST	10H
	RET	Z
J198B:	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	RET	NZ
	DEC	A
	CP	04H	; 4 
	JR	NC,J197D
	PUSH	AF
	CALL	C1CF7
	LD	B,0BH	; 11 
	CALL	C1CD2
	AND	0CH	; 12 
	LD	C,A
	POP	AF
	OR	C
	DEC	B
	JP	C1A59

J19A6:	CALL	C1CF7
	LD	B,0AH	; 10 
	CALL	C1CD2
	PUSH	AF
	RST	10H
	CP	2CH	; ","
	JR	Z,J19C8
	RST	28H			; evaluate byte operand
	DEC	A
	CP	04H	; 4 
	JR	NC,J19CE
	RLCA
	RLCA
	AND	0CH	; 12 
	LD	B,A
	POP	AF
	AND	03H	; 3 
	OR	B
	PUSH	AF
	DEC	HL
	RST	10H
	JR	Z,J19D7
J19C8:	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	DEC	A
	CP	04H	; 4 
J19CE:	JP	NC,J0546		; illegal function call error
	LD	B,A
	POP	AF
	AND	0CH	; 12 
	OR	B
	PUSH	AF
J19D7:	LD	B,0AH	; 10 
	POP	AF
	JP	C1A59

?19DD:	LD	A,01H	; 1 
	JR	J19E3

?19E1:	LD	A,02H	; 2 
J19E3:	CALL	C19EC
	DEC	HL
	RST	10H
	JP	NZ,J0540		; syntax error
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C19EC:	PUSH	AF
	CALL	C1825
	LD	C,A
	CALL	C1CF3
	LD	B,0CH	; 12 
	XOR	A
J19F7:	CALL	C1A59
	DEC	B
	DJNZ	J19F7
	POP	AF
	CALL	C1A59
	PUSH	HL
	EX	DE,HL
	DEC	A
	JR	Z,J1A17
	LD	E,06H	; 6 
J1A08:	DEC	C
	INC	C
	JR	Z,J1A15
	LD	A,(HL)
	INC	HL
	CALL	C1A50
	DEC	C
	DEC	E
	JR	NZ,J1A08
J1A15:	POP	HL
	RET

J1A17:	LD	A,21H	; "!"
	CALL	C1A50
	LD	A,03H	; 3 
	CALL	C1A59
	LD	A,C
	PUSH	AF
	CALL	C1CA5
	LD	B,04H	; 4 
	LD	A,E
	CALL	C1A50
	LD	A,D
	CALL	C1A50
	POP	AF
	LD	C,A
	XOR	A
	OUT	(7FH),A
	IN	A,(7FH)
	CP	0AAH
	JR	NZ,J1A15
	LD	A,C
	OR	A
	LD	A,01H	; 1 
	JR	Z,J1A42
	INC	A
J1A42:	CALL	C1A59
	PUSH	BC
	CALL	C1C97
	POP	BC
	LD	A,E
	CALL	C1A50
	LD	A,D
	POP	HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1A50:	PUSH	AF
	CALL	C1A59
	POP	AF
	RRCA
	RRCA
	RRCA
	RRCA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1A59:	PUSH	AF
	LD	A,B
	OUT	(0B4H),A
	INC	B
	POP	AF
	OUT	(0B5H),A
	RET

J1A62:	PUSH	HL
	CALL	C1AD0
	PUSH	AF
	DEC	B
	JR	Z,J1A90
	DEC	B
	JR	Z,J1AAD
	DEC	B
	JR	Z,J1ABC
	LD	E,55H	; "U"
	CALL	C1B11
	CALL	C1B1A
	CALL	C1B32
	LD	A,08H	; 8 
	CALL	C1B1E
	LD	BC,I07D0
	CALL	C1B28
J1A86:	CALL	C056B
	POP	AF
	LD	B,0DH	; 13 
J1A8C:	POP	HL
	JP	C1A59

J1A90:	LD	HL,I1B3E
	LD	E,0B8H
	CALL	C1B1C
	LD	E,0A7H
	LD	A,02H	; 2 
	CALL	C1B12
	LD	E,0A8H
	LD	A,04H	; 4 
	CALL	C1B12
	LD	E,0A6H
J1AA8:	CALL	C1AEA
	JR	J1A86

J1AAD:	LD	HL,I1B3E
	CALL	C1B1A
	LD	E,2AH	; "*"
	CALL	C1AEA
	LD	E,35H	; "5"
	JR	J1AA8

J1ABC:	LD	HL,I1B46
	CALL	C1B1A
	LD	E,6BH	; "k"
	CALL	C1AEA
	LD	E,47H	; "G"
	CALL	C1AEA
	LD	E,55H	; "U"
	JR	J1AA8


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1AD0:	LD	B,0DH	; 13 
	CALL	C1CD2
	PUSH	AF
	CALL	C1CF7
	LD	B,0AH	; 10 
	CALL	C1CD2
	LD	C,A
	RRCA
	RRCA
	AND	03H	; 3 
	LD	B,A
	LD	A,C
	AND	03H	; 3 
	LD	C,A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1AEA:	CALL	C1B11
	PUSH	BC
	PUSH	HL
	CALL	C1B32
	POP	HL
	PUSH	HL
	ADD	HL,BC
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
J1AF9:	LD	A,08H	; 8 
	CALL	C1B1E
	LD	A,09H	; 9 
	CALL	C1B1E
	LD	A,0AH	; 10 
	CALL	C1B1E
	CALL	C1B28
	DEC	E
	JR	NZ,J1AF9
	POP	HL
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1B11:	XOR	A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1B12:	CALL	C1B1E
	LD	E,00H
	INC	A
	JR	C1B1E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1B1A:	LD	E,0BEH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1B1C:	LD	A,07H	; 7 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1B1E:	DI
	OUT	(0A0H),A
	PUSH	AF
	LD	A,E
	EI
	OUT	(0A1H),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1B28:	PUSH	BC
J1B29:	DEC	BC
	EX	(SP),HL
	EX	(SP),HL
	LD	A,B
	OR	C
	JR	NZ,J1B29
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1B32:	LD	B,00H
	LD	HL,I1B3A
	ADD	HL,BC
	LD	E,(HL)
	RET

I1B3A:	DEFB	04H,07H,0AH,0FH
I1B3E:	DEFW	010D8H
	DEFW	009A0H
	DEFW	006BDH
	DEFW	0047EH
I1B46:	DEFW	0059DH
	DEFW	00335H
	DEFW	0023FH
	DEFW	0017FH

J1B4E:	CALL	C05AE			; fresh line to interpreter output
	CALL	C1CF3
	CALL	C1CD0
	CP	02H	; 2 
	LD	HL,I3FD7
	JP	NZ,C05F6		; message to interpreter output
J1B5F:	CALL	C1CDB
	JR	Z,J1B6A
	RST	18H
	LD	A,B
	CP	0DH	; 13 
	JR	C,J1B5F
J1B6A:	JP	J05A8			; newline to interpreter output

J1B6D:	CALL	C1C73
	LD	C,A
	CPL
	CALL	C1C74
	CALL	C1C73
	CPL
	CP	C
	LD	A,C
	CALL	C1C74
	LD	HL,I1C64
	LD	C,04H
	JR	Z,J1B8A
	LD	HL,I1C68
	LD	C,02H
J1B8A:	PUSH	HL
	LD	A,(D.FAFC)
	AND	0F9H
	OR	C
	LD	(D.FAFC),A
	LD	HL,00090H
	LD	A,0B4H
	CALL	C1D2B
	LD	HL,I1C5E
	CALL	C1C4B
	POP	HL
	CALL	C1C4B
	LD	HL,I1C6C
	CALL	C1C4B
	XOR	A
	OUT	(99H),A
	OUT	(99H),A
	OUT	(99H),A
	LD	A,8EH
	OUT	(99H),A
	CALL	C1CF3
	CALL	C1CD0
	JR	Z,J1C35
	DEC	A
	RET	NZ
	CALL	C1CD2
	CP	01H	; 1 
	RET	NZ
	CALL	C1CD2
	CP	02H	; 2 
	RET	NZ
	CALL	C1CD2
	CP	03H	; 3 
	RET	NZ
	LD	B,08H	; 8 
	CALL	C1CD2
	JR	Z,J1BEF
	XOR	A
	OUT	(7FH),A
	IN	A,(7FH)
	CP	0AAH
	JR	NZ,J1BEF
	PUSH	BC
	CALL	C1C97
	POP	BC
	CALL	C1CEA
	RST	20H
	RET	Z
	JR	J1C00

J1BEF:	LD	A,06H	; 6 
	CALL	C0590
	AND	04H	; 4 
	JR	NZ,J1C00
	LD	A,07H	; 7 
	CALL	C0590
	AND	10H	; 16 
	RET	Z
J1C00:	LD	HL,I0032
	LD	A,0D0H
	CALL	C1D2B
	LD	HL,I1C54
	CALL	C1C4B
	LD	B,08H	; 8 
	CALL	C1CD2
	DEC	A
J1C14:	JR	Z,J1C14
J1C16:	LD	HL,D.F55E
	LD	B,0FFH
J1C1B:	CALL	C0565
	CP	0DH	; 13 
	JR	Z,J1C26
	LD	(HL),A
	INC	HL
	DJNZ	J1C1B
J1C26:	LD	A,0FFH
	SUB	B
	CALL	C1CA2
	LD	B,04H	; 4 
	CALL	C1CEA
	RST	20H
	RET	Z
	JR	J1C16

J1C35:	LD	HL,I00C8
	LD	A,L
	CALL	C1D2B
J1C3C:	CALL	C1CDB
	RET	Z
	CALL	C1224
	LD	A,B
	CP	0DH	; 13 
	JR	C,J1C3C
	JP	C0565


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C4B:	LD	A,(HL)
	INC	HL
	OR	A
	RET	Z
	CALL	C1224
	JR	C1C4B

I1C54:	DEFM	'Password:',00H
I1C5E:	DEFM	'VRAM:',00H
I1C64:	DEFM	'128',00H
I1C68:	DEFM	' 64',00H
I1C6C:	DEFM	'Kbytes',00H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C73:	DEFB	0F6H

C1C74:	SCF
	PUSH	AF
	LD	A,07H	; 7 
	OUT	(99H),A
	LD	A,8EH
	OUT	(99H),A
	LD	A,0FFH
	OUT	(99H),A
	POP	AF
	PUSH	AF
	LD	A,7FH
	JR	C,J1C8A
	LD	A,3FH	; "?"
J1C8A:	OUT	(99H),A
	EX	(SP),HL
	EX	(SP),HL
	POP	AF
	JR	C,J1C94
	IN	A,(98H)
	RET

J1C94:	OUT	(98H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1C97:	IN	A,(7FH)
	LD	L,A
	IN	A,(7FH)
	LD	H,A
	LD	(D.F55E),HL
	LD	A,02H	; 2 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CA2:	LD	HL,D.F55E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CA5:	LD	DE,J0000
	LD	C,A
	OR	A
	RET	Z
	SCF
J1CAC:	PUSH	AF
J1CAD:	LD	B,08H	; 8 
J1CAF:	POP	AF
	PUSH	AF
	JR	NC,J1CB5
	RLC	(HL)
J1CB5:	RL	E
	RL	D
	JR	NC,J1CC3
	LD	A,D
	XOR	80H
	LD	D,A
	LD	A,E
	XOR	05H	; 5 
	LD	E,A
J1CC3:	DJNZ	J1CAF
	INC	HL
	DEC	C
	JR	NZ,J1CAD
	POP	AF
	RET	NC
	OR	A
	LD	C,02H	; 2 
	JR	J1CAC


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CD0:	LD	B,00H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CD2:	LD	A,B
	OUT	(0B4H),A
	INC	B
	IN	A,(0B5H)
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CDB:	PUSH	DE
	CALL	C1CD2
	LD	D,A
	CALL	C1CD2
	RLCA
	RLCA
	RLCA
	RLCA
	OR	D
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CEA:	CALL	C1CDB
	LD	L,A
	CALL	C1CDB
	LD	H,A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CF3:	LD	A,03H	; 3 
	JR	C1CF9


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CF7:	LD	A,02H	; 2 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1CF9:	PUSH	BC
	PUSH	AF
	LD	B,0DH	; 13 
	CALL	C1CD2
	AND	0CH	; 12 
	POP	BC
	OR	B
	OUT	(0B5H),A
	POP	BC
	RET

J1D08:	CALL	C1D1A
	IN	A,(0B5H)
	AND	0FH	; 15 
	RET

J1D10:	PUSH	AF
	CALL	C1D1A
	POP	AF
	AND	0FH	; 15 
	OUT	(0B5H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1D1A:	LD	A,C
	PUSH	AF
	AND	30H	; "0"
	RRCA
	RRCA
	RRCA
	RRCA
	CALL	C1CF9
	POP	AF
	AND	0FH	; 15 
	OUT	(0B4H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1D2B:	LD	(D.F92A),HL
	LD	(D.F92C),A
	RET

J1D32:	LD	A,(HL)
	EX	(SP),HL
	CP	(HL)
	JP	NZ,J0540		; syntax error
	INC	HL
	EX	(SP),HL
J1D3A:	CALL	H.CHRG
	INC	HL
J1D3E:	LD	A,(HL)
	CP	3AH	; ":"
	RET	NC
	CP	20H	; " "
	JR	Z,J1D3A
	JR	NC,J1DB1
	OR	A
	RET	Z
	CP	0BH	; 11 
	JR	C,J1DAC
	CP	1EH
	JR	NZ,J1D57
	LD	A,(D.F668)
	OR	A
	RET

J1D57:	CP	10H	; 16 
	JR	Z,J1D8F
	PUSH	AF
	INC	HL
	LD	(D.F668),A
	SUB	1CH
	JR	NC,J1D94
	SUB	0F5H
	JR	NC,J1D6E
	CP	0FEH
	JR	NZ,J1D82
	LD	A,(HL)
	INC	HL
J1D6E:	LD	(D.F666),HL
	LD	H,00H
J1D73:	LD	L,A
	LD	(D.F66A),HL
	LD	A,02H	; 2 
	LD	(D.F669),A
	LD	HL,M46E6
	POP	AF
	OR	A
	RET

J1D82:	LD	A,(HL)
	INC	HL
	INC	HL
	LD	(D.F666),HL
	DEC	HL
	LD	H,(HL)
	JR	J1D73

?1D8C:	CALL	C1DB7
J1D8F:	LD	HL,(D.F666)
	JR	J1D3E

J1D94:	INC	A
	RLCA
	LD	(D.F669),A
	PUSH	DE
	PUSH	BC
	LD	DE,D.F66A
	CALL	C1DF0
	POP	BC
	POP	DE
	LD	(D.F666),HL
	POP	AF
	LD	HL,M46E6
	OR	A
	RET

J1DAC:	CP	09H	; 9 
	JP	NC,J1D3A
J1DB1:	CP	30H	; "0"
	CCF
	INC	A
	DEC	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1DB7:	LD	A,(D.F668)
	CP	0FH	; 15 
	JR	NC,J1DD1
	CP	0DH	; 13 
	JR	C,J1DD1
	LD	HL,(D.F66A)
	JR	NZ,J1DCE
	INC	HL
	INC	HL
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
J1DCE:	JP	C05DE			; convert to SGN and put in DAC

J1DD1:	LD	A,(D.F669)
	LD	(D.F663),A
	CP	02H	; 2 
	JR	NZ,J1DE1
	LD	HL,(D.F66A)
	LD	(D.F7F8),HL
J1DE1:	LD	HL,D.F66A
	LD	DE,I$F7F6
	LD	A,(D.F663)
	CP	04H	; 4 
	JR	NC,C1DF0
	INC	DE
	INC	DE

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1DF0:	LD	C,A
	LD	B,00H
	LDIR
	RET

J1DF6:	JP	Z,J1ED5
	CP	0EFH
	JP	Z,J1ECA
	CP	0C7H
I1E00:	JP	Z,J2040
	LD	DE,(D.F3E9)
	PUSH	DE
	CP	2CH	; ","
	JR	Z,J1E17
	RST	28H			; evaluate byte operand
	CALL	C1E40
	POP	DE
	LD	E,A
	PUSH	DE
	DEC	HL
	RST	10H
	JR	Z,J1E33
J1E17:	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1E28
	RST	28H			; evaluate byte operand
	CALL	C1E40
	POP	DE
	LD	D,A
	PUSH	DE
	DEC	HL
	RST	10H
	JR	Z,J1E33
J1E28:	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	CALL	C1E40
	LD	(D.F3EB),A
	DEC	HL
	RST	10H
J1E33:	EX	(SP),HL
	LD	(D.F3E9),HL
	LD	A,L
	LD	(D.F3F2),A
	CALL	C0953
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1E40:	CALL	C1E47
	RET	NC
	JP	J0546			; illegal function call error


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1E47:	PUSH	AF
	LD	A,(D.FCAF)
	CP	06H	; 6 
	JR	Z,J1E5B
	CP	08H	; 8 
	JR	Z,J1E58
	POP	AF
	CP	10H	; 16 
	CCF
	RET

J1E58:	POP	AF
	AND	A
	RET

J1E5B:	POP	AF
	CP	20H	; " "
	CCF
	RET	C
	CP	10H	; 16 
	JR	C,J1E67
	AND	0FH	; 15 
	RET

J1E67:	AND	03H	; 3 
	PUSH	BC
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	POP	BC
	RET

J1E70:	RST	10H
	LD	A,0FH	; 15 
	CALL	C1EDC
	PUSH	AF
	CALL	C0F6A
	PUSH	BC
	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1E98
	LD	A,07H	; 7 
	CALL	C1EDC
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	E,A
	POP	BC
	LD	A,B
	AND	0FH	; 15 
	OR	E
	LD	B,A
	PUSH	BC
	DEC	HL
	RST	10H
	CP	29H	; ")"
	JR	Z,J1EBA
J1E98:	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1EAC
	LD	A,07H	; 7 
	CALL	C1EDC
	POP	BC
	LD	C,A
	PUSH	BC
	DEC	HL
	RST	10H
	CP	29H	; ")"
	JR	Z,J1EBA
J1EAC:	RST	08H
	DEFB	","
	LD	A,07H	; 7 
	CALL	C1EDC
	POP	BC
	LD	A,B
	AND	0F0H
	OR	E
	LD	B,A
	PUSH	BC
J1EBA:	RST	08H
	DEFB	")"
	POP	BC
	LD	A,B
	LD	E,C
	POP	BC
	LD	D,B
	PUSH	AF
	CALL	C1034
	POP	AF
	CALL	C0FD3
	RET

J1ECA:	RST	10H
	CP	28H	; "("
	JR	Z,J1E70
	CP	8CH
	JR	Z,J1ED8
	RST	08H
	DEFB	094H
J1ED5:	JP	J0F9F

J1ED8:	RST	10H
	JP	J0F7E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1EDC:	PUSH	AF
	RST	28H			; evaluate byte operand
	POP	AF
	CP	E
	LD	A,E
	RET	NC
	JP	J0546			; illegal function call error

J1EE5:	CP	2CH	; ","
	JR	Z,J1F1D
	RST	28H			; evaluate byte operand
	CP	09H	; 9 
	JP	NC,J0546		; illegal function call error
	CP	05H	; 5 
	JR	C,J1F0E
	PUSH	AF
	LD	A,(D.FAFC)
	RRCA
	AND	03H	; 3 
	LD	C,A
	POP	AF
	CP	07H	; 7 
	PUSH	AF
	LD	A,C
	JR	NC,J1F08
	CP	01H	; 1 
	JR	C,J1F0A
	JR	J1F0D

J1F08:	CP	02H	; 2 
J1F0A:	JP	C,J0546			; illegal function call error
J1F0D:	POP	AF
J1F0E:	PUSH	HL
	CALL	C09BF
	LD	A,(D.F3B0)
	LD	E,A
	CALL	C2033
	POP	HL
	DEC	HL
	RST	10H
	RET	Z
J1F1D:	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F3A
	RST	28H			; evaluate byte operand
	CP	04H	; 4 
	JP	NC,J0546		; illegal function call error
	LD	A,(D.F3E0)
	AND	0FCH
	OR	E
	LD	(D.F3E0),A
	PUSH	HL
	CALL	C06F5
	POP	HL
	DEC	HL
	RST	10H
	RET	Z
J1F3A:	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F45
	RST	28H			; evaluate byte operand
	LD	(D.F3DB),A
	RET	Z
J1F45:	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F51
	CALL	C1F7A
	DEC	HL
	RST	10H
	RET	Z
J1F51:	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J1F5C
	RST	28H			; evaluate byte operand
	LD	(D.F417),A
	RET	Z
J1F5C:	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	CP	04H	; 4 
	JP	NC,J0546		; illegal function call error
	ADD	A,A
	BIT	1,A
	JR	Z,J1F6B
	SET	3,A
J1F6B:	AND	0CH	; 12 
	LD	B,A
	LD	A,(RG9SAV)
	AND	0F3H
	OR	B
	LD	C,09H	; 9 
J1F76:	LD	B,A
	JP	C0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1F7A:	RST	28H			; evaluate byte operand
	DEC	A
	CP	02H	; 2 
	JP	NC,J0546		; illegal function call error
	PUSH	HL
	LD	BC,BDOS
	AND	A
	LD	HL,D.F3FC
	JR	Z,J1F8C
	ADD	HL,BC
J1F8C:	LD	DE,I.F406
	LDIR
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C1F93:	PUSH	BC
	LD	B,A
	CALL	C062C
	JR	C,J1FAE
	CP	07H	; 7 
	LD	A,01H	; 1 
	JR	NC,J1FAD
	LD	A,(D.FAFC)
	AND	06H	; 6 
	CP	04H	; 4 
	LD	A,01H	; 1 
	JR	C,J1FAD
	LD	A,03H	; 3 
J1FAD:	CP	B
J1FAE:	LD	A,B
	POP	BC
	RET

?1FB1:	LD	DE,(D.FAF5)
	CP	2CH	; ","
	JR	Z,J1FC7
	PUSH	DE
	RST	28H			; evaluate byte operand
	POP	DE
	CALL	C1F93
J1FBF:	JP	C,J0546			; illegal function call error
	LD	E,A
	DEC	HL
	RST	10H
	JR	Z,J1FD2
J1FC7:	PUSH	DE
	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	POP	DE
	CALL	C1F93
	JR	C,J1FBF
	LD	D,A
J1FD2:	LD	(D.FAF5),DE
	PUSH	HL
	CALL	C2980
	CALL	C06A8
	POP	HL
	RET

J1FDF:	JP	Z,J0546			; illegal function call error
	LD	A,(D.FCB0)
	AND	A
	LD	A,E
	JR	Z,J1FEE
	CP	21H	; "!"
	JP	NC,J0546		; illegal function call error
J1FEE:	CP	29H	; ")"
	JR	C,J1FF7
	CP	51H	; "Q"
	JP	NC,J0546		; illegal function call error
J1FF7:	LD	A,(D.F3B0)
	CP	E
	RET	Z
	LD	A,0CH	; 12 
	RST	18H
J1FFF:	LD	A,E
I2000:	LD	(D.F3B0),A
	CALL	C2033
	LD	A,(D.FCB0)
	DEC	A
	LD	A,E
	JR	NZ,J2014
	LD	(D.F3AF),A
	LD	A,0CH	; 12 
	RST	18H
	RET

J2014:	LD	C,29H	; ")"
	LD	A,(D.F3AE)
	CP	C
	LD	A,E
	LD	(D.F3AE),A
	PUSH	AF
	LD	A,0CH	; 12 
	RST	18H
	POP	AF
	JR	C,J2028
	CP	C
	RET	NC
	LD	C,A
J2028:	CP	C
	RET	C
	PUSH	AF
	PUSH	HL
	XOR	A
	CALL	C09BF
	POP	HL
	POP	AF
	LD	E,A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2033:	SUB	0EH	; 14 
	JR	NC,C2033
	ADD	A,1CH
	CPL
	INC	A
	ADD	A,E
	LD	(D$F3B2),A
	RET

J2040:	CALL	C0626
	JP	C,J0546			; illegal function call error
	RST	10H
	CP	24H	; "$"
	JR	Z,J2065
	LD	A,1FH
	CALL	C2318
	PUSH	HL
	CALL	C0775
	EX	(SP),HL
	RST	08H
	DEFB	0EFH
	RST	28H			; evaluate byte operand
	AND	A
	JP	M,J0546			; illegal function call error
	LD	BC,C0010
	EX	(SP),HL
	CALL	C0977
	POP	HL
	RET

J2065:	RST	08H
	DEFB	"$"
	LD	A,1FH
	CALL	C2318
	PUSH	HL
	CALL	C0775
	EX	(SP),HL
	RST	08H
	DEFB	0EFH
	CALL	C05FC			; evaluate expression
	PUSH	HL
	CALL	C0614			; free temporary string with type check
	LD	A,(HL)
	CP	11H	; 17 
	JR	C,J2081
	LD	A,10H	; 16 
J2081:	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	POP	HL
	EX	(SP),HL
	AND	A
	LD	B,A
	EX	DE,HL
	CALL	NZ,C0F2B
	POP	HL
	RET

J208F:	RST	10H
	RST	28H			; evaluate byte operand
	CP	20H	; " "
	JP	NC,J0546		; illegal function call error
	LD	(D.F560),A
	PUSH	HL
	PUSH	AF
	CALL	C0775
	LD	(D.FC18),HL
	LD	DE,I.FC1A
	LD	B,10H	; 16 
	CALL	C0F22
	POP	AF
	PUSH	AF
	CALL	C076A
	LD	(D.F55E),HL
	POP	AF
	LD	B,A
	LD	A,20H	; " "
	SUB	B
	LD	B,A
	LD	(D.F561),A
	LD	DE,D.F562
	PUSH	DE
	CALL	C0F22
	POP	HL
	EX	(SP),HL
	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J20F5
	CALL	C059C			; evaluate complex graphic coordinatepair
	EX	(SP),HL
	LD	(HL),E
	INC	HL
	LD	A,B
	ADD	A,A
	LD	A,C
	LD	C,00H
	JR	NC,J20DA
	ADD	A,20H	; " "
	LD	C,80H
J20DA:	LD	(HL),A
	PUSH	HL
	LD	HL,I.FC1A
I20DF:	LD	B,10H	; 16 
J20E1:	LD	A,(HL)
	AND	7FH
	OR	C
	LD	(HL),A
	INC	HL
	DJNZ	J20E1
	CALL	C217A
	POP	HL
	INC	HL
	EX	(SP),HL
	DEC	HL
	RST	10H
	POP	BC
	JR	Z,J212E
	PUSH	BC
J20F5:	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J2119
	RST	28H			; evaluate byte operand
	AND	A
	JP	M,J0546			; illegal function call error
	PUSH	HL
	LD	HL,I.FC1A
	LD	C,A
	LD	B,10H	; 16 
J2107:	LD	A,(HL)
	AND	80H
	OR	C
	LD	(HL),A
	INC	HL
	DJNZ	J2107
	CALL	C217A
	POP	HL
	DEC	HL
	RST	10H
	POP	BC
	JR	Z,J212E
	PUSH	BC
J2119:	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	CALL	C077F
	LD	A,E
	JR	NC,J2129
	CP	40H	; "@"
	JP	NC,J0546		; illegal function call error
	ADD	A,A
	ADD	A,A
J2129:	EX	(SP),HL
	LD	(HL),A
	LD	B,H
	LD	C,L
	POP	HL
J212E:	PUSH	HL
	LD	A,(D.F560)
	SUB	1FH
	JR	Z,J216A
	LD	HL,(D.FC18)
	LD	A,(D.F561)
	LD	B,A
J213D:	LD	DE,C0010
	ADD	HL,DE
	PUSH	HL
	PUSH	BC
	LD	DE,I.FC1A
	LD	B,10H	; 16 
	CALL	C0F22
	CALL	C2187
	POP	BC
	POP	HL
	JR	Z,J2154
	DJNZ	J213D
J2154:	LD	A,(D.F561)
	SUB	B
	JR	Z,J216A
	LD	B,A
	LD	HL,D.F566
	LD	DE,(D.F562)
J2162:	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	INC	HL
	INC	HL
	DJNZ	J2162
J216A:	INC	A
	ADD	A,A
	ADD	A,A
	LD	B,A
	LD	HL,D.F562
	LD	DE,(D.F55E)
	CALL	C0F2B
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C217A:	LD	HL,I.FC1A
	LD	DE,(D.FC18)
	LD	B,10H	; 16 
	CALL	C0F2B
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2187:	LD	HL,I.FC1A
	LD	B,10H	; 16 
J218C:	LD	A,(HL)
	AND	40H	; "@"
	RET	NZ
	INC	HL
	DJNZ	J218C
	XOR	A
	RET

?2195:	DEC	B
	JP	M,J0540			; syntax error
	LD	A,(D.FCAF)
	CP	05H	; 5 
	JP	C,J0546			; illegal function call error
	RST	10H
	CP	2CH	; ","
	CALL	NZ,C059C		; evaluate complex graphic coordinatepair
	RST	08H
	DEFB	","
	CALL	C0608			; evaluate integer operand
	PUSH	DE
	CALL	C256F
	CALL	C2594
	DEC	HL
	RST	10H
	CP	2CH	; ","
	LD	A,00H
	JR	NZ,J21C2
	RST	10H
	RST	28H			; evaluate byte operand
	CP	03H	; 3 
	JP	NC,J0546		; illegal function call error
J21C2:	POP	BC
	JP	J1049

J21C6:	LD	A,2FH	; "/"
	CALL	C2318
	CP	08H	; 8 
	JR	C,J21DD
	JP	Z,J0546			; illegal function call error
	DEC	E
	DEC	A
	CP	18H
	JR	C,J21DD
	CP	20H	; " "
	JP	C,J0546			; illegal function call error
J21DD:	PUSH	DE
	RST	08H
	DEFB	0EFH
	RST	28H			; evaluate byte operand
	POP	BC
	JP	J1F76

J21E5:	RST	10H
	RST	08H
	DEFB	"("
	CALL	C0608
	RST	08H
	DEFB	")"
	PUSH	HL
	LD	A,D
	RLCA
	JR	C,J220E
	AND	A
	JR	NZ,J21F8
	LD	A,E
	CP	19H
J21F8:	JP	NC,J0546		; illegal function call error
	CP	09H	; 9 
	JR	NC,J2204
	LD	HL,D.F3DF
	JR	J2207

J2204:	LD	HL,RG8SAV-8-1
J2207:	ADD	HL,DE
	LD	A,(HL)
J2209:	CALL	C05E4			; byte to DAC
	POP	HL
	RET

J220E:	EX	DE,HL
	CALL	C25DC
	EX	DE,HL
	LD	HL,I0009
	RST	20H
	JP	C,J0546			; illegal function call error
	LD	A,E
	CALL	C298B
	JR	J2209

J2220:	LD	A,13H	; 19 
	CALL	C2318
	LD	D,00H
	PUSH	DE
	RST	08H
	DEFB	0EFH
	CALL	C0608			; evaluate integer operand
	CP	40H	; "@"
	JP	NC,J0546		; illegal function call error
	EX	(SP),HL
	PUSH	HL
	LD	C,E
	LD	B,D
	POP	HL
	LD	A,L
	PUSH	AF
	ADD	HL,HL
	EX	DE,HL
	LD	HL,I226F
	ADD	HL,DE
	LD	A,C
	AND	(HL)
	JR	NZ,J2246
	INC	HL
	LD	A,B
	AND	(HL)
J2246:	JP	NZ,J0546		; illegal function call error
	LD	HL,D.F3B3
	ADD	HL,DE
	LD	(HL),C
	INC	HL
	LD	(HL),B
	POP	AF
	LD	E,0FFH
J2253:	INC	E
	SUB	05H	; 5 
	JR	NC,J2253
	LD	A,(D.FCAF)
	CP	E
	CALL	Z,C2261
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2261:	DEC	A
	JP	M,C0B42
	JP	Z,C0B9C
	DEC	A
	JP	Z,C0BD2
	JP	C0C22

I226F:	DEFW	003FFH
	DEFW	0003FH
	DEFW	007FFH
	DEFW	0007FH
	DEFW	007FFH
	DEFW	003FFH
	DEFW	0003FH
	DEFW	007FFH
	DEFW	0007FH
	DEFW	007FFH
	DEFW	003FFH
	DEFW	01FFFH
	DEFW	01FFFH
	DEFW	0007FH
	DEFW	007FFH
	DEFW	003FFH
	DEFW	0003FH
	DEFW	007FFH
	DEFW	0007FH
	DEFW	007FFH

J2297:	RST	10H
	LD	A,2CH	; ","
	CALL	C2318
	CP	14H	; 20 
	JR	NC,J22C2
	PUSH	HL
J22A2:	CP	02H	; 2 
	JR	NZ,J22B2
	LD	A,(D.F3B0)
	CP	29H	; ")"
	JR	C,J22B2
	LD	HL,I1000
	JR	J22BD

J22B2:	LD	HL,D.F3B3
	LD	D,00H
	ADD	HL,DE
	ADD	HL,DE
	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
J22BD:	CALL	C05DE			; convert to SGN and put in DAC
	POP	HL
	RET

J22C2:	PUSH	HL
	SUB	19H
	JR	NC,J22D3
	ADD	A,0FH	; 15 
	LD	E,A
	CP	0DH	; 13 
	JR	NZ,J22A2
	LD	HL,(D22DE)
	JR	J22BD

J22D3:	LD	D,00H
	LD	E,A
	LD	HL,I22E0
	ADD	HL,DE
	LD	H,(HL)
	LD	L,D
	JR	J22BD

D22DE:	DEFW	01E00H

I22E0:	DEFB	000H,000H,000H,076H,078H,000H,000H,000H
	DEFB	076H,078H,000H,000H,000H,0FAH,0F0H,000H
	DEFB	000H,000H,0FAH,0F0H

J22F4:	CALL	C0602			; evaluate address operand
	PUSH	DE
	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	EX	(SP),HL
	CALL	C08CB
	LD	HL,J0000
	CALL	C08D6
	POP	HL
	RET

J2307:	CALL	C05B4			; convert address to integer
	CALL	C08D6
	PUSH	AF
	LD	HL,J0000
	CALL	C08D6
	POP	AF
	JP	C05E4			; byte to DAC


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2318:	PUSH	AF
	RST	08H
	DEFB	"("
	RST	28H
	POP	AF
	CP	E
	JP	C,J0546			; illegal function call error
	RST	08H
	DEFB	")"
	LD	A,E
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2325:	LD	A,(D.F663)
	CP	08H	; 8 
	JR	NC,J2331
	SUB	03H	; 3 
	OR	A
	SCF
	RET

J2331:	SUB	03H	; 3 
	OR	A
	RET

?2335:	CALL	C2325
	LD	HL,(D.F7F8)
	RET	M
	JP	Z,J0552			; type mismatch error
	JP	J05F0			; convert float (SGN or DBL) to integer

J2342:	CP	0C5H
	JP	Z,J3676
	LD	(D.F55E),HL
	CP	28H	; "("
	JR	Z,J23C3
	CALL	C24F6
	LD	(D.F562),DE
	LD	(D.F564),BC
	JR	NC,J238C
	DEC	HL
	RST	10H
	JP	Z,J254D
	CP	0D9H
	JR	NZ,J236F
	RST	10H
	CP	28H	; "("
	JR	NZ,J2378
	XOR	A
	LD	(D.F56F),A
	JR	J2372

J236F:	CALL	C252B
J2372:	PUSH	HL
	LD	HL,J30A8
	JR	J23A4

J2378:	CALL	C24F6
	JP	C,J254D
	LD	(D.F566),DE
	LD	(D.F568),BC
	PUSH	HL
	LD	HL,J306F
	JR	J23BD

J238C:	DEC	HL
	RST	10H
	CP	0D9H
	JR	NZ,J239D
	RST	10H
	CP	28H	; "("
	JR	NZ,J23AB
	XOR	A
	LD	(D.F56F),A
	JR	J23A0

J239D:	CALL	C252B
J23A0:	PUSH	HL
	LD	HL,J2F42
J23A4:	LD	(D.F560),HL
	POP	HL
	JP	J24A9

J23AB:	CALL	C24F6
	JP	NC,J0540		; syntax error
	LD	(D.F566),DE
	LD	(D.F568),BC
	PUSH	HL
	LD	HL,J307C
J23BD:	LD	(D.F560),HL
	JP	J24E4

J23C3:	PUSH	HL
	LD	HL,J2EB9
	LD	(D.F560),HL
	POP	HL
	CALL	C059C			; evaluate complex graphic coordinatepair
	PUSH	BC
	PUSH	DE
	RST	08H
	DEFB	0F2H
	CALL	C05A2
	DEC	HL
	RST	10H
	CP	0D9H
	LD	A,(D.FAF6)
	JR	Z,J23E1
	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
J23E1:	CALL	C1F93
	JP	C,J0546			; illegal function call error
	LD	(D$F565),A
	POP	DE
	POP	BC
	RST	08H
	DEFB	0D9H
	PUSH	HL
	CALL	C12C4
	LD	(D.F562),BC
	LD	A,E
	LD	(D.F564),A
	CALL	C25F1
	CALL	C12C4
	CALL	C25F1
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C25D5
	JR	NC,J240F
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J240F:	INC	HL
	LD	(D.F56A),HL
	CALL	C25E6
	JR	NC,J241C
	EX	AF,AF'
	OR	08H	; 8 
	EX	AF,AF'
J241C:	INC	HL
	LD	(D.F56C),HL
	EX	AF,AF'
	LD	(D.F56F),A
	EX	AF,AF'
	PUSH	BC
	PUSH	DE
	LD	BC,(D.F56A)
	LD	E,L
	LD	D,H
	CALL	C3376
	JP	C,J0546			; illegal function call error
	POP	DE
	POP	BC
	POP	HL
	DEC	HL
	RST	10H
	CP	28H	; "("
	JR	Z,J24A9
	CALL	C24F6
	LD	(D.F566),DE
	LD	(D.F568),BC
	JR	NC,J2450
	PUSH	HL
	LD	HL,J31B4
	JP	J24A4

J2450:	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	BC,(D.F56A)
	LD	DE,(D.F56C)
	CALL	C3052
	LD	A,00H
	ADD	A,A
	LD	E,A
	CALL	C253B
	DEC	B
	JR	Z,J248D
	DEC	B
	JR	Z,J2480
	LD	BC,I0003
	ADD	HL,BC
	LD	A,E
	ADC	A,00H
	SRL	A
	RR	H
	RR	L
	SRL	A
	RR	H
	RR	L
	JR	J248D

J2480:	LD	BC,I0001
	ADD	HL,BC
	LD	A,E
	ADC	A,00H
	SRL	A
	RR	H
	RR	L
J248D:	POP	DE
	ADD	HL,DE
	JR	C,J249E
	NOP
	LD	DE,I0004
	ADD	HL,DE
	JR	C,J249E
	NOP
	POP	DE
	EX	DE,HL
	AND	A
	SBC	HL,DE
J249E:	JP	C,J0546			; illegal function call error
	LD	HL,J2EDF
J24A4:	LD	(D.F560),HL
	JR	J24DE

J24A9:	CALL	C05A2			; evaluate simple graphic coordinatepair
	PUSH	HL
	CALL	C12C4
	LD	(D.F566),BC
	LD	A,E
	LD	(D.F568),A
	POP	HL
	XOR	A
	LD	(D.F569),A
	DEC	HL
	RST	10H
	LD	A,(D.FAF6)
	JR	Z,J24CE
	RST	08H
	DEFB	","
	CP	2CH	; ","
	LD	A,(D.FAF6)
	CALL	NZ,C060E		; evaluate byte operand
J24CE:	CALL	C1F93
	JP	C,J0546			; illegal function call error
	LD	(D.F569),A
	CALL	C2594
	LD	(D$F570),A
	PUSH	HL
J24DE:	CALL	C062C
	JP	C,J0546			; illegal function call error
J24E4:	LD	HL,I24F0
	PUSH	HL
	LD	HL,(D.F560)
	PUSH	HL
	LD	HL,D.F562
	RET

I24F0:	POP	HL
	JP	C,J0546			; illegal function call error
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C24F6:	PUSH	HL
	CALL	C05FC			; evaluate expression
	LD	A,(D.F663)
	CP	03H	; 3 
	JR	Z,J2523
	POP	HL
	LD	A,01H	; 1 
	LD	(D.F6A5),A
	CALL	C05D8			; locate variable
	JP	NZ,J0546		; illegal function call error
	LD	(D.F6A5),A
	PUSH	HL
	LD	H,B
	LD	L,C
	EX	DE,HL
	ADD	HL,DE
	DEC	HL
	PUSH	HL
	LD	A,(BC)
	ADD	A,A
	LD	L,A
	LD	H,00H
	INC	BC
	ADD	HL,BC
	EX	DE,HL
	POP	BC
	POP	HL
	AND	A
	RET

J2523:	PUSH	HL
	CALL	C0614			; free temporary string with type check
	POP	HL
	POP	DE
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C252B:	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	CP	04H	; 4 
	JP	NC,J0546		; illegal function call error
	ADD	A,A
	ADD	A,A
	LD	(D.F56F),A
	RST	08H
	DEFB	0D9H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C253B:	LD	B,01H	; 1 
	LD	A,(D.FCAF)
	CP	08H	; 8 
	RET	Z
	INC	B
	CP	05H	; 5 
	RET	Z
	CP	07H	; 7 
	RET	Z
	INC	B
	INC	B
	RET

J254D:	XOR	A
	LD	(D.F6A5),A
	LD	HL,(D.F55E)
	SCF
	RET

J2556:	PUSH	AF
	CALL	C05A2			; evaluate simple graphic coordinatepair
	POP	AF
	CALL	C2572
	CALL	C2594
	PUSH	HL
	CALL	C12C4
	JR	NC,J256D
	CALL	C1342
	CALL	C13B5
J256D:	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C256F:	LD	A,(D.F3E9)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2572:	PUSH	BC
	PUSH	DE
	LD	E,A
	CALL	C0620
	JP	C,J0546			; illegal function call error
	DEC	HL
	RST	10H
	JR	Z,J2586
	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J2586
	RST	28H			; evaluate byte operand
J2586:	LD	A,E
	PUSH	HL
	CALL	C13AD
	JP	C,J0546			; illegal function call error
	POP	HL
	POP	DE
	POP	BC
	JP	J1D3E


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2594:	LD	A,00H
	PUSH	DE
	LD	D,00H
	LD	E,A
	DEC	HL
	RST	10H
	JR	Z,J25CC
	RST	08H
	DEFB	","
	JP	Z,J054C			; missing operand error
	CP	2CH	; ","
	JR	Z,J25CC
	LD	E,A
	CP	54H	; "T"
	JR	Z,J25C4
	CP	0D9H
	JR	Z,J25BC
	INC	A
	JR	NZ,J25CB
	RST	10H
	RST	08H
	DEFB	08DH
	RST	08H
	DEFB	"D"
	LD	E,0F6H
	JR	J25C1

J25BC:	RST	10H
	RST	08H
	DEFB	"R"
	LD	E,0F7H
J25C1:	DEC	HL
	JR	J25C9

J25C4:	RST	10H
	JP	Z,J0540			; syntax error
	LD	E,A
J25C9:	LD	D,08H	; 8 
J25CB:	RST	10H
J25CC:	LD	A,E
	CALL	C27B6
	JP	C,J0540			; syntax error
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25D5:	LD	HL,(D.FCB3)
	AND	A
	SBC	HL,BC
J25DB:	RET	NC

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25DC:	XOR	A
	SUB	L
	LD	L,A
	SBC	A,H
	SUB	L
	LD	H,A
	XOR	A
	SUB	01H	; 1 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25E6:	LD	HL,(D.FCB5)
	AND	A
	SBC	HL,DE
	JR	J25DB


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25EE:	CALL	C12C4

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25F1:	CALL	C2600

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C25F4:	PUSH	HL
	PUSH	BC
	LD	HL,(D.FCB3)
	EX	(SP),HL
	LD	(D.FCB3),HL
	POP	BC
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2600:	PUSH	HL
	LD	HL,(D.FCB5)
	EX	DE,HL
	JR	J263A

J2607:	CALL	C059C			; evaluate complex graphic coordinatepair
	PUSH	BC
	PUSH	DE
	RST	08H
	DEFB	0F2H
	CALL	C05A2
	CALL	C256F
	POP	DE
	POP	BC
	DEC	HL
	RST	10H
	JR	Z,J263F
	RST	08H
	DEFB	","
	CP	2CH	; ","
	JR	Z,J263F
	RST	08H
	DEFB	"B"
	JR	Z,J2648
	CP	2CH	; ","
	JR	Z,J2648
	RST	08H
	DEFB	"F"
J262A:	CALL	C2594
	PUSH	HL
	CALL	C2898
J2631:	LD	HL,(D.FCB7)
	LD	(D.FCB3),HL
	LD	HL,(D.FCB9)
J263A:	LD	(D.FCB5),HL
	POP	HL
	RET

J263F:	CALL	C2594
	PUSH	HL
	CALL	C2823
	JR	J2631

J2648:	CALL	C2594
	PUSH	HL
	CALL	C27E7
	JR	J2631

J2651:	CALL	C059C			; evaluate complex graphic coordinatepair
	PUSH	BC
	PUSH	DE
	CALL	C256F
	LD	A,(D.F3F2)
	LD	E,A
	DEC	HL
	RST	10H
	JR	Z,J2664
	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
J2664:	LD	A,E
	AND	A
	CALL	C14C7
	JP	C,J0546			; illegal function call error
	POP	DE
	POP	BC
	PUSH	HL
	CALL	C27AD
	CALL	C1342
	LD	DE,I0001
	CALL	C277E
	JR	Z,J2691
	PUSH	HL
	CALL	C278F
	POP	DE
	ADD	HL,DE
	EX	DE,HL
	XOR	A
	CALL	C275B
	LD	A,40H	; "@"
	CALL	C275B
	LD	B,0C0H
	JR	J26B3

J2691:	POP	HL
	RET

J2693:	LD	A,(D$FC9B)
	OR	A
	CALL	NZ,C0589
	LD	A,(D.F94A)
	OR	A
	JR	Z,J26AC
	LD	HL,(D.F94B)
	PUSH	HL
	LD	HL,(D.F949)
	PUSH	HL
	LD	HL,(D.F94D)
	PUSH	HL
J26AC:	POP	DE
	POP	BC
	POP	HL
	LD	A,C
	CALL	C137D
J26B3:	LD	A,B
	LD	(D.F953),A
	ADD	A,A
	JR	Z,J2691
	PUSH	DE
	JR	NC,J26C2
	CALL	C1414
	JR	J26C5

J26C2:	CALL	C13FC
J26C5:	POP	DE
	JR	C,J26AC
	CALL	C277E
	JP	Z,J26AC
	XOR	A
	LD	(D.F94A),A
	CALL	C278F
	LD	E,L
	LD	D,H
	OR	A
	JR	Z,J26F4
	DEC	HL
	DEC	HL
	LD	A,H
	ADD	A,A
	JR	C,J26F4
	LD	(D.F94D),DE
	CALL	C1376
	LD	(D.F94B),HL
	LD	(D.F949),A
	LD	A,(D.F953)
	CPL
	LD	(D.F94A),A
J26F4:	LD	HL,(D.F951)
	ADD	HL,DE
	EX	DE,HL
	CALL	C274F
	LD	HL,(D.F942)
	LD	A,(D.F944)
	CALL	C137D
J2705:	LD	HL,(D.F94F)
	LD	DE,(D.F951)
	OR	A
	SBC	HL,DE
	JR	Z,J274C
	JR	C,J272F
	EX	DE,HL
	LD	B,01H	; 1 
	CALL	C277E
	JR	Z,J274C
	OR	A
	JR	Z,J2705
	EX	DE,HL
	LD	HL,(D.F942)
	LD	A,(D.F944)
	LD	C,A
	LD	A,(D.F953)
	LD	B,A
	CALL	C2760
	JR	J2705

J272F:	CALL	C25DC
	DEC	HL
	DEC	HL
	LD	A,H
	ADD	A,A
	JR	C,J274C
	INC	HL
	PUSH	HL
	EX	DE,HL
	LD	HL,(D.F92A)
	OR	A
	SBC	HL,DE
	LD	(D.F92A),HL
	POP	DE
	LD	A,(D.F953)
	CPL
	CALL	C275B
J274C:	JP	J2693


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C274F:	LD	A,(D.F954)
	LD	C,A
	LD	A,(D.F955)
	OR	C
	RET	Z
	LD	A,(D.F953)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C275B:	LD	B,A
	CALL	C1376
	LD	C,A

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2760:	EX	(SP),HL
	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	C,02H	; 2 
	PUSH	HL
	LD	HL,(D.F6C6)
	LD	B,00H
	ADD	HL,BC
	ADD	HL,BC
	LD	A,88H
	SUB	L
	LD	L,A
	LD	A,0FFH
	SBC	A,H
	LD	H,A
	JR	C,J277B
	ADD	HL,SP
	POP	HL
	RET	C
J277B:	JP	J0558			; out of memory


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C277E:	CALL	C14DB
	LD	(D.F94F),DE
	LD	(D.F951),HL
	LD	A,H
	OR	L
	LD	A,C
	LD	(D.F955),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C278F:	CALL	C1376
	PUSH	HL
	PUSH	AF
	LD	HL,(D.F942)
	LD	A,(D.F944)
	CALL	C137D
	POP	AF
	POP	HL
	LD	(D.F942),HL
	LD	(D.F944),A
	CALL	C158F
	LD	A,C
	LD	(D.F954),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27AD:	PUSH	HL
	CALL	C12C4
	JP	NC,J0546		; illegal function call error
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27B6:	AND	A
	JR	Z,J27E2
	PUSH	BC
	LD	B,A
	CALL	C062C
	LD	A,B
	POP	BC
	RET	C
	CP	0F8H
	JR	Z,J27E0
	CP	0F7H
	JR	Z,J27DD
	CP	0F6H
	JR	Z,J27DA
	CP	0C3H
	JR	Z,J27D7
	CP	0C2H
	SCF
	RET	NZ
	XOR	A
	JP	NZ,J043E
J27D7	EQU	$-2
	JP	NZ,J013E
J27DA	EQU	$-2
	JP	NZ,J023E
J27DD	EQU	$-2
	JP	NZ,J033E
J27E0	EQU	$-2
J27E2:	OR	D
	LD	(LOGOPR),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C27E7:	CALL	C25EE
	CALL	C25EE
	CALL	C25D5
	JR	Z,C2823
	CALL	C,C25F4
	CALL	C25E6
	JR	Z,C2823
	CALL	C,C2600
	LD	HL,(D.FCB5)
	PUSH	HL
	PUSH	DE
	EX	DE,HL
	CALL	C2823
	POP	HL
	LD	(D.FCB5),HL
	EX	DE,HL
	CALL	C2823
	POP	HL
	DEC	HL
	INC	DE
	LD	(D.FCB5),HL
	LD	HL,(D.FCB3)
	PUSH	BC
	LD	C,L
	LD	B,H
	CALL	C2823
	POP	HL
	LD	(D.FCB3),HL
	LD	C,L
	LD	B,H

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2823:	PUSH	BC
	PUSH	DE
	PUSH	HL
	LD	HL,(D.FCB5)
	PUSH	HL
	LD	HL,(D.FCB3)
	PUSH	HL
	CALL	C25EE
	CALL	C12C4
	CALL	C25E6
	CALL	C,C25F1
	PUSH	DE
	PUSH	HL
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C25D5
	EX	DE,HL
	JR	NC,J2849
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J2849:	POP	HL
	RST	20H
	JR	C,J2852
	EX	DE,HL
	EX	AF,AF'
	OR	01H	; 1 
	EX	AF,AF'
J2852:	EX	(SP),HL
	CALL	C2980
	LD	A,24H	; "$"
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,C
	OUT	(9BH),A
	LD	A,B
	OUT	(9BH),A
	LD	A,L
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	LD	A,E
	OUT	(9BH),A
	LD	A,D
	OUT	(9BH),A
	POP	HL
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	LD	A,(D.F3F2)
	OUT	(9BH),A
	EX	AF,AF'
	OUT	(9BH),A
	LD	A,(LOGOPR)
	AND	0FH	; 15 
	OR	70H	; "p"
	OUT	(9BH),A
	EI
	POP	HL
	LD	(D.FCB3),HL
	POP	HL
	LD	(D.FCB5),HL
	POP	HL
	POP	DE
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2898:	CALL	C12C4
	LD	L,C
	LD	H,B
	LD	A,E
	CALL	C29A5
	CALL	C25F1
	CALL	C25EE
	EX	AF,AF'
	XOR	A
	EX	AF,AF'
	CALL	C25D5
	JR	NC,J28B3
	EX	AF,AF'
	OR	04H	; 4 
	EX	AF,AF'
J28B3:	INC	HL
	PUSH	HL
	CALL	C25E6
	JR	NC,J28BE
	EX	AF,AF'
	OR	08H	; 8 
	EX	AF,AF'
J28BE:	INC	HL
	POP	DE
	CALL	C29C4
	EX	AF,AF'
	CALL	C29DB
	EX	AF,AF'
	LD	A,(D.F3F2)
	CALL	C29EB
	LD	A,(LOGOPR)
	AND	0FH	; 15 
	ADD	A,80H
	CALL	C29E3

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28D8:	LD	B,04H	; 4 
	JR	J28E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28DC:	LD	B,06H	; 6 
	JR	J28E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28E0:	LD	B,02H	; 2 
	JR	J28E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C28E4:	LD	B,00H
J28E6:	PUSH	BC
	CALL	C2925
	POP	AF
	DI
	OUT	(99H),A
	LD	A,0ADH
	OUT	(99H),A
	LD	A,60H	; "`"
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	CALL	C2980
	AND	10H	; 16 
	RET	Z
	LD	A,08H	; 8 
	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	IN	A,(99H)
	LD	L,A
	LD	A,09H	; 9 
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	IN	A,(99H)
	PUSH	AF
	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	EI
	POP	AF
	AND	01H	; 1 
	LD	H,A
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2925:	PUSH	AF
	CALL	C2980
	LD	A,20H	; " "
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	LD	A,E
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0ACH
	OUT	(99H),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2949:	PUSH	DE
	CALL	C29A0
	XOR	A
	CALL	C29DB
	LD	A,40H	; "@"
	CALL	C29E3
	CALL	C2980
	LD	A,07H	; 7 
	CALL	C298B
	EI
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2961:	CALL	C29A5
	LD	A,2CH	; ","
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,(D.F3F2)
	OUT	(9BH),A
	XOR	A
	OUT	(9BH),A
	LD	A,(LOGOPR)
	AND	0FH	; 15 
	OR	50H	; "P"
	OUT	(9BH),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2980:	LD	A,02H	; 2 
	CALL	C298B
	EI
	RRCA
	JR	C,C2980
	RLCA
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C298B:	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
	POP	HL
	IN	A,(99H)
	PUSH	AF
	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	POP	AF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C29A0:	PUSH	AF
	LD	A,20H	; " "
	JR	J29A8


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C29A5:	PUSH	AF
	LD	A,24H	; "$"
J29A8:	PUSH	AF
	CALL	C2980
	DI
	POP	AF
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	POP	AF
	OUT	(9BH),A
	LD	A,(D.FAF6)
	OUT	(9BH),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C29C4:	LD	A,28H	; "("
	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	LD	A,E
	OUT	(9BH),A
	LD	A,D
	OUT	(9BH),A
	LD	A,L
	OUT	(9BH),A
	LD	A,H
	OUT	(9BH),A
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C29DB:	PUSH	AF
	DI
	OUT	(99H),A
	LD	A,0ADH
	JR	J29F1


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C29E3:	PUSH	AF
	DI
	OUT	(99H),A
	LD	A,0AEH
	JR	J29F1


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C29EB:	PUSH	AF
	DI
	OUT	(99H),A
	LD	A,0ACH
J29F1:	OUT	(99H),A
	EI
	POP	AF
	RET

I29F6:	DEFB	00H,20H,00H,00H,00H,00H,00H,00H
	DEFB	08H,00H,00H,00H,00H,00H,00H,00H
	DEFB	00H,00H,00H,00H,00H,3BH,05H,00H


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2A0E:	CALL	C2A14
	JP	J1B6D


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2A14:	CALL	C2B40
	DI
	LD	A,55H	; "U"
	LD	HL,J0000
	LD	BC,08000H
	CALL	C0977
	CALL	C2AFF
	LD	DE,I0705
	CALL	C2AC2
	LD	DE,I2D00
	CALL	C2AC2
	LD	D,2AH	; "*"
	CALL	C2AC2
	INC	D
	CALL	C2AC2
	LD	D,27H	; "'"
	CALL	C2AC2
	LD	E,37H	; "7"
	LD	HL,I2BF6
	EXX
	LD	HL,I2B6F
	EXX
	LD	DE,I0160
	CALL	C2AC2
	LD	A,0F0H
	LD	(D.F55E),A
J2A55:	DI
	CALL	C1034
	LD	A,(D.F55E)
	LD	B,A
	LD	C,17H
	CALL	C0647
	LD	A,B
	INC	A
	LD	(D.F55E),A
	EI
	LD	A,03H	; 3 
	PUSH	AF
	LD	BC,I002D
	LD	D,26H	; "&"
	CALL	C2AC2
	EXX
	LD	B,08H	; 8 
	LD	C,(HL)
	INC	HL
	EXX
J2A79:	CALL	C2AD8
	LD	A,(HL)
	INC	HL
	CP	0FEH
	JR	Z,J2AB9
	PUSH	HL
	PUSH	BC
	LD	BC,I01A6
	JR	NC,J2A8C
	LD	B,00H
	LD	C,A
J2A8C:	CALL	C2AD4
	POP	HL
	ADD	HL,BC
	LD	C,L
	LD	B,H
	POP	HL
	POP	AF
	XOR	03H	; 3 
	CALL	C2AE3
	PUSH	AF
	CALL	C2AEC
	EXX
	SLA	C
	DJNZ	J2AA7
	LD	B,08H	; 8 
	LD	C,(HL)
	INC	HL
J2AA7:	EXX
	JR	NC,J2A79
	DEC	BC
	CALL	C2AD8
	INC	BC
	LD	A,02H	; 2 
	CALL	C2AE3
	CALL	C2AFA
	JR	J2A79

J2AB9:	INC	E
	POP	AF
	LD	A,(HL)
	CP	0FEH
	JR	NZ,J2A55
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AC2:	PUSH	BC
	PUSH	AF
	DI
	LD	C,99H
	OUT	(C),E
	LD	A,D
	OR	80H
	EX	(SP),HL
	EX	(SP),HL
	OUT	(C),A
	EI
	POP	AF
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AD4:	LD	D,28H	; "("
	JR	J2ADA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AD8:	LD	D,24H	; "$"
J2ADA:	PUSH	DE
	LD	E,C
	CALL	C2AC2
	LD	E,B
	INC	D
	JR	J2AE7


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AE3:	PUSH	DE
	LD	E,A
	LD	D,2CH	; ","
J2AE7:	CALL	C2AC2
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AEC:	PUSH	DE
	LD	E,70H	; "p"
J2AEF:	LD	D,2EH	; "."
	CALL	C2AC2
	CALL	C2980
	DI
	POP	DE
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AFA:	PUSH	DE
	LD	E,50H	; "P"
	JR	J2AEF


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2AFF:	LD	A,02H	; 2 
	CALL	C1CF9
	LD	B,0BH	; 11 
	CALL	C1CD2
	RLCA
	RLCA
	AND	0CH	; 12 
	LD	C,A
	LD	B,00H
	LD	HL,I2B5F
	ADD	HL,BC
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	BC
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	LD	DE,I1000
	CALL	C2AC2
	CALL	C2B33
	POP	HL
	CALL	C2B33
	LD	HL,I0444
	CALL	C2B33
	LD	HL,I0777

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2B33:	PUSH	BC
	LD	C,9AH
	DI
	OUT	(C),L
	EX	(SP),HL
	EX	(SP),HL
	OUT	(C),H
	EI
	POP	BC
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2B40:	LD	B,08H	; 8 
	LD	HL,I2B4F
J2B45:	LD	D,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	CALL	C2AC2
	DJNZ	J2B45
	RET

I2B4F:	DEFB	00H,08H,01H,20H,08H,2AH,09H,00H
	DEFB	02H,1FH,05H,0F7H,0BH,00H,06H,0EH
I2B5F:	DEFB	07H,00H,00H,00H,20H,04H,27H,02H
	DEFB	72H,02H,56H,00H,70H,05H,70H,00H
I2B6F:	DEFB	00H,00H,00H,00H,00H,00H,00H,00H
	DEFB	00H,6EH,00H,9FH,00H,6FH,00H,9FH
	DEFB	00H,6FH,00H,9FH,00H,6FH,00H,9FH
	DEFB	00H,6FH,00H,9FH,00H,6FH,00H,9FH
	DEFB	00H,6FH,00H,0FFH,00H,07H,00H,0FCH
	DEFB	07H,00H,0F7H,00H,07H,00H,0F3H,00H
	DEFB	07H,00H,0F7H,00H,07H,00H,0FFH,00H
	DEFB	07H,00H,0FFH,00H,0FH,00H,0FCH,3CH
	DEFB	0FCH,3CH,0FCH,3CH,87H,0C0H,7BH,0C0H
	DEFB	87H,0C0H,7BH,0C0H,86H,0C0H,7BH,0C0H
	DEFB	86H,0C0H,7AH,0C0H,86H,0C0H,78H,0C0H
	DEFB	86H,90H,7AH,0F0H,86H,0F0H,7FH,0C0H
	DEFB	83H,0C0H,7FH,0C0H,0D7H,0C0H,2FH,0C0H
	DEFB	0D7H,0C0H,2FH,0C0H,0D7H,0C0H,2FH,0C0H
	DEFB	0D7H,0C0H,2FH,0C0H,0D7H,0C0H,2FH,0C0H
	DEFB	0D7H,0C0H,2FH,0C0H,0D5H,80H,00H,00H
	DEFB	00H,00H,00H,00H,00H,00H,00H
I2BF6:	DEFB	0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,44H,1DH,1DH,1CH,2FH,68H,2BH
	DEFB	28H,22H,0FEH,44H,1DH,1CH,1EH,2AH
	DEFB	6DH,29H,29H,22H,0FEH,43H,1FH,1BH
	DEFB	1EH,26H,73H,25H,29H,24H,0FEH,43H
	DEFB	1FH,1AH,20H,22H,77H,23H,29H,25H
	DEFB	0FEH,42H,21H,19H,20H,1FH,7CH,1FH
	DEFB	29H,27H,0FEH,42H,21H,18H,22H,1BH
	DEFB	80H,1DH,29H,28H,0FEH,41H,23H,17H
	DEFB	22H,19H,84H,1AH,28H,2AH,0FEH,41H
	DEFB	23H,16H,24H,17H,86H,17H,29H,2BH
	DEFB	0FEH,40H,25H,15H,24H,15H,8AH,14H
	DEFB	28H,2DH,0FEH,40H,25H,14H,26H,13H
	DEFB	8CH,11H,29H,2EH,0FEH,3FH,27H,13H
	DEFB	26H,12H,8FH,0EH,29H,2FH,0FEH,3FH
	DEFB	27H,12H,28H,10H,91H,0CH,28H,31H
	DEFB	0FEH,3EH,29H,11H,28H,0FH,94H,08H
	DEFB	29H,32H,0FEH,3EH,2AH,0FH,2AH,0DH
	DEFB	96H,06H,28H,34H,0FEH,3DH,2BH,0EH
	DEFB	2BH,0CH,99H,02H,29H,35H,0FEH,3DH
	DEFB	2CH,0DH,2CH,0BH,0C2H,37H,0FEH,3CH
	DEFB	2DH,0CH,2DH,0AH,26H,4CH,50H,38H
	DEFB	0FEH,3CH,2EH,0BH,2EH,09H,23H,51H
	DEFB	4CH,3AH,0FEH,3BH,2FH,0AH,2FH,09H
	DEFB	21H,54H,4AH,3BH,0FEH,3BH,30H,09H
	DEFB	30H,08H,20H,57H,46H,3DH,0FEH,3AH
	DEFB	31H,08H,31H,08H,21H,57H,44H,3EH
	DEFB	0FEH,3AH,32H,07H,32H,07H,23H,57H
	DEFB	41H,3FH,0FEH,39H,33H,06H,33H,07H
	DEFB	26H,55H,3EH,41H,0FEH,39H,34H,05H
	DEFB	34H,07H,47H,35H,3BH,42H,0FEH,38H
	DEFB	35H,04H,35H,07H,4BH,32H,38H,44H
	DEFB	0FEH
I2D00:	DEFB	38H,36H,03H,36H,07H,4EH,30H,35H
	DEFB	45H,0FEH,37H,37H,02H,37H,08H,50H
	DEFB	2EH,32H,47H,0FEH,37H,71H,08H
	DEFB	52H,2DH,2FH,48H,0FEH,36H,72H,09H
	DEFB	54H,2BH,2CH,4AH,0FEH,36H,73H,09H
	DEFB	55H,2BH,29H,4BH,0FEH,35H,74H,0AH
	DEFB	55H,29H,2AH,4BH,0FEH,35H,75H,0BH
	DEFB	55H,25H,2DH,4AH,0FEH,34H,76H,0CH
	DEFB	55H,23H,30H,48H,0FEH,34H,1FH,01H
	DEFB	37H,01H,1FH,0DH,54H,20H,33H,47H
	DEFB	0FEH,33H,20H,02H,36H,02H,1EH,10H
	DEFB	52H,1EH,36H,45H,0FEH,33H,1FH,03H
	DEFB	35H,03H,1FH,12H,50H,1BH,39H,44H
	DEFB	0FEH,32H,20H,04H,34H,04H,1EH,15H
	DEFB	4EH,19H,3CH,42H,0FEH,32H,1FH,05H
	DEFB	33H,05H,1FH,18H,4AH,18H,3EH,41H
	DEFB	0FEH,31H,20H,06H,32H,06H,1EH,1CH
	DEFB	47H,15H,42H,3FH,0FEH,31H,1FH,07H
	DEFB	31H,07H,1FH,3CH,26H,14H,44H,3EH
	DEFB	0FEH,30H,20H,08H,30H,08H,1EH,40H
	DEFB	22H,12H,48H,3CH,0FEH,30H,1FH,09H
	DEFB	2FH,09H,1FH,41H,20H,11H,4AH,3BH
	DEFB	0FEH,2FH,20H,0AH,2EH,0AH,1EH,41H
	DEFB	20H,0FH,4EH,39H,0FEH,2FH,1FH,0BH
	DEFB	2DH,0BH,1FH,40H,20H,0EH,28H,01H
	DEFB	27H,38H,0FEH,2EH,20H,0CH,2CH,0CH
	DEFB	1EH,3EH,22H,0CH,29H,04H,27H,36H
	DEFB	0FEH,2EH,1FH,0DH,2BH,0DH,1FH,39H
	DEFB	26H,0BH,29H,06H,27H,35H,0FEH,2DH
	DEFB	20H,0EH,2AH,0EH,7DH,0AH,28H,0AH
	DEFB	27H,33H,0FEH,2DH,1FH,0FH,29H,0FH
	DEFB	7CH,09H,29H,0CH,27H,32H,0FEH,2CH
	DEFB	20H,10H,28H,10H,7BH,08H,28H,10H
	DEFB	27H,30H,0FEH,2CH,1FH,11H,27H,11H
	DEFB	7AH,07H,29H,12H,27H,2FH,0FEH,2BH
	DEFB	1FH,13H,25H,13H,78H,07H,28H,16H
	DEFB	27H,2DH,0FEH,2BH,1FH,13H,25H,13H
	DEFB	77H,06H,29H,18H,27H,2CH,0FEH,2AH
	DEFB	1FH,15H,23H,15H,75H,06H,28H,1CH
	DEFB	27H,2AH,0FEH,2AH,1FH,15H,23H,15H
	DEFB	74H,06H,27H,1FH,27H,29H,0FEH,29H
	DEFB	1FH,17H,21H,17H,71H,06H,28H,22H
	DEFB	27H,27H,0FEH,29H,1FH,17H,21H,17H
	DEFB	70H,06H,27H,25H,27H,26H,0FEH,28H
	DEFB	1FH,19H,1FH,19H,6DH,06H,28H,28H
	DEFB	27H,24H,0FEH,28H,1FH,19H,1FH,19H
	DEFB	6AH,08H,27H,2BH,27H,23H,0FEH,27H
	DEFB	1FH,1BH,1DH,1BH,66H,09H,28H,2EH
	DEFB	27H,21H,0FEH,27H,1FH,1BH,1DH,1BH
	DEFB	63H,0BH,27H,31H,27H,20H,0FEH,26H
	DEFB	1FH,1DH,1BH,1DH,5FH,0CH,28H,34H
	DEFB	27H,1EH,0FEH,26H,1FH,1DH,1BH,1DH
	DEFB	5BH,0EH,28H,37H,27H,1DH,0FEH,0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,0FFH,0FEH,0FFH,0FEH,0FFH,0FEH,0FFH
	DEFB	0FEH,0FEH

J2EB9:	LD	BC,(D.F56A)
	LD	DE,(D.F56C)
	CALL	C3376
	RET	C
	CALL	C2980
	LD	A,20H	; " "
	CALL	C336E
	LD	HL,D.F562
	LD	BC,I0E9B
	OTIR
	LD	A,(HL)
	AND	0FH	; 15 
	OR	90H
	OUT	(C),A
	EI
	AND	A
	RET

J2EDF:	CALL	C3320
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J2EFA
	JR	Z,J2F1B
	DEC	A
	JR	Z,J2EFA
J2EEE:	CALL	C3354
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J2EEE
	RET

J2EFA:	LD	D,02H	; 2 
	LD	(HL),00H
J2EFE:	CALL	C2F13
	CALL	C3354
	OR	(HL)
	LD	(HL),A
	DEC	BC
	LD	A,C
	OR	B
	JR	Z,J2F11
	DEC	D
	JR	NZ,J2EFE
	INC	HL
	JR	J2EFA

J2F11:	DEC	D
	RET	Z

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C2F13:	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	(HL),A
	AND	A
	RET

J2F1B:	LD	D,04H	; 4 
	LD	(HL),00H
J2F1F:	LD	A,(HL)
	ADD	A,A
	ADD	A,A
	LD	(HL),A
	CALL	C3354
	OR	(HL)
	LD	(HL),A
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J2F31
	OR	E
	JR	Z,J2F37
	DEC	E
J2F31:	DEC	D
	JR	NZ,J2F1F
	INC	HL
	JR	J2F1B

J2F37:	DEC	D
	RET	Z
	LD	A,(HL)
J2F3A:	ADD	A,A
	ADD	A,A
	DEC	D
	JR	NZ,J2F3A
	LD	(HL),A
	AND	A
	RET

J2F42:	CALL	C32C9
	RET	C
	CALL	C2980
	LD	A,20H	; " "
	CALL	C336E
	PUSH	BC
	LD	HL,D.F562
	LD	BC,I0E9B
	OTIR
	POP	BC
	LD	A,(HL)
	AND	0FH	; 15 
	OR	0B0H
	POP	HL
	PUSH	AF
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J2F92
	JR	Z,J2FD4
	DEC	A
	JR	Z,J2F92
	CALL	C336C
	LD	A,(D.F5A8)
	LD	E,A
	AND	A
	CALL	NZ,C33A2
	LD	A,(HL)
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J2F81:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	INC	HL
	LD	A,E
	AND	A
	CALL	NZ,C33A2
	JR	C,J2F81
	LD	A,(HL)
	OUT	(9BH),A
	JR	J2F81

J2F92:	CALL	C336C
	LD	D,0FH	; 15 
	LD	A,(D.F5A8)
	LD	E,A
	AND	A
	CALL	NZ,C33A2
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J2FAF:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	LD	A,E
	AND	A
	CALL	NZ,C33A2
	JR	C,J2FBE
	LD	A,(HL)
	AND	D
	OUT	(9BH),A
J2FBE:	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	LD	A,E
	AND	A
	CALL	NZ,C33A2
	JR	C,J2FAF
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
	JR	J2FAF

J2FD4:	CALL	C336C
	LD	D,03H	; 3 
	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C33A2
	LD	A,(HL)
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J2FEE:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J2FF7
	OR	E
	RET	Z
	DEC	E
J2FF7:	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C33A2
	JR	C,J3008
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
J3008:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J3011
	OR	E
	RET	Z
	DEC	E
J3011:	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C33A2
	JR	C,J3020
	LD	A,(HL)
	RRCA
	RRCA
	AND	D
	OUT	(9BH),A
J3020:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J3029
	OR	E
	RET	Z
	DEC	E
J3029:	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C33A2
	JR	C,J3036
	LD	A,(HL)
	AND	D
	OUT	(9BH),A
J3036:	DEC	BC
	LD	A,C
	OR	B
	JP	NZ,J303F
	OR	E
	RET	Z
	DEC	E
J303F:	INC	HL
	LD	A,(D.F5A8)
	AND	A
	CALL	NZ,C33A2
	JR	C,J2FEE
	LD	A,(HL)
	RLCA
	RLCA
	AND	D
	OUT	(9BH),A
	JP	J2FEE


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3052:	LD	HL,J0000
	LD	A,10H	; 16 
	AND	A
J3058:	PUSH	AF
	ADD	HL,HL
	JR	NC,J305F
	POP	AF
	SCF
	PUSH	AF
J305F:	EX	DE,HL
	ADD	HL,HL
	EX	DE,HL
	JR	NC,J306A
	ADD	HL,BC
	JR	NC,J306A
	POP	AF
	SCF
	PUSH	AF
J306A:	POP	AF
	DEC	A
	JR	NZ,J3058
	RET

J306F:	PUSH	HL
	CALL	C32BB
	POP	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	LD	E,00H
	JR	J3087

J307C:	PUSH	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	CALL	C32BB
	POP	HL
	LD	E,01H	; 1 
J3087:	PUSH	DE
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	EX	DE,HL
	AND	A
	SBC	HL,BC
	INC	HL
	POP	DE
	PUSH	DE
	CALL	C33C7
	POP	DE
	DEC	E
	PUSH	AF
	CALL	NZ,C3444
	POP	AF
	CALL	Z,C3433
	CALL	C3457
	AND	A
	RET

J30A8:	PUSH	HL
	CALL	C32BB
	LD	HL,J0000
	LD	E,L
	CALL	C33C7
	CALL	C3444
	LD	(D.F575),HL
	LD	DE,(D.F571)
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	DEC	HL
	CALL	C32C9
	JR	C,J30F3
	CALL	C2980
	LD	A,20H	; " "
	CALL	C336E
	PUSH	BC
	LD	HL,D.F562
	LD	BC,I0E9B
	OTIR
	POP	BC
	LD	A,(HL)
	AND	0FH	; 15 
	OR	0B0H
	LD	HL,I30F2
	EX	(SP),HL
	PUSH	AF
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J311C
	JP	Z,J315C
	DEC	A
	JR	Z,J311C
	JR	J30F9

I30F2:	AND	A
J30F3:	PUSH	AF
	CALL	C3457
	POP	AF
	RET

J30F9:	CALL	C336C
	CALL	C339D
	LD	A,(HL)
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J310A:	DEC	BC
	LD	A,C
	OR	B
	RET	Z
	INC	HL
	CALL	C3279
	CALL	C339D
	JR	C,J310A
	LD	A,(HL)
	OUT	(9BH),A
	JR	J310A

J311C:	CALL	C336C
	LD	D,00H
	CALL	C339D
	LD	A,(HL)
	RRCA
	RRCA
	RRCA
	RRCA
	AND	0FH	; 15 
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J3135:	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J313E
	OR	E
	RET	Z
	DEC	E
J313E:	CALL	C3279
	LD	A,D
	RRCA
	LD	A,(HL)
	INC	HL
	JR	C,J314C
	DEC	HL
	RRCA
	RRCA
	RRCA
	RRCA
J314C:	PUSH	AF
	CALL	C339D
	JR	C,J3159
	POP	AF
	AND	0FH	; 15 
	OUT	(9BH),A
	JR	J3135

J3159:	POP	AF
	JR	J3135

J315C:	CALL	C336C
	LD	D,00H
	CALL	C339D
	LD	A,(HL)
	RRCA
	RRCA
	AND	03H	; 3 
	OUT	(9BH),A
	POP	AF
	OUT	(99H),A
	LD	A,0AEH
	OUT	(99H),A
	EI
J3173:	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J317C
	OR	E
	RET	Z
	DEC	E
J317C:	CALL	C3279
	LD	A,D
	AND	03H	; 3 
	JR	Z,J3197
	DEC	A
	JR	Z,J319F
	DEC	A
	JR	Z,J319A
	CALL	C339D
	JR	C,J3194
	LD	A,(HL)
	AND	03H	; 3 
	OUT	(9BH),A
J3194:	INC	HL
	JR	J3173

J3197:	LD	A,(HL)
	JR	J31A2

J319A:	LD	A,(HL)
	RRCA
	RRCA
	JR	J31A4

J319F:	LD	A,(HL)
	RLCA
	RLCA
J31A2:	RLCA
	RLCA
J31A4:	PUSH	AF
	CALL	C339D
	JR	C,J31B1
	POP	AF
	AND	03H	; 3 
	OUT	(9BH),A
	JR	J3173

J31B1:	POP	AF
	JR	J3173

J31B4:	PUSH	HL
	INC	HL
	INC	HL
	INC	HL
	INC	HL
	PUSH	HL
	CALL	C32BB
	LD	HL,J0000
	LD	E,01H	; 1 
	CALL	C33C7
	LD	DE,(D.F571)
	POP	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	POP	HL
	CALL	C3320
	LD	A,(D.FCAF)
	SUB	06H	; 6 
	JR	C,J31ED
	JR	Z,J3227
	DEC	A
	JR	Z,J31ED
J31DD:	CALL	C3292
	CALL	C3354
	LD	(HL),A
	INC	HL
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J31DD
	JP	J3270

J31ED:	LD	D,00H
J31EF:	CALL	C3292
	LD	A,07H	; 7 
	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
	POP	HL
	LD	A,D
	RRCA
	IN	A,(99H)
	JR	NC,J3208
	OR	(HL)
	LD	(HL),A
	INC	HL
	JR	J320D

J3208:	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	LD	(HL),A
J320D:	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	EI
	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J31EF
	OR	E
	JR	Z,J3221
	DEC	E
	JR	J31EF

J3221:	LD	A,D
	RRCA
	JR	C,J3271
	JR	J3270

J3227:	LD	D,00H
J3229:	CALL	C3292
	LD	A,07H	; 7 
	DI
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
	POP	HL
	LD	A,D
	AND	03H	; 3 
	JR	Z,J3249
	DEC	A
	JR	Z,J324F
	DEC	A
	IN	A,(99H)
	JR	Z,J3253
	OR	(HL)
	LD	(HL),A
	INC	HL
	JR	J3257

J3249:	IN	A,(99H)
	RRCA
	RRCA
	JR	J3256

J324F:	IN	A,(99H)
	RLCA
	RLCA
J3253:	RLCA
	RLCA
	OR	(HL)
J3256:	LD	(HL),A
J3257:	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	EI
	INC	D
	DEC	BC
	LD	A,C
	OR	B
	JR	NZ,J3229
	OR	E
	JR	Z,J326B
	DEC	E
	JR	J3229

J326B:	LD	A,D
	AND	03H	; 3 
	JR	NZ,J3271
J3270:	DEC	HL
J3271:	CALL	C32B0
	CALL	C3457
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3279:	PUSH	DE
	PUSH	HL
	LD	HL,(D.F571)
	LD	DE,(D.F575)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	20H
	POP	DE
	RET	C
	PUSH	BC
	PUSH	DE
	CALL	C3444
	LD	(D.F575),HL
	JR	J32AA


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3292:	PUSH	DE
	PUSH	HL
	LD	HL,(D.F571)
	LD	DE,(D.F573)
	ADD	HL,DE
	EX	DE,HL
	POP	HL
	RST	20H
	POP	DE
	RET	C
	LD	HL,(D.F573)
	PUSH	BC
	PUSH	DE
	CALL	C3436
	AND	A
J32AA:	POP	DE
	POP	BC
	LD	HL,(D.F571)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C32B0:	LD	DE,(D.F571)
	AND	A
	SBC	HL,DE
	INC	HL
	JP	C3436


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C32BB:	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	CALL	C05BA			; evaluate filespecification
	LD	A,D
	CP	09H	; 9 
	RET	C
	JP	J052E			; error 56


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C32C9:	LD	HL,(D.F562)
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	INC	HL
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	INC	HL
	CALL	C3376
	RET	C
	PUSH	HL
	PUSH	BC
	PUSH	DE
	LD	HL,(D.F566)
	LD	A,(D.F56F)
	AND	04H	; 4 
	JR	NZ,J32ED
	EX	DE,HL
	CALL	C3390
	AND	A
	SBC	HL,DE
	LD	A,23H	; "#"
J32ED	EQU	$-1
	LD	(D.F5A0),HL
	LD	(D.F5A2),HL
	LD	D,B
	LD	E,C
	EX	DE,HL
	SBC	HL,DE
	JR	NC,J32FE
	LD	HL,J0000
J32FE:	LD	(D.F5A4),HL
	LD	(D.F5A6),HL
	LD	A,H
	OR	L
	LD	(D.F5A8),A
	POP	DE
	POP	BC
	LD	(D.F56A),BC
	LD	(D.F56C),DE
	CALL	C3052
	LD	B,H
	LD	C,L
	LD	A,00H
	ADC	A,A
	LD	E,A
	AND	A
	POP	HL
	EX	(SP),HL
	JP	(HL)


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3320:	CALL	C2980
	LD	A,20H	; " "
	CALL	C336E
	LD	HL,D.F562
	LD	BC,I0E9B
	OTIR
	LD	A,0A0H
	OUT	(C),A
	EI
	LD	BC,(D.F56A)
	LD	DE,(D.F56C)
	LD	HL,(D.F566)
	LD	(HL),C
	INC	HL
	LD	(HL),B
	INC	HL
	LD	(HL),E
	INC	HL
	LD	(HL),D
	INC	HL
	PUSH	HL
	CALL	C3052
	LD	B,H
	LD	C,L
	LD	A,00H
	ADC	A,A
	LD	E,A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3354:	DI
	LD	A,07H	; 7 
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	PUSH	HL
	POP	HL
	IN	A,(99H)
	PUSH	AF
	XOR	A
	OUT	(99H),A
	LD	A,8FH
	OUT	(99H),A
	POP	AF
	EI
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C336C:	LD	A,0ACH

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C336E:	DI
	OUT	(99H),A
	LD	A,91H
	OUT	(99H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3376:	LD	A,B
	OR	C
	SCF
	RET	Z
	LD	A,D
	OR	E
	SCF
	RET	Z
	PUSH	HL
	PUSH	DE
	LD	E,C
	LD	D,B
	CALL	C3390
	RST	20H
	POP	DE
	POP	HL
	RET	C
	PUSH	HL
	LD	HL,I00D4
	RST	20H
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3390:	LD	HL,I0100
	LD	A,(D.FCAF)
	AND	06H	; 6 
	CP	06H	; 6 
	RET	NZ
	INC	H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C339D:	LD	A,(D.F5A8)
	AND	A
	RET	Z

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C33A2:	PUSH	HL
	LD	HL,(D.F5A2)
	LD	A,L
	OR	H
	JR	Z,J33B0
	DEC	HL
	LD	(D.F5A2),HL
	POP	HL
	RET

J33B0:	LD	HL,(D.F5A6)
	DEC	HL
	LD	A,L
	OR	H
	JR	NZ,J33C1
	LD	HL,(D.F5A0)
	LD	(D.F5A2),HL
	LD	HL,(D.F5A4)
J33C1:	LD	(D.F5A6),HL
	POP	HL
	SCF
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C33C7:	LD	A,(H.PHYD+0)
	CP	0C9H
	JP	Z,J0546			; illegal function call error
	PUSH	BC
	PUSH	HL
	LD	HL,I.F577
	PUSH	HL
	LD	(HL),D
	LD	A,E
	AND	A
	PUSH	AF
	EX	DE,HL
	INC	DE
	LD	HL,I.F866
	LD	BC,I000B
	LDIR
	XOR	A
	LD	B,19H
J33E6:	LD	(DE),A
	INC	DE
	DJNZ	J33E6
	POP	AF
	POP	DE
	PUSH	AF
	LD	C,0FH	; 15 
	JR	Z,J33F3
	LD	C,16H
J33F3:	CALL	C345C			; BDOS
	INC	A
	JR	NZ,J3401
	POP	AF
	JP	Z,J055E			; error 53
	LD	E,43H	; "C"
	JR	J3454

J3401:	LD	HL,I0001
	LD	(D$F585),HL
	POP	AF
	POP	HL
	POP	DE
	LD	A,H
	OR	L
	JR	NZ,J3428
	LD	HL,-256
	ADD	HL,SP
	JR	NC,J3421
	LD	DE,(D.F6C6)
	AND	A
	SBC	HL,DE
	JR	C,J3421
	LD	A,H
	AND	A
	JR	NZ,J3428
J3421:	LD	DE,(D$F862)
	LD	HL,I0100
J3428:	LD	(D.F571),DE
	LD	(D.F573),HL
	LD	C,1AH
	JR	C345C			; BDOS


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3433:	LD	HL,(D.F573)

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3436:	LD	DE,I.F577
	LD	C,26H	; "&"
	CALL	C345C			; BDOS
	AND	A
	RET	Z
	LD	E,42H	; "B"
	JR	J3454


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3444:	LD	HL,(D.F573)
	LD	DE,I.F577
	LD	C,27H	; "'"
	CALL	C345C			; BDOS
	LD	A,L
	OR	H
	RET	NZ
	LD	E,37H	; "7"
J3454:	JP	J05C6			; BASIC error


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3457:	LD	DE,I.F577
	LD	C,10H	; 16 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C345C:	LD	IX,M7FFD
	JP	C0262


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3463:	LD	B,00H
	AND	7FH
	LD	C,A
	SBC	HL,BC
	RET

J346B:	IN	A,(0BAH)
	CPL
	AND	08H	; 8 
	RET	Z
	LD	A,0FFH
	RET

J3474:	LD	HL,DFAFF
	XOR	A
	BIT	7,(HL)
	RET	Z
	RES	7,(HL)
	IN	A,(0BAH)
	AND	07H	; 7 
	LD	D,A
	IN	A,(0B8H)
	LD	L,A
	LD	H,00H
	IN	A,(0B9H)
	SRL	D
	RRA
	LD	E,A
	RL	H
	PUSH	HL
	PUSH	DE
	LD	BC,-3
	ADD	HL,BC
	EX	DE,HL
	LD	C,0EEH
	ADD	HL,BC
	LD	A,E
	OUT	(0B8H),A
	RR	D
	ADC	HL,HL
	LD	A,L
	OUT	(0B9H),A
	LD	A,H
	OUT	(0BAH),A
	POP	DE
	POP	HL
	IN	A,(0BAH)
	AND	20H	; " "
	RET	Z
	LD	A,(DFB01)
	CALL	C3463
	LD	BC,I00D3
	CALL	C34C7
	LD	A,L
	LD	(YSAVE),A
	EX	DE,HL
	LD	A,(DFAFF)
	CALL	C3463
	LD	BC,I00FF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C34C7:	LD	A,H
	RLA
	JR	C,J34D4
	PUSH	HL
	SBC	HL,BC
	POP	HL
	JR	C,J34D6
	LD	L,C
	LD	H,B
	JP	C,J002E
J34D4	EQU	$-2
J34D6:	LD	A,L
	LD	(XSAVE),A
	LD	A,0FFH
	RET

J34DD:	CP	08H	; 8 
	JR	Z,J3474
	CP	0BH	; 11 
	JR	Z,J346B
	LD	E,0FH	; 15 
	LD	BC,I00BF
	LD	HL,I10EF
	CP	0CH	; 12 
	JR	Z,J3509
	LD	BC,040FFH
	LD	HL,020DFH
	CP	10H	; 16 
	JR	Z,J3509
	AND	03H	; 3 
	SUB	02H	; 2 
	LD	A,(XSAVE)
	RET	M
	LD	A,(YSAVE)
	RET	Z
	XOR	A
	RET

J3509:	DI
	CALL	C357F
	CALL	C359A
	PUSH	AF
	CALL	C3585
	CALL	C3591
	PUSH	AF
	CALL	C357F
	CALL	C3597
	PUSH	AF
	CALL	C3585
	CALL	C3597
	PUSH	AF
	CALL	C357F
	CALL	C3597
	PUSH	AF
	CALL	C3585
	CALL	C3591
	PUSH	AF
	CALL	C357F
	CALL	C35AA
	CALL	C3585
	CALL	C35AA
	CALL	C357F
	EI
	POP	AF
	POP	HL
	POP	DE
	POP	BC
	XOR	08H	; 8 
	SUB	02H	; 2 
	CP	0DH	; 13 
	JR	C,J355D
	POP	AF
	CALL	C3577
	LD	(YSAVE),A
	POP	AF
	CALL	C3577
	JR	J3571

J355D:	LD	A,D
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	H
	NEG
	LD	(YSAVE),A
	POP	AF
	POP	DE
	ADD	A,A
	ADD	A,A
	ADD	A,A
	ADD	A,A
	OR	B
	NEG
J3571:	LD	(XSAVE),A
	LD	A,0FFH
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3577:	XOR	08H	; 8 
	BIT	3,A
	RET	Z
	OR	0F0H
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C357F:	CALL	C35A2
	AND	L
	JR	J3589


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3585:	CALL	C35A2
	OR	H
J3589:	PUSH	AF
	LD	A,E
	OUT	(0A0H),A
	POP	AF
	OUT	(0A1H),A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3591:	CALL	C35AA
	CALL	C35AA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3597:	CALL	C35AA

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C359A:	LD	A,0EH	; 14 
	CALL	C35A3
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C35A2:	LD	A,E

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C35A3:	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	C
	OR	B
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C35AA:	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	EX	(SP),HL
	RET

C35AF:	CP	","
	JR	Z,J35EF
	RST	28H			; evaluate byte operand
	CP	4
	JR	NC,J3635
	AND	A
	JR	Z,J35C2
	CP	1
	JR	Z,J35C2
	LD	E,0
	DEC	A
J35C2:	PUSH	DE
	RRCA
	RRCA
	LD	D,A
	RRCA
	RRCA
	LD	E,A
	LD	A,(RG9SAV)
	AND	0CFH
	OR	E
	LD	C,9
	CALL	C36B4
	LD	A,D
	XOR	0C0H
	LD	E,A			; b7,b6
	LD	A,3FH			; leave b5-b0
	CALL	C3661
	POP	DE
	LD	A,E
	RRCA
	RRCA
	RRCA
	LD	E,A
	LD	A,(RG8SAV)
	AND	0DFH
	OR	E
	CALL	C36B2
	DEC	HL
	RST	10H
	RET	Z
J35EF:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J3600
	CALL	C366C			; evaluate intensity parameter
	LD	A,0DFH			; leave b7,b6, b4-b0
	CALL	C3661
	DEC	HL
	RST	10H
	RET	Z
J3600:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J3617
	CALL	C366C			; evaluate color direction parameter
	RRC	E
	LD	A,(RG8SAV)
	AND	0EFH
	OR	E
	CALL	C36B2
	DEC	HL
	RST	10H
	RET	Z
J3617:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J362C
	CALL	C366C			; evaluate synchronization parameter
	RLCA
	RLCA
	RLCA
	LD	E,A			; b3
	LD	A,0F7H			; leave b7-b4, b2-b0
	CALL	C3661
	DEC	HL
	RST	10H
	RET	Z
J362C:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J3644
	RST	28H			; evaluate byte operand
	CP	4
J3635:	JP	NC,J0546		; illegal function call error
	CPL
	AND	03H
	LD	E,A			; b1, b0
	LD	A,0FCH			; leave b7-b2
	CALL	C3661
	DEC	HL
	RST	10H
	RET	Z
J3644:	RST	08H
	DEFB	","
	CP	","
	JR	Z,J3658
	CALL	C366C			; evaluate external videoinput parameter
	RLCA
	RLCA
	LD	E,A			; b2
	LD	A,0FBH			; leave b7-b3, b1-b0
	CALL	C3661
	DEC	HL
	RST	10H
	RET	Z
J3658:	RST	08H
	DEFB	","
	CALL	C366C			; evaluate external videooutput parameter
	RRC	E			; b4
	LD	A,0EFH			; leave b7-b5, b3-b0

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3661:	PUSH	HL
	LD	HL,D.FAF7
	AND	(HL)
	OR	E
	LD	(HL),A
	OUT	(0F7H),A
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C366C:	RST	28H			; evaluate byte operand
	CP	02H	; 2 
	JR	NC,J3635
	AND	A
	RET	Z
	LD	E,20H	; " "
	RET

J3676:	RST	10H
	JR	Z,J3686
	CP	2CH	; ","
	JR	Z,J3686
	CALL	C366C
	DEC	A
	JR	NZ,J3686
	LD	E,00H
	LD	BC,I021E
J3686	EQU	$-2
	DEC	HL
	RST	10H
	LD	A,0FFH
	JR	Z,J3693
	PUSH	DE
	RST	08H
	DEFB	","
	RST	28H			; evaluate byte operand
	POP	DE
J3693:	LD	D,A
	LD	A,(D$F3E6)
	PUSH	AF
	LD	A,D
	CALL	C36AE
	CALL	C36B8
	OR	40H	; "@"
	CALL	C36B4
	CALL	C36B8
	EI
	AND	0BFH
	CALL	C36B4
	POP	AF

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C36AE:	LD	C,07H	; 7 
	JR	C36B4


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C36B2:	LD	C,08H	; 8 

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C36B4:	LD	B,A
	JP	C0647


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C36B8:	LD	A,02H	; 2 
	CALL	C298B
	AND	40H	; "@"
	JR	Z,C36B8
J36C1:	LD	A,02H	; 2 
	CALL	C298B
	BIT	6,A
	JR	NZ,J36C1
	OR	E
	AND	02H	; 2 
	JR	Z,C36B8
	LD	A,(D.F3DF)
	LD	C,00H
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C36D5:	EI
	INC	A
	JR	NZ,J36DF
J36D9:	CALL	C392C
	RET	Z
	SCF
	RET

J36DF:	PUSH	HL
	LD	HL,I36ED
	ADD	A,L
	LD	L,A
	JR	NC,J36E8
	INC	H
J36E8:	LD	A,(HL)
	INC	HL
	LD	H,(HL)
	LD	L,A
	EX	(SP),HL
I36ED:	RET

?36EE:	DEFW	C3973
	DEFW	C39FA
	DEFW	C38B9
	DEFW	C3A1E
	DEFW	C3A7C
	DEFW	C3898
	DEFW	C38A3
	DEFW	C38B6
	DEFW	C38D7
	DEFW	C3AC8

?3702:	DEC	HL
	RST	10H
	LD	DE,07FFFH
	JR	Z,J3714
	RST	08H
	DEFB	"("
	CALL	C0608
	JP	M,J0546
	RST	08H
	DEFB	")"
	RET	NZ
J3714:	PUSH	HL
	PUSH	DE
	LD	A,(SLTWRK+0)
	AND	A
	JR	Z,J3722
	BIT	5,A
	JR	NZ,J3777
	JR	J377A

J3722:	LD	HL,EXPTBL
	LD	BC,I0400
	XOR	A
J3729:	AND	03H	; 3 
	OR	(HL)
J372C:	PUSH	BC
	PUSH	HL
	LD	H,C
J372F:	LD	L,10H	; 16 
J3731:	PUSH	AF
	CALL	C057D
	CPL
	LD	E,A
	POP	AF
	PUSH	DE
	PUSH	AF
	CALL	C0583
	POP	AF
	POP	DE
	PUSH	AF
	PUSH	DE
	CALL	C057D
	POP	BC
	LD	B,A
	LD	A,C
	CPL
	LD	E,A
	POP	AF
	PUSH	AF
	PUSH	BC
	CALL	C0583
	POP	BC
	LD	A,C
	CP	B
	JR	NZ,J3766
	POP	AF
	DEC	L
	JR	NZ,J3731
	INC	H
	INC	H
	INC	H
	INC	H
	JP	P,J372F
	POP	HL
	POP	HL
	LD	(SLTWRK+0),A
	JR	J377A

J3766:	POP	AF
	POP	HL
	POP	BC
	AND	A
	JP	P,J3773
	ADD	A,04H	; 4 
	CP	90H
	JR	C,J372C
J3773:	INC	HL
	INC	A
	DJNZ	J3729
J3777:	JP	J0546			; illegal function call error

J377A:	BIT	6,A
	JR	Z,J3795
	LD	IX,I0100
	LD	B,20H	; " "
J3784:	CALL	C3AD8
	LD	A,(D.FC25)
	AND	A
	JP	NZ,J3BF9
	LD	DE,C0010
	ADD	IX,DE
	DJNZ	J3784
J3795:	POP	HL
	XOR	A
	LD	DE,I03FF
	SBC	HL,DE
	JR	C,J3804
	INC	H
	PUSH	HL
	LD	B,80H
	LD	C,A
	DEC	A
J37A4:	INC	C
	CALL	C3AEC
	DJNZ	J37A4
	LD	B,H
	XOR	A
	LD	C,A
J37AD:	INC	C
	CALL	C3AEC
	DJNZ	J37AD
	LD	HL,D.FC18
	LD	DE,I$FC19
	LD	C,0FH	; 15 
	LD	(HL),B
	LDIR
	LD	IX,I0100
	LD	B,20H	; " "
J37C4:	CALL	C3AD9
	LD	DE,C0010
	ADD	IX,DE
	DJNZ	J37C4
	LD	HL,SLTWRK+0
	SET	6,(HL)
	POP	HL
	LD	L,B
	PUSH	HL
	CALL	C05CC			; print number
	CALL	C388F
	JR	NZ,J3840
	LD	A,C
	LD	(HL),H
	LD	H,L
	LD	(HL),E
	JR	NZ,J3845
	LD	L,H
	LD	L,H
	LD	L,A
	LD	H,E
	LD	H,C
	LD	(HL),H
	LD	H,L
	LD	H,H
	DEC	C
	LD	A,(BC)
	NOP
	POP	HL
	INC	H
	INC	H
	INC	H
	LD	(D.FC18),HL
	LD	HL,D.FC18
	LD	DE,J0000
	LD	BC,I0002
	CALL	C3B6A
	POP	HL
	RET

J3804:	XOR	A
	LD	(SLTWRK+0),A
	CALL	C388F
	LD	C,(HL)
	LD	L,A
	JR	NZ,J3861
	LD	B,C
	LD	C,L
	JR	NZ,J3877
	LD	L,C
	LD	(HL),E
	LD	L,E
	DEC	C
	LD	A,(BC)
	NOP
	POP	HL
	RET

?381B:	CALL	C3BFD
	CALL	C05AE			; fresh line to interpreter output
	PUSH	HL
	LD	IX,I0100
	LD	BC,I2000
J3829:	CALL	C3AD8
	LD	HL,D.FC18
	LD	A,(HL)
	AND	A
	JR	Z,J3861
	INC	C
	PUSH	IX
	PUSH	BC
	LD	B,08H	; 8 
	CALL	C3889
	LD	A,(HL)
	CP	20H	; " "
	JR	Z,J3843
	LD	A,2EH	; "."
J3843:	RST	18H
	LD	B,03H	; 3 
	CALL	C3889
	LD	A,(D.F3B0)
	LD	B,A
	LD	A,(D$F661)
	AND	A
	JR	Z,J385E
	ADD	A,0CH	; 12 
	CP	B
	JR	NC,J385B
	LD	A,20H	; " "
	RST	18H
J385B:	CALL	NC,C05AE		; fresh line to interpreter output
J385E:	POP	BC
	POP	IX
J3861:	LD	DE,C0010
	ADD	IX,DE
	DJNZ	J3829
	LD	A,C
	OR	A
	JP	Z,J055E			; error 53
	CALL	C05AE			; fresh line to interpreter output
	CALL	C38D7
	CALL	C05CC			; print number
	CALL	C388F
	JR	NZ,J38DD
	LD	A,C
	LD	(HL),H
	LD	H,L
	LD	(HL),E
	JR	NZ,J38E7
	LD	(HL),D
	LD	H,L
	LD	H,L
	DEC	C
	LD	A,(BC)
	NOP
	POP	HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3889:	LD	A,(HL)
	INC	HL
	RST	18H
	DJNZ	C3889
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C388F:	EX	(SP),HL
	LD	A,(HL)
	INC	HL
	EX	(SP),HL
	AND	A
	RET	Z
	RST	18H
	JR	C388F

C3898:	PUSH	HL
	POP	IY
	LD	H,(IY+5)
	LD	L,(IY+6)
	JR	J38E6

C38A3:	CALL	C3ACF
	PUSH	HL
	POP	IY
	LD	A,(HL)
	CP	01H	; 1 
	LD	HL,(D.FC26)
	JR	Z,J38E6
	LD	L,(IY+6)
	JR	J38E6

C38B6:	LD	A,(HL)
	CP	01H	; 1 

C38B9:	LD	E,3DH	; "="
	JP	NZ,J3C05
	PUSH	HL
	POP	IY
	CALL	C3ACF
	LD	L,(IY+6)
	LD	H,(IY+5)
	LD	DE,(D.FC26)
	RST	20H
	LD	HL,-1
	JR	NC,J38E6
	INC	HL
	JR	J38E6


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C38D7:	LD	BC,07D01H
	LD	HL,J0000
J38DD:	CALL	C3AEB
	JR	NZ,J38E3
	INC	H
J38E3:	INC	C
	DJNZ	J38DD
J38E6:	LD	(D.F7F8),HL
	LD	A,02H	; 2 
	LD	(D.F663),A
	RET

?38EF:	CALL	C3911
	RST	08H
	DEFB	")"
	CALL	C3BF1

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C38F7:	LD	(D.FC18),A
	CALL	C3AD9
	LD	A,(D.FC23)
	AND	A
	RET	Z
J3902:	LD	C,A
	CALL	C3AEB
	PUSH	AF
	XOR	A
	CALL	C3AEC
	POP	AF
	CP	0FFH
	JR	NZ,J3902
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3911:	RST	08H
	DEFB	"("
	CALL	C3BFD

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3916:	CALL	C05BA			; evaluate filespecification
	RET	Z
	LD	A,D
	CP	0FCH
	JR	NC,J3929
	CP	09H	; 9 
	JR	C,J3929
	PUSH	HL
	CALL	C392C
	POP	HL
	RET	Z
J3929:	JP	J052E			; error 56


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C392C:	LD	HL,PROCNM
	LD	DE,I3941
J3932:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J393C
	INC	HL
	INC	DE
	OR	A
	JR	NZ,J3932
	RET

J393C:	SUB	30H	; "0"
	RET	NZ
	OR	(HL)
	RET

I3941:	LD	C,L
	LD	B,L
	LD	C,L
	JR	NC,J3946
J3946:	CALL	C3911
	CALL	C3BF1
	PUSH	IX
	RST	08H
	DEFB	"A"
	RST	08H
	DEFB	"S"
	CALL	C3916
	RST	08H
	DEFB	")"
	CALL	C3B0D
	LD	E,41H	; "A"
	JP	Z,J3C05
	POP	IX
	CALL	C3AD8
J3964:	PUSH	HL
	LD	DE,D.FC18
	LD	HL,I.F866
	LD	BC,I000B
	LDIR
	POP	HL
	JR	J3995

C3973:	CALL	C3BFD
	CALL	C3B0D
	PUSH	AF
	LD	A,E
	CP	04H	; 4 
	JP	Z,J0534			; error 58
	CP	02H	; 2 
	JR	Z,J3998
	CP	08H	; 8 
	JR	Z,J39D1
	POP	AF
	JR	NZ,J39D2
	OR	A
	JR	NZ,J39D6
	CALL	C3BD6

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3991:	DEC	A
	LD	(D.FC25),A
J3995:	JP	C3AD9

J3998:	POP	AF
	JR	NZ,J39A1
	OR	A
	JR	NZ,J39D6
	CALL	C38F7
J39A1:	LD	IX,I0100
	LD	B,20H	; " "
J39A7:	CALL	C3AD8
	LD	A,(D.FC18)
	AND	A
	JR	Z,J39BC
	LD	DE,C0010
	ADD	IX,DE
	DJNZ	J39A7
	LD	E,43H	; "C"
	JP	J3C05

J39BC:	LD	E,02H	; 2 
	CALL	C3BD6
	LD	HL,D.FC18
	LD	B,10H	; 16 
J39C6:	LD	(HL),A
	INC	HL
	DJNZ	J39C6
	DEC	A
	LD	(D.FC25),A
	JP	J3964

J39D1:	POP	AF
J39D2:	JP	NZ,J055E		; error 53
	OR	A
J39D6:	JP	NZ,J053A		; error 54
	CALL	C3BD6
	LD	HL,(D.FC26)
	LD	(IY+5),H
	LD	(IY+6),L
	LD	L,A
	LD	(D.FC26),HL
	CALL	C3991
	LD	A,(D.FC23)
	AND	A
	RET	Z
	LD	A,(D.FC24)
	LD	(IY+7),A
	JP	C3B51

C39FA:	CALL	C3ACF
	XOR	A
	LD	(D.FC25),A
	CALL	C3AD9
	LD	A,(HL)
	CP	01H	; 1 
	RET	Z
	PUSH	HL
	POP	IY
	LD	A,(IY+6)
	AND	A
	RET	Z
	CALL	C3B52
	LD	HL,(D.FC26)
	LD	L,(IY+6)
	LD	(D.FC26),HL
	JR	J3A7A

C3A1E:	PUSH	HL
	POP	IY
	LD	A,(IY+6)
	AND	A
	JR	NZ,J3A5D
	PUSH	HL
	PUSH	BC
	CALL	C3ACF
	LD	BC,07D01H
J3A2F:	CALL	C3AEB
	JR	Z,J3A3C
	INC	C
	DJNZ	J3A2F
	LD	E,42H	; "B"
	JP	J3C05

J3A3C:	LD	A,(D.FC23)
	AND	A
	LD	A,C
	JR	NZ,J3A46
	LD	(D.FC23),A
J3A46:	LD	C,(IY+7)
	CALL	NZ,C3AEC
	LD	(D.FC24),A
	LD	(IY+7),A
	LD	C,A
	LD	A,0FFH
	CALL	C3AEC
	CALL	C3AD9
	POP	BC
	POP	HL
J3A5D:	LD	DE,I0009
	ADD	HL,DE
	LD	E,(IY+6)
	ADD	HL,DE
	LD	(HL),C
	INC	(IY+6)
	RET	NZ
	CALL	C3B52
	INC	(IY+5)
	PUSH	IY
	POP	HL
	CALL	C3ACF
	LD	HL,I$FC27
	INC	(HL)
J3A7A:	JR	C3AD9

C3A7C:	PUSH	HL
	PUSH	HL
	POP	IY
	CALL	C3ACF
	LD	L,(IY+6)
	LD	H,(IY+5)
	LD	DE,(D.FC26)
	RST	20H
	POP	HL
	CCF
	RET	C
	LD	A,(IY+3)
	AND	A
	LD	(IY+3),00H
	RET	NZ
	LD	A,(IY+6)
	AND	A
	JR	Z,J3AAF
	LD	BC,I0009
	ADD	HL,BC
	LD	C,A
	ADD	HL,BC
	LD	A,(HL)
	INC	(IY+6)
	RET	NZ
	INC	(IY+5)
	RET

J3AAF:	LD	A,(IY+7)
	AND	A
	LD	C,A
	LD	A,(D.FC23)
	CALL	NZ,C3AEB
	LD	(IY+7),A
	CALL	C3B51
	LD	A,(IY+9)
	INC	(IY+6)
	AND	A
	RET

C3AC8:	PUSH	HL
	POP	IY
	LD	(IY+3),C
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3ACF:	INC	HL
	LD	C,(HL)
	INC	HL
	LD	B,(HL)
	PUSH	BC
	POP	IX
	DEC	HL
	DEC	HL

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3AD8:	DEFB	0F6H

C3AD9:	SCF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	IX
	POP	HL
	LD	DE,D.FC18
	JR	NC,J3AE6
	EX	DE,HL
J3AE6:	LD	BC,C0010
	JR	J3B02


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3AEB:	DEFB	0F6H

C3AEC:	SCF
	PUSH	HL
	PUSH	DE
	PUSH	BC
	PUSH	AF
	LD	HL,I007F
	LD	B,00H
	ADD	HL,BC
	LD	DE,D.FC28
	POP	AF
	JR	NC,J3AFF
	EX	DE,HL
	LD	(HL),A
J3AFF:	LD	BC,I0001
J3B02:	CALL	C3B6A
	POP	BC
	POP	DE
	POP	HL
	LD	A,(D.FC28)
	AND	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3B0D:	PUSH	HL
	PUSH	DE
	LD	DE,I.F866
	LD	B,0BH	; 11 
J3B14:	LD	A,(DE)
	CP	61H	; "a"
	JR	C,J3B20
	CP	7BH	; "{"
	JR	NC,J3B20
	AND	0DFH
	LD	(DE),A
J3B20:	INC	DE
	DJNZ	J3B14
	LD	IX,I0100
	LD	C,20H	; " "
J3B29:	CALL	C3AD8
	LD	HL,D.FC18
	LD	A,(HL)
	AND	A
	JR	NZ,J3B3E
J3B33:	LD	DE,C0010
	ADD	IX,DE
	DEC	C
	JR	NZ,J3B29
	INC	C
	JR	J3B4B

J3B3E:	LD	DE,I.F866
	LD	B,0BH	; 11 
J3B43:	LD	A,(DE)
	CP	(HL)
	JR	NZ,J3B33
	INC	DE
	INC	HL
	DJNZ	J3B43
J3B4B:	POP	DE
	POP	HL
	LD	A,(D.FC25)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3B51:	DEFB	0F6H

C3B52:	SCF
	PUSH	AF
	PUSH	IY
	POP	HL
	LD	BC,I0009
	ADD	HL,BC
	LD	E,00H
	LD	A,(IY+7)
	ADD	A,02H	; 2 
	LD	D,A
	POP	AF
	JR	C,J3B67
	EX	DE,HL
J3B67:	LD	BC,I0100

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3B6A:	LD	A,H
	AND	A
	JP	P,J3B70
	LD	A,D
J3B70:	CP	40H	; "@"
	EXX
	LD	HL,D.FFFF
	LD	A,(SLTWRK+0)
	LD	D,A
	JR	C,J3BB7
	RRCA
	RRCA
	AND	0C0H
	LD	C,A
	RRCA
	RRCA
	RRCA
	RRCA
	OR	C
	LD	C,A
	IN	A,(0A8H)
	LD	B,A
	AND	33H	; "3"
	OR	C
	LD	E,A
	DI
	OUT	(0A8H),A
	LD	A,D
	AND	0CH	; 12 
	LD	D,A
	LD	A,(HL)
	CPL
	LD	C,A
	AND	0F3H
	OR	D
	LD	(HL),A
	LD	A,E
	AND	3FH	; "?"
	LD	D,A
	LD	A,B
	AND	0C0H
	OR	D
	EI
	OUT	(0A8H),A
	EXX
	LDIR
	EXX
	LD	A,E
	DI
	OUT	(0A8H),A
	LD	A,C
	LD	(HL),A
	LD	A,B
	EI
	OUT	(0A8H),A
	EXX
	RET

J3BB7:	RRCA
	RRCA
	AND	0C0H
	LD	C,A
	LD	A,D
	AND	03H	; 3 
	OR	C
	LD	C,A
	IN	A,(0A8H)
	LD	B,A
	AND	3CH	; "<"
	OR	C
	LD	E,A
	LD	A,D
	RRCA
	RRCA
	AND	03H	; 3 
	LD	D,A
	LD	A,E
	DI
	CALL	M51D7
	EI
	EXX
	RET

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3BD6:	PUSH	HL
	POP	IY
	PUSH	IX
	POP	BC
	LD	(IY+1),C
	LD	(IY+2),B
	XOR	A
	LD	(IY+3),A
	LD	(IY+5),A
	LD	(IY+6),A
	LD	(D$F864),HL
	LD	(HL),E
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3BF1:	CALL	C3B0D
	JP	NZ,J055E		; error 53
	AND	A
	RET	Z
J3BF9:	LD	E,40H	; "@"
	JR	J3C05


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3BFD:	LD	A,(SLTWRK+0)
	BIT	6,A
	RET	NZ
	LD	E,46H	; "F"
J3C05:	XOR	A
	LD	(D$F87C),A
	PUSH	DE
	CALL	C05C0			; close i/o channel
	POP	DE
	JP	J05C6			; BASIC error

I3C11:	LD	BC,I3C34
J3C14:	LD	A,(BC)
	INC	BC
	OR	A
	RET	Z
	SUB	E
	JR	Z,J3C1F
	INC	BC
	INC	BC
	JR	J3C14

J3C1F:	LD	L,C
	LD	H,B
	LD	E,(HL)
	INC	HL
	LD	D,(HL)
	LD	HL,D.F55E
	PUSH	HL
	LD	(HL),A
J3C29:	INC	DE
	INC	HL
	LD	A,(DE)
	LD	(HL),A
	OR	A
	JR	NZ,J3C29
	POP	HL
	LD	E,01H	; 1 
	RET

I3C34:	DEC	A
	LD	B,(HL)
	INC	A
	LD	B,B
	LD	D,H
	INC	A
	LD	B,C
	LD	H,H
	INC	A
	LD	B,D
	LD	A,B
	INC	A
	LD	B,E
	ADD	A,(HL)
	INC	A
	LD	B,(HL)
	SUB	L
	INC	A
	NOP
	LD	B,D
	LD	H,C
	LD	H,H
	JR	NZ,J3CB2
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J3CBE
	LD	L,A
	LD	H,H
	LD	H,L
	NOP
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J3CCE
	LD	(HL),H
	LD	L,C
	LD	L,H
	LD	L,H
	JR	NZ,J3CD0
	LD	(HL),B
	LD	H,L
	LD	L,(HL)
	NOP
	LD	B,(HL)
	LD	L,C
	LD	L,H
	LD	H,L
	JR	NZ,J3CCC
	LD	L,H
	LD	(HL),D
	LD	H,L
	LD	H,C
	LD	H,H
	LD	A,C
	JR	NZ,J3CD8
	LD	A,B
	LD	L,C
	LD	(HL),E
	LD	(HL),H
	LD	(HL),E
	NOP
	LD	D,D
	LD	B,C
	LD	C,L
	JR	NZ,J3CE2
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J3CE9
	LD	(HL),L
	LD	L,H
	LD	L,H
	NOP
	LD	D,H
	LD	L,A
	LD	L,A
	JR	NZ,J3CF9
	LD	H,C
	LD	L,(HL)
	LD	A,C
	JR	NZ,J3CF7
	LD	L,C
	LD	L,H
	LD	H,L
	LD	(HL),E
	NOP
	LD	D,D
	LD	B,C
	LD	C,L
	JR	NZ,J3CFF
	LD	L,C
	LD	(HL),E
	LD	L,E
	JR	NZ,J3D0F
	LD	H,(HL)
	LD	H,(HL)
	LD	L,H
	LD	L,C
	LD	L,(HL)
	LD	H,L
	NOP
J3CA7:	LD	HL,I$FCAD
	INC	(HL)
	DEC	(HL)
	LD	B,08H	; 8 
	LD	DE,I3F4E
	LD	HL,I3F3E
J3CB2	EQU	$-2
	JR	Z,J3CB9
	LD	HL,I3F46
J3CB9:	CP	(HL)
	JR	Z,J3CC6
	INC	HL
	INC	DE
J3CBE:	DJNZ	J3CB9
J3CC0:	CALL	C3ED1
	JP	J3DC7

J3CC6:	LD	A,(DE)
	JR	J3CC0

J3CC9:	PUSH	AF
	CALL	C3EE7
	POP	AF
J3CCE:	JR	Z,J3CD5
J3CD0:	LD	HL,D.FAFC
	BIT	0,(HL)
J3CD5:	JP	Z,C3ED1
J3CD8:	CP	41H	; "A"
	JR	C,J3CA7
	CP	5BH	; "["
	JR	C,J3CEC
	CP	61H	; "a"
J3CE2:	JR	C,J3CA7
	CP	7BH	; "{"
	JR	NC,J3CA7
	RES	7,(HL)
	JR	J3CEE

J3CEC:	SET	7,(HL)
J3CEE:	CP	61H	; "a"
	JR	C,J3CF4
	SUB	20H	; " "
J3CF4:	LD	D,A
	CP	58H	; "X"
J3CF7:	JR	Z,J3D15
J3CF9:	LD	A,(D.FAF9)
	OR	A
	JR	NZ,J3D1A
J3CFF:	LD	A,D
	CALL	C3E2F
	LD	A,D
	JP	NZ,C3EB6
	CALL	C3E20
	CP	80H
	RET	NC
	LD	A,D
	LD	(D.FAFA),A
	LD	A,01H	; 1 
	JR	J3D55

J3D15:	LD	A,0B0H
	JP	J3CC0

J3D1A:	DEC	A
	LD	A,D
	JR	NZ,J3D57
J3D1E:	LD	E,A
	CALL	C3E2F
	LD	A,(D.FAFA)
	JR	Z,J3D2C
	CALL	C3E3D
	JR	J3D38

J3D2C:	CP	E
	JR	NZ,J3D3F
	CP	4EH	; "N"
	JR	NZ,J3D3B
	LD	A,0FDH
	CALL	C3EBC
J3D38:	JP	J3DC7

J3D3B:	LD	A,8FH
	JR	J3D4D

J3D3F:	CP	4EH	; "N"
	LD	A,E
	JR	NZ,J3D50
	CP	59H	; "Y"
	JR	Z,J3D50
	LD	(D.FAFA),A
	LD	A,0FDH
J3D4D:	JP	C3EBC

J3D50:	LD	(D$FAFB),A
	LD	A,02H	; 2 
J3D55:	JR	J3DC8

J3D57:	LD	HL,D.FAFA
	LD	D,(HL)
	INC	HL
	LD	B,(HL)
	LD	C,A
	PUSH	BC
	CALL	C3E2F
	POP	BC
	JR	NZ,J3D72
	LD	A,B
	LD	(D.FAFA),A
	LD	A,01H	; 1 
	LD	(D.FAF9),A
	LD	A,C
	JP	J3D1E

J3D72:	LD	A,B
	CP	59H	; "Y"
	JR	NZ,J3D9D
	LD	A,D
	CP	43H	; "C"
	JR	Z,J3D90
	CP	4CH	; "L"
	JR	Z,J3DC1
	CP	46H	; "F"
	JR	Z,J3D99
	CP	57H	; "W"
	JR	Z,J3DF2
	LD	E,49H	; "I"
	PUSH	BC
	CALL	C3E3D
	JR	J3D96

J3D90:	LD	A,0E1H
J3D92:	PUSH	BC
	CALL	C3EBC
J3D96:	POP	BC
	JR	J3DC1

J3D99:	LD	A,0ECH
	JR	J3D92

J3D9D:	LD	A,B
	CP	48H	; "H"
	JR	NZ,J3DDC
	LD	A,D
	CP	43H	; "C"
	JR	Z,J3DB7
	CP	44H	; "D"
	JR	Z,J3DCC
	CP	54H	; "T"
	JR	Z,J3DD5
	CP	53H	; "S"
	JR	NZ,J3DF2
	LD	A,9CH
	JR	J3DB9

J3DB7:	LD	A,0E1H
J3DB9:	CALL	C3EBC
J3DBC:	LD	A,C
	CP	49H	; "I"
	JR	Z,J3DC7
J3DC1:	LD	A,4AH	; "J"
	LD	E,C
	CALL	C3EB9
J3DC7:	XOR	A
J3DC8:	LD	(D.FAF9),A
	RET

J3DCC:	LD	A,0E3H
	CALL	C3EBC
	LD	A,0DEH
	JR	J3DD7

J3DD5:	LD	A,0E3H
J3DD7:	CALL	C3EBC
	JR	J3DC1

J3DDC:	LD	A,D
	CP	54H	; "T"
	JR	NZ,J3DF2
	LD	A,B
	CP	53H	; "S"
	JR	NZ,J3DF2
	LD	A,C
	CP	55H	; "U"
	JR	NZ,J3DF2
	LD	A,0E2H
	CALL	C3EBC
	JR	J3DC7

J3DF2:	LD	A,B
	LD	E,C
	CALL	C3E3D
	JR	J3DC7


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3DF9:	CALL	C3E29
	LD	B,A
	ADD	A,A
	ADD	A,A
	ADD	A,B
	LD	D,A
	LD	A,E
	CALL	C3E2F
	ADD	A,D
	LD	L,A
	LD	A,D
	CP	0FH	; 15 
	JR	NC,J3E10
	LD	A,L
	SUB	70H	; "p"
	RET

J3E10:	CP	23H	; "#"
	JR	NC,J3E18
	LD	A,L
	SUB	30H	; "0"
	RET

J3E18:	LD	A,L
	SUB	23H	; "#"
	LD	BC,I3F71
	JR	J3E23


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E20:	LD	BC,I3F16
J3E23:	LD	L,A
	LD	H,00H
	ADD	HL,BC
	LD	A,(HL)
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E29:	CALL	C3E20
	AND	0FH	; 15 
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E2F:	CALL	C3E20
	SUB	14H	; 20 
	CP	01H	; 1 
	JR	C,J3E3B
	CP	06H	; 6 
	RET	C
J3E3B:	XOR	A
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E3D:	LD	D,A
	CALL	C3E20
	CP	0BH	; 11 
	JR	NC,J3E48
	LD	A,D
	JR	J3E8A

J3E48:	CP	21H	; "!"
	JR	C,J3E58
	CP	26H	; "&"
	JR	NC,J3E58
	LD	A,D
	CALL	C3EB9

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3E54:	LD	A,0DEH
	JR	C3EBC

J3E58:	LD	A,D
	CP	50H	; "P"
	JR	NZ,J3E67
	LD	A,48H	; "H"
	CALL	C3EB9
	LD	A,0DFH
	JP	C3EBC

J3E67:	CP	4AH	; "J"
	JR	NZ,J3E79
	LD	A,9CH
	PUSH	DE
	CALL	C3EBC
	CALL	C3E54
	POP	DE
	LD	C,E
	JP	J3DBC

J3E79:	CP	46H	; "F"
	JR	NZ,J3E8C
	LD	A,0ECH
	PUSH	DE
	CALL	C3EBC
J3E83:	POP	DE
	LD	A,E
	CP	55H	; "U"
	RET	Z
J3E88:	LD	A,4CH	; "L"
J3E8A:	JR	C3EB9

J3E8C:	CP	59H	; "Y"
	JR	NZ,J3E96
	CALL	C3EB9
	LD	A,E
	JR	J3EA2

J3E96:	CP	57H	; "W"
	JR	NZ,J3EA7
	CALL	C3EB9
	LD	A,E
	CP	49H	; "I"
	JR	Z,J3E88
J3EA2:	CP	45H	; "E"
	RET	NZ
	JR	J3E88

J3EA7:	CP	56H	; "V"
	JR	NZ,J3EB7
	LD	A,55H	; "U"
	PUSH	DE
	CALL	C3EB6
	CALL	C3E54
	JR	J3E83


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3EB6:	LD	E,A
J3EB7:	LD	A,51H	; "Q"

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3EB9:	CALL	C3DF9

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3EBC:	LD	HL,D.FAFC
	BIT	7,(HL)
	JR	Z,C3ED1
	CP	0E0H
	JR	C,J3ECB
	SUB	20H	; " "
	JR	C3ED1

J3ECB:	CP	0A0H
	JR	NC,C3ED1
	ADD	A,20H	; " "

;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3ED1:	LD	HL,(D.F3F8)
	LD	(HL),A
	INC	HL
	LD	A,L
	CP	18H
	JR	NZ,J3EDE
	LD	HL,I$FBF0
J3EDE:	LD	A,(D$F3FA)
	CP	L
	RET	Z
	LD	(D.F3F8),HL
	RET


;	  Subroutine __________________________
;	     Inputs  ________________________
;	     Outputs ________________________

C3EE7:	LD	A,(D.F3DB)
	AND	A
	RET	Z
	LD	A,(D.FBD9)
	AND	A
	RET	NZ
	LD	A,0FH	; 15 
	LD	(D.FBD9),A
	DI
	OUT	(0ABH),A
	LD	A,0AH	; 10 
J3EFB:	DEC	A
	JR	NZ,J3EFB
	LD	A,0EH	; 14 
	OUT	(0ABH),A
	EI
	RET

J3F04:	LD	HL,D.FAFC
	BIT	0,(HL)
	JR	Z,J3F10
	RES	0,(HL)
	XOR	A
	JR	J3F29

J3F10:	LD	A,(D.FCAC)
	INC	A
	JR	Z,J3F26
I3F16:	LD	A,(D.FBEB)
	RRCA
	JR	C,J3F24
	XOR	A
	LD	(D.FAF9),A
	SET	0,(HL)
	JR	J3F29

J3F24:	LD	A,0FFH
J3F26:	LD	(D.FCAC),A
J3F29:	PUSH	AF
	LD	A,0FH	; 15 
	OUT	(0A0H),A
	IN	A,(0A2H)
	AND	7FH
	LD	B,A
	POP	AF
	OR	A
	LD	A,80H
	JR	Z,J3F3A
	XOR	A
J3F3A:	OR	B
	OUT	(0A1H),A
	RET

I3F3E:	DEFB	"*:]_?>{}"

I3F46:	DEFB	"\@>?[<{}"

I3F4E:	DEFB	0B0H,0DEH,0A1H,0A5H,0DFH,0A4H,0A2H,0A3H

	DEFB	00AH,015H,025H,028H,023H,018H,040H,021H
	DEFB	005H,016H,04BH,001H,00AH,006H,004H,019H
	DEFB	028H,080H,008H,002H,003H,017H,040H,049H
	DEFB	08CH,047H,022H

	DEFB	0FDH,0F4H,092H,0F5H,092H,0F6H,0F7H,0F8H
	DEFB	0F9H,0FAH,0FBH,0FCH,093H,093H,093H,086H
	DEFB	087H,088H,089H,08AH,08BH,08CH,088H,08DH
	DEFB	08AH,08EH



	END
